items:
- uid: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig
  commentId: T:Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig
  id: AzureBlobStorageHttpLogsConfig
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.#ctor
  - Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.#ctor(System.String,System.Nullable{System.Int32},System.Nullable{System.Boolean})
  - Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.Enabled
  - Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.RetentionInDays
  - Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.SasUrl
  langs:
  - csharp
  - vb
  name: AzureBlobStorageHttpLogsConfig
  fullName: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig
  type: Class
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: AzureBlobStorageHttpLogsConfig
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nHttp logs to azure blob storage configuration\n"
  example: []
  syntax:
    content: public class AzureBlobStorageHttpLogsConfig
    content.vb: Public Class AzureBlobStorageHttpLogsConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.#ctor
  commentId: M:Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig
  langs:
  - csharp
  - vb
  name: AzureBlobStorageHttpLogsConfig()
  fullName: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.AzureBlobStorageHttpLogsConfig()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the AzureBlobStorageHttpLogsConfig\nclass.\n"
  example: []
  syntax:
    content: public AzureBlobStorageHttpLogsConfig()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.#ctor(System.String,System.Nullable{System.Int32},System.Nullable{System.Boolean})
  commentId: M:Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.#ctor(System.String,System.Nullable{System.Int32},System.Nullable{System.Boolean})
  id: '#ctor(System.String,System.Nullable{System.Int32},System.Nullable{System.Boolean})'
  parent: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig
  langs:
  - csharp
  - vb
  name: AzureBlobStorageHttpLogsConfig(String, Nullable<Int32>, Nullable<Boolean>)
  fullName: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.AzureBlobStorageHttpLogsConfig(System.String, System.Nullable<System.Int32>, System.Nullable<System.Boolean>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the AzureBlobStorageHttpLogsConfig\nclass.\n"
  example: []
  syntax:
    content: public AzureBlobStorageHttpLogsConfig(string sasUrl = null, int ? retentionInDays = null, bool ? enabled = null)
    content.vb: Public Sub New(sasUrl As String = Nothing, retentionInDays As Integer? = Nothing, enabled As Boolean? = Nothing)
    parameters:
    - id: sasUrl
      type: System.String
    - id: retentionInDays
      type: System.Nullable{System.Int32}
    - id: enabled
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.AzureBlobStorageHttpLogsConfig(System.String, System.Nullable(Of System.Int32), System.Nullable(Of System.Boolean))
  name.vb: AzureBlobStorageHttpLogsConfig(String, Nullable(Of Int32), Nullable(Of Boolean))
- uid: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.SasUrl
  commentId: P:Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.SasUrl
  id: SasUrl
  parent: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig
  langs:
  - csharp
  - vb
  name: SasUrl
  fullName: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.SasUrl
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: SasUrl
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
    startLine: 44
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nSAS url to a azure blob container with read/write/list/delete\npermissions\n"
  example: []
  syntax:
    content: public string SasUrl { get; set; }
    content.vb: Public Property SasUrl As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.RetentionInDays
  commentId: P:Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.RetentionInDays
  id: RetentionInDays
  parent: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig
  langs:
  - csharp
  - vb
  name: RetentionInDays
  fullName: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.RetentionInDays
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: RetentionInDays
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nRetention in days.\nRemove blobs older than X days.\n0 or lower means no retention.\n"
  example: []
  syntax:
    content: public int ? RetentionInDays { get; set; }
    content.vb: Public Property RetentionInDays As Integer?
    parameters: []
    return:
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.Enabled
  commentId: P:Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.Enabled
  id: Enabled
  parent: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig
  langs:
  - csharp
  - vb
  name: Enabled
  fullName: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageHttpLogsConfig.Enabled
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Enabled
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/AzureBlobStorageHttpLogsConfig.cs
    startLine: 58
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nEnabled\n"
  example: []
  syntax:
    content: public bool ? Enabled { get; set; }
    content.vb: Public Property Enabled As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  fullname.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
