items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  id: ApplicationGatewayFrontendPortInner
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.#ctor(System.String,System.Nullable{System.Int32},System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Etag
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Name
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Port
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.ProvisioningState
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFrontendPortInner
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayFrontendPortInner
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nFrontend Port of application gateway\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayFrontendPortInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class ApplicationGatewayFrontendPortInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFrontendPortInner()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.ApplicationGatewayFrontendPortInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayFrontendPortInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayFrontendPortInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.#ctor(System.String,System.Nullable{System.Int32},System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.#ctor(System.String,System.Nullable{System.Int32},System.String,System.String,System.String)
  id: '#ctor(System.String,System.Nullable{System.Int32},System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFrontendPortInner(String, Nullable<Int32>, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.ApplicationGatewayFrontendPortInner(System.String, System.Nullable<System.Int32>, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayFrontendPortInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayFrontendPortInner(string id = null, int ? port = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, port As Integer? = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: port
      type: System.Nullable{System.Int32}
      description: Frontend port
    - id: provisioningState
      type: System.String
      description: >-
        Provisioning state of the frontend

        port resource Updating/Deleting/Failed
    - id: name
      type: System.String
      description: >-
        Name of the resource that is unique within a

        resource group. This name can be used to access the

        resource
    - id: etag
      type: System.String
      description: >-
        A unique read-only string that changes whenever

        the resource is updated
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.ApplicationGatewayFrontendPortInner(System.String, System.Nullable(Of System.Int32), System.String, System.String, System.String)
  name.vb: ApplicationGatewayFrontendPortInner(String, Nullable(Of Int32), String, String, String)
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Port
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Port
  id: Port
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  langs:
  - csharp
  - vb
  name: Port
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Port
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Port
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets frontend port\n"
  example: []
  syntax:
    content: public int ? Port { get; set; }
    content.vb: Public Property Port As Integer?
    parameters: []
    return:
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
    startLine: 55
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets provisioning state of the frontend port resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
    startLine: 62
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets name of the resource that is unique within a resource\ngroup. This name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendPortInner.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendPortInner.cs
    startLine: 69
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets a unique read-only string that changes whenever the\nresource is updated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  fullname.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
