items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  id: ApplicationGatewaySslCertificateInner
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.#ctor(System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Data
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Etag
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Name
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Password
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.PublicCertData
  langs:
  - csharp
  - vb
  name: ApplicationGatewaySslCertificateInner
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewaySslCertificateInner
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nSSL certificates of application gateway\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewaySslCertificateInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class ApplicationGatewaySslCertificateInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewaySslCertificateInner()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.ApplicationGatewaySslCertificateInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewaySslCertificateInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewaySslCertificateInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.#ctor(System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.#ctor(System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String,System.String,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewaySslCertificateInner(String, String, String, String, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.ApplicationGatewaySslCertificateInner(System.String, System.String, System.String, System.String, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewaySslCertificateInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewaySslCertificateInner(string id = null, string data = null, string password = null, string publicCertData = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, data As String = Nothing, password As String = Nothing, publicCertData As String = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: data
      type: System.String
      description: 'SSL Certificate data '
    - id: password
      type: System.String
      description: 'SSL Certificate password '
    - id: publicCertData
      type: System.String
      description: 'SSL Certificate public data '
    - id: provisioningState
      type: System.String
      description: >-
        Provisioning state of the ssl

        certificate resource Updating/Deleting/Failed
    - id: name
      type: System.String
      description: >-
        Name of the resource that is unique within a

        resource group. This name can be used to access the

        resource
    - id: etag
      type: System.String
      description: >-
        A unique read-only string that changes whenever

        the resource is updated
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Data
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Data
  id: Data
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  langs:
  - csharp
  - vb
  name: Data
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Data
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Data
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets SSL Certificate data\n"
  example: []
  syntax:
    content: public string Data { get; set; }
    content.vb: Public Property Data As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Password
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Password
  id: Password
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  langs:
  - csharp
  - vb
  name: Password
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Password
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Password
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 58
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets SSL Certificate password\n"
  example: []
  syntax:
    content: public string Password { get; set; }
    content.vb: Public Property Password As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.PublicCertData
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.PublicCertData
  id: PublicCertData
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  langs:
  - csharp
  - vb
  name: PublicCertData
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.PublicCertData
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PublicCertData
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 64
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets SSL Certificate public data\n"
  example: []
  syntax:
    content: public string PublicCertData { get; set; }
    content.vb: Public Property PublicCertData As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 71
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets provisioning state of the ssl certificate resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 78
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets name of the resource that is unique within a resource\ngroup. This name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewaySslCertificateInner.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewaySslCertificateInner.cs
    startLine: 85
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets a unique read-only string that changes whenever the\nresource is updated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
