items:
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  commentId: T:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  id: ApplicationTokenCredentials
  parent: Microsoft.Azure.Management.V2.Resource.Authentication
  children:
  - Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(Microsoft.Azure.Management.V2.Resource.AzureEnvironment,System.String,System.String,System.String)
  - Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(System.String)
  - Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(System.String,System.String,System.String)
  - Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.DefaultSubscriptionId
  - Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage,System.Threading.CancellationToken)
  - Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.TokenCache
  - Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.WithDefaultSubscription(System.String)
  - Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.withTokenCache(TokenCache)
  langs:
  - csharp
  - vb
  name: ApplicationTokenCredentials
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationTokenCredentials
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 16
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: 'public class ApplicationTokenCredentials : ServiceClientCredentials'
    content.vb: >-
      Public Class ApplicationTokenCredentials
          Inherits ServiceClientCredentials
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.TokenCache
  commentId: P:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.TokenCache
  id: TokenCache
  parent: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  langs:
  - csharp
  - vb
  name: TokenCache
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.TokenCache
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: TokenCache
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: public TokenCache TokenCache { get; }
    content.vb: Public ReadOnly Property TokenCache As TokenCache
    parameters: []
    return:
      type: TokenCache
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.DefaultSubscriptionId
  commentId: P:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.DefaultSubscriptionId
  id: DefaultSubscriptionId
  parent: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  langs:
  - csharp
  - vb
  name: DefaultSubscriptionId
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.DefaultSubscriptionId
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefaultSubscriptionId
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: public string DefaultSubscriptionId { get; }
    content.vb: Public ReadOnly Property DefaultSubscriptionId As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(Microsoft.Azure.Management.V2.Resource.AzureEnvironment,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(Microsoft.Azure.Management.V2.Resource.AzureEnvironment,System.String,System.String,System.String)
  id: '#ctor(Microsoft.Azure.Management.V2.Resource.AzureEnvironment,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  langs:
  - csharp
  - vb
  name: ApplicationTokenCredentials(AzureEnvironment, String, String, String)
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.ApplicationTokenCredentials(Microsoft.Azure.Management.V2.Resource.AzureEnvironment, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 26
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: public ApplicationTokenCredentials(AzureEnvironment environment, string tenantId, string clientId, string clientSecret)
    content.vb: Public Sub New(environment As AzureEnvironment, tenantId As String, clientId As String, clientSecret As String)
    parameters:
    - id: environment
      type: Microsoft.Azure.Management.V2.Resource.AzureEnvironment
    - id: tenantId
      type: System.String
    - id: clientId
      type: System.String
    - id: clientSecret
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  langs:
  - csharp
  - vb
  name: ApplicationTokenCredentials(String, String, String)
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.ApplicationTokenCredentials(System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: public ApplicationTokenCredentials(string tenantId, string clientId, string clientSecret)
    content.vb: Public Sub New(tenantId As String, clientId As String, clientSecret As String)
    parameters:
    - id: tenantId
      type: System.String
    - id: clientId
      type: System.String
    - id: clientSecret
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  langs:
  - csharp
  - vb
  name: ApplicationTokenCredentials(String)
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.ApplicationTokenCredentials(System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: public ApplicationTokenCredentials(string authFile)
    content.vb: Public Sub New(authFile As String)
    parameters:
    - id: authFile
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.withTokenCache(TokenCache)
  commentId: M:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.withTokenCache(TokenCache)
  id: withTokenCache(TokenCache)
  parent: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  langs:
  - csharp
  - vb
  name: withTokenCache(TokenCache)
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.withTokenCache(TokenCache)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: withTokenCache
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: public ApplicationTokenCredentials withTokenCache(TokenCache tokenCache)
    content.vb: Public Function withTokenCache(tokenCache As TokenCache) As ApplicationTokenCredentials
    parameters:
    - id: tokenCache
      type: TokenCache
    return:
      type: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.WithDefaultSubscription(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.WithDefaultSubscription(System.String)
  id: WithDefaultSubscription(System.String)
  parent: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  langs:
  - csharp
  - vb
  name: WithDefaultSubscription(String)
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.WithDefaultSubscription(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDefaultSubscription
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 79
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: public ApplicationTokenCredentials WithDefaultSubscription(string subscriptionId)
    content.vb: Public Function WithDefaultSubscription(subscriptionId As String) As ApplicationTokenCredentials
    parameters:
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage,System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage,System.Threading.CancellationToken)
  id: ProcessHttpRequestAsync(HttpRequestMessage,System.Threading.CancellationToken)
  parent: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  langs:
  - csharp
  - vb
  name: ProcessHttpRequestAsync(HttpRequestMessage, CancellationToken)
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials.ProcessHttpRequestAsync(HttpRequestMessage, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProcessHttpRequestAsync
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Authentication/ApplicationTokenCredentials.cs
    startLine: 85
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Authentication
  syntax:
    content: public override Task ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    content.vb: Public Overrides Function ProcessHttpRequestAsync(request As HttpRequestMessage, cancellationToken As CancellationToken) As Task
    parameters:
    - id: request
      type: HttpRequestMessage
    - id: cancellationToken
      type: System.Threading.CancellationToken
    return:
      type: System.Threading.Tasks.Task
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Azure.Management.V2.Resource.Authentication
  isExternal: false
  name: Microsoft.Azure.Management.V2.Resource.Authentication
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: TokenCache
  isExternal: true
  name: TokenCache
  fullName: TokenCache
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Resource.AzureEnvironment
  parent: Microsoft.Azure.Management.V2.Resource
  isExternal: false
  name: AzureEnvironment
  fullName: Microsoft.Azure.Management.V2.Resource.AzureEnvironment
- uid: Microsoft.Azure.Management.V2.Resource
  isExternal: false
  name: Microsoft.Azure.Management.V2.Resource
  fullName: Microsoft.Azure.Management.V2.Resource
- uid: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
  parent: Microsoft.Azure.Management.V2.Resource.Authentication
  isExternal: false
  name: ApplicationTokenCredentials
  fullName: Microsoft.Azure.Management.V2.Resource.Authentication.ApplicationTokenCredentials
- uid: HttpRequestMessage
  isExternal: true
  name: HttpRequestMessage
  fullName: HttpRequestMessage
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  name: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading
  isExternal: false
  name: System.Threading
  fullName: System.Threading
- uid: System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  fullName: System.Threading.Tasks
