items:
- uid: Microsoft.Azure.Management.Azure.Configurable
  commentId: T:Microsoft.Azure.Management.Azure.Configurable
  id: Azure.Configurable
  parent: Microsoft.Azure.Management
  children:
  - Microsoft.Azure.Management.Azure.Configurable.Microsoft#Azure#Management#Azure#IConfigurable#Authenticate(AzureCredentials)
  - Microsoft.Azure.Management.Azure.Configurable.Microsoft#Azure#Management#Azure#IConfigurable#Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: Azure.Configurable
  fullName: Microsoft.Azure.Management.Azure.Configurable
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Configurable
    path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
    startLine: 288
  assemblies:
  - Microsoft.Azure.Management
  packages:
  - Microsoft.Azure.Management(1.0.0)
  namespace: Microsoft.Azure.Management
  syntax:
    content: 'protected class Configurable : AzureConfigurable<Azure.IConfigurable>, Azure.IConfigurable, IAzureConfigurable<Azure.IConfigurable>'
    content.vb: >-
      Protected Class Configurable
          Inherits AzureConfigurable(Of Azure.IConfigurable)
          Implements Azure.IConfigurable, IAzureConfigurable(Of Azure.IConfigurable)
  inheritance:
  - System.Object
  implements:
  - Microsoft.Azure.Management.Azure.IConfigurable
  - IAzureConfigurable{Microsoft.Azure.Management.Azure.IConfigurable}
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
- uid: Microsoft.Azure.Management.Azure.Configurable.Microsoft#Azure#Management#Azure#IConfigurable#Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.Azure.Configurable.Microsoft#Azure#Management#Azure#IConfigurable#Authenticate(ServiceClientCredentials,System.String)
  id: Microsoft#Azure#Management#Azure#IConfigurable#Authenticate(ServiceClientCredentials,System.String)
  isEii: true
  parent: Microsoft.Azure.Management.Azure.Configurable
  langs:
  - csharp
  - vb
  name: Azure.IConfigurable.Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.Azure.Configurable.Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate
    path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
    startLine: 292
  assemblies:
  - Microsoft.Azure.Management
  packages:
  - Microsoft.Azure.Management(1.0.0)
  namespace: Microsoft.Azure.Management
  syntax:
    content: Azure.IAuthenticated Azure.IConfigurable.Authenticate(ServiceClientCredentials credentials, string tenantId)
    content.vb: Function Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(credentials As ServiceClientCredentials, tenantId As String) As Azure.IAuthenticated Implements Azure.IConfigurable.Authenticate
    parameters:
    - id: credentials
      type: ServiceClientCredentials
    - id: tenantId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Azure.IAuthenticated
  implements:
  - Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  name.vb: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials, String)
- uid: Microsoft.Azure.Management.Azure.Configurable.Microsoft#Azure#Management#Azure#IConfigurable#Authenticate(AzureCredentials)
  commentId: M:Microsoft.Azure.Management.Azure.Configurable.Microsoft#Azure#Management#Azure#IConfigurable#Authenticate(AzureCredentials)
  id: Microsoft#Azure#Management#Azure#IConfigurable#Authenticate(AzureCredentials)
  isEii: true
  parent: Microsoft.Azure.Management.Azure.Configurable
  langs:
  - csharp
  - vb
  name: Azure.IConfigurable.Authenticate(AzureCredentials)
  fullName: Microsoft.Azure.Management.Azure.Configurable.Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate
    path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
    startLine: 297
  assemblies:
  - Microsoft.Azure.Management
  packages:
  - Microsoft.Azure.Management(1.0.0)
  namespace: Microsoft.Azure.Management
  syntax:
    content: Azure.IAuthenticated Azure.IConfigurable.Authenticate(AzureCredentials credentials)
    content.vb: Function Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(credentials As AzureCredentials) As Azure.IAuthenticated Implements Azure.IConfigurable.Authenticate
    parameters:
    - id: credentials
      type: AzureCredentials
    return:
      type: Microsoft.Azure.Management.Azure.IAuthenticated
  implements:
  - Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
  name.vb: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
references:
- uid: Microsoft.Azure.Management
  isExternal: false
  name: Microsoft.Azure.Management
  fullName: Microsoft.Azure.Management
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Azure.IConfigurable
  parent: Microsoft.Azure.Management
  isExternal: false
  name: Azure.IConfigurable
  fullName: Microsoft.Azure.Management.Azure.IConfigurable
- uid: IAzureConfigurable{Microsoft.Azure.Management.Azure.IConfigurable}
  definition: IAzureConfigurable`1
  name: IAzureConfigurable<Azure.IConfigurable>
  fullName: IAzureConfigurable<Microsoft.Azure.Management.Azure.IConfigurable>
  fullname.vb: IAzureConfigurable(Of Microsoft.Azure.Management.Azure.IConfigurable)
  name.vb: IAzureConfigurable(Of Azure.IConfigurable)
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Azure.IConfigurable
    name: Azure.IConfigurable
    fullName: Microsoft.Azure.Management.Azure.IConfigurable
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Azure.IConfigurable
    name: Azure.IConfigurable
    fullName: Microsoft.Azure.Management.Azure.IConfigurable
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: IAzureConfigurable`1
  isExternal: true
  name: IAzureConfigurable<>
  fullName: IAzureConfigurable<>
  fullname.vb: IAzureConfigurable(Of )
  name.vb: IAzureConfigurable(Of )
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.Azure.IConfigurable
  isExternal: true
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Azure.IAuthenticated
  parent: Microsoft.Azure.Management
  isExternal: false
  name: Azure.IAuthenticated
  fullName: Microsoft.Azure.Management.Azure.IAuthenticated
- uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
  parent: Microsoft.Azure.Management.Azure.IConfigurable
  isExternal: true
  name: Authenticate(AzureCredentials)
  fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: AzureCredentials
    name: AzureCredentials
    fullName: AzureCredentials
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: AzureCredentials
    name: AzureCredentials
    fullName: AzureCredentials
    isExternal: true
  - name: )
    fullName: )
- uid: AzureCredentials
  isExternal: true
  name: AzureCredentials
  fullName: AzureCredentials
