items:
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  commentId: T:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  id: IWithConfigurations
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  children:
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDeploymentDisabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDeploymentEnabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDiskEncryptionDisabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDiskEncryptionEnabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithTemplateDeploymentDisabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithTemplateDeploymentEnabled
  langs:
  - csharp
  - vb
  name: IWithConfigurations
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithConfigurations
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
    startLine: 28
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  summary: "\nA key vault definition allowing various configurations to be set.\n"
  example: []
  syntax:
    content: public interface IWithConfigurations
    content.vb: Public Interface IWithConfigurations
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDeploymentEnabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDeploymentEnabled
  id: WithDeploymentEnabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithDeploymentEnabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDeploymentEnabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDeploymentEnabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  summary: "\nEnable Azure Virtual Machines to retrieve certificates stored as secrets from the key vault.\n"
  example: []
  syntax:
    content: IWithCreate WithDeploymentEnabled()
    content.vb: Function WithDeploymentEnabled As IWithCreate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithCreate
      description: the next stage of key vault definition
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDiskEncryptionEnabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDiskEncryptionEnabled
  id: WithDiskEncryptionEnabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithDiskEncryptionEnabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDiskEncryptionEnabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDiskEncryptionEnabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  summary: "\nEnable Azure Disk Encryption to retrieve secrets from the vault and unwrap keys.\n"
  example: []
  syntax:
    content: IWithCreate WithDiskEncryptionEnabled()
    content.vb: Function WithDiskEncryptionEnabled As IWithCreate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithCreate
      description: the next stage of key vault definition
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithTemplateDeploymentEnabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithTemplateDeploymentEnabled
  id: WithTemplateDeploymentEnabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithTemplateDeploymentEnabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithTemplateDeploymentEnabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithTemplateDeploymentEnabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  summary: "\nEnable Azure Resource Manager to retrieve secrets from the key vault.\n"
  example: []
  syntax:
    content: IWithCreate WithTemplateDeploymentEnabled()
    content.vb: Function WithTemplateDeploymentEnabled As IWithCreate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithCreate
      description: the next stage of key vault definition
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDeploymentDisabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDeploymentDisabled
  id: WithDeploymentDisabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithDeploymentDisabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDeploymentDisabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDeploymentDisabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  summary: "\nDisable Azure Virtual Machines to retrieve certificates stored as secrets from the key vault.\n"
  example: []
  syntax:
    content: IWithCreate WithDeploymentDisabled()
    content.vb: Function WithDeploymentDisabled As IWithCreate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithCreate
      description: the next stage of key vault definition
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDiskEncryptionDisabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDiskEncryptionDisabled
  id: WithDiskEncryptionDisabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithDiskEncryptionDisabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithDiskEncryptionDisabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDiskEncryptionDisabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
    startLine: 58
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  summary: "\nDisable Azure Disk Encryption to retrieve secrets from the vault and unwrap keys.\n"
  example: []
  syntax:
    content: IWithCreate WithDiskEncryptionDisabled()
    content.vb: Function WithDiskEncryptionDisabled As IWithCreate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithCreate
      description: the next stage of key vault definition
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithTemplateDeploymentDisabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithTemplateDeploymentDisabled
  id: WithTemplateDeploymentDisabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithTemplateDeploymentDisabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithConfigurations.WithTemplateDeploymentDisabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithTemplateDeploymentDisabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Definition/IDefinition.cs
    startLine: 64
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  summary: "\nDisable Azure Resource Manager to retrieve secrets from the key vault.\n"
  example: []
  syntax:
    content: IWithCreate WithTemplateDeploymentDisabled()
    content.vb: Function WithTemplateDeploymentDisabled As IWithCreate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithCreate
      description: the next stage of key vault definition
references:
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithCreate
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition
  isExternal: false
  name: IWithCreate
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Definition.IWithCreate
