items:
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  commentId: T:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  id: VirtualMachineScaleSetNetworkConfigurationInner
  parent: Microsoft.Azure.Management.Compute.Models
  children:
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.#ctor
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner},System.String,System.Nullable{System.Boolean})
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.IpConfigurations
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Name
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Primary
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Validate
  langs:
  - csharp
  - vb
  name: VirtualMachineScaleSetNetworkConfigurationInner
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: VirtualMachineScaleSetNetworkConfigurationInner
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
    startLine: 16
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nDescribes a virtual machine scale set network profile's network\nconfigurations.\n"
  example: []
  syntax:
    content: 'public class VirtualMachineScaleSetNetworkConfigurationInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class VirtualMachineScaleSetNetworkConfigurationInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.#ctor
  commentId: M:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  langs:
  - csharp
  - vb
  name: VirtualMachineScaleSetNetworkConfigurationInner()
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.VirtualMachineScaleSetNetworkConfigurationInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
    startLine: 23
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nInitializes a new instance of the\nVirtualMachineScaleSetNetworkConfigurationInner class.\n"
  example: []
  syntax:
    content: public VirtualMachineScaleSetNetworkConfigurationInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner},System.String,System.Nullable{System.Boolean})
  commentId: M:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner},System.String,System.Nullable{System.Boolean})
  id: '#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner},System.String,System.Nullable{System.Boolean})'
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  langs:
  - csharp
  - vb
  name: VirtualMachineScaleSetNetworkConfigurationInner(String, IList<VirtualMachineScaleSetIPConfigurationInner>, String, Nullable<Boolean>)
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.VirtualMachineScaleSetNetworkConfigurationInner(System.String, System.Collections.Generic.IList<Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner>, System.String, System.Nullable<System.Boolean>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nInitializes a new instance of the\nVirtualMachineScaleSetNetworkConfigurationInner class.\n"
  example: []
  syntax:
    content: public VirtualMachineScaleSetNetworkConfigurationInner(string name, IList<VirtualMachineScaleSetIPConfigurationInner> ipConfigurations, string id = null, bool ? primary = null)
    content.vb: Public Sub New(name As String, ipConfigurations As IList(Of VirtualMachineScaleSetIPConfigurationInner), id As String = Nothing, primary As Boolean? = Nothing)
    parameters:
    - id: name
      type: System.String
      description: the network configuration name.
    - id: ipConfigurations
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner}
      description: >-
        the virtual machine scale set IP

        Configuration.
    - id: id
      type: System.String
    - id: primary
      type: System.Nullable{System.Boolean}
      description: >-
        whether this is a primary NIC on a virtual

        machine.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.VirtualMachineScaleSetNetworkConfigurationInner(System.String, System.Collections.Generic.IList(Of Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner), System.String, System.Nullable(Of System.Boolean))
  name.vb: VirtualMachineScaleSetNetworkConfigurationInner(String, IList(Of VirtualMachineScaleSetIPConfigurationInner), String, Nullable(Of Boolean))
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Name
  commentId: P:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
    startLine: 45
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nGets or sets the network configuration name.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Primary
  commentId: P:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Primary
  id: Primary
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  langs:
  - csharp
  - vb
  name: Primary
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Primary
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Primary
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
    startLine: 51
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nGets or sets whether this is a primary NIC on a virtual machine.\n"
  example: []
  syntax:
    content: public bool ? Primary { get; set; }
    content.vb: Public Property Primary As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.IpConfigurations
  commentId: P:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.IpConfigurations
  id: IpConfigurations
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  langs:
  - csharp
  - vb
  name: IpConfigurations
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.IpConfigurations
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IpConfigurations
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
    startLine: 57
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nGets or sets the virtual machine scale set IP Configuration.\n"
  example: []
  syntax:
    content: public IList<VirtualMachineScaleSetIPConfigurationInner> IpConfigurations { get; set; }
    content.vb: Public Property IpConfigurations As IList(Of VirtualMachineScaleSetIPConfigurationInner)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Validate
  commentId: M:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Validate
  id: Validate
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner
  langs:
  - csharp
  - vb
  name: Validate()
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfigurationInner.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfigurationInner.cs
    startLine: 66
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nValidate the object.\n"
  example: []
  syntax:
    content: public virtual void Validate()
    content.vb: Public Overridable Sub Validate
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: Microsoft.Azure.Management.Compute.Models
  fullName: Microsoft.Azure.Management.Compute.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<VirtualMachineScaleSetIPConfigurationInner>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner)
  name.vb: IList(Of VirtualMachineScaleSetIPConfigurationInner)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner
    name: VirtualMachineScaleSetIPConfigurationInner
    fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner
    name: VirtualMachineScaleSetIPConfigurationInner
    fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfigurationInner
  - name: )
    fullName: )
- uid: System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
