### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult
  id: GetPublishedApplicationResult
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  children:
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult.#ctor
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult.Result
  langs:
  - csharp
  - vb
  name: GetPublishedApplicationResult
  nameWithType: GetPublishedApplicationResult
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult
  type: Class
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetPublishedApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: GetPublishedApplicationResult
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetPublishedApplicationResult.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nDefinition for result of GetPublishedApplication operation.\n"
  example: []
  syntax:
    content: 'public class GetPublishedApplicationResult : AzureOperationResponse'
    content.vb: >-
      Public Class GetPublishedApplicationResult
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult.Result
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult.Result
  id: Result
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult
  langs:
  - csharp
  - vb
  name: Result
  nameWithType: GetPublishedApplicationResult.Result
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult.Result
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetPublishedApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Result
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetPublishedApplicationResult.cs
    startLine: 38
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nOptional. Details of published application.\n"
  example: []
  syntax:
    content: public PublishedApplicationDetails Result { get; set; }
    content.vb: Public Property Result As PublishedApplicationDetails
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishedApplicationDetails
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult
  langs:
  - csharp
  - vb
  name: GetPublishedApplicationResult()
  nameWithType: GetPublishedApplicationResult.GetPublishedApplicationResult()
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetPublishedApplicationResult.GetPublishedApplicationResult()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetPublishedApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetPublishedApplicationResult.cs
    startLine: 48
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the GetPublishedApplicationResult\nclass.\n"
  example: []
  syntax:
    content: public GetPublishedApplicationResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models
  commentId: N:Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.RemoteApp.Models
  nameWithType: Microsoft.WindowsAzure.Management.RemoteApp.Models
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishedApplicationDetails
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishedApplicationDetails
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: PublishedApplicationDetails
  nameWithType: PublishedApplicationDetails
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishedApplicationDetails
