items:
- uid: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  commentId: N:Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  id: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  children:
  - Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IUpdate
  - Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IUpdateStages
  - Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithMode
  - Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithParameters
  - Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithTemplate
  langs:
  - csharp
  - vb
  name: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  fullName: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  type: Namespace
  assemblies:
  - Microsoft.Azure.Management.Fluent.ResourceManager
  packages:
  - Microsoft.Azure.Management.Fluent.ResourceManager(0.0.1-prerelease)
references:
- uid: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IUpdateStages
  isExternal: false
  name: IUpdateStages
  fullName: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IUpdateStages
- uid: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithMode
  parent: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  isExternal: false
  name: IWithMode
  fullName: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithMode
- uid: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IUpdate
- uid: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithParameters
  parent: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  isExternal: false
  name: IWithParameters
  fullName: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithParameters
- uid: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithTemplate
  parent: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  isExternal: false
  name: IWithTemplate
  fullName: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update.IWithTemplate
- uid: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
  fullName: Microsoft.Azure.Management.Fluent.Resource.Deployment.Update
