items:
- uid: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  commentId: T:Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  id: StorageManager.IConfigurable
  parent: Microsoft.Azure.Management.V2.Storage
  children:
  - Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: StorageManager.IConfigurable
  fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Storage/Microsoft.Azure.Management.V2.Storage/StorageManager.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/Storage/Microsoft.Azure.Management.V2.Storage/StorageManager.cs
    startLine: 75
  assemblies:
  - Microsoft.Azure.Management.V2.Storage
  packages:
  - Microsoft.Azure.Management.V2.Storage(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Storage
  summary: "\nThe inteface allowing configurations to be set.\n"
  example: []
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<StorageManager.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of StorageManager.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Storage/Microsoft.Azure.Management.V2.Storage/StorageManager.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Storage/Microsoft.Azure.Management.V2.Storage/StorageManager.cs
    startLine: 77
  assemblies:
  - Microsoft.Azure.Management.V2.Storage
  packages:
  - Microsoft.Azure.Management.V2.Storage(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Storage
  syntax:
    content: IStorageManager Authenticate(ServiceClientCredentials serviceClientCredentials, string subscriptionId)
    content.vb: Function Authenticate(serviceClientCredentials As ServiceClientCredentials, subscriptionId As String) As IStorageManager
    parameters:
    - id: serviceClientCredentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.V2.Storage.IStorageManager
references:
- uid: Microsoft.Azure.Management.V2.Storage
  isExternal: false
  name: Microsoft.Azure.Management.V2.Storage
  fullName: Microsoft.Azure.Management.V2.Storage
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Storage.IStorageManager
  parent: Microsoft.Azure.Management.V2.Storage
  isExternal: false
  name: IStorageManager
  fullName: Microsoft.Azure.Management.V2.Storage.IStorageManager
- uid: System
  isExternal: false
  name: System
  fullName: System
