items:
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisManager.IConfigurable
  commentId: T:Microsoft.Azure.Management.Fluent.Redis.RedisManager.IConfigurable
  id: RedisManager.IConfigurable
  parent: Microsoft.Azure.Management.Fluent.Redis
  children:
  - Microsoft.Azure.Management.Fluent.Redis.RedisManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: RedisManager.IConfigurable
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisManager.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/RedisManager.cs
      branch: 7974ca03c7d6cb8e0c00d1addc5f9f63a9402530
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/RedisManager.cs
    startLine: 53
  assemblies:
  - Microsoft.Azure.Management.Fluent.Redis
  packages:
  - Microsoft.Azure.Management.Fluent.Redis(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Redis
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<RedisManager.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of RedisManager.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Redis.RedisManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.Fluent.Redis.RedisManager.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/RedisManager.cs
      branch: 7974ca03c7d6cb8e0c00d1addc5f9f63a9402530
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/RedisManager.cs
    startLine: 55
  assemblies:
  - Microsoft.Azure.Management.Fluent.Redis
  packages:
  - Microsoft.Azure.Management.Fluent.Redis(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Redis
  syntax:
    content: IRedisManager Authenticate(ServiceClientCredentials serviceClientCredentials, string subscriptionId)
    content.vb: Function Authenticate(serviceClientCredentials As ServiceClientCredentials, subscriptionId As String) As IRedisManager
    parameters:
    - id: serviceClientCredentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.Redis.IRedisManager
references:
- uid: Microsoft.Azure.Management.Fluent.Redis
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Redis
  fullName: Microsoft.Azure.Management.Fluent.Redis
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Redis.IRedisManager
  parent: Microsoft.Azure.Management.Fluent.Redis
  isExternal: false
  name: IRedisManager
  fullName: Microsoft.Azure.Management.Fluent.Redis.IRedisManager
- uid: System
  isExternal: false
  name: System
  fullName: System
