items:
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage
  id: IWithApplicationAndStorage
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  children: []
  langs:
  - csharp
  - vb
  name: IWithApplicationAndStorage
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Definition/IDefinition.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithApplicationAndStorage
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Definition/IDefinition.cs
    startLine: 53
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  summary: "\nA batch account definition allowing defining application and storage account.\n"
  example: []
  syntax:
    content: 'public interface IWithApplicationAndStorage : IWithStorage, IWithApplication'
    content.vb: >-
      Public Interface IWithApplicationAndStorage
          Inherits IWithStorage, IWithApplication
  inheritedMembers:
  - Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithExistingStorageAccount(IStorageAccount)
  - Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(ICreatable{Microsoft.Azure.Management.V2.Storage.IStorageAccount})
  - Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(System.String)
  - Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithExistingStorageAccount(IStorageAccount)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage
  isExternal: true
  name: WithExistingStorageAccount(IStorageAccount)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithExistingStorageAccount(IStorageAccount)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithExistingStorageAccount(IStorageAccount)
    name: WithExistingStorageAccount
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithExistingStorageAccount
  - name: (
    fullName: (
  - uid: IStorageAccount
    name: IStorageAccount
    fullName: IStorageAccount
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithExistingStorageAccount(IStorageAccount)
    name: WithExistingStorageAccount
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithExistingStorageAccount
  - name: (
    fullName: (
  - uid: IStorageAccount
    name: IStorageAccount
    fullName: IStorageAccount
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(ICreatable{Microsoft.Azure.Management.V2.Storage.IStorageAccount})
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage
  isExternal: true
  name: WithNewStorageAccount(ICreatable<V2.Storage.IStorageAccount>)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(ICreatable<Microsoft.Azure.Management.V2.Storage.IStorageAccount>)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(ICreatable(Of Microsoft.Azure.Management.V2.Storage.IStorageAccount))
  name.vb: WithNewStorageAccount(ICreatable(Of V2.Storage.IStorageAccount))
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(ICreatable{Microsoft.Azure.Management.V2.Storage.IStorageAccount})
    name: WithNewStorageAccount
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Storage.IStorageAccount
    name: V2.Storage.IStorageAccount
    fullName: Microsoft.Azure.Management.V2.Storage.IStorageAccount
    isExternal: true
  - name: '>'
    fullName: '>'
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(ICreatable{Microsoft.Azure.Management.V2.Storage.IStorageAccount})
    name: WithNewStorageAccount
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Storage.IStorageAccount
    name: V2.Storage.IStorageAccount
    fullName: Microsoft.Azure.Management.V2.Storage.IStorageAccount
    isExternal: true
  - name: )
    fullName: )
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage
  isExternal: true
  name: WithNewStorageAccount(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(System.String)
    name: WithNewStorageAccount
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount(System.String)
    name: WithNewStorageAccount
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage.WithNewStorageAccount
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication
  isExternal: true
  name: DefineNewApplication(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
    name: DefineNewApplication
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
    name: DefineNewApplication
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  isExternal: false
  name: IWithStorage
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithStorage
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  isExternal: false
  name: IWithApplication
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication
