items:
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication
  id: IWithApplication
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
  children:
  - Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.DefineNewApplication(System.String)
  - Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.UpdateApplication(System.String)
  - Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.WithoutApplication(System.String)
  langs:
  - csharp
  - vb
  name: IWithApplication
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Update/IUpdate.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithApplication
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Update/IUpdate.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
  summary: "\nA batch account definition to allow creation of application.\n"
  example: []
  syntax:
    content: public interface IWithApplication
    content.vb: Public Interface IWithApplication
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.DefineNewApplication(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.DefineNewApplication(System.String)
  id: DefineNewApplication(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication
  langs:
  - csharp
  - vb
  name: DefineNewApplication(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.DefineNewApplication(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Update/IUpdate.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefineNewApplication
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Update/IUpdate.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
  summary: "\nSpecifies definition of an application to be created in a batch account.\n"
  example: []
  syntax:
    content: IBlank<IUpdate> DefineNewApplication(string applicationId)
    content.vb: Function DefineNewApplication(applicationId As String) As IBlank(Of IUpdate)
    parameters:
    - id: applicationId
      type: System.String
      description: applicationId the reference name for application
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank{Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate}
      description: the stage representing configuration for the extension
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.UpdateApplication(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.UpdateApplication(System.String)
  id: UpdateApplication(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication
  langs:
  - csharp
  - vb
  name: UpdateApplication(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.UpdateApplication(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Update/IUpdate.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: UpdateApplication
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Update/IUpdate.cs
    startLine: 63
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
  summary: "\nBegins the description of an update of an existing application of this batch account.\n"
  example: []
  syntax:
    content: IUpdate UpdateApplication(string applicationId)
    content.vb: Function UpdateApplication(applicationId As String) As IUpdate
    parameters:
    - id: applicationId
      type: System.String
      description: applicationId the reference name for the application to be updated
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
      description: the stage representing updatable application.
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.WithoutApplication(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.WithoutApplication(System.String)
  id: WithoutApplication(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication
  langs:
  - csharp
  - vb
  name: WithoutApplication(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IWithApplication.WithoutApplication(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Update/IUpdate.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithoutApplication
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Update/IUpdate.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
  summary: "\nDeletes specified application from the batch account.\n"
  example: []
  syntax:
    content: IUpdate WithoutApplication(string applicationId)
    content.vb: Function WithoutApplication(applicationId As String) As IUpdate
    parameters:
    - id: applicationId
      type: System.String
      description: applicationId the reference name for the application to be removed
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate
      description: the stage representing updatable batch account definition.
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank{Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate}
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank`1
  name: IBlank<IUpdate>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank<Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank(Of Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate)
  name.vb: IBlank(Of IUpdate)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate
    name: IUpdate
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate
    name: IUpdate
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  isExternal: false
  name: IBlank<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank(Of ParentT)
  name.vb: IBlank(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Update.IUpdate
