items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration
  id: ApplicationGatewayWebApplicationFirewallConfiguration
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.#ctor(System.Boolean,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.Enabled
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.FirewallMode
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.Validate
  langs:
  - csharp
  - vb
  name: ApplicationGatewayWebApplicationFirewallConfiguration
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayWebApplicationFirewallConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nApplication gateway web application firewall configuration\n"
  example: []
  syntax:
    content: public class ApplicationGatewayWebApplicationFirewallConfiguration
    content.vb: Public Class ApplicationGatewayWebApplicationFirewallConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration
  langs:
  - csharp
  - vb
  name: ApplicationGatewayWebApplicationFirewallConfiguration()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.ApplicationGatewayWebApplicationFirewallConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayWebApplicationFirewallConfiguration class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayWebApplicationFirewallConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.#ctor(System.Boolean,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.#ctor(System.Boolean,System.String)
  id: '#ctor(System.Boolean,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration
  langs:
  - csharp
  - vb
  name: ApplicationGatewayWebApplicationFirewallConfiguration(Boolean, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.ApplicationGatewayWebApplicationFirewallConfiguration(System.Boolean, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayWebApplicationFirewallConfiguration class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayWebApplicationFirewallConfiguration(bool enabled, string firewallMode = null)
    content.vb: Public Sub New(enabled As Boolean, firewallMode As String = Nothing)
    parameters:
    - id: enabled
      type: System.Boolean
    - id: firewallMode
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.Enabled
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.Enabled
  id: Enabled
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration
  langs:
  - csharp
  - vb
  name: Enabled
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.Enabled
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Enabled
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nWhether web application firewall is enabled\n"
  example: []
  syntax:
    content: public bool Enabled { get; set; }
    content.vb: Public Property Enabled As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.FirewallMode
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.FirewallMode
  id: FirewallMode
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration
  langs:
  - csharp
  - vb
  name: FirewallMode
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.FirewallMode
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: FirewallMode
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nWeb application firewall mode. Possible values include:\n'Detection', 'Prevention'\n"
  example: []
  syntax:
    content: public string FirewallMode { get; set; }
    content.vb: Public Property FirewallMode As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.Validate
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.Validate
  id: Validate
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration
  langs:
  - csharp
  - vb
  name: Validate()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayWebApplicationFirewallConfiguration.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayWebApplicationFirewallConfiguration.cs
    startLine: 55
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nValidate the object. Throws ValidationException if validation fails.\n"
  example: []
  syntax:
    content: public virtual void Validate()
    content.vb: Public Overridable Sub Validate
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
