items:
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  commentId: T:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  id: VirtualMachineScaleSetNetworkConfiguration
  parent: Microsoft.Azure.Management.Compute.Models
  children:
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.#ctor
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration},System.String,System.Nullable{System.Boolean})
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.IpConfigurations
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Name
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Primary
  - Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Validate
  langs:
  - csharp
  - vb
  name: VirtualMachineScaleSetNetworkConfiguration
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
      branch: 8b1b76897c698a666a3f6c751a7ae04f4356a59f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: VirtualMachineScaleSetNetworkConfiguration
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.Compute
  packages:
  - Microsoft.Azure.Management.Compute(13.0.4-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nDescribes a virtual machine scale set network profile's network\nconfigurations.\n"
  example: []
  syntax:
    content: 'public class VirtualMachineScaleSetNetworkConfiguration : SubResource'
    content.vb: >-
      Public Class VirtualMachineScaleSetNetworkConfiguration
          Inherits SubResource
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Compute.Models.SubResource
  inheritedMembers:
  - Microsoft.Azure.Management.Compute.Models.SubResource.Id
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  langs:
  - csharp
  - vb
  name: VirtualMachineScaleSetNetworkConfiguration()
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.VirtualMachineScaleSetNetworkConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
      branch: 8b1b76897c698a666a3f6c751a7ae04f4356a59f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Compute
  packages:
  - Microsoft.Azure.Management.Compute(13.0.4-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nInitializes a new instance of the\nVirtualMachineScaleSetNetworkConfiguration class.\n"
  example: []
  syntax:
    content: public VirtualMachineScaleSetNetworkConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration},System.String,System.Nullable{System.Boolean})
  commentId: M:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration},System.String,System.Nullable{System.Boolean})
  id: '#ctor(System.String,System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration},System.String,System.Nullable{System.Boolean})'
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  langs:
  - csharp
  - vb
  name: VirtualMachineScaleSetNetworkConfiguration(String, IList<VirtualMachineScaleSetIPConfiguration>, String, Nullable<Boolean>)
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.VirtualMachineScaleSetNetworkConfiguration(System.String, System.Collections.Generic.IList<Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration>, System.String, System.Nullable<System.Boolean>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
      branch: 8b1b76897c698a666a3f6c751a7ae04f4356a59f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
    startLine: 35
  assemblies:
  - Microsoft.Azure.Management.Compute
  packages:
  - Microsoft.Azure.Management.Compute(13.0.4-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nInitializes a new instance of the\nVirtualMachineScaleSetNetworkConfiguration class.\n"
  example: []
  syntax:
    content: public VirtualMachineScaleSetNetworkConfiguration(string name, IList<VirtualMachineScaleSetIPConfiguration> ipConfigurations, string id = null, bool ? primary = null)
    content.vb: Public Sub New(name As String, ipConfigurations As IList(Of VirtualMachineScaleSetIPConfiguration), id As String = Nothing, primary As Boolean? = Nothing)
    parameters:
    - id: name
      type: System.String
    - id: ipConfigurations
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration}
    - id: id
      type: System.String
    - id: primary
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.VirtualMachineScaleSetNetworkConfiguration(System.String, System.Collections.Generic.IList(Of Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration), System.String, System.Nullable(Of System.Boolean))
  name.vb: VirtualMachineScaleSetNetworkConfiguration(String, IList(Of VirtualMachineScaleSetIPConfiguration), String, Nullable(Of Boolean))
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Name
  commentId: P:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Name
  id: Name
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
      branch: 8b1b76897c698a666a3f6c751a7ae04f4356a59f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Compute
  packages:
  - Microsoft.Azure.Management.Compute(13.0.4-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nthe network configuration name.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Primary
  commentId: P:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Primary
  id: Primary
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  langs:
  - csharp
  - vb
  name: Primary
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Primary
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
      branch: 8b1b76897c698a666a3f6c751a7ae04f4356a59f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Primary
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.Compute
  packages:
  - Microsoft.Azure.Management.Compute(13.0.4-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nwhether this is a primary NIC on a virtual machine.\n"
  example: []
  syntax:
    content: public bool ? Primary { get; set; }
    content.vb: Public Property Primary As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.IpConfigurations
  commentId: P:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.IpConfigurations
  id: IpConfigurations
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  langs:
  - csharp
  - vb
  name: IpConfigurations
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.IpConfigurations
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
      branch: 8b1b76897c698a666a3f6c751a7ae04f4356a59f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IpConfigurations
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
    startLine: 58
  assemblies:
  - Microsoft.Azure.Management.Compute
  packages:
  - Microsoft.Azure.Management.Compute(13.0.4-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nthe virtual machine scale set IP Configuration.\n"
  example: []
  syntax:
    content: public IList<VirtualMachineScaleSetIPConfiguration> IpConfigurations { get; set; }
    content.vb: Public Property IpConfigurations As IList(Of VirtualMachineScaleSetIPConfiguration)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Validate
  commentId: M:Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Validate
  id: Validate
  parent: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration
  langs:
  - csharp
  - vb
  name: Validate()
  fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetNetworkConfiguration.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
      branch: 8b1b76897c698a666a3f6c751a7ae04f4356a59f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Compute/Generated/Models/VirtualMachineScaleSetNetworkConfiguration.cs
    startLine: 64
  assemblies:
  - Microsoft.Azure.Management.Compute
  packages:
  - Microsoft.Azure.Management.Compute(13.0.4-prerelease)
  namespace: Microsoft.Azure.Management.Compute.Models
  summary: "\nValidate the object. Throws ValidationException if validation fails.\n"
  example: []
  syntax:
    content: public virtual void Validate()
    content.vb: Public Overridable Sub Validate
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: Microsoft.Azure.Management.Compute.Models
  fullName: Microsoft.Azure.Management.Compute.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Compute.Models.SubResource
  parent: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: SubResource
  fullName: Microsoft.Azure.Management.Compute.Models.SubResource
- uid: Microsoft.Azure.Management.Compute.Models.SubResource.Id
  parent: Microsoft.Azure.Management.Compute.Models.SubResource
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.Compute.Models.SubResource.Id
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<VirtualMachineScaleSetIPConfiguration>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration)
  name.vb: IList(Of VirtualMachineScaleSetIPConfiguration)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration
    name: VirtualMachineScaleSetIPConfiguration
    fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration
    name: VirtualMachineScaleSetIPConfiguration
    fullName: Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSetIPConfiguration
  - name: )
    fullName: )
- uid: System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
