items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition`1
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition`1
  id: IDefinition`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  children: []
  langs:
  - csharp
  - vb
  name: IDefinition<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IDefinition
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
    startLine: 12
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  syntax:
    content: 'public interface IDefinition<ParentT> : IBlank<ParentT>, IWithAttach<ParentT>, IInDefinition<ParentT>, IWithApplicationPackage<ParentT>'
    content.vb: >-
      Public Interface IDefinition(Of ParentT)
          Inherits IBlank(Of ParentT), IWithAttach(Of ParentT)
    typeParameters:
    - id: ParentT
  inheritedMembers:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}.WithAllowUpdates(System.Boolean)
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}.WithDisplayName(System.String)
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage{{ParentT}}.DefineNewApplicationPackage(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition(Of ParentT)
  name.vb: IDefinition(Of ParentT)
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}.WithAllowUpdates(System.Boolean)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
  name: WithAllowUpdates(Boolean)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithAllowUpdates(System.Boolean)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithAllowUpdates(System.Boolean)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
    name: WithAllowUpdates
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithAllowUpdates
  - name: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
    name: WithAllowUpdates
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithAllowUpdates
  - name: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}.WithDisplayName(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
  name: WithDisplayName(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithDisplayName(System.String)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithDisplayName(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
    name: WithDisplayName
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithDisplayName
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
    name: WithDisplayName
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithDisplayName
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage{{ParentT}}.DefineNewApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage{{ParentT}}
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  name: DefineNewApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage(System.String)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  isExternal: true
  name: WithAllowUpdates(Boolean)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithAllowUpdates(System.Boolean)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithAllowUpdates(System.Boolean)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
    name: WithAllowUpdates
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithAllowUpdates
  - name: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
    name: WithAllowUpdates
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithAllowUpdates
  - name: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  isExternal: true
  name: WithDisplayName(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithDisplayName(System.String)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithDisplayName(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
    name: WithDisplayName
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithDisplayName
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
    name: WithDisplayName
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithDisplayName
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  isExternal: true
  name: DefineNewApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage(System.String)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage{{ParentT}}
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  name: IWithApplicationPackage<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT)
  name.vb: IWithApplicationPackage(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IWithApplicationPackage<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT)
  name.vb: IWithApplicationPackage(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
