items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1
  id: IWithPublicIpAddress`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  children:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
  langs:
  - csharp
  - vb
  name: IWithPublicIpAddress<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 74
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  syntax:
    content: public interface IWithPublicIpAddress<ParentT>
    content.vb: Public Interface IWithPublicIpAddress(Of ParentT)
    typeParameters:
    - id: ParentT
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress(Of ParentT)
  name.vb: IWithPublicIpAddress(Of ParentT)
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  id: WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1
  langs:
  - csharp
  - vb
  name: WithNewPublicIpAddress(ICreatable<IPublicIpAddress>)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress(ICreatable<Microsoft.Azure.Management.V2.Network.IPublicIpAddress>)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 82
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  summary: "\nCreate a new public IP address to associate with the network interface IP configuration,\nbased on the provided definition.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithNewPublicIpAddress(ICreatable<IPublicIpAddress> creatable)
    content.vb: Function WithNewPublicIpAddress(creatable As ICreatable(Of IPublicIpAddress)) As IWithAttach(Of ParentT)
    parameters:
    - id: creatable
      type: ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress}
      description: creatable a creatable definition for a new public IP
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach{{ParentT}}
      description: the next stage of the network interface IP configuration definition
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress(ICreatable(Of Microsoft.Azure.Management.V2.Network.IPublicIpAddress))
  name.vb: WithNewPublicIpAddress(ICreatable(Of IPublicIpAddress))
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress
  id: WithNewPublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1
  langs:
  - csharp
  - vb
  name: WithNewPublicIpAddress()
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 91
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  syntax:
    content: IWithAttach<ParentT> WithNewPublicIpAddress()
    content.vb: Function WithNewPublicIpAddress As IWithAttach(Of ParentT)
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach{{ParentT}}
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress()
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
  id: WithNewPublicIpAddress(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1
  langs:
  - csharp
  - vb
  name: WithNewPublicIpAddress(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 101
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  syntax:
    content: IWithAttach<ParentT> WithNewPublicIpAddress(string leafDnsLabel)
    content.vb: Function WithNewPublicIpAddress(leafDnsLabel As String) As IWithAttach(Of ParentT)
    parameters:
    - id: leafDnsLabel
      type: System.String
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach{{ParentT}}
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress(System.String)
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  id: WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress`1
  langs:
  - csharp
  - vb
  name: WithExistingPublicIpAddress(IPublicIpAddress)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress<ParentT>.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithExistingPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 108
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  summary: "\nAssociates an existing public IP address with the network interface IP configuration.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithExistingPublicIpAddress(IPublicIpAddress publicIpAddress)
    content.vb: Function WithExistingPublicIpAddress(publicIpAddress As IPublicIpAddress) As IWithAttach(Of ParentT)
    parameters:
    - id: publicIpAddress
      type: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
      description: publicIpAddress an existing public IP address
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach{{ParentT}}
      description: the next stage of the IP configuration definition
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPublicIpAddress(Of ParentT).WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
- uid: ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress}
  definition: ICreatable`1
  name: ICreatable<IPublicIpAddress>
  fullName: ICreatable<Microsoft.Azure.Management.V2.Network.IPublicIpAddress>
  fullname.vb: ICreatable(Of Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  name.vb: ICreatable(Of IPublicIpAddress)
  spec.csharp:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach{{ParentT}}
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: ICreatable`1
  isExternal: true
  name: ICreatable<>
  fullName: ICreatable<>
  fullname.vb: ICreatable(Of )
  name.vb: ICreatable(Of )
  spec.csharp:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: IPublicIpAddress
  fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
- uid: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network
  fullName: Microsoft.Azure.Management.V2.Network
