items:
- uid: Microsoft.Azure.Management.V2.Batch.BatchManager.IConfigurable
  commentId: T:Microsoft.Azure.Management.V2.Batch.BatchManager.IConfigurable
  id: BatchManager.IConfigurable
  parent: Microsoft.Azure.Management.V2.Batch
  children:
  - Microsoft.Azure.Management.V2.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: BatchManager.IConfigurable
  fullName: Microsoft.Azure.Management.V2.Batch.BatchManager.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/BatchManager.cs
      branch: a22251cda68f724317d3ae2d0ae390f6642eb358
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/BatchManager.cs
    startLine: 57
  assemblies:
  - Microsoft.Azure.Management.V2.Batch
  packages:
  - Microsoft.Azure.Management.V2.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Batch
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<BatchManager.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of BatchManager.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.V2.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.V2.Batch.BatchManager.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.V2.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/BatchManager.cs
      branch: a22251cda68f724317d3ae2d0ae390f6642eb358
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/BatchManager.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.V2.Batch
  packages:
  - Microsoft.Azure.Management.V2.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Batch
  syntax:
    content: IBatchManager Authenticate(ServiceClientCredentials serviceClientCredentials, string subscriptionId)
    content.vb: Function Authenticate(serviceClientCredentials As ServiceClientCredentials, subscriptionId As String) As IBatchManager
    parameters:
    - id: serviceClientCredentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.V2.Batch.IBatchManager
references:
- uid: Microsoft.Azure.Management.V2.Batch
  isExternal: false
  name: Microsoft.Azure.Management.V2.Batch
  fullName: Microsoft.Azure.Management.V2.Batch
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Batch.IBatchManager
  parent: Microsoft.Azure.Management.V2.Batch
  isExternal: false
  name: IBatchManager
  fullName: Microsoft.Azure.Management.V2.Batch.IBatchManager
- uid: System
  isExternal: false
  name: System
  fullName: System
