items:
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IWithEnvironment
  commentId: T:Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IWithEnvironment
  id: RestClient.RestClientBuilder.IWithEnvironment
  parent: Microsoft.Azure.Management.Fluent.Resource.Core
  children:
  - Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IWithEnvironment.withEnvironment(Microsoft.Azure.Management.Fluent.Resource.AzureEnvironment)
  langs:
  - csharp
  - vb
  name: RestClient.RestClientBuilder.IWithEnvironment
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IWithEnvironment
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Core/RestClient/RestClient.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithEnvironment
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Core/RestClient/RestClient.cs
    startLine: 92
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Resource.Core
  syntax:
    content: public interface IWithEnvironment
    content.vb: Public Interface IWithEnvironment
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IWithEnvironment.withEnvironment(Microsoft.Azure.Management.Fluent.Resource.AzureEnvironment)
  commentId: M:Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IWithEnvironment.withEnvironment(Microsoft.Azure.Management.Fluent.Resource.AzureEnvironment)
  id: withEnvironment(Microsoft.Azure.Management.Fluent.Resource.AzureEnvironment)
  parent: Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IWithEnvironment
  langs:
  - csharp
  - vb
  name: withEnvironment(AzureEnvironment)
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IWithEnvironment.withEnvironment(Microsoft.Azure.Management.Fluent.Resource.AzureEnvironment)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Core/RestClient/RestClient.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: withEnvironment
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Core/RestClient/RestClient.cs
    startLine: 94
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Resource.Core
  syntax:
    content: RestClient.RestClientBuilder.IBuildable withEnvironment(AzureEnvironment environment)
    content.vb: Function withEnvironment(environment As AzureEnvironment) As RestClient.RestClientBuilder.IBuildable
    parameters:
    - id: environment
      type: Microsoft.Azure.Management.Fluent.Resource.AzureEnvironment
    return:
      type: Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IBuildable
references:
- uid: Microsoft.Azure.Management.Fluent.Resource.Core
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Resource.Core
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core
- uid: Microsoft.Azure.Management.Fluent.Resource.AzureEnvironment
  parent: Microsoft.Azure.Management.Fluent.Resource
  isExternal: false
  name: AzureEnvironment
  fullName: Microsoft.Azure.Management.Fluent.Resource.AzureEnvironment
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IBuildable
  parent: Microsoft.Azure.Management.Fluent.Resource.Core
  isExternal: false
  name: RestClient.RestClientBuilder.IBuildable
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.RestClient.RestClientBuilder.IBuildable
- uid: Microsoft.Azure.Management.Fluent.Resource
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Resource
  fullName: Microsoft.Azure.Management.Fluent.Resource
