items:
- uid: Microsoft.Azure.Management.V2.Network.NetworkManager.IConfigurable
  commentId: T:Microsoft.Azure.Management.V2.Network.NetworkManager.IConfigurable
  id: NetworkManager.IConfigurable
  parent: Microsoft.Azure.Management.V2.Network
  children:
  - Microsoft.Azure.Management.V2.Network.NetworkManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: NetworkManager.IConfigurable
  fullName: Microsoft.Azure.Management.V2.Network.NetworkManager.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/NetworkManager.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/NetworkManager.cs
    startLine: 68
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  summary: "\nThe inteface allowing configurations to be set.\n"
  example: []
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<NetworkManager.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of NetworkManager.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Network.NetworkManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NetworkManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.V2.Network.NetworkManager.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.V2.Network.NetworkManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/NetworkManager.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/NetworkManager.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  syntax:
    content: INetworkManager Authenticate(ServiceClientCredentials serviceClientCredentials, string subscriptionId)
    content.vb: Function Authenticate(serviceClientCredentials As ServiceClientCredentials, subscriptionId As String) As INetworkManager
    parameters:
    - id: serviceClientCredentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.V2.Network.INetworkManager
references:
- uid: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network
  fullName: Microsoft.Azure.Management.V2.Network
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Network.INetworkManager
  parent: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: INetworkManager
  fullName: Microsoft.Azure.Management.V2.Network.INetworkManager
- uid: System
  isExternal: false
  name: System
  fullName: System
