items:
- uid: Microsoft.Azure.Management.Azure.IConfigurable
  commentId: T:Microsoft.Azure.Management.Azure.IConfigurable
  id: Azure.IConfigurable
  parent: Microsoft.Azure.Management
  children:
  - Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
  - Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: Azure.IConfigurable
  fullName: Microsoft.Azure.Management.Azure.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
    startLine: 281
  assemblies:
  - Microsoft.Azure.Management
  packages:
  - Microsoft.Azure.Management(1.0.0)
  namespace: Microsoft.Azure.Management
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<Azure.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of Azure.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.Azure.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
    startLine: 283
  assemblies:
  - Microsoft.Azure.Management
  packages:
  - Microsoft.Azure.Management(1.0.0)
  namespace: Microsoft.Azure.Management
  syntax:
    content: Azure.IAuthenticated Authenticate(ServiceClientCredentials serviceClientCredentials, string tenantId)
    content.vb: Function Authenticate(serviceClientCredentials As ServiceClientCredentials, tenantId As String) As Azure.IAuthenticated
    parameters:
    - id: serviceClientCredentials
      type: ServiceClientCredentials
    - id: tenantId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Azure.IAuthenticated
- uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
  commentId: M:Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
  id: Authenticate(AzureCredentials)
  parent: Microsoft.Azure.Management.Azure.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(AzureCredentials)
  fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(AzureCredentials)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
    startLine: 285
  assemblies:
  - Microsoft.Azure.Management
  packages:
  - Microsoft.Azure.Management(1.0.0)
  namespace: Microsoft.Azure.Management
  syntax:
    content: Azure.IAuthenticated Authenticate(AzureCredentials azureCredentials)
    content.vb: Function Authenticate(azureCredentials As AzureCredentials) As Azure.IAuthenticated
    parameters:
    - id: azureCredentials
      type: AzureCredentials
    return:
      type: Microsoft.Azure.Management.Azure.IAuthenticated
references:
- uid: Microsoft.Azure.Management
  isExternal: false
  name: Microsoft.Azure.Management
  fullName: Microsoft.Azure.Management
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Azure.IAuthenticated
  parent: Microsoft.Azure.Management
  isExternal: false
  name: Azure.IAuthenticated
  fullName: Microsoft.Azure.Management.Azure.IAuthenticated
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: AzureCredentials
  isExternal: true
  name: AzureCredentials
  fullName: AzureCredentials
