items:
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration
  commentId: T:Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration
  id: IWithRedisConfiguration
  parent: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  children:
  - Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithoutRedisConfiguration
  - Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithoutRedisConfiguration(System.String)
  - Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.Collections.Generic.IDictionary{System.String,System.String})
  - Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.String,System.String)
  langs:
  - csharp
  - vb
  name: IWithRedisConfiguration
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithRedisConfiguration
    path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.Fluent.Redis
  packages:
  - Microsoft.Azure.Management.Fluent.Redis(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  summary: "\nA Redis Cache update allowing Redis configuration to be modified.\n"
  example: []
  syntax:
    content: public interface IWithRedisConfiguration
    content.vb: Public Interface IWithRedisConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.Collections.Generic.IDictionary{System.String,System.String})
  commentId: M:Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.Collections.Generic.IDictionary{System.String,System.String})
  id: WithRedisConfiguration(System.Collections.Generic.IDictionary{System.String,System.String})
  parent: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration
  langs:
  - csharp
  - vb
  name: WithRedisConfiguration(IDictionary<String, String>)
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.Collections.Generic.IDictionary<System.String, System.String>)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithRedisConfiguration
    path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
    startLine: 44
  assemblies:
  - Microsoft.Azure.Management.Fluent.Redis
  packages:
  - Microsoft.Azure.Management.Fluent.Redis(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  summary: "\nAll Redis Settings. Few possible keys:\nrdb-backup-enabled, rdb-storage-connection-string, rdb-backup-frequency, maxmemory-delta, maxmemory-policy,\nnotify-keyspace-events, maxmemory-samples, slowlog-log-slower-than, slowlog-max-len, list-max-ziplist-entries,\nlist-max-ziplist-value, hash-max-ziplist-entries, hash-max-ziplist-value, set -max-intset-entries,\nzset-max-ziplist-entries, zset-max-ziplist-value etc.\n"
  example: []
  syntax:
    content: IUpdate WithRedisConfiguration(IDictionary<string, string> redisConfiguration)
    content.vb: Function WithRedisConfiguration(redisConfiguration As IDictionary(Of String, String)) As IUpdate
    parameters:
    - id: redisConfiguration
      type: System.Collections.Generic.IDictionary{System.String,System.String}
      description: redisConfiguration configuration of Redis Cache as a map indexed by configuration name
    return:
      type: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IUpdate
      description: the next stage of Redis Cache update.
  fullName.vb: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.Collections.Generic.IDictionary(Of System.String, System.String))
  name.vb: WithRedisConfiguration(IDictionary(Of String, String))
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.String,System.String)
  id: WithRedisConfiguration(System.String,System.String)
  parent: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration
  langs:
  - csharp
  - vb
  name: WithRedisConfiguration(String, String)
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithRedisConfiguration(System.String, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithRedisConfiguration
    path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Fluent.Redis
  packages:
  - Microsoft.Azure.Management.Fluent.Redis(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  summary: "\nSpecifies Redis Setting.\nrdb-backup-enabled, rdb-storage-connection-string, rdb-backup-frequency, maxmemory-delta, maxmemory-policy,\nnotify-keyspace-events, maxmemory-samples, slowlog-log-slower-than, slowlog-max-len, list-max-ziplist-entries,\nlist-max-ziplist-value, hash-max-ziplist-entries, hash-max-ziplist-value, set -max-intset-entries,\nzset-max-ziplist-entries, zset-max-ziplist-value etc.\n"
  example: []
  syntax:
    content: IUpdate WithRedisConfiguration(string key, string value)
    content.vb: Function WithRedisConfiguration(key As String, value As String) As IUpdate
    parameters:
    - id: key
      type: System.String
      description: key   Redis configuration name.
    - id: value
      type: System.String
      description: value Redis configuration value.
    return:
      type: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IUpdate
      description: the next stage of Redis Cache update.
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithoutRedisConfiguration
  commentId: M:Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithoutRedisConfiguration
  id: WithoutRedisConfiguration
  parent: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration
  langs:
  - csharp
  - vb
  name: WithoutRedisConfiguration()
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithoutRedisConfiguration()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithoutRedisConfiguration
    path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
    startLine: 62
  assemblies:
  - Microsoft.Azure.Management.Fluent.Redis
  packages:
  - Microsoft.Azure.Management.Fluent.Redis(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  summary: "\nCleans all the configuration settings being set on Redis Cache.\n"
  example: []
  syntax:
    content: IUpdate WithoutRedisConfiguration()
    content.vb: Function WithoutRedisConfiguration As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IUpdate
      description: the next stage of Redis Cache update.
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithoutRedisConfiguration(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithoutRedisConfiguration(System.String)
  id: WithoutRedisConfiguration(System.String)
  parent: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration
  langs:
  - csharp
  - vb
  name: WithoutRedisConfiguration(String)
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IWithRedisConfiguration.WithoutRedisConfiguration(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithoutRedisConfiguration
    path: src/ResourceManagement/RedisCache/Microsoft.Azure.Management.Fluent.Redis/Domain/RedisCache/Update/IUpdate.cs
    startLine: 69
  assemblies:
  - Microsoft.Azure.Management.Fluent.Redis
  packages:
  - Microsoft.Azure.Management.Fluent.Redis(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  summary: "\nRemoves specified Redis Cache configuration setting.\n"
  example: []
  syntax:
    content: IUpdate WithoutRedisConfiguration(string key)
    content.vb: Function WithoutRedisConfiguration(key As String) As IUpdate
    parameters:
    - id: key
      type: System.String
      description: key Redis configuration name.
    return:
      type: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IUpdate
      description: the next stage of Redis Cache update.
references:
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
- uid: System.Collections.Generic.IDictionary{System.String,System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  name: IDictionary<String, String>
  fullName: System.Collections.Generic.IDictionary<System.String, System.String>
  fullname.vb: System.Collections.Generic.IDictionary(Of System.String, System.String)
  name.vb: IDictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Redis.RedisCache.Update.IUpdate
- uid: System.Collections.Generic.IDictionary`2
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  fullname.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
