items:
- uid: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  commentId: T:Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  id: MonitorConfig
  parent: Microsoft.Azure.Management.TrafficManager.Models
  children:
  - Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.#ctor
  - Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.#ctor(System.String,System.String,System.Nullable{System.Int64},System.String)
  - Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Path
  - Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Port
  - Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.ProfileMonitorStatus
  - Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Protocol
  langs:
  - csharp
  - vb
  name: MonitorConfig
  fullName: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  type: Class
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
      branch: 47afe683d699d960e0c708603e1600ddd33fbbb3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: MonitorConfig
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
    startLine: 18
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nClass containing endpoint monitoring settings in a Traffic Manager\nprofile.\n"
  example: []
  syntax:
    content: public class MonitorConfig
    content.vb: Public Class MonitorConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.#ctor
  commentId: M:Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  langs:
  - csharp
  - vb
  name: MonitorConfig()
  fullName: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.MonitorConfig()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
      branch: 47afe683d699d960e0c708603e1600ddd33fbbb3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
    startLine: 23
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nInitializes a new instance of the MonitorConfig class.\n"
  example: []
  syntax:
    content: public MonitorConfig()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.#ctor(System.String,System.String,System.Nullable{System.Int64},System.String)
  commentId: M:Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.#ctor(System.String,System.String,System.Nullable{System.Int64},System.String)
  id: '#ctor(System.String,System.String,System.Nullable{System.Int64},System.String)'
  parent: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  langs:
  - csharp
  - vb
  name: MonitorConfig(String, String, Nullable<Int64>, String)
  fullName: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.MonitorConfig(System.String, System.String, System.Nullable<System.Int64>, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
      branch: 47afe683d699d960e0c708603e1600ddd33fbbb3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
    startLine: 28
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nInitializes a new instance of the MonitorConfig class.\n"
  example: []
  syntax:
    content: public MonitorConfig(string profileMonitorStatus = null, string protocol = null, long ? port = null, string path = null)
    content.vb: Public Sub New(profileMonitorStatus As String = Nothing, protocol As String = Nothing, port As Long? = Nothing, path As String = Nothing)
    parameters:
    - id: profileMonitorStatus
      type: System.String
    - id: protocol
      type: System.String
    - id: port
      type: System.Nullable{System.Int64}
    - id: path
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.MonitorConfig(System.String, System.String, System.Nullable(Of System.Int64), System.String)
  name.vb: MonitorConfig(String, String, Nullable(Of Int64), String)
- uid: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.ProfileMonitorStatus
  commentId: P:Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.ProfileMonitorStatus
  id: ProfileMonitorStatus
  parent: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  langs:
  - csharp
  - vb
  name: ProfileMonitorStatus
  fullName: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.ProfileMonitorStatus
  type: Property
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
      branch: 47afe683d699d960e0c708603e1600ddd33fbbb3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProfileMonitorStatus
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nGets or sets the profile-level monitoring status of the Traffic\nManager profile.\n"
  example: []
  syntax:
    content: public string ProfileMonitorStatus { get; set; }
    content.vb: Public Property ProfileMonitorStatus As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Protocol
  commentId: P:Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Protocol
  id: Protocol
  parent: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  langs:
  - csharp
  - vb
  name: Protocol
  fullName: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Protocol
  type: Property
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
      branch: 47afe683d699d960e0c708603e1600ddd33fbbb3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Protocol
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nGets or sets the protocol (HTTP or HTTPS) used to probe for\nendpoint health.\n"
  example: []
  syntax:
    content: public string Protocol { get; set; }
    content.vb: Public Property Protocol As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Port
  commentId: P:Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Port
  id: Port
  parent: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  langs:
  - csharp
  - vb
  name: Port
  fullName: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Port
  type: Property
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
      branch: 47afe683d699d960e0c708603e1600ddd33fbbb3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Port
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
    startLine: 53
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nGets or sets the TCP port used to probe for endpoint health.\n"
  example: []
  syntax:
    content: public long ? Port { get; set; }
    content.vb: Public Property Port As Long?
    parameters: []
    return:
      type: System.Nullable{System.Int64}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Path
  commentId: P:Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Path
  id: Path
  parent: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig
  langs:
  - csharp
  - vb
  name: Path
  fullName: Microsoft.Azure.Management.TrafficManager.Models.MonitorConfig.Path
  type: Property
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
      branch: 47afe683d699d960e0c708603e1600ddd33fbbb3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Path
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/MonitorConfig.cs
    startLine: 60
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nGets or sets the path relative to the endpoint domain name used to\nprobe for endpoint health.\n"
  example: []
  syntax:
    content: public string Path { get; set; }
    content.vb: Public Property Path As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.TrafficManager.Models
  isExternal: false
  name: Microsoft.Azure.Management.TrafficManager.Models
  fullName: Microsoft.Azure.Management.TrafficManager.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.Int64}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int64>
  fullName: System.Nullable<System.Int64>
  fullname.vb: System.Nullable(Of System.Int64)
  name.vb: Nullable(Of Int64)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int64
    name: Int64
    fullName: System.Int64
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int64
    name: Int64
    fullName: System.Int64
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
