items:
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  commentId: T:Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  id: IPConfigurationInner
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.#ctor
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.#ctor(System.String,System.String,System.String,Microsoft.Azure.Management.Network.Models.SubnetInner,Microsoft.Azure.Management.Network.Models.PublicIPAddressInner,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Etag
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Name
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PrivateIPAddress
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PrivateIPAllocationMethod
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PublicIPAddress
  - Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Subnet
  langs:
  - csharp
  - vb
  name: IPConfigurationInner
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IPConfigurationInner
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nIPConfiguration\n"
  example: []
  syntax:
    content: 'public class IPConfigurationInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class IPConfigurationInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: IPConfigurationInner()
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.IPConfigurationInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the IPConfigurationInner class.\n"
  example: []
  syntax:
    content: public IPConfigurationInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.#ctor(System.String,System.String,System.String,Microsoft.Azure.Management.Network.Models.SubnetInner,Microsoft.Azure.Management.Network.Models.PublicIPAddressInner,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.#ctor(System.String,System.String,System.String,Microsoft.Azure.Management.Network.Models.SubnetInner,Microsoft.Azure.Management.Network.Models.PublicIPAddressInner,System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String,Microsoft.Azure.Management.Network.Models.SubnetInner,Microsoft.Azure.Management.Network.Models.PublicIPAddressInner,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: IPConfigurationInner(String, String, String, SubnetInner, PublicIPAddressInner, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.IPConfigurationInner(System.String, System.String, System.String, Microsoft.Azure.Management.Network.Models.SubnetInner, Microsoft.Azure.Management.Network.Models.PublicIPAddressInner, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the IPConfigurationInner class.\n"
  example: []
  syntax:
    content: public IPConfigurationInner(string id = null, string privateIPAddress = null, string privateIPAllocationMethod = null, SubnetInner subnet = null, PublicIPAddressInner publicIPAddress = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, privateIPAddress As String = Nothing, privateIPAllocationMethod As String = Nothing, subnet As SubnetInner = Nothing, publicIPAddress As PublicIPAddressInner = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: privateIPAddress
      type: System.String
      description: >-
        Gets or sets the privateIPAddress

        of the IP Configuration
    - id: privateIPAllocationMethod
      type: System.String
      description: >-
        Gets or sets PrivateIP

        allocation method. Possible values include: 'Static',

        'Dynamic'
    - id: subnet
      type: Microsoft.Azure.Management.Network.Models.SubnetInner
      description: >-
        Gets or sets the reference of the subnet

        resource
    - id: publicIPAddress
      type: Microsoft.Azure.Management.Network.Models.PublicIPAddressInner
      description: >-
        Gets or sets the reference of the

        PublicIP resource
    - id: provisioningState
      type: System.String
      description: >-
        Gets provisioning state of the

        PublicIP resource Updating/Deleting/Failed
    - id: name
      type: System.String
      description: >-
        Gets name of the resource that is unique within

        a resource group. This name can be used to access the

        resource
    - id: etag
      type: System.String
      description: >-
        A unique read-only string that changes whenever

        the resource is updated
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PrivateIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PrivateIPAddress
  id: PrivateIPAddress
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: PrivateIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PrivateIPAddress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIPAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 57
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the privateIPAddress of the IP Configuration\n"
  example: []
  syntax:
    content: public string PrivateIPAddress { get; set; }
    content.vb: Public Property PrivateIPAddress As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PrivateIPAllocationMethod
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PrivateIPAllocationMethod
  id: PrivateIPAllocationMethod
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: PrivateIPAllocationMethod
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PrivateIPAllocationMethod
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIPAllocationMethod
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 64
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets PrivateIP allocation method. Possible values include:\n'Static', 'Dynamic'\n"
  example: []
  syntax:
    content: public string PrivateIPAllocationMethod { get; set; }
    content.vb: Public Property PrivateIPAllocationMethod As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Subnet
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Subnet
  id: Subnet
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: Subnet
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Subnet
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Subnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the reference of the subnet resource\n"
  example: []
  syntax:
    content: public SubnetInner Subnet { get; set; }
    content.vb: Public Property Subnet As SubnetInner
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.SubnetInner
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PublicIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PublicIPAddress
  id: PublicIPAddress
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: PublicIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.PublicIPAddress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PublicIPAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 76
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the reference of the PublicIP resource\n"
  example: []
  syntax:
    content: public PublicIPAddressInner PublicIPAddress { get; set; }
    content.vb: Public Property PublicIPAddress As PublicIPAddressInner
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.PublicIPAddressInner
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 83
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets provisioning state of the PublicIP resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 90
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets name of the resource that is unique within a resource group.\nThis name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.IPConfigurationInner
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.IPConfigurationInner.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/IPConfigurationInner.cs
    startLine: 97
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets a unique read-only string that changes whenever the\nresource is updated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Network.Models.SubnetInner
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: SubnetInner
  fullName: Microsoft.Azure.Management.Network.Models.SubnetInner
- uid: Microsoft.Azure.Management.Network.Models.PublicIPAddressInner
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: PublicIPAddressInner
  fullName: Microsoft.Azure.Management.Network.Models.PublicIPAddressInner
