items:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  commentId: N:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  id: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  children:
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IDefinition`1
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithAttach`1
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithLoadBalancer`1
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithNetwork`1
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPrivateIp`1
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithSubnet`1
  langs:
  - csharp
  - vb
  name: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  type: Namespace
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
references:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithSubnet`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithSubnet<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithSubnet<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithSubnet(Of ParentT)
  name.vb: IWithSubnet(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithSubnet`1
    name: IWithSubnet
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithSubnet
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithSubnet`1
    name: IWithSubnet
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithSubnet
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithLoadBalancer`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithLoadBalancer<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithLoadBalancer<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithLoadBalancer(Of ParentT)
  name.vb: IWithLoadBalancer(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithLoadBalancer`1
    name: IWithLoadBalancer
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithLoadBalancer
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithLoadBalancer`1
    name: IWithLoadBalancer
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithLoadBalancer
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPrivateIp`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithPrivateIp<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPrivateIp<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPrivateIp(Of ParentT)
  name.vb: IWithPrivateIp(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPrivateIp
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPrivateIp
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IBlank<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank(Of ParentT)
  name.vb: IBlank(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithNetwork`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithNetwork<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT)
  name.vb: IWithNetwork(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithNetwork`1
    name: IWithNetwork
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithNetwork
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithNetwork`1
    name: IWithNetwork
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithNetwork
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithAttach`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IDefinition`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IDefinition<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IDefinition<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IDefinition(Of ParentT)
  name.vb: IDefinition(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IDefinition`1
    name: IDefinition
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IDefinition
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IDefinition`1
    name: IDefinition
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IDefinition
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithPublicIpAddress<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT)
  name.vb: IWithPublicIpAddress(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
    name: IWithPublicIpAddress
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPublicIpAddress
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
    name: IWithPublicIpAddress
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IWithPublicIpAddress
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
