items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  commentId: N:Microsoft.Azure.Management.Fluent.Batch.Application.Update
  id: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  children:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  langs:
  - csharp
  - vb
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  type: Namespace
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: IWithOptionalProperties
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: IWithApplicationPackage
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update
