items:
- uid: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings
  commentId: T:Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings
  id: IWithOsDiskSettings
  parent: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  children:
  - Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  - Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskEncryptionSettings(Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings)
  - Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskName(System.String)
  - Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskSizeInGb(System.Int32)
  - Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskVhdLocation(System.String,System.String)
  langs:
  - csharp
  - vb
  name: IWithOsDiskSettings
  fullName: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithOsDiskSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
    startLine: 175
  assemblies:
  - Microsoft.Azure.Management.Fluent.Compute
  packages:
  - Microsoft.Azure.Management.Fluent.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  summary: "\nThe stage of the virtual machine definition allowing to specify OS disk configurations.\n"
  example: []
  syntax:
    content: public interface IWithOsDiskSettings
    content.vb: Public Interface IWithOsDiskSettings
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  commentId: M:Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  id: WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  parent: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings
  langs:
  - csharp
  - vb
  name: WithOsDiskCaching(CachingTypes)
  fullName: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithOsDiskCaching
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
    startLine: 182
  assemblies:
  - Microsoft.Azure.Management.Fluent.Compute
  packages:
  - Microsoft.Azure.Management.Fluent.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  summary: "\nSpecifies the caching type for the Operating System disk.\n"
  example: []
  syntax:
    content: IWithCreate WithOsDiskCaching(CachingTypes cachingType)
    content.vb: Function WithOsDiskCaching(cachingType As CachingTypes) As IWithCreate
    parameters:
    - id: cachingType
      type: Microsoft.Azure.Management.Compute.Models.CachingTypes
      description: cachingType the caching type.
    return:
      type: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithCreate
      description: the stage representing creatable VM definition
- uid: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskVhdLocation(System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskVhdLocation(System.String,System.String)
  id: WithOsDiskVhdLocation(System.String,System.String)
  parent: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings
  langs:
  - csharp
  - vb
  name: WithOsDiskVhdLocation(String, String)
  fullName: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskVhdLocation(System.String, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithOsDiskVhdLocation
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
    startLine: 190
  assemblies:
  - Microsoft.Azure.Management.Fluent.Compute
  packages:
  - Microsoft.Azure.Management.Fluent.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  summary: "\nSpecifies the name of the OS Disk Vhd file and it's parent container.\n"
  example: []
  syntax:
    content: IWithCreate WithOsDiskVhdLocation(string containerName, string vhdName)
    content.vb: Function WithOsDiskVhdLocation(containerName As String, vhdName As String) As IWithCreate
    parameters:
    - id: containerName
      type: System.String
      description: containerName the name of the container in the selected storage account.
    - id: vhdName
      type: System.String
      description: vhdName the name for the OS Disk vhd.
    return:
      type: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithCreate
      description: the stage representing creatable VM definition
- uid: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskEncryptionSettings(Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings)
  commentId: M:Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskEncryptionSettings(Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings)
  id: WithOsDiskEncryptionSettings(Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings)
  parent: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings
  langs:
  - csharp
  - vb
  name: WithOsDiskEncryptionSettings(DiskEncryptionSettings)
  fullName: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskEncryptionSettings(Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithOsDiskEncryptionSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
    startLine: 197
  assemblies:
  - Microsoft.Azure.Management.Fluent.Compute
  packages:
  - Microsoft.Azure.Management.Fluent.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  summary: "\nSpecifies the encryption settings for the OS Disk.\n"
  example: []
  syntax:
    content: IWithCreate WithOsDiskEncryptionSettings(DiskEncryptionSettings settings)
    content.vb: Function WithOsDiskEncryptionSettings(settings As DiskEncryptionSettings) As IWithCreate
    parameters:
    - id: settings
      type: Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings
      description: settings the encryption settings.
    return:
      type: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithCreate
      description: the stage representing creatable VM definition
- uid: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskSizeInGb(System.Int32)
  commentId: M:Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskSizeInGb(System.Int32)
  id: WithOsDiskSizeInGb(System.Int32)
  parent: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings
  langs:
  - csharp
  - vb
  name: WithOsDiskSizeInGb(Int32)
  fullName: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskSizeInGb(System.Int32)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithOsDiskSizeInGb
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
    startLine: 204
  assemblies:
  - Microsoft.Azure.Management.Fluent.Compute
  packages:
  - Microsoft.Azure.Management.Fluent.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  summary: "\nSpecifies the size of the OSDisk in GB.\n"
  example: []
  syntax:
    content: IWithCreate WithOsDiskSizeInGb(int size)
    content.vb: Function WithOsDiskSizeInGb(size As Integer) As IWithCreate
    parameters:
    - id: size
      type: System.Int32
      description: size the VHD size.
    return:
      type: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithCreate
      description: the stage representing creatable VM definition
- uid: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskName(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskName(System.String)
  id: WithOsDiskName(System.String)
  parent: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings
  langs:
  - csharp
  - vb
  name: WithOsDiskName(String)
  fullName: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithOsDiskSettings.WithOsDiskName(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithOsDiskName
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.Fluent.Compute/Domain/VirtualMachine/Definition/IDefinition.cs
    startLine: 211
  assemblies:
  - Microsoft.Azure.Management.Fluent.Compute
  packages:
  - Microsoft.Azure.Management.Fluent.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  summary: "\nSpecifies the name for the OS Disk.\n"
  example: []
  syntax:
    content: IWithCreate WithOsDiskName(string name)
    content.vb: Function WithOsDiskName(name As String) As IWithCreate
    parameters:
    - id: name
      type: System.String
      description: name the OS Disk name.
    return:
      type: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithCreate
      description: the stage representing creatable VM definition
references:
- uid: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  fullName: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
- uid: Microsoft.Azure.Management.Compute.Models.CachingTypes
  parent: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: CachingTypes
  fullName: Microsoft.Azure.Management.Compute.Models.CachingTypes
- uid: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithCreate
  parent: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition
  isExternal: false
  name: IWithCreate
  fullName: Microsoft.Azure.Management.Fluent.Compute.VirtualMachine.Definition.IWithCreate
- uid: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: Microsoft.Azure.Management.Compute.Models
  fullName: Microsoft.Azure.Management.Compute.Models
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings
  parent: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: DiskEncryptionSettings
  fullName: Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  fullName: System.Int32
