items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode
  id: ApplicationGatewayFirewallMode
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode.Detection
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode.Prevention
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFirewallMode
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayFirewallMode.cs
      branch: d379d8d7cc630da30685344b7f7b0698c456763f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayFirewallMode
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayFirewallMode.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nDefines values for ApplicationGatewayFirewallMode.\n"
  example: []
  syntax:
    content: public class ApplicationGatewayFirewallMode
    content.vb: Public Class ApplicationGatewayFirewallMode
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode.Detection
  commentId: F:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode.Detection
  id: Detection
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode
  langs:
  - csharp
  - vb
  name: Detection
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode.Detection
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayFirewallMode.cs
      branch: d379d8d7cc630da30685344b7f7b0698c456763f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Detection
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayFirewallMode.cs
    startLine: 19
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  syntax:
    content: public const string Detection = "Detection"
    content.vb: Public Const Detection As String = "Detection"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode.Prevention
  commentId: F:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode.Prevention
  id: Prevention
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode
  langs:
  - csharp
  - vb
  name: Prevention
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFirewallMode.Prevention
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayFirewallMode.cs
      branch: d379d8d7cc630da30685344b7f7b0698c456763f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Prevention
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayFirewallMode.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  syntax:
    content: public const string Prevention = "Prevention"
    content.vb: Public Const Prevention As String = "Prevention"
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
