items:
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  commentId: T:Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  id: GraphRbacManager.IConfigurable
  parent: Microsoft.Azure.Management.Fluent.Graph.RBAC
  children:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  langs:
  - csharp
  - vb
  name: GraphRbacManager.IConfigurable
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Graph.RBAC/Microsoft.Azure.Management.Fluent.Graph.RBAC/GraphRBACManager.cs
      branch: dab8b1150e5a5b24b90fb532e969147f16a69ec8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/Graph.RBAC/Microsoft.Azure.Management.Fluent.Graph.RBAC/GraphRBACManager.cs
    startLine: 64
  assemblies:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC
  packages:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Graph.RBAC
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<GraphRbacManager.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of GraphRbacManager.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  id: Authenticate(ServiceClientCredentials,System.String,System.String)
  parent: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String, String)
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Graph.RBAC/Microsoft.Azure.Management.Fluent.Graph.RBAC/GraphRBACManager.cs
      branch: dab8b1150e5a5b24b90fb532e969147f16a69ec8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Graph.RBAC/Microsoft.Azure.Management.Fluent.Graph.RBAC/GraphRBACManager.cs
    startLine: 66
  assemblies:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC
  packages:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Graph.RBAC
  syntax:
    content: IGraphRbacManager Authenticate(ServiceClientCredentials graphCredentials, string subscriptionId, string tenantId)
    content.vb: Function Authenticate(graphCredentials As ServiceClientCredentials, subscriptionId As String, tenantId As String) As IGraphRbacManager
    parameters:
    - id: graphCredentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    - id: tenantId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.Graph.RBAC.IGraphRbacManager
references:
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Graph.RBAC
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.IGraphRbacManager
  parent: Microsoft.Azure.Management.Fluent.Graph.RBAC
  isExternal: false
  name: IGraphRbacManager
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.IGraphRbacManager
- uid: System
  isExternal: false
  name: System
  fullName: System
