### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  commentId: T:Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  id: SettingsGetResponse
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models
  children:
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.#ctor
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.Value
  langs:
  - csharp
  - vb
  name: SettingsGetResponse
  nameWithType: SettingsGetResponse
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  type: Class
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: SettingsGetResponse
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nThe get setting operation response.\n"
  example: []
  syntax:
    content: 'public class SettingsGetResponse : AzureOperationResponse'
    content.vb: >-
      Public Class SettingsGetResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.Value
  commentId: P:Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.Value
  id: Value
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: SettingsGetResponse.Value
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.Value
  type: Property
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Value
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nOptional. The setting value.\n"
  example: []
  syntax:
    content: public string Value { get; set; }
    content.vb: Public Property Value As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse
  langs:
  - csharp
  - vb
  name: SettingsGetResponse()
  nameWithType: SettingsGetResponse.SettingsGetResponse()
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.SettingsGetResponse.SettingsGetResponse()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/SettingsGetResponse.cs
    startLine: 46
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nInitializes a new instance of the SettingsGetResponse class.\n"
  example: []
  syntax:
    content: public SettingsGetResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models
  commentId: N:Microsoft.WindowsAzure.WebSitesExtensions.Models
  isExternal: false
  name: Microsoft.WindowsAzure.WebSitesExtensions.Models
  nameWithType: Microsoft.WindowsAzure.WebSitesExtensions.Models
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
