items:
- uid: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig
  commentId: T:Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig
  id: ApplicationLogsConfig
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.#ctor
  - Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.#ctor(Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig,Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig,Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig)
  - Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.AzureBlobStorage
  - Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.AzureTableStorage
  - Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.FileSystem
  langs:
  - csharp
  - vb
  name: ApplicationLogsConfig
  fullName: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig
  type: Class
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
      branch: 6532f686f273e0213bedf20dfa2fa2c008ae0da8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationLogsConfig
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nApplication logs configuration\n"
  example: []
  syntax:
    content: public class ApplicationLogsConfig
    content.vb: Public Class ApplicationLogsConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.#ctor
  commentId: M:Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig
  langs:
  - csharp
  - vb
  name: ApplicationLogsConfig()
  fullName: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.ApplicationLogsConfig()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
      branch: 6532f686f273e0213bedf20dfa2fa2c008ae0da8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
    startLine: 26
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the ApplicationLogsConfig class.\n"
  example: []
  syntax:
    content: public ApplicationLogsConfig()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.#ctor(Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig,Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig,Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig)
  commentId: M:Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.#ctor(Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig,Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig,Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig)
  id: '#ctor(Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig,Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig,Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig)'
  parent: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig
  langs:
  - csharp
  - vb
  name: ApplicationLogsConfig(FileSystemApplicationLogsConfig, AzureTableStorageApplicationLogsConfig, AzureBlobStorageApplicationLogsConfig)
  fullName: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.ApplicationLogsConfig(Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig, Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig, Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
      branch: 6532f686f273e0213bedf20dfa2fa2c008ae0da8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the ApplicationLogsConfig class.\n"
  example: []
  syntax:
    content: public ApplicationLogsConfig(FileSystemApplicationLogsConfig fileSystem = null, AzureTableStorageApplicationLogsConfig azureTableStorage = null, AzureBlobStorageApplicationLogsConfig azureBlobStorage = null)
    content.vb: Public Sub New(fileSystem As FileSystemApplicationLogsConfig = Nothing, azureTableStorage As AzureTableStorageApplicationLogsConfig = Nothing, azureBlobStorage As AzureBlobStorageApplicationLogsConfig = Nothing)
    parameters:
    - id: fileSystem
      type: Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig
    - id: azureTableStorage
      type: Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig
    - id: azureBlobStorage
      type: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.FileSystem
  commentId: P:Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.FileSystem
  id: FileSystem
  parent: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig
  langs:
  - csharp
  - vb
  name: FileSystem
  fullName: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.FileSystem
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
      branch: 6532f686f273e0213bedf20dfa2fa2c008ae0da8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: FileSystem
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
    startLine: 41
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nApplication logs to file system configuration\n"
  example: []
  syntax:
    content: public FileSystemApplicationLogsConfig FileSystem { get; set; }
    content.vb: Public Property FileSystem As FileSystemApplicationLogsConfig
    parameters: []
    return:
      type: Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.AzureTableStorage
  commentId: P:Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.AzureTableStorage
  id: AzureTableStorage
  parent: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig
  langs:
  - csharp
  - vb
  name: AzureTableStorage
  fullName: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.AzureTableStorage
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
      branch: 6532f686f273e0213bedf20dfa2fa2c008ae0da8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: AzureTableStorage
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nApplication logs to azure table storage configuration\n"
  example: []
  syntax:
    content: public AzureTableStorageApplicationLogsConfig AzureTableStorage { get; set; }
    content.vb: Public Property AzureTableStorage As AzureTableStorageApplicationLogsConfig
    parameters: []
    return:
      type: Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.AzureBlobStorage
  commentId: P:Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.AzureBlobStorage
  id: AzureBlobStorage
  parent: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig
  langs:
  - csharp
  - vb
  name: AzureBlobStorage
  fullName: Microsoft.Azure.Management.WebSites.Models.ApplicationLogsConfig.AzureBlobStorage
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
      branch: 6532f686f273e0213bedf20dfa2fa2c008ae0da8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: AzureBlobStorage
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ApplicationLogsConfig.cs
    startLine: 53
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nApplication logs to blob storage configuration\n"
  example: []
  syntax:
    content: public AzureBlobStorageApplicationLogsConfig AzureBlobStorage { get; set; }
    content.vb: Public Property AzureBlobStorage As AzureBlobStorageApplicationLogsConfig
    parameters: []
    return:
      type: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: FileSystemApplicationLogsConfig
  fullName: Microsoft.Azure.Management.WebSites.Models.FileSystemApplicationLogsConfig
- uid: Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: AzureTableStorageApplicationLogsConfig
  fullName: Microsoft.Azure.Management.WebSites.Models.AzureTableStorageApplicationLogsConfig
- uid: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: AzureBlobStorageApplicationLogsConfig
  fullName: Microsoft.Azure.Management.WebSites.Models.AzureBlobStorageApplicationLogsConfig
