items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  id: ApplicationGatewayUrlPathMap
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.#ctor(System.String,Microsoft.Azure.Management.Network.Models.SubResource,Microsoft.Azure.Management.Network.Models.SubResource,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule},System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.DefaultBackendAddressPool
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.DefaultBackendHttpSettings
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.Etag
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.Name
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.PathRules
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.ProvisioningState
  langs:
  - csharp
  - vb
  name: ApplicationGatewayUrlPathMap
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayUrlPathMap
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nUrlPathMap of application gateway\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayUrlPathMap : SubResource'
    content.vb: >-
      Public Class ApplicationGatewayUrlPathMap
          Inherits SubResource
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Network.Models.SubResource
  inheritedMembers:
  - Microsoft.Azure.Management.Network.Models.SubResource.Id
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  langs:
  - csharp
  - vb
  name: ApplicationGatewayUrlPathMap()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.ApplicationGatewayUrlPathMap()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 28
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the ApplicationGatewayUrlPathMap\nclass.\n"
  example: []
  syntax:
    content: public ApplicationGatewayUrlPathMap()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.#ctor(System.String,Microsoft.Azure.Management.Network.Models.SubResource,Microsoft.Azure.Management.Network.Models.SubResource,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule},System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.#ctor(System.String,Microsoft.Azure.Management.Network.Models.SubResource,Microsoft.Azure.Management.Network.Models.SubResource,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule},System.String,System.String,System.String)
  id: '#ctor(System.String,Microsoft.Azure.Management.Network.Models.SubResource,Microsoft.Azure.Management.Network.Models.SubResource,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule},System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  langs:
  - csharp
  - vb
  name: ApplicationGatewayUrlPathMap(String, SubResource, SubResource, IList<ApplicationGatewayPathRule>, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.ApplicationGatewayUrlPathMap(System.String, Microsoft.Azure.Management.Network.Models.SubResource, Microsoft.Azure.Management.Network.Models.SubResource, System.Collections.Generic.IList<Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule>, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the ApplicationGatewayUrlPathMap\nclass.\n"
  example: []
  syntax:
    content: public ApplicationGatewayUrlPathMap(string id = null, SubResource defaultBackendAddressPool = null, SubResource defaultBackendHttpSettings = null, IList<ApplicationGatewayPathRule> pathRules = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, defaultBackendAddressPool As SubResource = Nothing, defaultBackendHttpSettings As SubResource = Nothing, pathRules As IList(Of ApplicationGatewayPathRule) = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: defaultBackendAddressPool
      type: Microsoft.Azure.Management.Network.Models.SubResource
    - id: defaultBackendHttpSettings
      type: Microsoft.Azure.Management.Network.Models.SubResource
    - id: pathRules
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule}
    - id: provisioningState
      type: System.String
    - id: name
      type: System.String
    - id: etag
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.ApplicationGatewayUrlPathMap(System.String, Microsoft.Azure.Management.Network.Models.SubResource, Microsoft.Azure.Management.Network.Models.SubResource, System.Collections.Generic.IList(Of Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule), System.String, System.String, System.String)
  name.vb: ApplicationGatewayUrlPathMap(String, SubResource, SubResource, IList(Of ApplicationGatewayPathRule), String, String, String)
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.DefaultBackendAddressPool
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.DefaultBackendAddressPool
  id: DefaultBackendAddressPool
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  langs:
  - csharp
  - vb
  name: DefaultBackendAddressPool
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.DefaultBackendAddressPool
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefaultBackendAddressPool
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nDefault backend address pool resource of URL path map\n"
  example: []
  syntax:
    content: public SubResource DefaultBackendAddressPool { get; set; }
    content.vb: Public Property DefaultBackendAddressPool As SubResource
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.DefaultBackendHttpSettings
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.DefaultBackendHttpSettings
  id: DefaultBackendHttpSettings
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  langs:
  - csharp
  - vb
  name: DefaultBackendHttpSettings
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.DefaultBackendHttpSettings
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefaultBackendHttpSettings
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 54
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nDefault backend http settings resource of URL path map\n"
  example: []
  syntax:
    content: public SubResource DefaultBackendHttpSettings { get; set; }
    content.vb: Public Property DefaultBackendHttpSettings As SubResource
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.PathRules
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.PathRules
  id: PathRules
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  langs:
  - csharp
  - vb
  name: PathRules
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.PathRules
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PathRules
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 60
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nPath rule of URL path map resource\n"
  example: []
  syntax:
    content: public IList<ApplicationGatewayPathRule> PathRules { get; set; }
    content.vb: Public Property PathRules As IList(Of ApplicationGatewayPathRule)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 67
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nProvisioning state of the backend http settings resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 74
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nName of the resource that is unique within a resource group. This\nname can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayUrlPathMap.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
      branch: 1e8a408f7ed32401e52b1860c7c8e0ed0833dde5
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayUrlPathMap.cs
    startLine: 81
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nA unique read-only string that changes whenever the resource is\nupdated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Network.Models.SubResource
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: SubResource
  fullName: Microsoft.Azure.Management.Network.Models.SubResource
- uid: Microsoft.Azure.Management.Network.Models.SubResource.Id
  parent: Microsoft.Azure.Management.Network.Models.SubResource
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.Network.Models.SubResource.Id
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<ApplicationGatewayPathRule>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule)
  name.vb: IList(Of ApplicationGatewayPathRule)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule
    name: ApplicationGatewayPathRule
    fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule
    name: ApplicationGatewayPathRule
    fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
