items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  id: IWithPublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  children:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(System.String)
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithoutPublicIpAddress
  langs:
  - csharp
  - vb
  name: IWithPublicIpAddress
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 45
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nThe stage of the network interface IP configuration update allowing to specify public IP address.\n"
  example: []
  syntax:
    content: public interface IWithPublicIpAddress
    content.vb: Public Interface IWithPublicIpAddress
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  id: WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  langs:
  - csharp
  - vb
  name: WithNewPublicIpAddress(ICreatable<IPublicIpAddress>)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(ICreatable<Microsoft.Azure.Management.V2.Network.IPublicIpAddress>)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  syntax:
    content: IUpdate WithNewPublicIpAddress(ICreatable<IPublicIpAddress> creatable)
    content.vb: Function WithNewPublicIpAddress(creatable As ICreatable(Of IPublicIpAddress)) As IUpdate
    parameters:
    - id: creatable
      type: ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress}
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(ICreatable(Of Microsoft.Azure.Management.V2.Network.IPublicIpAddress))
  name.vb: WithNewPublicIpAddress(ICreatable(Of IPublicIpAddress))
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress
  id: WithNewPublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  langs:
  - csharp
  - vb
  name: WithNewPublicIpAddress()
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 66
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  syntax:
    content: IUpdate WithNewPublicIpAddress()
    content.vb: Function WithNewPublicIpAddress As IUpdate
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(System.String)
  id: WithNewPublicIpAddress(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  langs:
  - csharp
  - vb
  name: WithNewPublicIpAddress(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithNewPublicIpAddress(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 77
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  syntax:
    content: IUpdate WithNewPublicIpAddress(string leafDnsLabel)
    content.vb: Function WithNewPublicIpAddress(leafDnsLabel As String) As IUpdate
    parameters:
    - id: leafDnsLabel
      type: System.String
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithoutPublicIpAddress
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithoutPublicIpAddress
  id: WithoutPublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  langs:
  - csharp
  - vb
  name: WithoutPublicIpAddress()
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPublicIpAddress.WithoutPublicIpAddress()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithoutPublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 83
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nSpecifies that remove any public IP associated with the IP configuration.\n"
  example: []
  syntax:
    content: IUpdate WithoutPublicIpAddress()
    content.vb: Function WithoutPublicIpAddress As IUpdate
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the network interface IP configuration update
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
- uid: ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress}
  definition: ICreatable`1
  name: ICreatable<IPublicIpAddress>
  fullName: ICreatable<Microsoft.Azure.Management.V2.Network.IPublicIpAddress>
  fullname.vb: ICreatable(Of Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  name.vb: ICreatable(Of IPublicIpAddress)
  spec.csharp:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
- uid: ICreatable`1
  isExternal: true
  name: ICreatable<>
  fullName: ICreatable<>
  fullname.vb: ICreatable(Of )
  name.vb: ICreatable(Of )
  spec.csharp:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
