items:
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration
  commentId: T:Microsoft.Azure.Management.Network.Models.IPConfiguration
  id: IPConfiguration
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.#ctor
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.#ctor(System.String,System.String,System.String,Microsoft.Azure.Management.Network.Models.Subnet,Microsoft.Azure.Management.Network.Models.PublicIPAddress,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.Etag
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.Name
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.PrivateIPAddress
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.PrivateIPAllocationMethod
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.PublicIPAddress
  - Microsoft.Azure.Management.Network.Models.IPConfiguration.Subnet
  langs:
  - csharp
  - vb
  name: IPConfiguration
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IPConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nIPConfiguration\n"
  example: []
  syntax:
    content: 'public class IPConfiguration : SubResource'
    content.vb: >-
      Public Class IPConfiguration
          Inherits SubResource
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Network.Models.SubResource
  inheritedMembers:
  - Microsoft.Azure.Management.Network.Models.SubResource.Id
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.IPConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: IPConfiguration()
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.IPConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the IPConfiguration class.\n"
  example: []
  syntax:
    content: public IPConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.#ctor(System.String,System.String,System.String,Microsoft.Azure.Management.Network.Models.Subnet,Microsoft.Azure.Management.Network.Models.PublicIPAddress,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.IPConfiguration.#ctor(System.String,System.String,System.String,Microsoft.Azure.Management.Network.Models.Subnet,Microsoft.Azure.Management.Network.Models.PublicIPAddress,System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String,Microsoft.Azure.Management.Network.Models.Subnet,Microsoft.Azure.Management.Network.Models.PublicIPAddress,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: IPConfiguration(String, String, String, Subnet, PublicIPAddress, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.IPConfiguration(System.String, System.String, System.String, Microsoft.Azure.Management.Network.Models.Subnet, Microsoft.Azure.Management.Network.Models.PublicIPAddress, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the IPConfiguration class.\n"
  example: []
  syntax:
    content: public IPConfiguration(string id = null, string privateIPAddress = null, string privateIPAllocationMethod = null, Subnet subnet = null, PublicIPAddress publicIPAddress = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, privateIPAddress As String = Nothing, privateIPAllocationMethod As String = Nothing, subnet As Subnet = Nothing, publicIPAddress As PublicIPAddress = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: privateIPAddress
      type: System.String
    - id: privateIPAllocationMethod
      type: System.String
    - id: subnet
      type: Microsoft.Azure.Management.Network.Models.Subnet
    - id: publicIPAddress
      type: Microsoft.Azure.Management.Network.Models.PublicIPAddress
    - id: provisioningState
      type: System.String
    - id: name
      type: System.String
    - id: etag
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.PrivateIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfiguration.PrivateIPAddress
  id: PrivateIPAddress
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: PrivateIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.PrivateIPAddress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIPAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the privateIPAddress of the IP Configuration\n"
  example: []
  syntax:
    content: public string PrivateIPAddress { get; set; }
    content.vb: Public Property PrivateIPAddress As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.PrivateIPAllocationMethod
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfiguration.PrivateIPAllocationMethod
  id: PrivateIPAllocationMethod
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: PrivateIPAllocationMethod
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.PrivateIPAllocationMethod
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIPAllocationMethod
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 54
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets PrivateIP allocation method. Possible values include:\n'Static', 'Dynamic'\n"
  example: []
  syntax:
    content: public string PrivateIPAllocationMethod { get; set; }
    content.vb: Public Property PrivateIPAllocationMethod As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.Subnet
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfiguration.Subnet
  id: Subnet
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: Subnet
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.Subnet
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Subnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 60
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the reference of the subnet resource\n"
  example: []
  syntax:
    content: public Subnet Subnet { get; set; }
    content.vb: Public Property Subnet As Subnet
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.Subnet
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.PublicIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfiguration.PublicIPAddress
  id: PublicIPAddress
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: PublicIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.PublicIPAddress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PublicIPAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 66
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the reference of the PublicIP resource\n"
  example: []
  syntax:
    content: public PublicIPAddress PublicIPAddress { get; set; }
    content.vb: Public Property PublicIPAddress As PublicIPAddress
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.PublicIPAddress
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfiguration.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets provisioning state of the PublicIP resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfiguration.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 80
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets name of the resource that is unique within a resource group.\nThis name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.IPConfiguration.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.IPConfiguration.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.IPConfiguration
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.IPConfiguration.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
      branch: 5764856d77d065ab52175a08b6143b84af608b85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/IPConfiguration.cs
    startLine: 87
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nA unique read-only string that changes whenever the resource is\nupdated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Network.Models.SubResource
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: SubResource
  fullName: Microsoft.Azure.Management.Network.Models.SubResource
- uid: Microsoft.Azure.Management.Network.Models.SubResource.Id
  parent: Microsoft.Azure.Management.Network.Models.SubResource
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.Network.Models.SubResource.Id
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Network.Models.Subnet
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Subnet
  fullName: Microsoft.Azure.Management.Network.Models.Subnet
- uid: Microsoft.Azure.Management.Network.Models.PublicIPAddress
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: PublicIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.PublicIPAddress
