items:
- uid: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations
  commentId: T:Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations
  id: IServiceDiagnosticSettingsOperations
  parent: Microsoft.Azure.Management.Insights
  children:
  - Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(System.String,Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.Threading.CancellationToken)
  - Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.GetWithHttpMessagesAsync(System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.Threading.CancellationToken)
  langs:
  - csharp
  - vb
  name: IServiceDiagnosticSettingsOperations
  fullName: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/IServiceDiagnosticSettingsOperations.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IServiceDiagnosticSettingsOperations
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/IServiceDiagnosticSettingsOperations.cs
    startLine: 16
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights
  summary: "\nServiceDiagnosticSettingsOperations operations.\n"
  example: []
  syntax:
    content: public interface IServiceDiagnosticSettingsOperations
    content.vb: Public Interface IServiceDiagnosticSettingsOperations
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.GetWithHttpMessagesAsync(System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.GetWithHttpMessagesAsync(System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.Threading.CancellationToken)
  id: GetWithHttpMessagesAsync(System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.Threading.CancellationToken)
  parent: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations
  langs:
  - csharp
  - vb
  name: GetWithHttpMessagesAsync(String, Dictionary<String, List<String>>, CancellationToken)
  fullName: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.GetWithHttpMessagesAsync(System.String, System.Collections.Generic.Dictionary<System.String, System.Collections.Generic.List<System.String>>, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/IServiceDiagnosticSettingsOperations.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: GetWithHttpMessagesAsync
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/IServiceDiagnosticSettingsOperations.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights
  summary: "\nGets the active diagnostic settings for the specified resource.\n"
  example: []
  syntax:
    content: Task<Rest.Azure.AzureOperationResponse<ServiceDiagnosticSettingsResource>> GetWithHttpMessagesAsync(string resourceUri, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = null)
    content.vb: Function GetWithHttpMessagesAsync(resourceUri As String, customHeaders As Dictionary(Of String, List(Of String)) = Nothing, cancellationToken As CancellationToken = Nothing) As Task(Of Rest.Azure.AzureOperationResponse(Of ServiceDiagnosticSettingsResource))
    parameters:
    - id: resourceUri
      type: System.String
      description: "\nThe identifier of the resource.\n"
    - id: customHeaders
      type: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}}
      description: "\nThe headers that will be added to request.\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\nThe cancellation token.\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Rest.Azure.AzureOperationResponse{Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource}}
  fullName.vb: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.GetWithHttpMessagesAsync(System.String, System.Collections.Generic.Dictionary(Of System.String, System.Collections.Generic.List(Of System.String)), System.Threading.CancellationToken)
  name.vb: GetWithHttpMessagesAsync(String, Dictionary(Of String, List(Of String)), CancellationToken)
- uid: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(System.String,Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.Threading.CancellationToken)
  commentId: M:Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(System.String,Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.Threading.CancellationToken)
  id: CreateOrUpdateWithHttpMessagesAsync(System.String,Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.Threading.CancellationToken)
  parent: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations
  langs:
  - csharp
  - vb
  name: CreateOrUpdateWithHttpMessagesAsync(String, ServiceDiagnosticSettingsCreateOrUpdateParameters, Dictionary<String, List<String>>, CancellationToken)
  fullName: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(System.String, Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters, System.Collections.Generic.Dictionary<System.String, System.Collections.Generic.List<System.String>>, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/IServiceDiagnosticSettingsOperations.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: CreateOrUpdateWithHttpMessagesAsync
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/IServiceDiagnosticSettingsOperations.cs
    startLine: 65
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights
  summary: "\nCreate or update new diagnostic settings for the specified\nresource.\n"
  example: []
  syntax:
    content: Task<Rest.Azure.AzureOperationResponse<ServiceDiagnosticSettingsResource>> CreateOrUpdateWithHttpMessagesAsync(string resourceUri, ServiceDiagnosticSettingsCreateOrUpdateParameters parameters, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = null)
    content.vb: Function CreateOrUpdateWithHttpMessagesAsync(resourceUri As String, parameters As ServiceDiagnosticSettingsCreateOrUpdateParameters, customHeaders As Dictionary(Of String, List(Of String)) = Nothing, cancellationToken As CancellationToken = Nothing) As Task(Of Rest.Azure.AzureOperationResponse(Of ServiceDiagnosticSettingsResource))
    parameters:
    - id: resourceUri
      type: System.String
      description: "\nThe identifier of the resource.\n"
    - id: parameters
      type: Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters
      description: "\nParameters supplied to the operation.\n"
    - id: customHeaders
      type: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}}
      description: "\nThe headers that will be added to request.\n"
    - id: cancellationToken
      type: System.Threading.CancellationToken
      description: "\nThe cancellation token.\n"
    return:
      type: System.Threading.Tasks.Task{Microsoft.Rest.Azure.AzureOperationResponse{Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource}}
  fullName.vb: Microsoft.Azure.Management.Insights.IServiceDiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(System.String, Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters, System.Collections.Generic.Dictionary(Of System.String, System.Collections.Generic.List(Of System.String)), System.Threading.CancellationToken)
  name.vb: CreateOrUpdateWithHttpMessagesAsync(String, ServiceDiagnosticSettingsCreateOrUpdateParameters, Dictionary(Of String, List(Of String)), CancellationToken)
references:
- uid: Microsoft.Azure.Management.Insights
  isExternal: false
  name: Microsoft.Azure.Management.Insights
  fullName: Microsoft.Azure.Management.Insights
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  name: Dictionary<String, List<String>>
  fullName: System.Collections.Generic.Dictionary<System.String, System.Collections.Generic.List<System.String>>
  fullname.vb: System.Collections.Generic.Dictionary(Of System.String, System.Collections.Generic.List(Of System.String))
  name.vb: Dictionary(Of String, List(Of String))
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Collections.Generic.List`1
    name: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: '>'
    fullName: '>'
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Collections.Generic.List`1
    name: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  - name: )
    fullName: )
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task{Microsoft.Rest.Azure.AzureOperationResponse{Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource}}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<Rest.Azure.AzureOperationResponse<ServiceDiagnosticSettingsResource>>
  fullName: System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource>>
  fullname.vb: System.Threading.Tasks.Task(Of Microsoft.Rest.Azure.AzureOperationResponse(Of Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource))
  name.vb: Task(Of Rest.Azure.AzureOperationResponse(Of ServiceDiagnosticSettingsResource))
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Rest.Azure.AzureOperationResponse`1
    name: Rest.Azure.AzureOperationResponse
    fullName: Microsoft.Rest.Azure.AzureOperationResponse
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource
    name: ServiceDiagnosticSettingsResource
    fullName: Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource
  - name: '>'
    fullName: '>'
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Rest.Azure.AzureOperationResponse`1
    name: Rest.Azure.AzureOperationResponse
    fullName: Microsoft.Rest.Azure.AzureOperationResponse
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource
    name: ServiceDiagnosticSettingsResource
    fullName: Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsResource
  - name: )
    fullName: )
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.Dictionary`2
  parent: System.Collections.Generic
  isExternal: true
  name: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  fullname.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    fullName: <
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Threading
  isExternal: false
  name: System.Threading
  fullName: System.Threading
- uid: System.Threading.Tasks.Task`1
  parent: System.Threading.Tasks
  isExternal: true
  name: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  fullname.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    fullName: <
  - name: TResult
    fullName: TResult
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TResult
    fullName: TResult
  - name: )
    fullName: )
- uid: System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  fullName: System.Threading.Tasks
- uid: Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters
  parent: Microsoft.Azure.Management.Insights.Models
  isExternal: false
  name: ServiceDiagnosticSettingsCreateOrUpdateParameters
  fullName: Microsoft.Azure.Management.Insights.Models.ServiceDiagnosticSettingsCreateOrUpdateParameters
- uid: Microsoft.Azure.Management.Insights.Models
  isExternal: false
  name: Microsoft.Azure.Management.Insights.Models
  fullName: Microsoft.Azure.Management.Insights.Models
