items:
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1
  commentId: T:Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1
  id: IAzureConfigurable`1
  parent: Microsoft.Azure.Management.Fluent.Resource.Core
  children:
  - Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withDelegatingHandler(DelegatingHandler)
  - Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withLogLevel(Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level)
  - Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withRetryPolicy(RetryPolicy)
  - Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withUserAgent(System.String,System.String)
  langs:
  - csharp
  - vb
  name: IAzureConfigurable<T>
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable<T>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IAzureConfigurable
    path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
    startLine: 8
  assemblies:
  - Microsoft.Azure.Management.Fluent.ResourceManager
  packages:
  - Microsoft.Azure.Management.Fluent.ResourceManager(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Resource.Core
  syntax:
    content: >-
      public interface IAzureConfigurable<T>
          where T : IAzureConfigurable<T>
    content.vb: Public Interface IAzureConfigurable(Of T As IAzureConfigurable(Of T))
    typeParameters:
    - id: T
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable(Of T)
  name.vb: IAzureConfigurable(Of T)
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withUserAgent(System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withUserAgent(System.String,System.String)
  id: withUserAgent(System.String,System.String)
  parent: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1
  langs:
  - csharp
  - vb
  name: withUserAgent(String, String)
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable<T>.withUserAgent(System.String, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: withUserAgent
    path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
    startLine: 10
  assemblies:
  - Microsoft.Azure.Management.Fluent.ResourceManager
  packages:
  - Microsoft.Azure.Management.Fluent.ResourceManager(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Resource.Core
  syntax:
    content: T withUserAgent(string product, string version)
    content.vb: Function withUserAgent(product As String, version As String) As T
    parameters:
    - id: product
      type: System.String
    - id: version
      type: System.String
    return:
      type: '{T}'
  fullName.vb: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable(Of T).withUserAgent(System.String, System.String)
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withRetryPolicy(RetryPolicy)
  commentId: M:Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withRetryPolicy(RetryPolicy)
  id: withRetryPolicy(RetryPolicy)
  parent: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1
  langs:
  - csharp
  - vb
  name: withRetryPolicy(RetryPolicy)
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable<T>.withRetryPolicy(RetryPolicy)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: withRetryPolicy
    path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
    startLine: 11
  assemblies:
  - Microsoft.Azure.Management.Fluent.ResourceManager
  packages:
  - Microsoft.Azure.Management.Fluent.ResourceManager(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Resource.Core
  syntax:
    content: T withRetryPolicy(RetryPolicy retryPolicy)
    content.vb: Function withRetryPolicy(retryPolicy As RetryPolicy) As T
    parameters:
    - id: retryPolicy
      type: RetryPolicy
    return:
      type: '{T}'
  fullName.vb: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable(Of T).withRetryPolicy(RetryPolicy)
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withDelegatingHandler(DelegatingHandler)
  commentId: M:Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withDelegatingHandler(DelegatingHandler)
  id: withDelegatingHandler(DelegatingHandler)
  parent: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1
  langs:
  - csharp
  - vb
  name: withDelegatingHandler(DelegatingHandler)
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable<T>.withDelegatingHandler(DelegatingHandler)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: withDelegatingHandler
    path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
    startLine: 12
  assemblies:
  - Microsoft.Azure.Management.Fluent.ResourceManager
  packages:
  - Microsoft.Azure.Management.Fluent.ResourceManager(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Resource.Core
  syntax:
    content: T withDelegatingHandler(DelegatingHandler delegatingHandler)
    content.vb: Function withDelegatingHandler(delegatingHandler As DelegatingHandler) As T
    parameters:
    - id: delegatingHandler
      type: DelegatingHandler
    return:
      type: '{T}'
  fullName.vb: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable(Of T).withDelegatingHandler(DelegatingHandler)
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withLogLevel(Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level)
  commentId: M:Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1.withLogLevel(Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level)
  id: withLogLevel(Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level)
  parent: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable`1
  langs:
  - csharp
  - vb
  name: withLogLevel(HttpLoggingDelegatingHandler.Level)
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable<T>.withLogLevel(Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: withLogLevel
    path: src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.Fluent.ResourceManager/Core/IAzureConfigurable.cs
    startLine: 13
  assemblies:
  - Microsoft.Azure.Management.Fluent.ResourceManager
  packages:
  - Microsoft.Azure.Management.Fluent.ResourceManager(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Resource.Core
  syntax:
    content: T withLogLevel(HttpLoggingDelegatingHandler.Level level)
    content.vb: Function withLogLevel(level As HttpLoggingDelegatingHandler.Level) As T
    parameters:
    - id: level
      type: Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level
    return:
      type: '{T}'
  fullName.vb: Microsoft.Azure.Management.Fluent.Resource.Core.IAzureConfigurable(Of T).withLogLevel(Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level)
references:
- uid: Microsoft.Azure.Management.Fluent.Resource.Core
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Resource.Core
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: '{T}'
  isExternal: false
  name: T
  fullName: T
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: RetryPolicy
  isExternal: true
  name: RetryPolicy
  fullName: RetryPolicy
- uid: DelegatingHandler
  isExternal: true
  name: DelegatingHandler
  fullName: DelegatingHandler
- uid: Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level
  parent: Microsoft.Azure.Management.Fluent.Resource.Core
  isExternal: false
  name: HttpLoggingDelegatingHandler.Level
  fullName: Microsoft.Azure.Management.Fluent.Resource.Core.HttpLoggingDelegatingHandler.Level
