items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  id: ApplicationGatewayFrontendIPConfigurationInner
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.#ctor(System.String,System.String,System.String,Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Etag
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Name
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PrivateIPAddress
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PrivateIPAllocationMethod
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PublicIPAddress
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Subnet
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFrontendIPConfigurationInner
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayFrontendIPConfigurationInner
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nFrontend IP configuration of application gateway\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayFrontendIPConfigurationInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class ApplicationGatewayFrontendIPConfigurationInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFrontendIPConfigurationInner()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.ApplicationGatewayFrontendIPConfigurationInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayFrontendIPConfigurationInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayFrontendIPConfigurationInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.#ctor(System.String,System.String,System.String,Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.#ctor(System.String,System.String,System.String,Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String,Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayFrontendIPConfigurationInner(String, String, String, Rest.Azure.SubResource, Rest.Azure.SubResource, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.ApplicationGatewayFrontendIPConfigurationInner(System.String, System.String, System.String, Microsoft.Rest.Azure.SubResource, Microsoft.Rest.Azure.SubResource, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 43
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayFrontendIPConfigurationInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayFrontendIPConfigurationInner(string id = null, string privateIPAddress = null, string privateIPAllocationMethod = null, Rest.Azure.SubResource subnet = null, Rest.Azure.SubResource publicIPAddress = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, privateIPAddress As String = Nothing, privateIPAllocationMethod As String = Nothing, subnet As Rest.Azure.SubResource = Nothing, publicIPAddress As Rest.Azure.SubResource = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: privateIPAddress
      type: System.String
      description: >-
        PrivateIPAddress of the Network

        Interface IP Configuration
    - id: privateIPAllocationMethod
      type: System.String
      description: >-
        PrivateIP allocation

        method (Static/Dynamic). Possible values include: 'Static',

        'Dynamic'
    - id: subnet
      type: Microsoft.Rest.Azure.SubResource
      description: Reference of the subnet resource
    - id: publicIPAddress
      type: Microsoft.Rest.Azure.SubResource
      description: >-
        Reference of the PublicIP

        resource
    - id: provisioningState
      type: System.String
      description: >-
        Provisioning state of the PublicIP

        resource Updating/Deleting/Failed
    - id: name
      type: System.String
      description: >-
        Name of the resource that is unique within a

        resource group. This name can be used to access the

        resource
    - id: etag
      type: System.String
      description: >-
        A unique read-only string that changes whenever

        the resource is updated
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PrivateIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PrivateIPAddress
  id: PrivateIPAddress
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: PrivateIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PrivateIPAddress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIPAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets privateIPAddress of the Network Interface IP\nConfiguration\n"
  example: []
  syntax:
    content: public string PrivateIPAddress { get; set; }
    content.vb: Public Property PrivateIPAddress As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PrivateIPAllocationMethod
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PrivateIPAllocationMethod
  id: PrivateIPAllocationMethod
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: PrivateIPAllocationMethod
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PrivateIPAllocationMethod
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIPAllocationMethod
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 66
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets privateIP allocation method (Static/Dynamic).\nPossible values include: 'Static', 'Dynamic'\n"
  example: []
  syntax:
    content: public string PrivateIPAllocationMethod { get; set; }
    content.vb: Public Property PrivateIPAllocationMethod As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Subnet
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Subnet
  id: Subnet
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Subnet
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Subnet
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Subnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 72
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets reference of the subnet resource\n"
  example: []
  syntax:
    content: public Rest.Azure.SubResource Subnet { get; set; }
    content.vb: Public Property Subnet As Rest.Azure.SubResource
    parameters: []
    return:
      type: Microsoft.Rest.Azure.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PublicIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PublicIPAddress
  id: PublicIPAddress
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: PublicIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.PublicIPAddress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PublicIPAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 78
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets reference of the PublicIP resource\n"
  example: []
  syntax:
    content: public Rest.Azure.SubResource PublicIPAddress { get; set; }
    content.vb: Public Property PublicIPAddress As Rest.Azure.SubResource
    parameters: []
    return:
      type: Microsoft.Rest.Azure.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 85
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets provisioning state of the PublicIP resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 92
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets name of the resource that is unique within a resource\ngroup. This name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayFrontendIPConfigurationInner.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
      branch: b5400192ce8d5df11f466ed2ca49a6bb436c128e
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayFrontendIPConfigurationInner.cs
    startLine: 99
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets a unique read-only string that changes whenever the\nresource is updated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Rest.Azure.SubResource
  isExternal: false
  name: Rest.Azure.SubResource
  fullName: Microsoft.Rest.Azure.SubResource
