items:
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchManager.Configurable
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.BatchManager.Configurable
  id: BatchManager.Configurable
  parent: Microsoft.Azure.Management.Fluent.Batch
  children:
  - Microsoft.Azure.Management.Fluent.Batch.BatchManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: BatchManager.Configurable
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchManager.Configurable
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/BatchManager.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Configurable
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/BatchManager.cs
    startLine: 62
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch
  syntax:
    content: 'protected class Configurable : AzureConfigurable<BatchManager.IConfigurable>, BatchManager.IConfigurable, IAzureConfigurable<BatchManager.IConfigurable>'
    content.vb: >-
      Protected Class Configurable
          Inherits AzureConfigurable(Of BatchManager.IConfigurable)
          Implements BatchManager.IConfigurable, IAzureConfigurable(Of BatchManager.IConfigurable)
  inheritance:
  - System.Object
  implements:
  - Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable
  - IAzureConfigurable{Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable}
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.BatchManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchManager.Configurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchManager.Configurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/BatchManager.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/BatchManager.cs
    startLine: 66
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch
  syntax:
    content: public IBatchManager Authenticate(ServiceClientCredentials credentials, string subscriptionId)
    content.vb: Public Function Authenticate(credentials As ServiceClientCredentials, subscriptionId As String) As IBatchManager
    parameters:
    - id: credentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.IBatchManager
  implements:
  - Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Fluent.Batch
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch
  fullName: Microsoft.Azure.Management.Fluent.Batch
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable
  parent: Microsoft.Azure.Management.Fluent.Batch
  isExternal: false
  name: BatchManager.IConfigurable
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable
- uid: IAzureConfigurable{Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable}
  definition: IAzureConfigurable`1
  name: IAzureConfigurable<BatchManager.IConfigurable>
  fullName: IAzureConfigurable<Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable>
  fullname.vb: IAzureConfigurable(Of Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable)
  name.vb: IAzureConfigurable(Of BatchManager.IConfigurable)
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable
    name: BatchManager.IConfigurable
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable
    name: BatchManager.IConfigurable
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: IAzureConfigurable`1
  isExternal: true
  name: IAzureConfigurable<>
  fullName: IAzureConfigurable<>
  fullname.vb: IAzureConfigurable(Of )
  name.vb: IAzureConfigurable(Of )
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable
  isExternal: true
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchManager.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Batch.IBatchManager
  parent: Microsoft.Azure.Management.Fluent.Batch
  isExternal: false
  name: IBatchManager
  fullName: Microsoft.Azure.Management.Fluent.Batch.IBatchManager
