items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithSubnet
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithSubnet
  id: IWithSubnet
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  children:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithSubnet.WithSubnet(System.String)
  langs:
  - csharp
  - vb
  name: IWithSubnet
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithSubnet
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: dab8b1150e5a5b24b90fb532e969147f16a69ec8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithSubnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 86
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nThe stage of the network interface IP configuration update allowing to specify subnet.\n"
  example: []
  syntax:
    content: public interface IWithSubnet
    content.vb: Public Interface IWithSubnet
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithSubnet.WithSubnet(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithSubnet.WithSubnet(System.String)
  id: WithSubnet(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithSubnet
  langs:
  - csharp
  - vb
  name: WithSubnet(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithSubnet.WithSubnet(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: dab8b1150e5a5b24b90fb532e969147f16a69ec8
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithSubnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 93
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nAssociate a subnet with the network interface IP configuration.\n"
  example: []
  syntax:
    content: IUpdate WithSubnet(string name)
    content.vb: Function WithSubnet(name As String) As IUpdate
    parameters:
    - id: name
      type: System.String
      description: name the subnet name
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the network interface IP configuration update
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
- uid: System
  isExternal: false
  name: System
  fullName: System
