items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1
  id: IWithPrivateIp`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  children:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1.WithPrivateIpAddressDynamic
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1.WithPrivateIpAddressStatic(System.String)
  langs:
  - csharp
  - vb
  name: IWithPrivateIp<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
      branch: 5a8eaf14f2d96c6f4818218d22fcacdccb1235de
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithPrivateIp
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
    startLine: 135
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  syntax:
    content: public interface IWithPrivateIp<ParentT>
    content.vb: Public Interface IWithPrivateIp(Of ParentT)
    typeParameters:
    - id: ParentT
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp(Of ParentT)
  name.vb: IWithPrivateIp(Of ParentT)
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1.WithPrivateIpAddressDynamic
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1.WithPrivateIpAddressDynamic
  id: WithPrivateIpAddressDynamic
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1
  langs:
  - csharp
  - vb
  name: WithPrivateIpAddressDynamic()
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp<ParentT>.WithPrivateIpAddressDynamic()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
      branch: 5a8eaf14f2d96c6f4818218d22fcacdccb1235de
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithPrivateIpAddressDynamic
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
    startLine: 142
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  summary: "\nEnables dynamic private IP address allocation within the specified existing virtual network\nsubnet for the network interface IP configuration.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithPrivateIpAddressDynamic()
    content.vb: Function WithPrivateIpAddressDynamic As IWithAttach(Of ParentT)
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach{{ParentT}}
      description: the next stage of network interface IP configuration definition
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp(Of ParentT).WithPrivateIpAddressDynamic()
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1.WithPrivateIpAddressStatic(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1.WithPrivateIpAddressStatic(System.String)
  id: WithPrivateIpAddressStatic(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp`1
  langs:
  - csharp
  - vb
  name: WithPrivateIpAddressStatic(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp<ParentT>.WithPrivateIpAddressStatic(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
      branch: 5a8eaf14f2d96c6f4818218d22fcacdccb1235de
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithPrivateIpAddressStatic
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
    startLine: 151
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  summary: "\nAssigns the specified static private IP address within the specified existing virtual network\nsubnet to the network interface IP configuration.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithPrivateIpAddressStatic(string staticPrivateIpAddress)
    content.vb: Function WithPrivateIpAddressStatic(staticPrivateIpAddress As String) As IWithAttach(Of ParentT)
    parameters:
    - id: staticPrivateIpAddress
      type: System.String
      description: staticPrivateIpAddress the static IP address within the specified subnet to assign to
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach{{ParentT}}
      description: the next stage of network interface IP configuration definition
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPrivateIp(Of ParentT).WithPrivateIpAddressStatic(System.String)
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach{{ParentT}}
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach`1
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
