items:
- uid: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration
  commentId: T:Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration
  id: INicIpConfiguration
  parent: Microsoft.Azure.Management.Fluent.Network
  children:
  - Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.GetNetwork
  - Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.ListAssociatedLoadBalancerBackends
  - Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.ListAssociatedLoadBalancerInboundNatRules
  - Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.PrivateIpAddressVersion
  langs:
  - csharp
  - vb
  name: INicIpConfiguration
  fullName: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: INicIpConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
    startLine: 11
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network
  summary: "\nAn IP configuration in a network interface.\n"
  example: []
  syntax:
    content: 'public interface INicIpConfiguration : IWrapper<NetworkInterfaceIPConfigurationInner>, IChildResource<INetworkInterface>, IHasPrivateIpAddress, IHasPublicIpAddress, IHasSubnet'
    content.vb: >-
      Public Interface INicIpConfiguration
          Inherits IWrapper(Of NetworkInterfaceIPConfigurationInner), IChildResource(Of INetworkInterface), IHasPrivateIpAddress, IHasPublicIpAddress, IHasSubnet
  inheritedMembers:
  - Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress.PrivateIpAddress
  - Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress.PrivateIpAllocationMethod
  - Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.PublicIpAddressId
  - Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.GetPublicIpAddress
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.GetNetwork
  commentId: M:Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.GetNetwork
  id: GetNetwork
  parent: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: GetNetwork()
  fullName: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.GetNetwork()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: GetNetwork
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
    startLine: 19
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network
  example: []
  syntax:
    content: INetwork GetNetwork()
    content.vb: Function GetNetwork As INetwork
    return:
      type: Microsoft.Azure.Management.Fluent.Network.INetwork
      description: the virtual network associated with this IP configuration
- uid: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.PrivateIpAddressVersion
  commentId: P:Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.PrivateIpAddressVersion
  id: PrivateIpAddressVersion
  parent: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: PrivateIpAddressVersion
  fullName: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.PrivateIpAddressVersion
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIpAddressVersion
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network
  example: []
  syntax:
    content: string PrivateIpAddressVersion { get; }
    content.vb: ReadOnly Property PrivateIpAddressVersion As String
    parameters: []
    return:
      type: System.String
      description: private IP address version
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.ListAssociatedLoadBalancerBackends
  commentId: M:Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.ListAssociatedLoadBalancerBackends
  id: ListAssociatedLoadBalancerBackends
  parent: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: ListAssociatedLoadBalancerBackends()
  fullName: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.ListAssociatedLoadBalancerBackends()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ListAssociatedLoadBalancerBackends
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
    startLine: 25
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network
  example: []
  syntax:
    content: List<IBackend> ListAssociatedLoadBalancerBackends()
    content.vb: Function ListAssociatedLoadBalancerBackends As List(Of IBackend)
    return:
      type: System.Collections.Generic.List{Microsoft.Azure.Management.Fluent.Network.IBackend}
      description: the load balancer backends associated with this network interface IP configuration
- uid: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.ListAssociatedLoadBalancerInboundNatRules
  commentId: M:Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.ListAssociatedLoadBalancerInboundNatRules
  id: ListAssociatedLoadBalancerInboundNatRules
  parent: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: ListAssociatedLoadBalancerInboundNatRules()
  fullName: Microsoft.Azure.Management.Fluent.Network.INicIpConfiguration.ListAssociatedLoadBalancerInboundNatRules()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ListAssociatedLoadBalancerInboundNatRules
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/INicIpConfiguration.cs
    startLine: 28
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network
  example: []
  syntax:
    content: List<IInboundNatRule> ListAssociatedLoadBalancerInboundNatRules()
    content.vb: Function ListAssociatedLoadBalancerInboundNatRules As List(Of IInboundNatRule)
    return:
      type: System.Collections.Generic.List{Microsoft.Azure.Management.Fluent.Network.IInboundNatRule}
      description: the load balancer inbound NAT rules associated with this network interface IP configuration
references:
- uid: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network
  fullName: Microsoft.Azure.Management.Fluent.Network
- uid: Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress.PrivateIpAddress
  parent: Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress
  isExternal: false
  name: PrivateIpAddress
  fullName: Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress.PrivateIpAddress
- uid: Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress.PrivateIpAllocationMethod
  parent: Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress
  isExternal: false
  name: PrivateIpAllocationMethod
  fullName: Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress.PrivateIpAllocationMethod
- uid: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.PublicIpAddressId
  parent: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress
  isExternal: false
  name: PublicIpAddressId
  fullName: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.PublicIpAddressId
- uid: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.GetPublicIpAddress
  parent: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress
  isExternal: false
  name: GetPublicIpAddress()
  fullName: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.GetPublicIpAddress()
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.GetPublicIpAddress
    name: GetPublicIpAddress
    fullName: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.GetPublicIpAddress
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.GetPublicIpAddress
    name: GetPublicIpAddress
    fullName: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress.GetPublicIpAddress
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress
  parent: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: IHasPrivateIpAddress
  fullName: Microsoft.Azure.Management.Fluent.Network.IHasPrivateIpAddress
- uid: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress
  parent: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: IHasPublicIpAddress
  fullName: Microsoft.Azure.Management.Fluent.Network.IHasPublicIpAddress
- uid: Microsoft.Azure.Management.Fluent.Network.INetwork
  parent: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: INetwork
  fullName: Microsoft.Azure.Management.Fluent.Network.INetwork
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.List{Microsoft.Azure.Management.Fluent.Network.IBackend}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<IBackend>
  fullName: System.Collections.Generic.List<Microsoft.Azure.Management.Fluent.Network.IBackend>
  fullname.vb: System.Collections.Generic.List(Of Microsoft.Azure.Management.Fluent.Network.IBackend)
  name.vb: List(Of IBackend)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Network.IBackend
    name: IBackend
    fullName: Microsoft.Azure.Management.Fluent.Network.IBackend
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Network.IBackend
    name: IBackend
    fullName: Microsoft.Azure.Management.Fluent.Network.IBackend
  - name: )
    fullName: )
- uid: System.Collections.Generic.List`1
  parent: System.Collections.Generic
  isExternal: true
  name: List<T>
  fullName: System.Collections.Generic.List<T>
  fullname.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Collections.Generic.List{Microsoft.Azure.Management.Fluent.Network.IInboundNatRule}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<IInboundNatRule>
  fullName: System.Collections.Generic.List<Microsoft.Azure.Management.Fluent.Network.IInboundNatRule>
  fullname.vb: System.Collections.Generic.List(Of Microsoft.Azure.Management.Fluent.Network.IInboundNatRule)
  name.vb: List(Of IInboundNatRule)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Network.IInboundNatRule
    name: IInboundNatRule
    fullName: Microsoft.Azure.Management.Fluent.Network.IInboundNatRule
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Network.IInboundNatRule
    name: IInboundNatRule
    fullName: Microsoft.Azure.Management.Fluent.Network.IInboundNatRule
  - name: )
    fullName: )
