items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp
  id: IWithPrivateIp
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  children:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp.WithPrivateIpAddressDynamic
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp.WithPrivateIpAddressStatic(System.String)
  langs:
  - csharp
  - vb
  name: IWithPrivateIp
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithPrivateIp
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 102
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nThe stage of the network interface IP configuration update allowing to specify private IP.\n"
  example: []
  syntax:
    content: public interface IWithPrivateIp
    content.vb: Public Interface IWithPrivateIp
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp.WithPrivateIpAddressDynamic
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp.WithPrivateIpAddressDynamic
  id: WithPrivateIpAddressDynamic
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp
  langs:
  - csharp
  - vb
  name: WithPrivateIpAddressDynamic()
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp.WithPrivateIpAddressDynamic()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithPrivateIpAddressDynamic
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 109
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nEnables dynamic private IP address allocation within the specified existing virtual network\nsubnet to the network interface IP configuration.\n"
  example: []
  syntax:
    content: IUpdate WithPrivateIpAddressDynamic()
    content.vb: Function WithPrivateIpAddressDynamic As IUpdate
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the network interface IP configuration update
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp.WithPrivateIpAddressStatic(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp.WithPrivateIpAddressStatic(System.String)
  id: WithPrivateIpAddressStatic(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp
  langs:
  - csharp
  - vb
  name: WithPrivateIpAddressStatic(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithPrivateIp.WithPrivateIpAddressStatic(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithPrivateIpAddressStatic
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 118
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nAssigns the specified static private IP address within the specified existing virtual network\nsubnet to the network interface IP configuration.\n"
  example: []
  syntax:
    content: IUpdate WithPrivateIpAddressStatic(string staticPrivateIpAddress)
    content.vb: Function WithPrivateIpAddressStatic(staticPrivateIpAddress As String) As IUpdate
    parameters:
    - id: staticPrivateIpAddress
      type: System.String
      description: staticPrivateIpAddress the static IP address within the specified subnet to assign to
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the network interface IP configuration update
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
