### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig
  commentId: T:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig
  id: EndpointConfig
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  children:
  - Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.#ctor
  - Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.ConfigId
  - Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Location
  - Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Name
  - Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Url
  langs:
  - csharp
  - vb
  name: EndpointConfig
  nameWithType: EndpointConfig
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: EndpointConfig
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nThe configuration to enable endpoint monitoring for a Url.\n"
  example: []
  syntax:
    content: public class EndpointConfig
    content.vb: Public Class EndpointConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.ConfigId
  commentId: P:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.ConfigId
  id: ConfigId
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig
  langs:
  - csharp
  - vb
  name: ConfigId
  nameWithType: EndpointConfig.ConfigId
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.ConfigId
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ConfigId
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
    startLine: 36
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nOptional. The config id for endpoint monitoring config.\n"
  example: []
  syntax:
    content: public string ConfigId { get; set; }
    content.vb: Public Property ConfigId As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Location
  commentId: P:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Location
  id: Location
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig
  langs:
  - csharp
  - vb
  name: Location
  nameWithType: EndpointConfig.Location
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Location
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Location
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
    startLine: 47
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nOptional. The location from which the endpoint is monitored.\n"
  example: []
  syntax:
    content: public string Location { get; set; }
    content.vb: Public Property Location As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Name
  commentId: P:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Name
  id: Name
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: EndpointConfig.Name
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Name
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
    startLine: 59
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nOptional. The friendly name for the url for which endpoint\nmonitoring is configured.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Url
  commentId: P:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Url
  id: Url
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig
  langs:
  - csharp
  - vb
  name: Url
  nameWithType: EndpointConfig.Url
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.Url
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Url
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
    startLine: 70
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nOptional. The Url to be monitored.\n"
  example: []
  syntax:
    content: public Uri Url { get; set; }
    content.vb: Public Property Url As Uri
    parameters: []
    return:
      type: System.Uri
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig
  langs:
  - csharp
  - vb
  name: EndpointConfig()
  nameWithType: EndpointConfig.EndpointConfig()
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.EndpointConfig.EndpointConfig()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/EndpointConfig.cs
    startLine: 79
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nInitializes a new instance of the EndpointConfig class.\n"
  example: []
  syntax:
    content: public EndpointConfig()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  commentId: N:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  nameWithType: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Uri
  commentId: T:System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
