items:
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner
  commentId: T:Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner
  id: ListApplicationsResultInner
  parent: Microsoft.Azure.Management.Batch.Models
  children:
  - Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.#ctor
  - Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationInner},System.String)
  - Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.NextLink
  - Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.Value
  langs:
  - csharp
  - vb
  name: ListApplicationsResultInner
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
      branch: 103a27efa2658342d95a385715c4448ba1b34efa
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ListApplicationsResultInner
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Batch
  packages:
  - Microsoft.Azure.Management.V2.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nResponse to an ApplicationOperations.ListApplications request.\n"
  example: []
  syntax:
    content: public class ListApplicationsResultInner
    content.vb: Public Class ListApplicationsResultInner
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.#ctor
  commentId: M:Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner
  langs:
  - csharp
  - vb
  name: ListApplicationsResultInner()
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.ListApplicationsResultInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
      branch: 103a27efa2658342d95a385715c4448ba1b34efa
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.V2.Batch
  packages:
  - Microsoft.Azure.Management.V2.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nInitializes a new instance of the ListApplicationsResultInner\nclass.\n"
  example: []
  syntax:
    content: public ListApplicationsResultInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationInner},System.String)
  commentId: M:Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationInner},System.String)
  id: '#ctor(System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationInner},System.String)'
  parent: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner
  langs:
  - csharp
  - vb
  name: ListApplicationsResultInner(IList<ApplicationInner>, String)
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.ListApplicationsResultInner(System.Collections.Generic.IList<Microsoft.Azure.Management.Batch.Models.ApplicationInner>, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
      branch: 103a27efa2658342d95a385715c4448ba1b34efa
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.V2.Batch
  packages:
  - Microsoft.Azure.Management.V2.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nInitializes a new instance of the ListApplicationsResultInner\nclass.\n"
  example: []
  syntax:
    content: public ListApplicationsResultInner(IList<ApplicationInner> value = null, string nextLink = null)
    content.vb: Public Sub New(value As IList(Of ApplicationInner) = Nothing, nextLink As String = Nothing)
    parameters:
    - id: value
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationInner}
      description: The list of applications.
    - id: nextLink
      type: System.String
      description: >-
        The URL to get the next set of

        results.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.ListApplicationsResultInner(System.Collections.Generic.IList(Of Microsoft.Azure.Management.Batch.Models.ApplicationInner), System.String)
  name.vb: ListApplicationsResultInner(IList(Of ApplicationInner), String)
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.Value
  commentId: P:Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.Value
  id: Value
  parent: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner
  langs:
  - csharp
  - vb
  name: Value
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.Value
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
      branch: 103a27efa2658342d95a385715c4448ba1b34efa
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Value
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.V2.Batch
  packages:
  - Microsoft.Azure.Management.V2.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nGets or sets the list of applications.\n"
  example: []
  syntax:
    content: public IList<ApplicationInner> Value { get; set; }
    content.vb: Public Property Value As IList(Of ApplicationInner)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationInner}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.NextLink
  commentId: P:Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.NextLink
  id: NextLink
  parent: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner
  langs:
  - csharp
  - vb
  name: NextLink
  fullName: Microsoft.Azure.Management.Batch.Models.ListApplicationsResultInner.NextLink
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
      branch: 103a27efa2658342d95a385715c4448ba1b34efa
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: NextLink
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.V2.Batch/Generated/Models/ListApplicationsResultInner.cs
    startLine: 45
  assemblies:
  - Microsoft.Azure.Management.V2.Batch
  packages:
  - Microsoft.Azure.Management.V2.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nGets or sets the URL to get the next set of results.\n"
  example: []
  syntax:
    content: public string NextLink { get; set; }
    content.vb: Public Property NextLink As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Microsoft.Azure.Management.Batch.Models
  fullName: Microsoft.Azure.Management.Batch.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Batch.Models.ApplicationInner}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<ApplicationInner>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Batch.Models.ApplicationInner>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Batch.Models.ApplicationInner)
  name.vb: IList(Of ApplicationInner)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Batch.Models.ApplicationInner
    name: ApplicationInner
    fullName: Microsoft.Azure.Management.Batch.Models.ApplicationInner
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Batch.Models.ApplicationInner
    name: ApplicationInner
    fullName: Microsoft.Azure.Management.Batch.Models.ApplicationInner
  - name: )
    fullName: )
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
