### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  id: RemoteManagementModeConfiguration
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  children:
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Disabled
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsEnabled
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Unknown
  langs:
  - csharp
  - vb
  name: RemoteManagementModeConfiguration
  nameWithType: RemoteManagementModeConfiguration
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: RemoteManagementModeConfiguration
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nRemoteManagementModeConfiguration\n"
  example: []
  syntax:
    content: public enum RemoteManagementModeConfiguration
    content.vb: Public Enum RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Unknown
  commentId: F:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Unknown
  id: Unknown
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: RemoteManagementModeConfiguration.Unknown
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Unknown
  type: Field
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Unknown
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  syntax:
    content: Unknown = 0
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Disabled
  commentId: F:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Disabled
  id: Disabled
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: RemoteManagementModeConfiguration.Disabled
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Disabled
  type: Field
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Disabled
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 33
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  syntax:
    content: Disabled = 1
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsEnabled
  commentId: F:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsEnabled
  id: HttpsEnabled
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  langs:
  - csharp
  - vb
  name: HttpsEnabled
  nameWithType: RemoteManagementModeConfiguration.HttpsEnabled
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsEnabled
  type: Field
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: HttpsEnabled
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 35
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  syntax:
    content: HttpsEnabled = 2
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  commentId: F:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  id: HttpsAndHttpEnabled
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  langs:
  - csharp
  - vb
  name: HttpsAndHttpEnabled
  nameWithType: RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  type: Field
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: HttpsAndHttpEnabled
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  syntax:
    content: HttpsAndHttpEnabled = 3
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models
  commentId: N:Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.StorSimple.Models
  nameWithType: Microsoft.WindowsAzure.Management.StorSimple.Models
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: RemoteManagementModeConfiguration
  nameWithType: RemoteManagementModeConfiguration
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
