items:
- uid: Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable
  commentId: T:Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable
  id: KeyVaultManager.IConfigurable
  parent: Microsoft.Azure.Management.Fluent.KeyVault
  children:
  - Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable.Authenticate(AzureCredentials,System.String)
  - Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  langs:
  - csharp
  - vb
  name: KeyVaultManager.IConfigurable
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/KeyVaultManager.cs
      branch: a22251cda68f724317d3ae2d0ae390f6642eb358
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/KeyVaultManager.cs
    startLine: 79
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<KeyVaultManager.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of KeyVaultManager.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  id: Authenticate(ServiceClientCredentials,System.String,System.String)
  parent: Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String, String)
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/KeyVaultManager.cs
      branch: a22251cda68f724317d3ae2d0ae390f6642eb358
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/KeyVaultManager.cs
    startLine: 81
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault
  syntax:
    content: IKeyVaultManager Authenticate(ServiceClientCredentials serviceClientCredentials, string subscriptionId, string tenantId)
    content.vb: Function Authenticate(serviceClientCredentials As ServiceClientCredentials, subscriptionId As String, tenantId As String) As IKeyVaultManager
    parameters:
    - id: serviceClientCredentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    - id: tenantId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.IKeyVaultManager
- uid: Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable.Authenticate(AzureCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable.Authenticate(AzureCredentials,System.String)
  id: Authenticate(AzureCredentials,System.String)
  parent: Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(AzureCredentials, String)
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.KeyVaultManager.IConfigurable.Authenticate(AzureCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/KeyVaultManager.cs
      branch: a22251cda68f724317d3ae2d0ae390f6642eb358
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/KeyVaultManager.cs
    startLine: 83
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault
  syntax:
    content: IKeyVaultManager Authenticate(AzureCredentials azureCredentials, string subscriptionId)
    content.vb: Function Authenticate(azureCredentials As AzureCredentials, subscriptionId As String) As IKeyVaultManager
    parameters:
    - id: azureCredentials
      type: AzureCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.IKeyVaultManager
references:
- uid: Microsoft.Azure.Management.Fluent.KeyVault
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.KeyVault
  fullName: Microsoft.Azure.Management.Fluent.KeyVault
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.KeyVault.IKeyVaultManager
  parent: Microsoft.Azure.Management.Fluent.KeyVault
  isExternal: false
  name: IKeyVaultManager
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.IKeyVaultManager
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: AzureCredentials
  isExternal: true
  name: AzureCredentials
  fullName: AzureCredentials
