items:
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  commentId: T:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  id: IWithConfigurations
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  children:
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDeploymentDisabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDeploymentEnabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDiskEncryptionDisabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDiskEncryptionEnabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithTemplateDeploymentDisabled
  - Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithTemplateDeploymentEnabled
  langs:
  - csharp
  - vb
  name: IWithConfigurations
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithConfigurations
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
    startLine: 13
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  summary: "\nA key vault update allowing various configurations to be set.\n"
  example: []
  syntax:
    content: public interface IWithConfigurations
    content.vb: Public Interface IWithConfigurations
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDeploymentEnabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDeploymentEnabled
  id: WithDeploymentEnabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithDeploymentEnabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDeploymentEnabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDeploymentEnabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
    startLine: 19
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  summary: "\nEnable Azure Virtual Machines to retrieve certificates stored as secrets from the key vault.\n"
  example: []
  syntax:
    content: IUpdate WithDeploymentEnabled()
    content.vb: Function WithDeploymentEnabled As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IUpdate
      description: the key vault update stage
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDiskEncryptionEnabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDiskEncryptionEnabled
  id: WithDiskEncryptionEnabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithDiskEncryptionEnabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDiskEncryptionEnabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDiskEncryptionEnabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
    startLine: 25
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  summary: "\nEnable Azure Disk Encryption to retrieve secrets from the vault and unwrap keys.\n"
  example: []
  syntax:
    content: IUpdate WithDiskEncryptionEnabled()
    content.vb: Function WithDiskEncryptionEnabled As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IUpdate
      description: the key vault update stage
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithTemplateDeploymentEnabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithTemplateDeploymentEnabled
  id: WithTemplateDeploymentEnabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithTemplateDeploymentEnabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithTemplateDeploymentEnabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithTemplateDeploymentEnabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  summary: "\nEnable Azure Resource Manager to retrieve secrets from the key vault.\n"
  example: []
  syntax:
    content: IUpdate WithTemplateDeploymentEnabled()
    content.vb: Function WithTemplateDeploymentEnabled As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IUpdate
      description: the key vault update stage
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDeploymentDisabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDeploymentDisabled
  id: WithDeploymentDisabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithDeploymentDisabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDeploymentDisabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDeploymentDisabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  summary: "\nDisable Azure Virtual Machines to retrieve certificates stored as secrets from the key vault.\n"
  example: []
  syntax:
    content: IUpdate WithDeploymentDisabled()
    content.vb: Function WithDeploymentDisabled As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IUpdate
      description: the key vault update stage
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDiskEncryptionDisabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDiskEncryptionDisabled
  id: WithDiskEncryptionDisabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithDiskEncryptionDisabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithDiskEncryptionDisabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDiskEncryptionDisabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
    startLine: 43
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  summary: "\nDisable Azure Disk Encryption to retrieve secrets from the vault and unwrap keys.\n"
  example: []
  syntax:
    content: IUpdate WithDiskEncryptionDisabled()
    content.vb: Function WithDiskEncryptionDisabled As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IUpdate
      description: the next stage of key vault definition
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithTemplateDeploymentDisabled
  commentId: M:Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithTemplateDeploymentDisabled
  id: WithTemplateDeploymentDisabled
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations
  langs:
  - csharp
  - vb
  name: WithTemplateDeploymentDisabled()
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IWithConfigurations.WithTemplateDeploymentDisabled()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
      branch: c09fd548dd5625bdfafd1e6eff301aa537692f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithTemplateDeploymentDisabled
    path: src/ResourceManagement/KeyVault/Microsoft.Azure.Management.Fluent.KeyVault/Domain/Vault/Update/IUpdate.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Fluent.KeyVault
  packages:
  - Microsoft.Azure.Management.Fluent.KeyVault(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  summary: "\nDisable Azure Resource Manager to retrieve secrets from the key vault.\n"
  example: []
  syntax:
    content: IUpdate WithTemplateDeploymentDisabled()
    content.vb: Function WithTemplateDeploymentDisabled As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IUpdate
      description: the key vault update stage
references:
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
- uid: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.KeyVault.Vault.Update.IUpdate
