items:
- uid: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration
  commentId: T:Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration
  id: IWithIpConfiguration
  parent: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update
  children:
  - Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration.DefineSecondaryIpConfiguration(System.String)
  - Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration.UpdateIpConfiguration(System.String)
  langs:
  - csharp
  - vb
  name: IWithIpConfiguration
  fullName: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NetworkInterface/Update/IUpdate.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithIpConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NetworkInterface/Update/IUpdate.cs
    startLine: 196
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update
  summary: "\nThe stage of the network interface update allowing to configure IP configuration.\n"
  example: []
  syntax:
    content: public interface IWithIpConfiguration
    content.vb: Public Interface IWithIpConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration.DefineSecondaryIpConfiguration(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration.DefineSecondaryIpConfiguration(System.String)
  id: DefineSecondaryIpConfiguration(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration
  langs:
  - csharp
  - vb
  name: DefineSecondaryIpConfiguration(String)
  fullName: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration.DefineSecondaryIpConfiguration(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NetworkInterface/Update/IUpdate.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefineSecondaryIpConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NetworkInterface/Update/IUpdate.cs
    startLine: 203
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update
  summary: "\nStarts definition of a secondary IP configuration.\n"
  example: []
  syntax:
    content: IBlank<IUpdate> DefineSecondaryIpConfiguration(string name)
    content.vb: Function DefineSecondaryIpConfiguration(name As String) As IBlank(Of IUpdate)
    parameters:
    - id: name
      type: System.String
      description: name name for the IP configuration
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank{Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IUpdate}
      description: the first stage of a secondary IP configuration definition
- uid: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration.UpdateIpConfiguration(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration.UpdateIpConfiguration(System.String)
  id: UpdateIpConfiguration(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration
  langs:
  - csharp
  - vb
  name: UpdateIpConfiguration(String)
  fullName: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IWithIpConfiguration.UpdateIpConfiguration(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NetworkInterface/Update/IUpdate.cs
      branch: 6741b9cfb99de698ca40cefe7507c88bd740f361
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: UpdateIpConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NetworkInterface/Update/IUpdate.cs
    startLine: 210
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update
  summary: "\nStarts update of an IP configuration.\n"
  example: []
  syntax:
    content: IUpdate UpdateIpConfiguration(string name)
    content.vb: Function UpdateIpConfiguration(name As String) As IUpdate
    parameters:
    - id: name
      type: System.String
      description: name name of the IP configuration
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
      description: the first stage of an IP configuration update
references:
- uid: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update
  fullName: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank{Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IUpdate}
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank`1
  name: IBlank<IUpdate>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank<Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IUpdate>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank(Of Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IUpdate)
  name.vb: IBlank(Of IUpdate)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IUpdate
    name: IUpdate
    fullName: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IUpdate
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IUpdate
    name: IUpdate
    fullName: Microsoft.Azure.Management.V2.Network.NetworkInterface.Update.IUpdate
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: IBlank<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank(Of ParentT)
  name.vb: IBlank(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
