items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  id: ApplicationGatewayAuthenticationCertificateInner
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.#ctor(System.String,System.String,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Data
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Etag
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Name
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.ProvisioningState
  langs:
  - csharp
  - vb
  name: ApplicationGatewayAuthenticationCertificateInner
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayAuthenticationCertificateInner
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nAuthentication certificates of application gateway\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayAuthenticationCertificateInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class ApplicationGatewayAuthenticationCertificateInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayAuthenticationCertificateInner()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.ApplicationGatewayAuthenticationCertificateInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayAuthenticationCertificateInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayAuthenticationCertificateInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.#ctor(System.String,System.String,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.#ctor(System.String,System.String,System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayAuthenticationCertificateInner(String, String, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.ApplicationGatewayAuthenticationCertificateInner(System.String, System.String, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayAuthenticationCertificateInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayAuthenticationCertificateInner(string id = null, string data = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, data As String = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: data
      type: System.String
      description: 'Certificate public data '
    - id: provisioningState
      type: System.String
      description: >-
        Provisioning state of the

        authentication certificate resource

        Updating/Deleting/Failed
    - id: name
      type: System.String
      description: >-
        Name of the resource that is unique within a

        resource group. This name can be used to access the

        resource
    - id: etag
      type: System.String
      description: >-
        A unique read-only string that changes whenever

        the resource is updated
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Data
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Data
  id: Data
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  langs:
  - csharp
  - vb
  name: Data
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Data
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Data
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets certificate public data\n"
  example: []
  syntax:
    content: public string Data { get; set; }
    content.vb: Public Property Data As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets provisioning state of the authentication certificate\nresource Updating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
    startLine: 63
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets name of the resource that is unique within a resource\ngroup. This name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayAuthenticationCertificateInner.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayAuthenticationCertificateInner.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets a unique read-only string that changes whenever the\nresource is updated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
