items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach`1
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach`1
  id: IWithAttach`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  children: []
  langs:
  - csharp
  - vb
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithAttach
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  syntax:
    content: 'public interface IWithAttach<ParentT> : IInDefinition<ParentT>, IWithPublicIpAddress<ParentT>'
    content.vb: >-
      Public Interface IWithAttach(Of ParentT)
          Inherits IInDefinition(Of ParentT), IWithPublicIpAddress(Of ParentT)
    typeParameters:
    - id: ParentT
  inheritedMembers:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}.WithNewPublicIpAddress
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}.WithNewPublicIpAddress(System.String)
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  name: WithNewPublicIpAddress(ICreatable<IPublicIpAddress>)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress(ICreatable<Microsoft.Azure.Management.V2.Network.IPublicIpAddress>)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress(ICreatable(Of Microsoft.Azure.Management.V2.Network.IPublicIpAddress))
  name.vb: WithNewPublicIpAddress(ICreatable(Of IPublicIpAddress))
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: '>'
    fullName: '>'
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: )
    fullName: )
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}.WithNewPublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress
  name: WithNewPublicIpAddress()
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress()
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress()
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}.WithNewPublicIpAddress(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
  name: WithNewPublicIpAddress(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress(System.String)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  name: WithExistingPublicIpAddress(IPublicIpAddress)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
    name: WithExistingPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithExistingPublicIpAddress
  - name: (
    fullName: (
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
    name: WithExistingPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithExistingPublicIpAddress
  - name: (
    fullName: (
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
  isExternal: true
  name: WithNewPublicIpAddress(ICreatable<IPublicIpAddress>)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress(ICreatable<Microsoft.Azure.Management.V2.Network.IPublicIpAddress>)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress(ICreatable(Of Microsoft.Azure.Management.V2.Network.IPublicIpAddress))
  name.vb: WithNewPublicIpAddress(ICreatable(Of IPublicIpAddress))
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: '>'
    fullName: '>'
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(ICreatable{Microsoft.Azure.Management.V2.Network.IPublicIpAddress})
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: )
    fullName: )
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress{{ParentT}}
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
  name: IWithPublicIpAddress<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT)
  name.vb: IWithPublicIpAddress(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
    name: IWithPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
    name: IWithPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
  isExternal: false
  name: WithNewPublicIpAddress()
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress()
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress()
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
  isExternal: true
  name: WithNewPublicIpAddress(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress(System.String)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithNewPublicIpAddress
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithNewPublicIpAddress(System.String)
    name: WithNewPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithNewPublicIpAddress
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
  isExternal: false
  name: WithExistingPublicIpAddress(IPublicIpAddress)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
    name: WithExistingPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>.WithExistingPublicIpAddress
  - name: (
    fullName: (
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1.WithExistingPublicIpAddress(Microsoft.Azure.Management.V2.Network.IPublicIpAddress)
    name: WithExistingPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT).WithExistingPublicIpAddress
  - name: (
    fullName: (
  - uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
    name: IPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithPublicIpAddress<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress(Of ParentT)
  name.vb: IWithPublicIpAddress(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
    name: IWithPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress`1
    name: IWithPublicIpAddress
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithPublicIpAddress
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
