items:
- uid: Microsoft.Azure.Management.Insights.Models.MetricSettings
  commentId: T:Microsoft.Azure.Management.Insights.Models.MetricSettings
  id: MetricSettings
  parent: Microsoft.Azure.Management.Insights.Models
  children:
  - Microsoft.Azure.Management.Insights.Models.MetricSettings.#ctor
  - Microsoft.Azure.Management.Insights.Models.MetricSettings.#ctor(System.TimeSpan,System.Boolean,Microsoft.Azure.Management.Insights.Models.RetentionPolicy)
  - Microsoft.Azure.Management.Insights.Models.MetricSettings.Enabled
  - Microsoft.Azure.Management.Insights.Models.MetricSettings.RetentionPolicy
  - Microsoft.Azure.Management.Insights.Models.MetricSettings.TimeGrain
  - Microsoft.Azure.Management.Insights.Models.MetricSettings.Validate
  langs:
  - csharp
  - vb
  name: MetricSettings
  fullName: Microsoft.Azure.Management.Insights.Models.MetricSettings
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: MetricSettings
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
    startLine: 16
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights.Models
  summary: "\nPart of MultiTenantDiagnosticSettings. Specifies the settings for a\nparticular metric.\n"
  example: []
  syntax:
    content: public class MetricSettings
    content.vb: Public Class MetricSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Insights.Models.MetricSettings.#ctor
  commentId: M:Microsoft.Azure.Management.Insights.Models.MetricSettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Insights.Models.MetricSettings
  langs:
  - csharp
  - vb
  name: MetricSettings()
  fullName: Microsoft.Azure.Management.Insights.Models.MetricSettings.MetricSettings()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights.Models
  summary: "\nInitializes a new instance of the MetricSettings class.\n"
  example: []
  syntax:
    content: public MetricSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Insights.Models.MetricSettings.#ctor(System.TimeSpan,System.Boolean,Microsoft.Azure.Management.Insights.Models.RetentionPolicy)
  commentId: M:Microsoft.Azure.Management.Insights.Models.MetricSettings.#ctor(System.TimeSpan,System.Boolean,Microsoft.Azure.Management.Insights.Models.RetentionPolicy)
  id: '#ctor(System.TimeSpan,System.Boolean,Microsoft.Azure.Management.Insights.Models.RetentionPolicy)'
  parent: Microsoft.Azure.Management.Insights.Models.MetricSettings
  langs:
  - csharp
  - vb
  name: MetricSettings(TimeSpan, Boolean, RetentionPolicy)
  fullName: Microsoft.Azure.Management.Insights.Models.MetricSettings.MetricSettings(System.TimeSpan, System.Boolean, Microsoft.Azure.Management.Insights.Models.RetentionPolicy)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights.Models
  summary: "\nInitializes a new instance of the MetricSettings class.\n"
  example: []
  syntax:
    content: public MetricSettings(TimeSpan timeGrain, bool enabled, RetentionPolicy retentionPolicy = null)
    content.vb: Public Sub New(timeGrain As TimeSpan, enabled As Boolean, retentionPolicy As RetentionPolicy = Nothing)
    parameters:
    - id: timeGrain
      type: System.TimeSpan
      description: >-
        the timegrain of the metric in ISO8601

        format.
    - id: enabled
      type: System.Boolean
      description: >-
        a value indicating whether this timegrain is

        enabled.
    - id: retentionPolicy
      type: Microsoft.Azure.Management.Insights.Models.RetentionPolicy
      description: >-
        the retention policy for this

        timegrain.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Insights.Models.MetricSettings.TimeGrain
  commentId: P:Microsoft.Azure.Management.Insights.Models.MetricSettings.TimeGrain
  id: TimeGrain
  parent: Microsoft.Azure.Management.Insights.Models.MetricSettings
  langs:
  - csharp
  - vb
  name: TimeGrain
  fullName: Microsoft.Azure.Management.Insights.Models.MetricSettings.TimeGrain
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: TimeGrain
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights.Models
  summary: "\nGets or sets the timegrain of the metric in ISO8601 format.\n"
  example: []
  syntax:
    content: public TimeSpan TimeGrain { get; set; }
    content.vb: Public Property TimeGrain As TimeSpan
    parameters: []
    return:
      type: System.TimeSpan
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Insights.Models.MetricSettings.Enabled
  commentId: P:Microsoft.Azure.Management.Insights.Models.MetricSettings.Enabled
  id: Enabled
  parent: Microsoft.Azure.Management.Insights.Models.MetricSettings
  langs:
  - csharp
  - vb
  name: Enabled
  fullName: Microsoft.Azure.Management.Insights.Models.MetricSettings.Enabled
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Enabled
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights.Models
  summary: "\nGets or sets a value indicating whether this timegrain is enabled.\n"
  example: []
  syntax:
    content: public bool Enabled { get; set; }
    content.vb: Public Property Enabled As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Insights.Models.MetricSettings.RetentionPolicy
  commentId: P:Microsoft.Azure.Management.Insights.Models.MetricSettings.RetentionPolicy
  id: RetentionPolicy
  parent: Microsoft.Azure.Management.Insights.Models.MetricSettings
  langs:
  - csharp
  - vb
  name: RetentionPolicy
  fullName: Microsoft.Azure.Management.Insights.Models.MetricSettings.RetentionPolicy
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: RetentionPolicy
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
    startLine: 54
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights.Models
  summary: "\nGets or sets the retention policy for this timegrain.\n"
  example: []
  syntax:
    content: public RetentionPolicy RetentionPolicy { get; set; }
    content.vb: Public Property RetentionPolicy As RetentionPolicy
    parameters: []
    return:
      type: Microsoft.Azure.Management.Insights.Models.RetentionPolicy
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Insights.Models.MetricSettings.Validate
  commentId: M:Microsoft.Azure.Management.Insights.Models.MetricSettings.Validate
  id: Validate
  parent: Microsoft.Azure.Management.Insights.Models.MetricSettings
  langs:
  - csharp
  - vb
  name: Validate()
  fullName: Microsoft.Azure.Management.Insights.Models.MetricSettings.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
      branch: 4dc4bf42758194ef2b3a6bcf7711274d02e79f41
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/Insights/Microsoft.Azure.Insights/Generated/Management/Insights/Models/MetricSettings.cs
    startLine: 63
  assemblies:
  - Microsoft.Azure.Insights
  packages:
  - Microsoft.Azure.Insights(0.14.0-preview)
  namespace: Microsoft.Azure.Management.Insights.Models
  summary: "\nValidate the object.\n"
  example: []
  syntax:
    content: public virtual void Validate()
    content.vb: Public Overridable Sub Validate
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.Azure.Management.Insights.Models
  isExternal: false
  name: Microsoft.Azure.Management.Insights.Models
  fullName: Microsoft.Azure.Management.Insights.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  fullName: System.TimeSpan
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: Microsoft.Azure.Management.Insights.Models.RetentionPolicy
  parent: Microsoft.Azure.Management.Insights.Models
  isExternal: false
  name: RetentionPolicy
  fullName: Microsoft.Azure.Management.Insights.Models.RetentionPolicy
