items:
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  commentId: T:Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  id: AddApplicationPackageResult
  parent: Microsoft.Azure.Management.Batch.Models
  children:
  - Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.#ctor
  - Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.#ctor(System.String,System.String,System.String,System.Nullable{System.DateTime})
  - Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.Id
  - Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.StorageUrl
  - Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.StorageUrlExpiry
  - Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.Version
  langs:
  - csharp
  - vb
  name: AddApplicationPackageResult
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: AddApplicationPackageResult
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.Batch
  packages:
  - Microsoft.Azure.Management.Batch(2.1.0)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nResponse to an ApplicationOperations.AddApplicationPackage request.\n"
  example: []
  syntax:
    content: public class AddApplicationPackageResult
    content.vb: Public Class AddApplicationPackageResult
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.#ctor
  commentId: M:Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  langs:
  - csharp
  - vb
  name: AddApplicationPackageResult()
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.AddApplicationPackageResult()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
    startLine: 23
  assemblies:
  - Microsoft.Azure.Management.Batch
  packages:
  - Microsoft.Azure.Management.Batch(2.1.0)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nInitializes a new instance of the AddApplicationPackageResult\nclass.\n"
  example: []
  syntax:
    content: public AddApplicationPackageResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.#ctor(System.String,System.String,System.String,System.Nullable{System.DateTime})
  commentId: M:Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.#ctor(System.String,System.String,System.String,System.Nullable{System.DateTime})
  id: '#ctor(System.String,System.String,System.String,System.Nullable{System.DateTime})'
  parent: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  langs:
  - csharp
  - vb
  name: AddApplicationPackageResult(String, String, String, Nullable<DateTime>)
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.AddApplicationPackageResult(System.String, System.String, System.String, System.Nullable<System.DateTime>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Batch
  packages:
  - Microsoft.Azure.Management.Batch(2.1.0)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nInitializes a new instance of the AddApplicationPackageResult\nclass.\n"
  example: []
  syntax:
    content: public AddApplicationPackageResult(string id = null, string version = null, string storageUrl = null, DateTime? storageUrlExpiry = null)
    content.vb: Public Sub New(id As String = Nothing, version As String = Nothing, storageUrl As String = Nothing, storageUrlExpiry As Date? = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: version
      type: System.String
    - id: storageUrl
      type: System.String
    - id: storageUrlExpiry
      type: System.Nullable{System.DateTime}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.AddApplicationPackageResult(System.String, System.String, System.String, System.Nullable(Of System.DateTime))
  name.vb: AddApplicationPackageResult(String, String, String, Nullable(Of DateTime))
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.Id
  commentId: P:Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.Id
  id: Id
  parent: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  langs:
  - csharp
  - vb
  name: Id
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.Id
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Id
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.Batch
  packages:
  - Microsoft.Azure.Management.Batch(2.1.0)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nGets or sets the id of the application.\n"
  example: []
  syntax:
    content: public string Id { get; set; }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.Version
  commentId: P:Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.Version
  id: Version
  parent: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  langs:
  - csharp
  - vb
  name: Version
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.Version
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Version
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Batch
  packages:
  - Microsoft.Azure.Management.Batch(2.1.0)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nGets or sets the version of the application.\n"
  example: []
  syntax:
    content: public string Version { get; set; }
    content.vb: Public Property Version As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.StorageUrl
  commentId: P:Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.StorageUrl
  id: StorageUrl
  parent: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  langs:
  - csharp
  - vb
  name: StorageUrl
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.StorageUrl
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: StorageUrl
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
    startLine: 53
  assemblies:
  - Microsoft.Azure.Management.Batch
  packages:
  - Microsoft.Azure.Management.Batch(2.1.0)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nGets or sets the URL to which the application package binary file\nshould be uploaded.\n"
  example: []
  syntax:
    content: public string StorageUrl { get; set; }
    content.vb: Public Property StorageUrl As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.StorageUrlExpiry
  commentId: P:Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.StorageUrlExpiry
  id: StorageUrlExpiry
  parent: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult
  langs:
  - csharp
  - vb
  name: StorageUrlExpiry
  fullName: Microsoft.Azure.Management.Batch.Models.AddApplicationPackageResult.StorageUrlExpiry
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
      branch: 70979be0a08bbd73d0189634e9b24ade291baee4
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: StorageUrlExpiry
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Batch/Generated/Models/AddApplicationPackageResult.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.Batch
  packages:
  - Microsoft.Azure.Management.Batch(2.1.0)
  namespace: Microsoft.Azure.Management.Batch.Models
  summary: "\nGets or sets the UTC time at which the storage URL will expire.\n"
  example: []
  syntax:
    content: public DateTime? StorageUrlExpiry { get; set; }
    content.vb: Public Property StorageUrlExpiry As Date?
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Batch.Models
  isExternal: false
  name: Microsoft.Azure.Management.Batch.Models
  fullName: Microsoft.Azure.Management.Batch.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.DateTime}
  parent: System
  definition: System.Nullable`1
  name: Nullable<DateTime>
  fullName: System.Nullable<System.DateTime>
  fullname.vb: System.Nullable(Of System.DateTime)
  name.vb: Nullable(Of DateTime)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.DateTime
    name: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.DateTime
    name: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
