items:
- uid: Microsoft.Azure.Management.V2.Storage.StorageManager.Configurable
  commentId: T:Microsoft.Azure.Management.V2.Storage.StorageManager.Configurable
  id: StorageManager.Configurable
  parent: Microsoft.Azure.Management.V2.Storage
  children:
  - Microsoft.Azure.Management.V2.Storage.StorageManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: StorageManager.Configurable
  fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.Configurable
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Storage/Microsoft.Azure.Management.V2.Storage/StorageManager.cs
      branch: 7974ca03c7d6cb8e0c00d1addc5f9f63a9402530
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Configurable
    path: src/ResourceManagement/Storage/Microsoft.Azure.Management.V2.Storage/StorageManager.cs
    startLine: 80
  assemblies:
  - Microsoft.Azure.Management.V2.Storage
  packages:
  - Microsoft.Azure.Management.V2.Storage(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Storage
  syntax:
    content: 'protected class Configurable : AzureConfigurable<StorageManager.IConfigurable>, StorageManager.IConfigurable, IAzureConfigurable<StorageManager.IConfigurable>'
    content.vb: >-
      Protected Class Configurable
          Inherits AzureConfigurable(Of StorageManager.IConfigurable)
          Implements StorageManager.IConfigurable, IAzureConfigurable(Of StorageManager.IConfigurable)
  inheritance:
  - System.Object
  implements:
  - Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  - IAzureConfigurable{Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable}
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
- uid: Microsoft.Azure.Management.V2.Storage.StorageManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.V2.Storage.StorageManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.V2.Storage.StorageManager.Configurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.Configurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Storage/Microsoft.Azure.Management.V2.Storage/StorageManager.cs
      branch: 7974ca03c7d6cb8e0c00d1addc5f9f63a9402530
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Storage/Microsoft.Azure.Management.V2.Storage/StorageManager.cs
    startLine: 90
  assemblies:
  - Microsoft.Azure.Management.V2.Storage
  packages:
  - Microsoft.Azure.Management.V2.Storage(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Storage
  syntax:
    content: public IStorageManager Authenticate(ServiceClientCredentials credentials, string subscriptionId)
    content.vb: Public Function Authenticate(credentials As ServiceClientCredentials, subscriptionId As String) As IStorageManager
    parameters:
    - id: credentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.V2.Storage.IStorageManager
  implements:
  - Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.V2.Storage
  isExternal: false
  name: Microsoft.Azure.Management.V2.Storage
  fullName: Microsoft.Azure.Management.V2.Storage
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  parent: Microsoft.Azure.Management.V2.Storage
  isExternal: false
  name: StorageManager.IConfigurable
  fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
- uid: IAzureConfigurable{Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable}
  definition: IAzureConfigurable`1
  name: IAzureConfigurable<StorageManager.IConfigurable>
  fullName: IAzureConfigurable<Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable>
  fullname.vb: IAzureConfigurable(Of Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable)
  name.vb: IAzureConfigurable(Of StorageManager.IConfigurable)
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
    name: StorageManager.IConfigurable
    fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
    name: StorageManager.IConfigurable
    fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: IAzureConfigurable`1
  isExternal: true
  name: IAzureConfigurable<>
  fullName: IAzureConfigurable<>
  fullname.vb: IAzureConfigurable(Of )
  name.vb: IAzureConfigurable(Of )
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable
  isExternal: true
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.V2.Storage.StorageManager.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Storage.IStorageManager
  parent: Microsoft.Azure.Management.V2.Storage
  isExternal: false
  name: IStorageManager
  fullName: Microsoft.Azure.Management.V2.Storage.IStorageManager
