### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult
  id: GetStartMenuApplicationListResult
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  children:
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult.#ctor
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult.ResultList
  langs:
  - csharp
  - vb
  name: GetStartMenuApplicationListResult
  nameWithType: GetStartMenuApplicationListResult
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult
  type: Class
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationListResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: GetStartMenuApplicationListResult
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationListResult.cs
    startLine: 33
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nDefinition for result of GetStartMenuApplicationList operation.\n"
  example: []
  syntax:
    content: 'public class GetStartMenuApplicationListResult : AzureOperationResponse'
    content.vb: >-
      Public Class GetStartMenuApplicationListResult
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult.ResultList
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult.ResultList
  id: ResultList
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult
  langs:
  - csharp
  - vb
  name: ResultList
  nameWithType: GetStartMenuApplicationListResult.ResultList
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult.ResultList
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationListResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ResultList
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationListResult.cs
    startLine: 40
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nOptional. List of details of start menu applications.\n"
  example: []
  syntax:
    content: public IList<StartMenuApplication> ResultList { get; set; }
    content.vb: Public Property ResultList As IList(Of StartMenuApplication)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult
  langs:
  - csharp
  - vb
  name: GetStartMenuApplicationListResult()
  nameWithType: GetStartMenuApplicationListResult.GetStartMenuApplicationListResult()
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationListResult.GetStartMenuApplicationListResult()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationListResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationListResult.cs
    startLine: 50
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the GetStartMenuApplicationListResult\nclass.\n"
  example: []
  syntax:
    content: public GetStartMenuApplicationListResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models
  commentId: N:Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.RemoteApp.Models
  nameWithType: Microsoft.WindowsAzure.Management.RemoteApp.Models
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.IList{Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication}
  commentId: T:System.Collections.Generic.IList{Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<StartMenuApplication>
  nameWithType: IList<StartMenuApplication>
  fullName: System.Collections.Generic.IList<Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication>
  nameWithType.vb: IList(Of StartMenuApplication)
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication)
  name.vb: IList(Of StartMenuApplication)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication
    name: StartMenuApplication
    nameWithType: StartMenuApplication
    fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication
    name: StartMenuApplication
    nameWithType: StartMenuApplication
    fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  commentId: T:System.Collections.Generic.IList`1
  isExternal: true
  name: IList<T>
  nameWithType: IList<T>
  fullName: System.Collections.Generic.IList<T>
  nameWithType.vb: IList(Of T)
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
