### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  commentId: T:Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  id: ContinuousWebJobSettingsResponse
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models
  children:
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.#ctor
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.IsSingleton
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  langs:
  - csharp
  - vb
  name: ContinuousWebJobSettingsResponse
  nameWithType: ContinuousWebJobSettingsResponse
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  type: Class
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ContinuousWebJobSettingsResponse
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nThe continuous WebJob settings operation response.\n"
  example: []
  syntax:
    content: 'public class ContinuousWebJobSettingsResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ContinuousWebJobSettingsResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.IsSingleton
  commentId: P:Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.IsSingleton
  id: IsSingleton
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  langs:
  - csharp
  - vb
  name: IsSingleton
  nameWithType: ContinuousWebJobSettingsResponse.IsSingleton
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.IsSingleton
  type: Property
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IsSingleton
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nOptional. If a continuous job is set as singleton it'll run only on\na single instance opposed to running on all instances.\n"
  example: []
  syntax:
    content: public bool ? IsSingleton { get; set; }
    content.vb: Public Property IsSingleton As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  commentId: P:Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  id: ShutdownGraceTimeInSeconds
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  langs:
  - csharp
  - vb
  name: ShutdownGraceTimeInSeconds
  nameWithType: ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  type: Property
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ShutdownGraceTimeInSeconds
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nOptional. Specify the time in seconds to wait for the WebJob to\ngracefully shutdown.\n"
  example: []
  syntax:
    content: public int ? ShutdownGraceTimeInSeconds { get; set; }
    content.vb: Public Property ShutdownGraceTimeInSeconds As Integer?
    parameters: []
    return:
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse
  langs:
  - csharp
  - vb
  name: ContinuousWebJobSettingsResponse()
  nameWithType: ContinuousWebJobSettingsResponse.ContinuousWebJobSettingsResponse()
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.ContinuousWebJobSettingsResponse.ContinuousWebJobSettingsResponse()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/ContinuousWebJobSettingsResponse.cs
    startLine: 60
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nInitializes a new instance of the ContinuousWebJobSettingsResponse\nclass.\n"
  example: []
  syntax:
    content: public ContinuousWebJobSettingsResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models
  commentId: N:Microsoft.WindowsAzure.WebSitesExtensions.Models
  isExternal: false
  name: Microsoft.WindowsAzure.WebSitesExtensions.Models
  nameWithType: Microsoft.WindowsAzure.WebSitesExtensions.Models
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  nameWithType: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  nameWithType.vb: Nullable(Of Boolean)
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable{System.Int32}
  commentId: T:System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  nameWithType: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  nameWithType.vb: Nullable(Of Int32)
  fullname.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
