### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult
  id: ModifyApplicationResult
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  children:
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult.#ctor
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult.Result
  langs:
  - csharp
  - vb
  name: ModifyApplicationResult
  nameWithType: ModifyApplicationResult
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult
  type: Class
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ModifyApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ModifyApplicationResult
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ModifyApplicationResult.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nDefinition for result of ModifyApplicaton operation.\n"
  example: []
  syntax:
    content: 'public class ModifyApplicationResult : AzureOperationResponse'
    content.vb: >-
      Public Class ModifyApplicationResult
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult.Result
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult.Result
  id: Result
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult
  langs:
  - csharp
  - vb
  name: Result
  nameWithType: ModifyApplicationResult.Result
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult.Result
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ModifyApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Result
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ModifyApplicationResult.cs
    startLine: 38
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nOptional. Publishing operation result.\n"
  example: []
  syntax:
    content: public PublishingOperationResult Result { get; set; }
    content.vb: Public Property Result As PublishingOperationResult
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult
  langs:
  - csharp
  - vb
  name: ModifyApplicationResult()
  nameWithType: ModifyApplicationResult.ModifyApplicationResult()
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ModifyApplicationResult.ModifyApplicationResult()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ModifyApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ModifyApplicationResult.cs
    startLine: 47
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the ModifyApplicationResult class.\n"
  example: []
  syntax:
    content: public ModifyApplicationResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models
  commentId: N:Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.RemoteApp.Models
  nameWithType: Microsoft.WindowsAzure.Management.RemoteApp.Models
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: PublishingOperationResult
  nameWithType: PublishingOperationResult
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult
