### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings
  id: WebProxySettings
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  children:
  - Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.#ctor
  - Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.#ctor(Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType,System.String,System.String)
  - Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.Authentication
  - Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.ConnectionURI
  - Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.Username
  langs:
  - csharp
  - vb
  name: WebProxySettings
  nameWithType: WebProxySettings
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings
  type: Class
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WebProxySettings
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nDevice WebProxy settings\n"
  example: []
  syntax:
    content: public class WebProxySettings
    content.vb: Public Class WebProxySettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.Authentication
  commentId: P:Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.Authentication
  id: Authentication
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings
  langs:
  - csharp
  - vb
  name: Authentication
  nameWithType: WebProxySettings.Authentication
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.Authentication
  type: Property
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authentication
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nRequired. Gets or sets the Authentication\n"
  example: []
  syntax:
    content: public AuthenticationType Authentication { get; set; }
    content.vb: Public Property Authentication As AuthenticationType
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.ConnectionURI
  commentId: P:Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.ConnectionURI
  id: ConnectionURI
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings
  langs:
  - csharp
  - vb
  name: ConnectionURI
  nameWithType: WebProxySettings.ConnectionURI
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.ConnectionURI
  type: Property
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ConnectionURI
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
    startLine: 48
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nRequired. Gets or sets the Connection URI\n"
  example: []
  syntax:
    content: public string ConnectionURI { get; set; }
    content.vb: Public Property ConnectionURI As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.Username
  commentId: P:Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.Username
  id: Username
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings
  langs:
  - csharp
  - vb
  name: Username
  nameWithType: WebProxySettings.Username
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.Username
  type: Property
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Username
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
    startLine: 59
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nRequired. Gets or sets the Username\n"
  example: []
  syntax:
    content: public string Username { get; set; }
    content.vb: Public Property Username As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings
  langs:
  - csharp
  - vb
  name: WebProxySettings()
  nameWithType: WebProxySettings.WebProxySettings()
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.WebProxySettings()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
    startLine: 68
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nInitializes a new instance of the WebProxySettings class.\n"
  example: []
  syntax:
    content: public WebProxySettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.#ctor(Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType,System.String,System.String)
  commentId: M:Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.#ctor(Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType,System.String,System.String)
  id: '#ctor(Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType,System.String,System.String)'
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings
  langs:
  - csharp
  - vb
  name: WebProxySettings(AuthenticationType, String, String)
  nameWithType: WebProxySettings.WebProxySettings(AuthenticationType, String, String)
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.WebProxySettings.WebProxySettings(Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/WebProxySettings.cs
    startLine: 76
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nInitializes a new instance of the WebProxySettings class with\nrequired arguments.\n"
  example: []
  syntax:
    content: public WebProxySettings(AuthenticationType authentication, string connectionURI, string username)
    content.vb: Public Sub New(authentication As AuthenticationType, connectionURI As String, username As String)
    parameters:
    - id: authentication
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType
    - id: connectionURI
      type: System.String
    - id: username
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models
  commentId: N:Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.StorSimple.Models
  nameWithType: Microsoft.WindowsAzure.Management.StorSimple.Models
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: AuthenticationType
  nameWithType: AuthenticationType
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.AuthenticationType
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
