items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
  id: IUpdate
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  children: []
  langs:
  - csharp
  - vb
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IUpdate
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  summary: "\nThe entirety of application update as a part of parent batch account update.\n"
  example: []
  syntax:
    content: 'public interface IUpdate : ISettable<IUpdate>, IWithOptionalProperties, IWithApplicationPackage'
    content.vb: >-
      Public Interface IUpdate
          Inherits ISettable(Of IUpdate), IWithOptionalProperties, IWithApplicationPackage
  inheritedMembers:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  isExternal: true
  name: WithAllowUpdates(Boolean)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
    name: WithAllowUpdates
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates
  - name: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
    name: WithAllowUpdates
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates
  - name: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  isExternal: true
  name: WithDisplayName(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
    name: WithDisplayName
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
    name: WithDisplayName
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  isExternal: true
  name: DefineNewApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  isExternal: true
  name: WithoutApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
    name: WithoutApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
    name: WithoutApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: IWithOptionalProperties
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: IWithApplicationPackage
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
