### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings
  commentId: T:Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings
  id: CloudServiceSettings
  parent: Microsoft.WindowsAzure.Management.Automation.Models
  children:
  - Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.#ctor
  - Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.#ctor(System.String)
  - Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.GeoRegion
  langs:
  - csharp
  - vb
  name: CloudServiceSettings
  nameWithType: CloudServiceSettings
  fullName: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/CloudServiceSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: CloudServiceSettings
    path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/CloudServiceSettings.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.Automation
  namespace: Microsoft.WindowsAzure.Management.Automation.Models
  summary: "\nInformation about the cloud service settings.\n"
  example: []
  syntax:
    content: public class CloudServiceSettings
    content.vb: Public Class CloudServiceSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.GeoRegion
  commentId: P:Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.GeoRegion
  id: GeoRegion
  parent: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings
  langs:
  - csharp
  - vb
  name: GeoRegion
  nameWithType: CloudServiceSettings.GeoRegion
  fullName: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.GeoRegion
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/CloudServiceSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: GeoRegion
    path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/CloudServiceSettings.cs
    startLine: 36
  assemblies:
  - Microsoft.WindowsAzure.Management.Automation
  namespace: Microsoft.WindowsAzure.Management.Automation.Models
  summary: "\nRequired. Gets or sets the region for the account.\n"
  example: []
  syntax:
    content: public string GeoRegion { get; set; }
    content.vb: Public Property GeoRegion As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings
  langs:
  - csharp
  - vb
  name: CloudServiceSettings()
  nameWithType: CloudServiceSettings.CloudServiceSettings()
  fullName: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.CloudServiceSettings()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/CloudServiceSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/CloudServiceSettings.cs
    startLine: 45
  assemblies:
  - Microsoft.WindowsAzure.Management.Automation
  namespace: Microsoft.WindowsAzure.Management.Automation.Models
  summary: "\nInitializes a new instance of the CloudServiceSettings class.\n"
  example: []
  syntax:
    content: public CloudServiceSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.#ctor(System.String)
  commentId: M:Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings
  langs:
  - csharp
  - vb
  name: CloudServiceSettings(String)
  nameWithType: CloudServiceSettings.CloudServiceSettings(String)
  fullName: Microsoft.WindowsAzure.Management.Automation.Models.CloudServiceSettings.CloudServiceSettings(System.String)
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/CloudServiceSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/CloudServiceSettings.cs
    startLine: 53
  assemblies:
  - Microsoft.WindowsAzure.Management.Automation
  namespace: Microsoft.WindowsAzure.Management.Automation.Models
  summary: "\nInitializes a new instance of the CloudServiceSettings class with\nrequired arguments.\n"
  example: []
  syntax:
    content: public CloudServiceSettings(string geoRegion)
    content.vb: Public Sub New(geoRegion As String)
    parameters:
    - id: geoRegion
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Automation.Models
  commentId: N:Microsoft.WindowsAzure.Management.Automation.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Automation.Models
  nameWithType: Microsoft.WindowsAzure.Management.Automation.Models
  fullName: Microsoft.WindowsAzure.Management.Automation.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
