items:
- uid: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  commentId: T:Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  id: EncryptionConfigType
  parent: Microsoft.Azure.Management.DataLake.Store.Models
  children:
  - Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.ServiceManaged
  - Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.UserManaged
  langs:
  - csharp
  - vb
  name: EncryptionConfigType
  fullName: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
      branch: d379d8d7cc630da30685344b7f7b0698c456763f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: EncryptionConfigType
    path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.DataLake.Store
  packages:
  - Microsoft.Azure.Management.DataLake.Store(0.12.6-preview)
  namespace: Microsoft.Azure.Management.DataLake.Store.Models
  summary: "\nDefines values for EncryptionConfigType.\n"
  example: []
  syntax:
    content: public enum EncryptionConfigType
    content.vb: Public Enum EncryptionConfigType
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.UserManaged
  commentId: F:Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.UserManaged
  id: UserManaged
  parent: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  langs:
  - csharp
  - vb
  name: UserManaged
  fullName: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.UserManaged
  type: Field
  source:
    remote:
      path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
      branch: d379d8d7cc630da30685344b7f7b0698c456763f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: UserManaged
    path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.DataLake.Store
  packages:
  - Microsoft.Azure.Management.DataLake.Store(0.12.6-preview)
  namespace: Microsoft.Azure.Management.DataLake.Store.Models
  syntax:
    content: UserManaged = 0
    return:
      type: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.ServiceManaged
  commentId: F:Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.ServiceManaged
  id: ServiceManaged
  parent: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  langs:
  - csharp
  - vb
  name: ServiceManaged
  fullName: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType.ServiceManaged
  type: Field
  source:
    remote:
      path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
      branch: d379d8d7cc630da30685344b7f7b0698c456763f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ServiceManaged
    path: src/ResourceManagement/DataLake.Store/Microsoft.Azure.Management.DataLake.Store/Generated/Models/EncryptionConfigType.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.DataLake.Store
  packages:
  - Microsoft.Azure.Management.DataLake.Store(0.12.6-preview)
  namespace: Microsoft.Azure.Management.DataLake.Store.Models
  syntax:
    content: ServiceManaged = 1
    return:
      type: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.DataLake.Store.Models
  isExternal: false
  name: Microsoft.Azure.Management.DataLake.Store.Models
  fullName: Microsoft.Azure.Management.DataLake.Store.Models
- uid: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
  parent: Microsoft.Azure.Management.DataLake.Store.Models
  isExternal: false
  name: EncryptionConfigType
  fullName: Microsoft.Azure.Management.DataLake.Store.Models.EncryptionConfigType
