items:
- uid: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties
  commentId: T:Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties
  id: ArtifactDeploymentStatusProperties
  parent: Microsoft.Azure.Management.DevTestLabs.Models
  children:
  - Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.#ctor
  - Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.#ctor(System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})
  - Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.ArtifactsApplied
  - Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.DeploymentStatus
  - Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.TotalArtifacts
  langs:
  - csharp
  - vb
  name: ArtifactDeploymentStatusProperties
  fullName: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties
  type: Class
  source:
    remote:
      path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
      branch: 41495cb45af7c314d98419263610fccfffd715b9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ArtifactDeploymentStatusProperties
    path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.DevTestLabs
  packages:
  - Microsoft.Azure.Management.DevTestLabs(1.1.2)
  namespace: Microsoft.Azure.Management.DevTestLabs.Models
  summary: "\nProperties of an artifact deployment.\n"
  example: []
  syntax:
    content: public class ArtifactDeploymentStatusProperties
    content.vb: Public Class ArtifactDeploymentStatusProperties
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.#ctor
  commentId: M:Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties
  langs:
  - csharp
  - vb
  name: ArtifactDeploymentStatusProperties()
  fullName: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.ArtifactDeploymentStatusProperties()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
      branch: 41495cb45af7c314d98419263610fccfffd715b9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.DevTestLabs
  packages:
  - Microsoft.Azure.Management.DevTestLabs(1.1.2)
  namespace: Microsoft.Azure.Management.DevTestLabs.Models
  summary: "\nInitializes a new instance of the\nArtifactDeploymentStatusProperties class.\n"
  example: []
  syntax:
    content: public ArtifactDeploymentStatusProperties()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.#ctor(System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})
  commentId: M:Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.#ctor(System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})
  id: '#ctor(System.String,System.Nullable{System.Int32},System.Nullable{System.Int32})'
  parent: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties
  langs:
  - csharp
  - vb
  name: ArtifactDeploymentStatusProperties(String, Nullable<Int32>, Nullable<Int32>)
  fullName: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.ArtifactDeploymentStatusProperties(System.String, System.Nullable<System.Int32>, System.Nullable<System.Int32>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
      branch: 41495cb45af7c314d98419263610fccfffd715b9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.DevTestLabs
  packages:
  - Microsoft.Azure.Management.DevTestLabs(1.1.2)
  namespace: Microsoft.Azure.Management.DevTestLabs.Models
  summary: "\nInitializes a new instance of the\nArtifactDeploymentStatusProperties class.\n"
  example: []
  syntax:
    content: public ArtifactDeploymentStatusProperties(string deploymentStatus = null, int ? artifactsApplied = null, int ? totalArtifacts = null)
    content.vb: Public Sub New(deploymentStatus As String = Nothing, artifactsApplied As Integer? = Nothing, totalArtifacts As Integer? = Nothing)
    parameters:
    - id: deploymentStatus
      type: System.String
    - id: artifactsApplied
      type: System.Nullable{System.Int32}
    - id: totalArtifacts
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.ArtifactDeploymentStatusProperties(System.String, System.Nullable(Of System.Int32), System.Nullable(Of System.Int32))
  name.vb: ArtifactDeploymentStatusProperties(String, Nullable(Of Int32), Nullable(Of Int32))
- uid: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.DeploymentStatus
  commentId: P:Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.DeploymentStatus
  id: DeploymentStatus
  parent: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties
  langs:
  - csharp
  - vb
  name: DeploymentStatus
  fullName: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.DeploymentStatus
  type: Property
  source:
    remote:
      path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
      branch: 41495cb45af7c314d98419263610fccfffd715b9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DeploymentStatus
    path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
    startLine: 43
  assemblies:
  - Microsoft.Azure.Management.DevTestLabs
  packages:
  - Microsoft.Azure.Management.DevTestLabs(1.1.2)
  namespace: Microsoft.Azure.Management.DevTestLabs.Models
  summary: "\nThe deployment status of the artifact.\n"
  example: []
  syntax:
    content: public string DeploymentStatus { get; set; }
    content.vb: Public Property DeploymentStatus As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.ArtifactsApplied
  commentId: P:Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.ArtifactsApplied
  id: ArtifactsApplied
  parent: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties
  langs:
  - csharp
  - vb
  name: ArtifactsApplied
  fullName: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.ArtifactsApplied
  type: Property
  source:
    remote:
      path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
      branch: 41495cb45af7c314d98419263610fccfffd715b9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ArtifactsApplied
    path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.DevTestLabs
  packages:
  - Microsoft.Azure.Management.DevTestLabs(1.1.2)
  namespace: Microsoft.Azure.Management.DevTestLabs.Models
  summary: "\nThe total count of the artifacts that were successfully applied.\n"
  example: []
  syntax:
    content: public int ? ArtifactsApplied { get; set; }
    content.vb: Public Property ArtifactsApplied As Integer?
    parameters: []
    return:
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.TotalArtifacts
  commentId: P:Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.TotalArtifacts
  id: TotalArtifacts
  parent: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties
  langs:
  - csharp
  - vb
  name: TotalArtifacts
  fullName: Microsoft.Azure.Management.DevTestLabs.Models.ArtifactDeploymentStatusProperties.TotalArtifacts
  type: Property
  source:
    remote:
      path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
      branch: 41495cb45af7c314d98419263610fccfffd715b9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: TotalArtifacts
    path: src/ResourceManagement/DevTestLabs/Microsoft.Azure.Management.DevTestLabs/Generated/Models/ArtifactDeploymentStatusProperties.cs
    startLine: 55
  assemblies:
  - Microsoft.Azure.Management.DevTestLabs
  packages:
  - Microsoft.Azure.Management.DevTestLabs(1.1.2)
  namespace: Microsoft.Azure.Management.DevTestLabs.Models
  summary: "\nThe total count of the artifacts that were tentatively applied.\n"
  example: []
  syntax:
    content: public int ? TotalArtifacts { get; set; }
    content.vb: Public Property TotalArtifacts As Integer?
    parameters: []
    return:
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.DevTestLabs.Models
  isExternal: false
  name: Microsoft.Azure.Management.DevTestLabs.Models
  fullName: Microsoft.Azure.Management.DevTestLabs.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  fullname.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
