items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool
  id: ApplicationGatewayBackendHealthPool
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.#ctor(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings})
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.BackendAddressPool
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.BackendHttpSettingsCollection
  langs:
  - csharp
  - vb
  name: ApplicationGatewayBackendHealthPool
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
      branch: 90abd71e223211ca3db26acbd29390809f4183dd
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ApplicationGatewayBackendHealthPool
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nApplication gateway backendhealth pool.\n"
  example: []
  syntax:
    content: public class ApplicationGatewayBackendHealthPool
    content.vb: Public Class ApplicationGatewayBackendHealthPool
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool
  langs:
  - csharp
  - vb
  name: ApplicationGatewayBackendHealthPool()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.ApplicationGatewayBackendHealthPool()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
      branch: 90abd71e223211ca3db26acbd29390809f4183dd
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayBackendHealthPool class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayBackendHealthPool()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.#ctor(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings})
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.#ctor(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings})
  id: '#ctor(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings})'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool
  langs:
  - csharp
  - vb
  name: ApplicationGatewayBackendHealthPool(ApplicationGatewayBackendAddressPool, IList<ApplicationGatewayBackendHealthHttpSettings>)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.ApplicationGatewayBackendHealthPool(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool, System.Collections.Generic.IList<Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
      branch: 90abd71e223211ca3db26acbd29390809f4183dd
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayBackendHealthPool class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayBackendHealthPool(ApplicationGatewayBackendAddressPool backendAddressPool = null, IList<ApplicationGatewayBackendHealthHttpSettings> backendHttpSettingsCollection = null)
    content.vb: Public Sub New(backendAddressPool As ApplicationGatewayBackendAddressPool = Nothing, backendHttpSettingsCollection As IList(Of ApplicationGatewayBackendHealthHttpSettings) = Nothing)
    parameters:
    - id: backendAddressPool
      type: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool
    - id: backendHttpSettingsCollection
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.ApplicationGatewayBackendHealthPool(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool, System.Collections.Generic.IList(Of Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings))
  name.vb: ApplicationGatewayBackendHealthPool(ApplicationGatewayBackendAddressPool, IList(Of ApplicationGatewayBackendHealthHttpSettings))
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.BackendAddressPool
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.BackendAddressPool
  id: BackendAddressPool
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool
  langs:
  - csharp
  - vb
  name: BackendAddressPool
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.BackendAddressPool
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
      branch: 90abd71e223211ca3db26acbd29390809f4183dd
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: BackendAddressPool
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nReference of application gateway backend address pool resource.\n"
  example: []
  syntax:
    content: public ApplicationGatewayBackendAddressPool BackendAddressPool { get; set; }
    content.vb: Public Property BackendAddressPool As ApplicationGatewayBackendAddressPool
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.BackendHttpSettingsCollection
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.BackendHttpSettingsCollection
  id: BackendHttpSettingsCollection
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool
  langs:
  - csharp
  - vb
  name: BackendHttpSettingsCollection
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthPool.BackendHttpSettingsCollection
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
      branch: 90abd71e223211ca3db26acbd29390809f4183dd
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: BackendHttpSettingsCollection
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthPool.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nList of application gateway backendhealth http settings.\n"
  example: []
  syntax:
    content: public IList<ApplicationGatewayBackendHealthHttpSettings> BackendHttpSettingsCollection { get; set; }
    content.vb: Public Property BackendHttpSettingsCollection As IList(Of ApplicationGatewayBackendHealthHttpSettings)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ApplicationGatewayBackendAddressPool
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendAddressPool
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<ApplicationGatewayBackendHealthHttpSettings>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings)
  name.vb: IList(Of ApplicationGatewayBackendHealthHttpSettings)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
    name: ApplicationGatewayBackendHealthHttpSettings
    fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
    name: ApplicationGatewayBackendHealthHttpSettings
    fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
