### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult
  id: GetStartMenuApplicationResult
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  children:
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult.#ctor
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult.Result
  langs:
  - csharp
  - vb
  name: GetStartMenuApplicationResult
  nameWithType: GetStartMenuApplicationResult
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult
  type: Class
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: GetStartMenuApplicationResult
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationResult.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nDefinition for result of GetStartMenuApplication operation.\n"
  example: []
  syntax:
    content: 'public class GetStartMenuApplicationResult : AzureOperationResponse'
    content.vb: >-
      Public Class GetStartMenuApplicationResult
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult.Result
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult.Result
  id: Result
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult
  langs:
  - csharp
  - vb
  name: Result
  nameWithType: GetStartMenuApplicationResult.Result
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult.Result
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Result
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationResult.cs
    startLine: 38
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nOptional. Start menu application details.\n"
  example: []
  syntax:
    content: public StartMenuApplication Result { get; set; }
    content.vb: Public Property Result As StartMenuApplication
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult
  langs:
  - csharp
  - vb
  name: GetStartMenuApplicationResult()
  nameWithType: GetStartMenuApplicationResult.GetStartMenuApplicationResult()
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.GetStartMenuApplicationResult.GetStartMenuApplicationResult()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/GetStartMenuApplicationResult.cs
    startLine: 48
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the GetStartMenuApplicationResult\nclass.\n"
  example: []
  syntax:
    content: public GetStartMenuApplicationResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models
  commentId: N:Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.RemoteApp.Models
  nameWithType: Microsoft.WindowsAzure.Management.RemoteApp.Models
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: StartMenuApplication
  nameWithType: StartMenuApplication
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.StartMenuApplication
