items:
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication
  id: IWithApplication
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  children:
  - Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
  langs:
  - csharp
  - vb
  name: IWithApplication
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Definition/IDefinition.cs
      branch: 33fd3ea99c60bab0a8ccbb1cd87328cb5e82e49f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithApplication
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Definition/IDefinition.cs
    startLine: 69
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  summary: "\nA batch account definition to allow creation of application.\n"
  example: []
  syntax:
    content: public interface IWithApplication
    content.vb: Public Interface IWithApplication
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
  id: DefineNewApplication(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication
  langs:
  - csharp
  - vb
  name: DefineNewApplication(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplication.DefineNewApplication(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Definition/IDefinition.cs
      branch: 33fd3ea99c60bab0a8ccbb1cd87328cb5e82e49f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefineNewApplication
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/BatchAccount/Definition/IDefinition.cs
    startLine: 76
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  summary: "\nFirst stage to create new application in Batch account.\n"
  example: []
  syntax:
    content: IBlank<IWithApplicationAndStorage> DefineNewApplication(string applicationId)
    content.vb: Function DefineNewApplication(applicationId As String) As IBlank(Of IWithApplicationAndStorage)
    parameters:
    - id: applicationId
      type: System.String
      description: applicationId id of the application to create
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank{Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage}
      description: next stage to create the Batch account.
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
  fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank{Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage}
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
  name: IBlank<IWithApplicationAndStorage>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank<Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank(Of Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage)
  name.vb: IBlank(Of IWithApplicationAndStorage)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage
    name: IWithApplicationAndStorage
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage
    name: IWithApplicationAndStorage
    fullName: Microsoft.Azure.Management.Fluent.Batch.BatchAccount.Definition.IWithApplicationAndStorage
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IBlank<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank(Of ParentT)
  name.vb: IBlank(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
