items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  id: IWithAttach`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  children:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
  langs:
  - csharp
  - vb
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithAttach
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  syntax:
    content: 'public interface IWithAttach<ParentT> : IInDefinition<ParentT>, IWithApplicationPackage<ParentT>'
    content.vb: >-
      Public Interface IWithAttach(Of ParentT)
          Inherits IInDefinition(Of ParentT), IWithApplicationPackage(Of ParentT)
    typeParameters:
    - id: ParentT
  inheritedMembers:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage{{ParentT}}.DefineNewApplicationPackage(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithAllowUpdates(System.Boolean)
  id: WithAllowUpdates(System.Boolean)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  langs:
  - csharp
  - vb
  name: WithAllowUpdates(Boolean)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithAllowUpdates(System.Boolean)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithAllowUpdates
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  summary: "\nAllow automatic application updates.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithAllowUpdates(bool allowUpdates)
    content.vb: Function WithAllowUpdates(allowUpdates As Boolean) As IWithAttach(Of ParentT)
    parameters:
    - id: allowUpdates
      type: System.Boolean
      description: allowUpdates true to allow the automatic updates of application, otherwise false
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
      description: parent batch account definition.
  fullName.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithAllowUpdates(System.Boolean)
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1.WithDisplayName(System.String)
  id: WithDisplayName(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  langs:
  - csharp
  - vb
  name: WithDisplayName(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>.WithDisplayName(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDisplayName
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
    startLine: 55
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  summary: "\nSpecifies the display name for the application.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithDisplayName(string displayName)
    content.vb: Function WithDisplayName(displayName As String) As IWithAttach(Of ParentT)
    parameters:
    - id: displayName
      type: System.String
      description: displayName the displayName value to set
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
      description: parent batch account definition.
  fullName.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT).WithDisplayName(System.String)
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage{{ParentT}}.DefineNewApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage{{ParentT}}
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  name: DefineNewApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage(System.String)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  isExternal: true
  name: DefineNewApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage(System.String)
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
    name: DefineNewApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage{{ParentT}}
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  name: IWithApplicationPackage<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT)
  name.vb: IWithApplicationPackage(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IWithApplicationPackage<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT)
  name.vb: IWithApplicationPackage(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
