items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithLoadBalancer
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithLoadBalancer
  id: IWithLoadBalancer
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  children:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancer(Microsoft.Azure.Management.V2.Network.ILoadBalancer)
  langs:
  - csharp
  - vb
  name: IWithLoadBalancer
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithLoadBalancer
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithLoadBalancer
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nThe stage of the network interface's IP configuration allowing to specify the load balancer\nto associate this IP configuration with.\n"
  example: []
  syntax:
    content: public interface IWithLoadBalancer
    content.vb: Public Interface IWithLoadBalancer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancer(Microsoft.Azure.Management.V2.Network.ILoadBalancer)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancer(Microsoft.Azure.Management.V2.Network.ILoadBalancer)
  id: WithExistingLoadBalancer(Microsoft.Azure.Management.V2.Network.ILoadBalancer)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithLoadBalancer
  langs:
  - csharp
  - vb
  name: WithExistingLoadBalancer(ILoadBalancer)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancer(Microsoft.Azure.Management.V2.Network.ILoadBalancer)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithExistingLoadBalancer
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nSpecifies the load balancer to associate this IP configuration with.\n"
  example: []
  syntax:
    content: IWithBackendAddressPool WithExistingLoadBalancer(ILoadBalancer loadBalancer)
    content.vb: Function WithExistingLoadBalancer(loadBalancer As ILoadBalancer) As IWithBackendAddressPool
    parameters:
    - id: loadBalancer
      type: Microsoft.Azure.Management.V2.Network.ILoadBalancer
      description: loadBalancer an existing load balancer
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool
      description: the next stage of the update
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
- uid: Microsoft.Azure.Management.V2.Network.ILoadBalancer
  parent: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: ILoadBalancer
  fullName: Microsoft.Azure.Management.V2.Network.ILoadBalancer
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: IWithBackendAddressPool
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool
- uid: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network
  fullName: Microsoft.Azure.Management.V2.Network
