items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  id: ApplicationGatewayPathRuleInner
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.#ctor(System.String,System.Collections.Generic.IList{System.String},Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.BackendAddressPool
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.BackendHttpSettings
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Etag
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Name
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Paths
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.ProvisioningState
  langs:
  - csharp
  - vb
  name: ApplicationGatewayPathRuleInner
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayPathRuleInner
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nPath rule of URL path map of application gateway\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayPathRuleInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class ApplicationGatewayPathRuleInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayPathRuleInner()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.ApplicationGatewayPathRuleInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the ApplicationGatewayPathRuleInner\nclass.\n"
  example: []
  syntax:
    content: public ApplicationGatewayPathRuleInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.#ctor(System.String,System.Collections.Generic.IList{System.String},Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.#ctor(System.String,System.Collections.Generic.IList{System.String},Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  id: '#ctor(System.String,System.Collections.Generic.IList{System.String},Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayPathRuleInner(String, IList<String>, Rest.Azure.SubResource, Rest.Azure.SubResource, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.ApplicationGatewayPathRuleInner(System.String, System.Collections.Generic.IList<System.String>, Microsoft.Rest.Azure.SubResource, Microsoft.Rest.Azure.SubResource, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the ApplicationGatewayPathRuleInner\nclass.\n"
  example: []
  syntax:
    content: public ApplicationGatewayPathRuleInner(string id = null, IList<string> paths = null, Rest.Azure.SubResource backendAddressPool = null, Rest.Azure.SubResource backendHttpSettings = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, paths As IList(Of String) = Nothing, backendAddressPool As Rest.Azure.SubResource = Nothing, backendHttpSettings As Rest.Azure.SubResource = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: paths
      type: System.Collections.Generic.IList{System.String}
      description: Path rules of URL path map
    - id: backendAddressPool
      type: Microsoft.Rest.Azure.SubResource
      description: "Backend address pool resource of\nURL path map "
    - id: backendHttpSettings
      type: Microsoft.Rest.Azure.SubResource
      description: "Backend http settings resource\nof URL path map "
    - id: provisioningState
      type: System.String
      description: >-
        Path rule of URL path map resource

        Updating/Deleting/Failed
    - id: name
      type: System.String
      description: >-
        Name of the resource that is unique within a

        resource group. This name can be used to access the

        resource
    - id: etag
      type: System.String
      description: >-
        A unique read-only string that changes whenever

        the resource is updated
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.ApplicationGatewayPathRuleInner(System.String, System.Collections.Generic.IList(Of System.String), Microsoft.Rest.Azure.SubResource, Microsoft.Rest.Azure.SubResource, System.String, System.String, System.String)
  name.vb: ApplicationGatewayPathRuleInner(String, IList(Of String), Rest.Azure.SubResource, Rest.Azure.SubResource, String, String, String)
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Paths
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Paths
  id: Paths
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  langs:
  - csharp
  - vb
  name: Paths
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Paths
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Paths
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 54
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets path rules of URL path map\n"
  example: []
  syntax:
    content: public IList<string> Paths { get; set; }
    content.vb: Public Property Paths As IList(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.BackendAddressPool
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.BackendAddressPool
  id: BackendAddressPool
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  langs:
  - csharp
  - vb
  name: BackendAddressPool
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.BackendAddressPool
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: BackendAddressPool
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 60
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets backend address pool resource of URL path map\n"
  example: []
  syntax:
    content: public Rest.Azure.SubResource BackendAddressPool { get; set; }
    content.vb: Public Property BackendAddressPool As Rest.Azure.SubResource
    parameters: []
    return:
      type: Microsoft.Rest.Azure.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.BackendHttpSettings
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.BackendHttpSettings
  id: BackendHttpSettings
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  langs:
  - csharp
  - vb
  name: BackendHttpSettings
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.BackendHttpSettings
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: BackendHttpSettings
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 66
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets backend http settings resource of URL path map\n"
  example: []
  syntax:
    content: public Rest.Azure.SubResource BackendHttpSettings { get; set; }
    content.vb: Public Property BackendHttpSettings As Rest.Azure.SubResource
    parameters: []
    return:
      type: Microsoft.Rest.Azure.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets path rule of URL path map resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 80
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets name of the resource that is unique within a resource\ngroup. This name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRuleInner.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayPathRuleInner.cs
    startLine: 87
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets a unique read-only string that changes whenever the\nresource is updated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Collections.Generic.IList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<String>
  fullName: System.Collections.Generic.IList<System.String>
  fullname.vb: System.Collections.Generic.IList(Of System.String)
  name.vb: IList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Rest.Azure.SubResource
  isExternal: false
  name: Rest.Azure.SubResource
  fullName: Microsoft.Rest.Azure.SubResource
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
