items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  id: ApplicationGatewayIPConfiguration
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.#ctor(System.String,Microsoft.Azure.Management.Network.Models.SubResource,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Etag
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Name
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Subnet
  langs:
  - csharp
  - vb
  name: ApplicationGatewayIPConfiguration
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
      branch: 2d793328d097bcb56ec8f92d3d36ef0ffe249a1d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayIPConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.0.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nIP configuration of application gateway\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayIPConfiguration : SubResource'
    content.vb: >-
      Public Class ApplicationGatewayIPConfiguration
          Inherits SubResource
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Network.Models.SubResource
  inheritedMembers:
  - Microsoft.Azure.Management.Network.Models.SubResource.Id
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  langs:
  - csharp
  - vb
  name: ApplicationGatewayIPConfiguration()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.ApplicationGatewayIPConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
      branch: 2d793328d097bcb56ec8f92d3d36ef0ffe249a1d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
    startLine: 28
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.0.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayIPConfiguration class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayIPConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.#ctor(System.String,Microsoft.Azure.Management.Network.Models.SubResource,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.#ctor(System.String,Microsoft.Azure.Management.Network.Models.SubResource,System.String,System.String,System.String)
  id: '#ctor(System.String,Microsoft.Azure.Management.Network.Models.SubResource,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  langs:
  - csharp
  - vb
  name: ApplicationGatewayIPConfiguration(String, SubResource, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.ApplicationGatewayIPConfiguration(System.String, Microsoft.Azure.Management.Network.Models.SubResource, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
      branch: 2d793328d097bcb56ec8f92d3d36ef0ffe249a1d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.0.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayIPConfiguration class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayIPConfiguration(string id = null, SubResource subnet = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, subnet As SubResource = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: subnet
      type: Microsoft.Azure.Management.Network.Models.SubResource
    - id: provisioningState
      type: System.String
    - id: name
      type: System.String
    - id: etag
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Subnet
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Subnet
  id: Subnet
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  langs:
  - csharp
  - vb
  name: Subnet
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Subnet
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
      branch: 2d793328d097bcb56ec8f92d3d36ef0ffe249a1d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Subnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.0.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nReference of the subnet resource. A subnet from where application\ngateway gets its private address\n"
  example: []
  syntax:
    content: public SubResource Subnet { get; set; }
    content.vb: Public Property Subnet As SubResource
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
      branch: 2d793328d097bcb56ec8f92d3d36ef0ffe249a1d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
    startLine: 54
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.0.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nProvisioning state of the application gateway subnet resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
      branch: 2d793328d097bcb56ec8f92d3d36ef0ffe249a1d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.0.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nName of the resource that is unique within a resource group. This\nname can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfiguration.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
      branch: 2d793328d097bcb56ec8f92d3d36ef0ffe249a1d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayIpConfiguration.cs
    startLine: 68
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.0.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nA unique read-only string that changes whenever the resource is\nupdated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Network.Models.SubResource
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: SubResource
  fullName: Microsoft.Azure.Management.Network.Models.SubResource
- uid: Microsoft.Azure.Management.Network.Models.SubResource.Id
  parent: Microsoft.Azure.Management.Network.Models.SubResource
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.Network.Models.SubResource.Id
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
