### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate
  id: ApplicationGatewayCertificate
  parent: Microsoft.WindowsAzure.Management.Network.Models
  children:
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.#ctor
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.CertificateFormat
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.Data
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.Password
  langs:
  - csharp
  - vb
  name: ApplicationGatewayCertificate
  nameWithType: ApplicationGatewayCertificate
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayCertificate
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nParameters supplied to AddApplicationGatewayCertificate\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayCertificate : AzureOperationResponse'
    content.vb: >-
      Public Class ApplicationGatewayCertificate
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.CertificateFormat
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.CertificateFormat
  id: CertificateFormat
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate
  langs:
  - csharp
  - vb
  name: CertificateFormat
  nameWithType: ApplicationGatewayCertificate.CertificateFormat
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.CertificateFormat
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: CertificateFormat
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Certificate file format.\n"
  example: []
  syntax:
    content: public string CertificateFormat { get; set; }
    content.vb: Public Property CertificateFormat As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.Data
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.Data
  id: Data
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: ApplicationGatewayCertificate.Data
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.Data
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Data
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
    startLine: 48
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Certificate file data.\n"
  example: []
  syntax:
    content: public string Data { get; set; }
    content.vb: Public Property Data As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.Password
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.Password
  id: Password
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: ApplicationGatewayCertificate.Password
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.Password
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Password
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
    startLine: 59
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Certificate file password.\n"
  example: []
  syntax:
    content: public string Password { get; set; }
    content.vb: Public Property Password As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate
  langs:
  - csharp
  - vb
  name: ApplicationGatewayCertificate()
  nameWithType: ApplicationGatewayCertificate.ApplicationGatewayCertificate()
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayCertificate.ApplicationGatewayCertificate()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayCertificate.cs
    startLine: 69
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nInitializes a new instance of the ApplicationGatewayCertificate\nclass.\n"
  example: []
  syntax:
    content: public ApplicationGatewayCertificate()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Network.Models
  commentId: N:Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Network.Models
  nameWithType: Microsoft.WindowsAzure.Management.Network.Models
  fullName: Microsoft.WindowsAzure.Management.Network.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
