items:
- uid: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings
  commentId: T:Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings
  id: AS2ErrorSettings
  parent: Microsoft.Azure.Management.Logic.Models
  children:
  - Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.#ctor
  - Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.#ctor(System.Nullable{System.Boolean},System.Nullable{System.Boolean})
  - Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.ResendIfMdnNotReceived
  - Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.SuspendDuplicateMessage
  langs:
  - csharp
  - vb
  name: AS2ErrorSettings
  fullName: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: AS2ErrorSettings
    path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
    startLine: 18
  assemblies:
  - Microsoft.Azure.Management.Logic
  packages:
  - Microsoft.Azure.Management.Logic(1.0.0)
  namespace: Microsoft.Azure.Management.Logic.Models
  syntax:
    content: public class AS2ErrorSettings
    content.vb: Public Class AS2ErrorSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.#ctor
  commentId: M:Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings
  langs:
  - csharp
  - vb
  name: AS2ErrorSettings()
  fullName: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.AS2ErrorSettings()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
    startLine: 23
  assemblies:
  - Microsoft.Azure.Management.Logic
  packages:
  - Microsoft.Azure.Management.Logic(1.0.0)
  namespace: Microsoft.Azure.Management.Logic.Models
  summary: "\nInitializes a new instance of the AS2ErrorSettings class.\n"
  example: []
  syntax:
    content: public AS2ErrorSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.#ctor(System.Nullable{System.Boolean},System.Nullable{System.Boolean})
  commentId: M:Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.#ctor(System.Nullable{System.Boolean},System.Nullable{System.Boolean})
  id: '#ctor(System.Nullable{System.Boolean},System.Nullable{System.Boolean})'
  parent: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings
  langs:
  - csharp
  - vb
  name: AS2ErrorSettings(Nullable<Boolean>, Nullable<Boolean>)
  fullName: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.AS2ErrorSettings(System.Nullable<System.Boolean>, System.Nullable<System.Boolean>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
    startLine: 28
  assemblies:
  - Microsoft.Azure.Management.Logic
  packages:
  - Microsoft.Azure.Management.Logic(1.0.0)
  namespace: Microsoft.Azure.Management.Logic.Models
  summary: "\nInitializes a new instance of the AS2ErrorSettings class.\n"
  example: []
  syntax:
    content: public AS2ErrorSettings(bool ? suspendDuplicateMessage = null, bool ? resendIfMdnNotReceived = null)
    content.vb: Public Sub New(suspendDuplicateMessage As Boolean? = Nothing, resendIfMdnNotReceived As Boolean? = Nothing)
    parameters:
    - id: suspendDuplicateMessage
      type: System.Nullable{System.Boolean}
    - id: resendIfMdnNotReceived
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.AS2ErrorSettings(System.Nullable(Of System.Boolean), System.Nullable(Of System.Boolean))
  name.vb: AS2ErrorSettings(Nullable(Of Boolean), Nullable(Of Boolean))
- uid: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.SuspendDuplicateMessage
  commentId: P:Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.SuspendDuplicateMessage
  id: SuspendDuplicateMessage
  parent: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings
  langs:
  - csharp
  - vb
  name: SuspendDuplicateMessage
  fullName: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.SuspendDuplicateMessage
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: SuspendDuplicateMessage
    path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Logic
  packages:
  - Microsoft.Azure.Management.Logic(1.0.0)
  namespace: Microsoft.Azure.Management.Logic.Models
  summary: "\nGets or sets the value indicating whether to suspend duplicate\nmessage.\n"
  example: []
  syntax:
    content: public bool ? SuspendDuplicateMessage { get; set; }
    content.vb: Public Property SuspendDuplicateMessage As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.ResendIfMdnNotReceived
  commentId: P:Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.ResendIfMdnNotReceived
  id: ResendIfMdnNotReceived
  parent: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings
  langs:
  - csharp
  - vb
  name: ResendIfMdnNotReceived
  fullName: Microsoft.Azure.Management.Logic.Models.AS2ErrorSettings.ResendIfMdnNotReceived
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ResendIfMdnNotReceived
    path: src/ResourceManagement/Logic/Microsoft.Azure.Management.Logic/Generated/Models/AS2ErrorSettings.cs
    startLine: 45
  assemblies:
  - Microsoft.Azure.Management.Logic
  packages:
  - Microsoft.Azure.Management.Logic(1.0.0)
  namespace: Microsoft.Azure.Management.Logic.Models
  summary: "\nGets or sets the value indicating whether to resend message If MDN\nis not received.\n"
  example: []
  syntax:
    content: public bool ? ResendIfMdnNotReceived { get; set; }
    content.vb: Public Property ResendIfMdnNotReceived As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Logic.Models
  isExternal: false
  name: Microsoft.Azure.Management.Logic.Models
  fullName: Microsoft.Azure.Management.Logic.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
