items:
- uid: Microsoft.Azure.Management.Azure.IConfigurable
  commentId: T:Microsoft.Azure.Management.Azure.IConfigurable
  id: Azure.IConfigurable
  parent: Microsoft.Azure.Management
  children:
  - Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials)
  langs:
  - csharp
  - vb
  name: Azure.IConfigurable
  fullName: Microsoft.Azure.Management.Azure.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
    startLine: 246
  assemblies:
  - Microsoft.Azure.Management
  packages:
  - Microsoft.Azure.Management(1.0.0)
  namespace: Microsoft.Azure.Management
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<Azure.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of Azure.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials)
  commentId: M:Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials)
  id: Authenticate(ServiceClientCredentials)
  parent: Microsoft.Azure.Management.Azure.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials)
  fullName: Microsoft.Azure.Management.Azure.IConfigurable.Authenticate(ServiceClientCredentials)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Azure/Microsoft.Azure.Management/Azure.cs
    startLine: 248
  assemblies:
  - Microsoft.Azure.Management
  packages:
  - Microsoft.Azure.Management(1.0.0)
  namespace: Microsoft.Azure.Management
  syntax:
    content: Azure.IAuthenticated Authenticate(ServiceClientCredentials serviceClientCredentials)
    content.vb: Function Authenticate(serviceClientCredentials As ServiceClientCredentials) As Azure.IAuthenticated
    parameters:
    - id: serviceClientCredentials
      type: ServiceClientCredentials
    return:
      type: Microsoft.Azure.Management.Azure.IAuthenticated
references:
- uid: Microsoft.Azure.Management
  isExternal: false
  name: Microsoft.Azure.Management
  fullName: Microsoft.Azure.Management
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: Microsoft.Azure.Management.Azure.IAuthenticated
  parent: Microsoft.Azure.Management
  isExternal: false
  name: Azure.IAuthenticated
  fullName: Microsoft.Azure.Management.Azure.IAuthenticated
