items:
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource
  commentId: T:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource
  id: SlotConfigNamesResource
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.#ctor
  - Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.#ctor(System.String,System.String,System.String,System.String,System.Collections.Generic.IDictionary{System.String,System.String},System.Collections.Generic.IList{System.String},System.Collections.Generic.IList{System.String})
  - Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.AppSettingNames
  - Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.ConnectionStringNames
  - Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.Validate
  langs:
  - csharp
  - vb
  name: SlotConfigNamesResource
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource
  type: Class
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
      branch: 7102889aafab03345c2d03ebaa4f387e5e2db8d9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: SlotConfigNamesResource
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nSlot Config names azure resource\n"
  example: []
  syntax:
    content: 'public class SlotConfigNamesResource : Resource'
    content.vb: >-
      Public Class SlotConfigNamesResource
          Inherits Resource
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.WebSites.Models.Resource
  inheritedMembers:
  - Microsoft.Azure.Management.WebSites.Models.Resource.Id
  - Microsoft.Azure.Management.WebSites.Models.Resource.Name
  - Microsoft.Azure.Management.WebSites.Models.Resource.Location
  - Microsoft.Azure.Management.WebSites.Models.Resource.Type
  - Microsoft.Azure.Management.WebSites.Models.Resource.Tags
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.#ctor
  commentId: M:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource
  langs:
  - csharp
  - vb
  name: SlotConfigNamesResource()
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.SlotConfigNamesResource()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
      branch: 7102889aafab03345c2d03ebaa4f387e5e2db8d9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
    startLine: 26
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the SlotConfigNamesResource class.\n"
  example: []
  syntax:
    content: public SlotConfigNamesResource()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.#ctor(System.String,System.String,System.String,System.String,System.Collections.Generic.IDictionary{System.String,System.String},System.Collections.Generic.IList{System.String},System.Collections.Generic.IList{System.String})
  commentId: M:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.#ctor(System.String,System.String,System.String,System.String,System.Collections.Generic.IDictionary{System.String,System.String},System.Collections.Generic.IList{System.String},System.Collections.Generic.IList{System.String})
  id: '#ctor(System.String,System.String,System.String,System.String,System.Collections.Generic.IDictionary{System.String,System.String},System.Collections.Generic.IList{System.String},System.Collections.Generic.IList{System.String})'
  parent: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource
  langs:
  - csharp
  - vb
  name: SlotConfigNamesResource(String, String, String, String, IDictionary<String, String>, IList<String>, IList<String>)
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.SlotConfigNamesResource(System.String, System.String, System.String, System.String, System.Collections.Generic.IDictionary<System.String, System.String>, System.Collections.Generic.IList<System.String>, System.Collections.Generic.IList<System.String>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
      branch: 7102889aafab03345c2d03ebaa4f387e5e2db8d9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the SlotConfigNamesResource class.\n"
  example: []
  syntax:
    content: public SlotConfigNamesResource(string location, string id = null, string name = null, string type = null, IDictionary<string, string> tags = null, IList<string> connectionStringNames = null, IList<string> appSettingNames = null)
    content.vb: Public Sub New(location As String, id As String = Nothing, name As String = Nothing, type As String = Nothing, tags As IDictionary(Of String, String) = Nothing, connectionStringNames As IList(Of String) = Nothing, appSettingNames As IList(Of String) = Nothing)
    parameters:
    - id: location
      type: System.String
    - id: id
      type: System.String
    - id: name
      type: System.String
    - id: type
      type: System.String
    - id: tags
      type: System.Collections.Generic.IDictionary{System.String,System.String}
    - id: connectionStringNames
      type: System.Collections.Generic.IList{System.String}
    - id: appSettingNames
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.SlotConfigNamesResource(System.String, System.String, System.String, System.String, System.Collections.Generic.IDictionary(Of System.String, System.String), System.Collections.Generic.IList(Of System.String), System.Collections.Generic.IList(Of System.String))
  name.vb: SlotConfigNamesResource(String, String, String, String, IDictionary(Of String, String), IList(Of String), IList(Of String))
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.ConnectionStringNames
  commentId: P:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.ConnectionStringNames
  id: ConnectionStringNames
  parent: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource
  langs:
  - csharp
  - vb
  name: ConnectionStringNames
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.ConnectionStringNames
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
      branch: 7102889aafab03345c2d03ebaa4f387e5e2db8d9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ConnectionStringNames
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
    startLine: 41
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nList of connection string names\n"
  example: []
  syntax:
    content: public IList<string> ConnectionStringNames { get; set; }
    content.vb: Public Property ConnectionStringNames As IList(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.AppSettingNames
  commentId: P:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.AppSettingNames
  id: AppSettingNames
  parent: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource
  langs:
  - csharp
  - vb
  name: AppSettingNames
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.AppSettingNames
  type: Property
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
      branch: 7102889aafab03345c2d03ebaa4f387e5e2db8d9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: AppSettingNames
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nList of application settings names\n"
  example: []
  syntax:
    content: public IList<string> AppSettingNames { get; set; }
    content.vb: Public Property AppSettingNames As IList(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.Validate
  commentId: M:Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.Validate
  id: Validate
  parent: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource
  langs:
  - csharp
  - vb
  name: Validate()
  fullName: Microsoft.Azure.Management.WebSites.Models.SlotConfigNamesResource.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
      branch: 7102889aafab03345c2d03ebaa4f387e5e2db8d9
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/SlotConfigNamesResource.cs
    startLine: 53
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nValidate the object. Throws ValidationException if validation fails.\n"
  example: []
  syntax:
    content: public override void Validate()
    content.vb: Public Overrides Sub Validate
  overridden: Microsoft.Azure.Management.WebSites.Models.Resource.Validate
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.WebSites.Models.Resource
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Resource
  fullName: Microsoft.Azure.Management.WebSites.Models.Resource
- uid: Microsoft.Azure.Management.WebSites.Models.Resource.Id
  parent: Microsoft.Azure.Management.WebSites.Models.Resource
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.WebSites.Models.Resource.Id
- uid: Microsoft.Azure.Management.WebSites.Models.Resource.Name
  parent: Microsoft.Azure.Management.WebSites.Models.Resource
  isExternal: false
  name: Name
  fullName: Microsoft.Azure.Management.WebSites.Models.Resource.Name
- uid: Microsoft.Azure.Management.WebSites.Models.Resource.Location
  parent: Microsoft.Azure.Management.WebSites.Models.Resource
  isExternal: false
  name: Location
  fullName: Microsoft.Azure.Management.WebSites.Models.Resource.Location
- uid: Microsoft.Azure.Management.WebSites.Models.Resource.Type
  parent: Microsoft.Azure.Management.WebSites.Models.Resource
  isExternal: false
  name: Type
  fullName: Microsoft.Azure.Management.WebSites.Models.Resource.Type
- uid: Microsoft.Azure.Management.WebSites.Models.Resource.Tags
  parent: Microsoft.Azure.Management.WebSites.Models.Resource
  isExternal: false
  name: Tags
  fullName: Microsoft.Azure.Management.WebSites.Models.Resource.Tags
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Collections.Generic.IDictionary{System.String,System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  name: IDictionary<String, String>
  fullName: System.Collections.Generic.IDictionary<System.String, System.String>
  fullname.vb: System.Collections.Generic.IDictionary(Of System.String, System.String)
  name.vb: IDictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<String>
  fullName: System.Collections.Generic.IList<System.String>
  fullname.vb: System.Collections.Generic.IList(Of System.String)
  name.vb: IList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IDictionary`2
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  fullname.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.WebSites.Models.Resource.Validate
  parent: Microsoft.Azure.Management.WebSites.Models.Resource
  isExternal: false
  name: Validate()
  fullName: Microsoft.Azure.Management.WebSites.Models.Resource.Validate()
  spec.csharp:
  - uid: Microsoft.Azure.Management.WebSites.Models.Resource.Validate
    name: Validate
    fullName: Microsoft.Azure.Management.WebSites.Models.Resource.Validate
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.WebSites.Models.Resource.Validate
    name: Validate
    fullName: Microsoft.Azure.Management.WebSites.Models.Resource.Validate
  - name: (
    fullName: (
  - name: )
    fullName: )
