items:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1
  commentId: T:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1
  id: IWithLoadBalancer`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  children:
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1.WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1.WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  langs:
  - csharp
  - vb
  name: IWithLoadBalancer<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithLoadBalancer
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 139
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  syntax:
    content: public interface IWithLoadBalancer<ParentT>
    content.vb: Public Interface IWithLoadBalancer(Of ParentT)
    typeParameters:
    - id: ParentT
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer(Of ParentT)
  name.vb: IWithLoadBalancer(Of ParentT)
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1.WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1.WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  id: WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1
  langs:
  - csharp
  - vb
  name: WithExistingLoadBalancerBackend(ILoadBalancer, String)
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer<ParentT>.WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithExistingLoadBalancerBackend
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 147
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  summary: "\nSpecifies the load balancer to associate this IP configuration with.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithExistingLoadBalancerBackend(ILoadBalancer loadBalancer, string backendName)
    content.vb: Function WithExistingLoadBalancerBackend(loadBalancer As ILoadBalancer, backendName As String) As IWithAttach(Of ParentT)
    parameters:
    - id: loadBalancer
      type: Microsoft.Azure.Management.Fluent.Network.ILoadBalancer
      description: loadBalancer an existing load balancer
    - id: backendName
      type: System.String
      description: backendName the name of an existing backend on that load balancer
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach{{ParentT}}
      description: the next stage of the update
  fullName.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer(Of ParentT).WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer, System.String)
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1.WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1.WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  id: WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer`1
  langs:
  - csharp
  - vb
  name: WithExistingLoadBalancerInboundNatRule(ILoadBalancer, String)
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer<ParentT>.WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithExistingLoadBalancerInboundNatRule
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 155
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  summary: "\nSpecifies the load balancer inbound NAT rule to associate this IP configuration with.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithExistingLoadBalancerInboundNatRule(ILoadBalancer loadBalancer, string inboundNatRuleName)
    content.vb: Function WithExistingLoadBalancerInboundNatRule(loadBalancer As ILoadBalancer, inboundNatRuleName As String) As IWithAttach(Of ParentT)
    parameters:
    - id: loadBalancer
      type: Microsoft.Azure.Management.Fluent.Network.ILoadBalancer
      description: loadBalancer an existing load balancer
    - id: inboundNatRuleName
      type: System.String
      description: inboundNatRuleName the name of an existing inbound NAT rule on the selected load balancer
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach{{ParentT}}
      description: the next stage of the update
  fullName.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithLoadBalancer(Of ParentT).WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer, System.String)
references:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
- uid: Microsoft.Azure.Management.Fluent.Network.ILoadBalancer
  parent: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: ILoadBalancer
  fullName: Microsoft.Azure.Management.Fluent.Network.ILoadBalancer
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach{{ParentT}}
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  definition: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network
  fullName: Microsoft.Azure.Management.Fluent.Network
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
