items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
  id: IWithSubnet`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  children:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1.WithSubnet(System.String)
  langs:
  - csharp
  - vb
  name: IWithSubnet<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithSubnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 116
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  syntax:
    content: public interface IWithSubnet<ParentT>
    content.vb: Public Interface IWithSubnet(Of ParentT)
    typeParameters:
    - id: ParentT
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet(Of ParentT)
  name.vb: IWithSubnet(Of ParentT)
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1.WithSubnet(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1.WithSubnet(System.String)
  id: WithSubnet(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
  langs:
  - csharp
  - vb
  name: WithSubnet(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet<ParentT>.WithSubnet(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithSubnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 123
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  summary: "\nAssociate a subnet with the network interface IP configuration.\n"
  example: []
  syntax:
    content: IWithPrivateIp<ParentT> WithSubnet(string name)
    content.vb: Function WithSubnet(name As String) As IWithPrivateIp(Of ParentT)
    parameters:
    - id: name
      type: System.String
      description: name the subnet name
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp{{ParentT}}
      description: the next stage of the network interface IP configuration definition
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet(Of ParentT).WithSubnet(System.String)
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp{{ParentT}}
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
  name: IWithPrivateIp<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp(Of ParentT)
  name.vb: IWithPrivateIp(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: IWithPrivateIp<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp(Of ParentT)
  name.vb: IWithPrivateIp(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
