items:
- uid: Microsoft.Azure.Management.Network.Models.BgpSettings
  commentId: T:Microsoft.Azure.Management.Network.Models.BgpSettings
  id: BgpSettings
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.BgpSettings.#ctor
  - Microsoft.Azure.Management.Network.Models.BgpSettings.#ctor(System.Nullable{System.Int64},System.String,System.Nullable{System.Int32})
  - Microsoft.Azure.Management.Network.Models.BgpSettings.Asn
  - Microsoft.Azure.Management.Network.Models.BgpSettings.BgpPeeringAddress
  - Microsoft.Azure.Management.Network.Models.BgpSettings.PeerWeight
  langs:
  - csharp
  - vb
  name: BgpSettings
  fullName: Microsoft.Azure.Management.Network.Models.BgpSettings
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: BgpSettings
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
    startLine: 18
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  syntax:
    content: public class BgpSettings
    content.vb: Public Class BgpSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.BgpSettings.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.BgpSettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.BgpSettings
  langs:
  - csharp
  - vb
  name: BgpSettings()
  fullName: Microsoft.Azure.Management.Network.Models.BgpSettings.BgpSettings()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
    startLine: 23
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the BgpSettings class.\n"
  example: []
  syntax:
    content: public BgpSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.BgpSettings.#ctor(System.Nullable{System.Int64},System.String,System.Nullable{System.Int32})
  commentId: M:Microsoft.Azure.Management.Network.Models.BgpSettings.#ctor(System.Nullable{System.Int64},System.String,System.Nullable{System.Int32})
  id: '#ctor(System.Nullable{System.Int64},System.String,System.Nullable{System.Int32})'
  parent: Microsoft.Azure.Management.Network.Models.BgpSettings
  langs:
  - csharp
  - vb
  name: BgpSettings(Nullable<Int64>, String, Nullable<Int32>)
  fullName: Microsoft.Azure.Management.Network.Models.BgpSettings.BgpSettings(System.Nullable<System.Int64>, System.String, System.Nullable<System.Int32>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
    startLine: 28
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the BgpSettings class.\n"
  example: []
  syntax:
    content: public BgpSettings(long ? asn = null, string bgpPeeringAddress = null, int ? peerWeight = null)
    content.vb: Public Sub New(asn As Long? = Nothing, bgpPeeringAddress As String = Nothing, peerWeight As Integer? = Nothing)
    parameters:
    - id: asn
      type: System.Nullable{System.Int64}
    - id: bgpPeeringAddress
      type: System.String
    - id: peerWeight
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Network.Models.BgpSettings.BgpSettings(System.Nullable(Of System.Int64), System.String, System.Nullable(Of System.Int32))
  name.vb: BgpSettings(Nullable(Of Int64), String, Nullable(Of Int32))
- uid: Microsoft.Azure.Management.Network.Models.BgpSettings.Asn
  commentId: P:Microsoft.Azure.Management.Network.Models.BgpSettings.Asn
  id: Asn
  parent: Microsoft.Azure.Management.Network.Models.BgpSettings
  langs:
  - csharp
  - vb
  name: Asn
  fullName: Microsoft.Azure.Management.Network.Models.BgpSettings.Asn
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Asn
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets this BGP speaker's ASN\n"
  example: []
  syntax:
    content: public long ? Asn { get; set; }
    content.vb: Public Property Asn As Long?
    parameters: []
    return:
      type: System.Nullable{System.Int64}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.BgpSettings.BgpPeeringAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.BgpSettings.BgpPeeringAddress
  id: BgpPeeringAddress
  parent: Microsoft.Azure.Management.Network.Models.BgpSettings
  langs:
  - csharp
  - vb
  name: BgpPeeringAddress
  fullName: Microsoft.Azure.Management.Network.Models.BgpSettings.BgpPeeringAddress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: BgpPeeringAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
    startLine: 45
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the BGP peering address and BGP identifier of this\nBGP speaker\n"
  example: []
  syntax:
    content: public string BgpPeeringAddress { get; set; }
    content.vb: Public Property BgpPeeringAddress As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.BgpSettings.PeerWeight
  commentId: P:Microsoft.Azure.Management.Network.Models.BgpSettings.PeerWeight
  id: PeerWeight
  parent: Microsoft.Azure.Management.Network.Models.BgpSettings
  langs:
  - csharp
  - vb
  name: PeerWeight
  fullName: Microsoft.Azure.Management.Network.Models.BgpSettings.PeerWeight
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
      branch: 967803e8a0144ab049c79e1c732490267b7528d7
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PeerWeight
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/BgpSettings.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(6.1.0-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the weight added to routes learned from this BGP\nspeaker\n"
  example: []
  syntax:
    content: public int ? PeerWeight { get; set; }
    content.vb: Public Property PeerWeight As Integer?
    parameters: []
    return:
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Nullable{System.Int64}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int64>
  fullName: System.Nullable<System.Int64>
  fullname.vb: System.Nullable(Of System.Int64)
  name.vb: Nullable(Of Int64)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int64
    name: Int64
    fullName: System.Int64
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int64
    name: Int64
    fullName: System.Int64
    isExternal: true
  - name: )
    fullName: )
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  fullname.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
