items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage`1
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage`1
  id: IWithApplicationPackage`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  children:
  - Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  langs:
  - csharp
  - vb
  name: IWithApplicationPackage<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/UpdateDefinition/IUpdateDefinition.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithApplicationPackage
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/UpdateDefinition/IUpdateDefinition.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  syntax:
    content: public interface IWithApplicationPackage<ParentT>
    content.vb: Public Interface IWithApplicationPackage(Of ParentT)
    typeParameters:
    - id: ParentT
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage(Of ParentT)
  name.vb: IWithApplicationPackage(Of ParentT)
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  id: DefineNewApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage`1
  langs:
  - csharp
  - vb
  name: DefineNewApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/UpdateDefinition/IUpdateDefinition.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefineNewApplicationPackage
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/UpdateDefinition/IUpdateDefinition.cs
    startLine: 63
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  summary: "\nFirst stage to create new application package in Batch account application.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> DefineNewApplicationPackage(string version)
    content.vb: Function DefineNewApplicationPackage(version As String) As IWithAttach(Of ParentT)
    parameters:
    - id: version
      type: System.String
      description: version the version of the application
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach{{ParentT}}
      description: next stage to create the application.
  fullName.vb: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage(System.String)
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach{{ParentT}}
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach`1
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.UpdateDefinition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
