### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult
  id: ActiveDirectoryConfigResult
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  children:
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult.#ctor
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult.ActiveDirectoryConfig
  langs:
  - csharp
  - vb
  name: ActiveDirectoryConfigResult
  nameWithType: ActiveDirectoryConfigResult
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult
  type: Class
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfigResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ActiveDirectoryConfigResult
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfigResult.cs
    startLine: 32
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nSimilar in structure to the VNet class but used to return one of these\nin GET requests.\n"
  example: []
  syntax:
    content: 'public class ActiveDirectoryConfigResult : AzureOperationResponse'
    content.vb: >-
      Public Class ActiveDirectoryConfigResult
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult.ActiveDirectoryConfig
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult.ActiveDirectoryConfig
  id: ActiveDirectoryConfig
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult
  langs:
  - csharp
  - vb
  name: ActiveDirectoryConfig
  nameWithType: ActiveDirectoryConfigResult.ActiveDirectoryConfig
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult.ActiveDirectoryConfig
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfigResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ActiveDirectoryConfig
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfigResult.cs
    startLine: 39
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nOptional.\n"
  example: []
  syntax:
    content: public ActiveDirectoryConfig ActiveDirectoryConfig { get; set; }
    content.vb: Public Property ActiveDirectoryConfig As ActiveDirectoryConfig
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult
  langs:
  - csharp
  - vb
  name: ActiveDirectoryConfigResult()
  nameWithType: ActiveDirectoryConfigResult.ActiveDirectoryConfigResult()
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfigResult.ActiveDirectoryConfigResult()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfigResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfigResult.cs
    startLine: 48
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the ActiveDirectoryConfigResult class.\n"
  example: []
  syntax:
    content: public ActiveDirectoryConfigResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models
  commentId: N:Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.RemoteApp.Models
  nameWithType: Microsoft.WindowsAzure.Management.RemoteApp.Models
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: ActiveDirectoryConfig
  nameWithType: ActiveDirectoryConfig
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
