items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  commentId: N:Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  id: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  children:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition`1
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  langs:
  - csharp
  - vb
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  type: Namespace
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition`1
  isExternal: false
  name: IDefinition<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition(Of ParentT)
  name.vb: IDefinition(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition`1
    name: IDefinition
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition`1
    name: IDefinition
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IDefinition
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IWithApplicationPackage<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT)
  name.vb: IWithApplicationPackage(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
    name: IWithApplicationPackage
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IBlank<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank(Of ParentT)
  name.vb: IBlank(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
