items:
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  commentId: T:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  id: ManagedHostingEnvironmentStatus
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Deleting
  - Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Preparing
  - Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Ready
  langs:
  - csharp
  - vb
  name: ManagedHostingEnvironmentStatus
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
      branch: 08a533223b1012cdbb21477270acfac04b8573a3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ManagedHostingEnvironmentStatus
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nDefines values for ManagedHostingEnvironmentStatus.\n"
  example: []
  syntax:
    content: public enum ManagedHostingEnvironmentStatus
    content.vb: Public Enum ManagedHostingEnvironmentStatus
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Preparing
  commentId: F:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Preparing
  id: Preparing
  parent: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Preparing
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Preparing
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
      branch: 08a533223b1012cdbb21477270acfac04b8573a3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Preparing
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: Preparing = 0
    return:
      type: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Ready
  commentId: F:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Ready
  id: Ready
  parent: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Ready
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Ready
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
      branch: 08a533223b1012cdbb21477270acfac04b8573a3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Ready
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: Ready = 1
    return:
      type: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Deleting
  commentId: F:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Deleting
  id: Deleting
  parent: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Deleting
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Deleting
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
      branch: 08a533223b1012cdbb21477270acfac04b8573a3
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Deleting
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
    startLine: 24
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: Deleting = 2
    return:
      type: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: ManagedHostingEnvironmentStatus
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
