items:
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings
  commentId: T:Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings
  id: IWithSettings
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  children:
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSetting(System.String,System.Object)
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSetting(System.String,System.Object)
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  langs:
  - csharp
  - vb
  name: IWithSettings
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
    startLine: 69
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  summary: "\nThe stage of the virtual machine extension update allowing to add or update public and private settings.\n"
  example: []
  syntax:
    content: public interface IWithSettings
    content.vb: Public Interface IWithSettings
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSetting(System.String,System.Object)
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSetting(System.String,System.Object)
  id: WithPublicSetting(System.String,System.Object)
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings
  langs:
  - csharp
  - vb
  name: WithPublicSetting(String, Object)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSetting(System.String, System.Object)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithPublicSetting
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
    startLine: 77
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  summary: "\nSpecifies a public settings entry.\n"
  example: []
  syntax:
    content: IUpdate WithPublicSetting(string key, object value)
    content.vb: Function WithPublicSetting(key As String, value As Object) As IUpdate
    parameters:
    - id: key
      type: System.String
      description: key the key of a public settings entry
    - id: value
      type: System.Object
      description: value the value of the public settings entry
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IUpdate
      description: the next stage of the update
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSetting(System.String,System.Object)
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSetting(System.String,System.Object)
  id: WithProtectedSetting(System.String,System.Object)
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings
  langs:
  - csharp
  - vb
  name: WithProtectedSetting(String, Object)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSetting(System.String, System.Object)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithProtectedSetting
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
    startLine: 85
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  summary: "\nSpecifies a private settings entry.\n"
  example: []
  syntax:
    content: IUpdate WithProtectedSetting(string key, object value)
    content.vb: Function WithProtectedSetting(key As String, value As Object) As IUpdate
    parameters:
    - id: key
      type: System.String
      description: key the key of a private settings entry
    - id: value
      type: System.Object
      description: value the value of the private settings entry
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IUpdate
      description: the next stage of the update
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  id: WithPublicSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings
  langs:
  - csharp
  - vb
  name: WithPublicSettings(IDictionary<String, Object>)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSettings(System.Collections.Generic.IDictionary<System.String, System.Object>)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithPublicSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
    startLine: 92
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  summary: "\nSpecifies public settings.\n"
  example: []
  syntax:
    content: IUpdate WithPublicSettings(IDictionary<string, object> settings)
    content.vb: Function WithPublicSettings(settings As IDictionary(Of String, Object)) As IUpdate
    parameters:
    - id: settings
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: settings the public settings
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IUpdate
      description: the next stage of the update
  fullName.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithPublicSettings(System.Collections.Generic.IDictionary(Of System.String, System.Object))
  name.vb: WithPublicSettings(IDictionary(Of String, Object))
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  id: WithProtectedSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings
  langs:
  - csharp
  - vb
  name: WithProtectedSettings(IDictionary<String, Object>)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSettings(System.Collections.Generic.IDictionary<System.String, System.Object>)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithProtectedSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineExtension/Update/IUpdate.cs
    startLine: 99
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  summary: "\nSpecifies private settings.\n"
  example: []
  syntax:
    content: IUpdate WithProtectedSettings(IDictionary<string, object> settings)
    content.vb: Function WithProtectedSettings(settings As IDictionary(Of String, Object)) As IUpdate
    parameters:
    - id: settings
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: settings the private settings
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IUpdate
      description: the next stage of the update
  fullName.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IWithSettings.WithProtectedSettings(System.Collections.Generic.IDictionary(Of System.String, System.Object))
  name.vb: WithProtectedSettings(IDictionary(Of String, Object))
references:
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IUpdate
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineExtension.Update.IUpdate
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  name: IDictionary<String, Object>
  fullName: System.Collections.Generic.IDictionary<System.String, System.Object>
  fullname.vb: System.Collections.Generic.IDictionary(Of System.String, System.Object)
  name.vb: IDictionary(Of String, Object)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IDictionary`2
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  fullname.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
