items:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  commentId: N:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  id: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  children:
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithPrivateIp
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithSubnet
  langs:
  - csharp
  - vb
  name: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  type: Namespace
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
references:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithSubnet
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  isExternal: false
  name: IWithSubnet
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithSubnet
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithPublicIpAddress
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  isExternal: false
  name: IWithPublicIpAddress
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithPublicIpAddress
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  isExternal: false
  name: IWithLoadBalancer
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithPrivateIp
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  isExternal: false
  name: IWithPrivateIp
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithPrivateIp
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
