items:
- uid: Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  commentId: T:Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  id: INicIpConfiguration
  parent: Microsoft.Azure.Management.V2.Network
  children:
  - Microsoft.Azure.Management.V2.Network.INicIpConfiguration.Network
  - Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PrivateIp
  - Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PrivateIpAllocationMethod
  - Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PublicIpAddress
  - Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PublicIpAddressId
  - Microsoft.Azure.Management.V2.Network.INicIpConfiguration.SubnetId
  langs:
  - csharp
  - vb
  name: INicIpConfiguration
  fullName: Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: INicIpConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
    startLine: 11
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  summary: "\nAn IP configuration in a network interface.\n"
  example: []
  syntax:
    content: 'public interface INicIpConfiguration : IWrapper<NetworkInterfaceIPConfigurationInner>, IChildResource<INetworkInterface>'
    content.vb: >-
      Public Interface INicIpConfiguration
          Inherits IWrapper(Of NetworkInterfaceIPConfigurationInner), IChildResource(Of INetworkInterface)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PublicIpAddressId
  commentId: P:Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PublicIpAddressId
  id: PublicIpAddressId
  parent: Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: PublicIpAddressId
  fullName: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PublicIpAddressId
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PublicIpAddressId
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
    startLine: 19
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  summary: "\nGets the resource id of the public IP address associated with this IP configuration.\n"
  example: []
  syntax:
    content: string PublicIpAddressId { get; }
    content.vb: ReadOnly Property PublicIpAddressId As String
    parameters: []
    return:
      type: System.String
      description: public IP resource ID or null if there is no public IP associated
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PublicIpAddress
  commentId: M:Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PublicIpAddress
  id: PublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: PublicIpAddress()
  fullName: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PublicIpAddress()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PublicIpAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  syntax:
    content: IPublicIpAddress PublicIpAddress()
    content.vb: Function PublicIpAddress As IPublicIpAddress
    return:
      type: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
- uid: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.SubnetId
  commentId: P:Microsoft.Azure.Management.V2.Network.INicIpConfiguration.SubnetId
  id: SubnetId
  parent: Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: SubnetId
  fullName: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.SubnetId
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: SubnetId
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  example: []
  syntax:
    content: string SubnetId { get; }
    content.vb: ReadOnly Property SubnetId As String
    parameters: []
    return:
      type: System.String
      description: the resource id of the virtual network subnet associated with this IP configuration.
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.Network
  commentId: M:Microsoft.Azure.Management.V2.Network.INicIpConfiguration.Network
  id: Network
  parent: Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: Network()
  fullName: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.Network()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Network
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  syntax:
    content: INetwork Network()
    content.vb: Function Network As INetwork
    return:
      type: Microsoft.Azure.Management.V2.Network.INetwork
- uid: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PrivateIp
  commentId: P:Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PrivateIp
  id: PrivateIp
  parent: Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: PrivateIp
  fullName: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PrivateIp
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIp
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  syntax:
    content: string PrivateIp { get; }
    content.vb: ReadOnly Property PrivateIp As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PrivateIpAllocationMethod
  commentId: P:Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PrivateIpAllocationMethod
  id: PrivateIpAllocationMethod
  parent: Microsoft.Azure.Management.V2.Network.INicIpConfiguration
  langs:
  - csharp
  - vb
  name: PrivateIpAllocationMethod
  fullName: Microsoft.Azure.Management.V2.Network.INicIpConfiguration.PrivateIpAllocationMethod
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIpAllocationMethod
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/INicIpConfiguration.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network
  example: []
  syntax:
    content: string PrivateIpAllocationMethod { get; }
    content.vb: ReadOnly Property PrivateIpAllocationMethod As String
    parameters: []
    return:
      type: System.String
      description: the private IP allocation method (Dynamic, Static)
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network
  fullName: Microsoft.Azure.Management.V2.Network
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
  parent: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: IPublicIpAddress
  fullName: Microsoft.Azure.Management.V2.Network.IPublicIpAddress
- uid: Microsoft.Azure.Management.V2.Network.INetwork
  parent: Microsoft.Azure.Management.V2.Network
  isExternal: false
  name: INetwork
  fullName: Microsoft.Azure.Management.V2.Network.INetwork
