items:
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  commentId: T:Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  id: DeploymentExtendedInner
  parent: Microsoft.Azure.Management.ResourceManager.Models
  children:
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.#ctor
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.#ctor(System.String,System.String,Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Id
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Name
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Properties
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Validate
  langs:
  - csharp
  - vb
  name: DeploymentExtendedInner
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DeploymentExtendedInner
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nDeployment information.\n"
  example: []
  syntax:
    content: public class DeploymentExtendedInner
    content.vb: Public Class DeploymentExtendedInner
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.#ctor
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  langs:
  - csharp
  - vb
  name: DeploymentExtendedInner()
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.DeploymentExtendedInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nInitializes a new instance of the DeploymentExtendedInner class.\n"
  example: []
  syntax:
    content: public DeploymentExtendedInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.#ctor(System.String,System.String,Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.#ctor(System.String,System.String,Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)
  id: '#ctor(System.String,System.String,Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)'
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  langs:
  - csharp
  - vb
  name: DeploymentExtendedInner(String, String, DeploymentPropertiesExtended)
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.DeploymentExtendedInner(System.String, System.String, Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
    startLine: 28
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nInitializes a new instance of the DeploymentExtendedInner class.\n"
  example: []
  syntax:
    content: public DeploymentExtendedInner(string name, string id = null, DeploymentPropertiesExtended properties = null)
    content.vb: Public Sub New(name As String, id As String = Nothing, properties As DeploymentPropertiesExtended = Nothing)
    parameters:
    - id: name
      type: System.String
      description: The name of the deployment.
    - id: id
      type: System.String
      description: The ID of the deployment.
    - id: properties
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended
      description: Deployment properties.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Id
  commentId: P:Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Id
  id: Id
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  langs:
  - csharp
  - vb
  name: Id
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Id
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Id
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nGets or sets the ID of the deployment.\n"
  example: []
  syntax:
    content: public string Id { get; set; }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Name
  commentId: P:Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Name
  id: Name
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
    startLine: 44
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nGets or sets the name of the deployment.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Properties
  commentId: P:Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Properties
  id: Properties
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  langs:
  - csharp
  - vb
  name: Properties
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Properties
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nGets or sets deployment properties.\n"
  example: []
  syntax:
    content: public DeploymentPropertiesExtended Properties { get; set; }
    content.vb: Public Property Properties As DeploymentPropertiesExtended
    parameters: []
    return:
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Validate
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Validate
  id: Validate
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner
  langs:
  - csharp
  - vb
  name: Validate()
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentExtendedInner.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Generated/Models/DeploymentExtendedInner.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nValidate the object.\n"
  example: []
  syntax:
    content: public virtual void Validate()
    content.vb: Public Overridable Sub Validate
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: Microsoft.Azure.Management.ResourceManager.Models
  fullName: Microsoft.Azure.Management.ResourceManager.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended
  parent: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: DeploymentPropertiesExtended
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended
