items:
- uid: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig
  commentId: T:Microsoft.Azure.Management.TrafficManager.Models.DnsConfig
  id: DnsConfig
  parent: Microsoft.Azure.Management.TrafficManager.Models
  children:
  - Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.#ctor
  - Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.#ctor(System.String,System.String,System.Nullable{System.Int64})
  - Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.Fqdn
  - Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.RelativeName
  - Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.Ttl
  langs:
  - csharp
  - vb
  name: DnsConfig
  fullName: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig
  type: Class
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
      branch: 9fcfd197b6707b17f8ee0fa1f28e0e820d1f087a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DnsConfig
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nClass containing DNS settings in a Traffic Manager profile.\n"
  example: []
  syntax:
    content: public class DnsConfig
    content.vb: Public Class DnsConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.#ctor
  commentId: M:Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig
  langs:
  - csharp
  - vb
  name: DnsConfig()
  fullName: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.DnsConfig()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
      branch: 9fcfd197b6707b17f8ee0fa1f28e0e820d1f087a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nInitializes a new instance of the DnsConfig class.\n"
  example: []
  syntax:
    content: public DnsConfig()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.#ctor(System.String,System.String,System.Nullable{System.Int64})
  commentId: M:Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.#ctor(System.String,System.String,System.Nullable{System.Int64})
  id: '#ctor(System.String,System.String,System.Nullable{System.Int64})'
  parent: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig
  langs:
  - csharp
  - vb
  name: DnsConfig(String, String, Nullable<Int64>)
  fullName: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.DnsConfig(System.String, System.String, System.Nullable<System.Int64>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
      branch: 9fcfd197b6707b17f8ee0fa1f28e0e820d1f087a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nInitializes a new instance of the DnsConfig class.\n"
  example: []
  syntax:
    content: public DnsConfig(string relativeName = null, string fqdn = null, long ? ttl = null)
    content.vb: Public Sub New(relativeName As String = Nothing, fqdn As String = Nothing, ttl As Long? = Nothing)
    parameters:
    - id: relativeName
      type: System.String
    - id: fqdn
      type: System.String
    - id: ttl
      type: System.Nullable{System.Int64}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.DnsConfig(System.String, System.String, System.Nullable(Of System.Int64))
  name.vb: DnsConfig(String, String, Nullable(Of Int64))
- uid: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.RelativeName
  commentId: P:Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.RelativeName
  id: RelativeName
  parent: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig
  langs:
  - csharp
  - vb
  name: RelativeName
  fullName: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.RelativeName
  type: Property
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
      branch: 9fcfd197b6707b17f8ee0fa1f28e0e820d1f087a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: RelativeName
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nGets or sets the relative DNS name provided by this Traffic\nManager profile.  This value is combined with the DNS domain name\nused by Azure Traffic Manager to form the fully-qualified domain\nname (FQDN) of the profile.\n"
  example: []
  syntax:
    content: public string RelativeName { get; set; }
    content.vb: Public Property RelativeName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.Fqdn
  commentId: P:Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.Fqdn
  id: Fqdn
  parent: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig
  langs:
  - csharp
  - vb
  name: Fqdn
  fullName: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.Fqdn
  type: Property
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
      branch: 9fcfd197b6707b17f8ee0fa1f28e0e820d1f087a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Fqdn
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nGets or sets the fully-qualified domain name (FQDN) of the Traffic\nManager profile.  This is formed from the concatenation of the\nRelativeName with the DNS domain used by Azure Traffic Manager.\n"
  example: []
  syntax:
    content: public string Fqdn { get; set; }
    content.vb: Public Property Fqdn As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.Ttl
  commentId: P:Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.Ttl
  id: Ttl
  parent: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig
  langs:
  - csharp
  - vb
  name: Ttl
  fullName: Microsoft.Azure.Management.TrafficManager.Models.DnsConfig.Ttl
  type: Property
  source:
    remote:
      path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
      branch: 9fcfd197b6707b17f8ee0fa1f28e0e820d1f087a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Ttl
    path: src/ResourceManagement/TrafficManager/Microsoft.Azure.Management.TrafficManager/Generated/Models/DnsConfig.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.TrafficManager
  packages:
  - Microsoft.Azure.Management.TrafficManager(2.0.2-preview)
  namespace: Microsoft.Azure.Management.TrafficManager.Models
  summary: "\nGets or sets the DNS Ttime-To-Live (TTL), in seconds.  This\ninforms the local DNS resolvers and DNS clients how long to cache\nDNS responses provided by this Traffic Manager profile.\n"
  example: []
  syntax:
    content: public long ? Ttl { get; set; }
    content.vb: Public Property Ttl As Long?
    parameters: []
    return:
      type: System.Nullable{System.Int64}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.TrafficManager.Models
  isExternal: false
  name: Microsoft.Azure.Management.TrafficManager.Models
  fullName: Microsoft.Azure.Management.TrafficManager.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.Int64}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int64>
  fullName: System.Nullable<System.Int64>
  fullname.vb: System.Nullable(Of System.Int64)
  name.vb: Nullable(Of Int64)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Int64
    name: Int64
    fullName: System.Int64
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Int64
    name: Int64
    fullName: System.Int64
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
