### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse
  commentId: T:Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse
  id: TriggeredWebJobSettingsResponse
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models
  children:
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse.#ctor
  - Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  langs:
  - csharp
  - vb
  name: TriggeredWebJobSettingsResponse
  nameWithType: TriggeredWebJobSettingsResponse
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse
  type: Class
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/TriggeredWebJobSettingsResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: TriggeredWebJobSettingsResponse
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/TriggeredWebJobSettingsResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nThe triggered WebJob settings operation response.\n"
  example: []
  syntax:
    content: 'public class TriggeredWebJobSettingsResponse : AzureOperationResponse'
    content.vb: >-
      Public Class TriggeredWebJobSettingsResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  commentId: P:Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  id: ShutdownGraceTimeInSeconds
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse
  langs:
  - csharp
  - vb
  name: ShutdownGraceTimeInSeconds
  nameWithType: TriggeredWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse.ShutdownGraceTimeInSeconds
  type: Property
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/TriggeredWebJobSettingsResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ShutdownGraceTimeInSeconds
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/TriggeredWebJobSettingsResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nOptional. The time in seconds to wait for the WebJob to gracefully\nshutdown.\n"
  example: []
  syntax:
    content: public int ? ShutdownGraceTimeInSeconds { get; set; }
    content.vb: Public Property ShutdownGraceTimeInSeconds As Integer?
    parameters: []
    return:
      type: System.Nullable{System.Int32}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse
  langs:
  - csharp
  - vb
  name: TriggeredWebJobSettingsResponse()
  nameWithType: TriggeredWebJobSettingsResponse.TriggeredWebJobSettingsResponse()
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models.TriggeredWebJobSettingsResponse.TriggeredWebJobSettingsResponse()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/TriggeredWebJobSettingsResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/TriggeredWebJobSettingsResponse.cs
    startLine: 48
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.WebSitesExtensions.Models
  summary: "\nInitializes a new instance of the TriggeredWebJobSettingsResponse\nclass.\n"
  example: []
  syntax:
    content: public TriggeredWebJobSettingsResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.WebSitesExtensions.Models
  commentId: N:Microsoft.WindowsAzure.WebSitesExtensions.Models
  isExternal: false
  name: Microsoft.WindowsAzure.WebSitesExtensions.Models
  nameWithType: Microsoft.WindowsAzure.WebSitesExtensions.Models
  fullName: Microsoft.WindowsAzure.WebSitesExtensions.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Nullable{System.Int32}
  commentId: T:System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  nameWithType: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  nameWithType.vb: Nullable(Of Int32)
  fullname.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
