items:
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  commentId: T:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  id: VirtualNetworkGatewayIPConfigurationInner
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.#ctor
  - Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.#ctor(System.String,System.String,Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Etag
  - Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Name
  - Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.PrivateIPAllocationMethod
  - Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.PublicIPAddress
  - Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Subnet
  langs:
  - csharp
  - vb
  name: VirtualNetworkGatewayIPConfigurationInner
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: VirtualNetworkGatewayIPConfigurationInner
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nIpConfiguration for Virtual network gateway\n"
  example: []
  syntax:
    content: 'public class VirtualNetworkGatewayIPConfigurationInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class VirtualNetworkGatewayIPConfigurationInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: VirtualNetworkGatewayIPConfigurationInner()
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.VirtualNetworkGatewayIPConfigurationInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nVirtualNetworkGatewayIPConfigurationInner class.\n"
  example: []
  syntax:
    content: public VirtualNetworkGatewayIPConfigurationInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.#ctor(System.String,System.String,Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.#ctor(System.String,System.String,Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,Microsoft.Rest.Azure.SubResource,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: VirtualNetworkGatewayIPConfigurationInner(String, String, Rest.Azure.SubResource, Rest.Azure.SubResource, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.VirtualNetworkGatewayIPConfigurationInner(System.String, System.String, Microsoft.Rest.Azure.SubResource, Microsoft.Rest.Azure.SubResource, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nVirtualNetworkGatewayIPConfigurationInner class.\n"
  example: []
  syntax:
    content: public VirtualNetworkGatewayIPConfigurationInner(string id = null, string privateIPAllocationMethod = null, Rest.Azure.SubResource subnet = null, Rest.Azure.SubResource publicIPAddress = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, privateIPAllocationMethod As String = Nothing, subnet As Rest.Azure.SubResource = Nothing, publicIPAddress As Rest.Azure.SubResource = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: privateIPAllocationMethod
      type: System.String
      description: >-
        Gets or sets PrivateIP

        allocation method. Possible values include: 'Static',

        'Dynamic'
    - id: subnet
      type: Microsoft.Rest.Azure.SubResource
      description: >-
        Gets or sets the reference of the subnet

        resource
    - id: publicIPAddress
      type: Microsoft.Rest.Azure.SubResource
      description: >-
        Gets or sets the reference of the

        PublicIP resource
    - id: provisioningState
      type: System.String
      description: >-
        Gets provisioning state of the

        PublicIP resource Updating/Deleting/Failed
    - id: name
      type: System.String
      description: >-
        Gets name of the resource that is unique within

        a resource group. This name can be used to access the

        resource
    - id: etag
      type: System.String
      description: >-
        A unique read-only string that changes whenever

        the resource is updated
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.PrivateIPAllocationMethod
  commentId: P:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.PrivateIPAllocationMethod
  id: PrivateIPAllocationMethod
  parent: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: PrivateIPAllocationMethod
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.PrivateIPAllocationMethod
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PrivateIPAllocationMethod
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 57
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets PrivateIP allocation method. Possible values include:\n'Static', 'Dynamic'\n"
  example: []
  syntax:
    content: public string PrivateIPAllocationMethod { get; set; }
    content.vb: Public Property PrivateIPAllocationMethod As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Subnet
  commentId: P:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Subnet
  id: Subnet
  parent: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Subnet
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Subnet
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Subnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 63
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the reference of the subnet resource\n"
  example: []
  syntax:
    content: public Rest.Azure.SubResource Subnet { get; set; }
    content.vb: Public Property Subnet As Rest.Azure.SubResource
    parameters: []
    return:
      type: Microsoft.Rest.Azure.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.PublicIPAddress
  commentId: P:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.PublicIPAddress
  id: PublicIPAddress
  parent: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: PublicIPAddress
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.PublicIPAddress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: PublicIPAddress
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 69
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets the reference of the PublicIP resource\n"
  example: []
  syntax:
    content: public Rest.Azure.SubResource PublicIPAddress { get; set; }
    content.vb: Public Property PublicIPAddress As Rest.Azure.SubResource
    parameters: []
    return:
      type: Microsoft.Rest.Azure.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 76
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets provisioning state of the PublicIP resource\nUpdating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 83
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets name of the resource that is unique within a resource group.\nThis name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayIPConfigurationInner.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
      branch: 9023be37d52853162afcbfd0bcabe8a4e2b1cc85
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/VirtualNetworkGatewayIPConfigurationInner.cs
    startLine: 90
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets a unique read-only string that changes whenever the\nresource is updated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Rest.Azure.SubResource
  isExternal: false
  name: Rest.Azure.SubResource
  fullName: Microsoft.Rest.Azure.SubResource
