items:
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult
  commentId: T:Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult
  id: DeploymentValidateResult
  parent: Microsoft.Azure.Management.ResourceManager.Models
  children:
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.#ctor
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.#ctor(Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails,Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Error
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Properties
  - Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Validate
  langs:
  - csharp
  - vb
  name: DeploymentValidateResult
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
      branch: b699595315704e1c9871127f746bcdcb4a56bc11
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DeploymentValidateResult
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  packages:
  - Microsoft.Azure.Management.ResourceManager(1.3.0-preview)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nInformation from validate template deployment response.\n"
  example: []
  syntax:
    content: public class DeploymentValidateResult
    content.vb: Public Class DeploymentValidateResult
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.#ctor
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult
  langs:
  - csharp
  - vb
  name: DeploymentValidateResult()
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.DeploymentValidateResult()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
      branch: b699595315704e1c9871127f746bcdcb4a56bc11
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
    startLine: 26
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  packages:
  - Microsoft.Azure.Management.ResourceManager(1.3.0-preview)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nInitializes a new instance of the DeploymentValidateResult class.\n"
  example: []
  syntax:
    content: public DeploymentValidateResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.#ctor(Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails,Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.#ctor(Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails,Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)
  id: '#ctor(Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails,Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)'
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult
  langs:
  - csharp
  - vb
  name: DeploymentValidateResult(ResourceManagementErrorWithDetails, DeploymentPropertiesExtended)
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.DeploymentValidateResult(Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails, Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
      branch: b699595315704e1c9871127f746bcdcb4a56bc11
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  packages:
  - Microsoft.Azure.Management.ResourceManager(1.3.0-preview)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nInitializes a new instance of the DeploymentValidateResult class.\n"
  example: []
  syntax:
    content: public DeploymentValidateResult(ResourceManagementErrorWithDetails error = null, DeploymentPropertiesExtended properties = null)
    content.vb: Public Sub New(error As ResourceManagementErrorWithDetails = Nothing, properties As DeploymentPropertiesExtended = Nothing)
    parameters:
    - id: error
      type: Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails
    - id: properties
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Error
  commentId: P:Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Error
  id: Error
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult
  langs:
  - csharp
  - vb
  name: Error
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Error
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
      branch: b699595315704e1c9871127f746bcdcb4a56bc11
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Error
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  packages:
  - Microsoft.Azure.Management.ResourceManager(1.3.0-preview)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nValidation error.\n"
  example: []
  syntax:
    content: public ResourceManagementErrorWithDetails Error { get; set; }
    content.vb: Public Property Error As ResourceManagementErrorWithDetails
    parameters: []
    return:
      type: Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Properties
  commentId: P:Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Properties
  id: Properties
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult
  langs:
  - csharp
  - vb
  name: Properties
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
      branch: b699595315704e1c9871127f746bcdcb4a56bc11
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Properties
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  packages:
  - Microsoft.Azure.Management.ResourceManager(1.3.0-preview)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nThe template deployment properties.\n"
  example: []
  syntax:
    content: public DeploymentPropertiesExtended Properties { get; set; }
    content.vb: Public Property Properties As DeploymentPropertiesExtended
    parameters: []
    return:
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Validate
  commentId: M:Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Validate
  id: Validate
  parent: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult
  langs:
  - csharp
  - vb
  name: Validate()
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentValidateResult.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
      branch: b699595315704e1c9871127f746bcdcb4a56bc11
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/Models/DeploymentValidateResult.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.ResourceManager
  packages:
  - Microsoft.Azure.Management.ResourceManager(1.3.0-preview)
  namespace: Microsoft.Azure.Management.ResourceManager.Models
  summary: "\nValidate the object. Throws ValidationException if validation fails.\n"
  example: []
  syntax:
    content: public virtual void Validate()
    content.vb: Public Overridable Sub Validate
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: Microsoft.Azure.Management.ResourceManager.Models
  fullName: Microsoft.Azure.Management.ResourceManager.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails
  parent: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: ResourceManagementErrorWithDetails
  fullName: Microsoft.Azure.Management.ResourceManager.Models.ResourceManagementErrorWithDetails
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended
  parent: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: DeploymentPropertiesExtended
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentPropertiesExtended
