items:
- uid: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration
  commentId: T:Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration
  id: DiagnosticsConfiguration
  parent: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  children:
  - Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.#ctor
  - Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.#ctor(System.String,System.Nullable{System.DateTime})
  - Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Expiry
  - Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Level
  - Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Validate
  langs:
  - csharp
  - vb
  name: DiagnosticsConfiguration
  fullName: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
      branch: 6969d0e6090867b7f08eaa804ab4edc32e5e8a08
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DiagnosticsConfiguration
    path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.MachineLearning
  packages:
  - Microsoft.Azure.Management.MachineLearning(0.9.5-preview)
  namespace: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  summary: "\nDiagnostics settings for an Azure ML web service.\n"
  example: []
  syntax:
    content: public class DiagnosticsConfiguration
    content.vb: Public Class DiagnosticsConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration
  langs:
  - csharp
  - vb
  name: DiagnosticsConfiguration()
  fullName: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.DiagnosticsConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
      branch: 6969d0e6090867b7f08eaa804ab4edc32e5e8a08
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.MachineLearning
  packages:
  - Microsoft.Azure.Management.MachineLearning(0.9.5-preview)
  namespace: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  summary: "\nInitializes a new instance of the DiagnosticsConfiguration class.\n"
  example: []
  syntax:
    content: public DiagnosticsConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.#ctor(System.String,System.Nullable{System.DateTime})
  commentId: M:Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.#ctor(System.String,System.Nullable{System.DateTime})
  id: '#ctor(System.String,System.Nullable{System.DateTime})'
  parent: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration
  langs:
  - csharp
  - vb
  name: DiagnosticsConfiguration(String, Nullable<DateTime>)
  fullName: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.DiagnosticsConfiguration(System.String, System.Nullable<System.DateTime>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
      branch: 6969d0e6090867b7f08eaa804ab4edc32e5e8a08
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.MachineLearning
  packages:
  - Microsoft.Azure.Management.MachineLearning(0.9.5-preview)
  namespace: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  summary: "\nInitializes a new instance of the DiagnosticsConfiguration class.\n"
  example: []
  syntax:
    content: public DiagnosticsConfiguration(string level, DateTime? expiry = null)
    content.vb: Public Sub New(level As String, expiry As Date? = Nothing)
    parameters:
    - id: level
      type: System.String
      description: >-
        Level of tracing to be used: None - disables

        tracing; Error - collects only error (stderr) traces; All -

        collects all traces (stdout and stderr). Possible values include:

        'None', 'Error', 'All'
    - id: expiry
      type: System.Nullable{System.DateTime}
      description: >-
        Moment of time after which diagnostics are no

        longer collected. If null, diagnostic collection is not time

        limited.
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.DiagnosticsConfiguration(System.String, System.Nullable(Of System.DateTime))
  name.vb: DiagnosticsConfiguration(String, Nullable(Of DateTime))
- uid: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Level
  commentId: P:Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Level
  id: Level
  parent: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration
  langs:
  - csharp
  - vb
  name: Level
  fullName: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Level
  type: Property
  source:
    remote:
      path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
      branch: 6969d0e6090867b7f08eaa804ab4edc32e5e8a08
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Level
    path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
    startLine: 44
  assemblies:
  - Microsoft.Azure.Management.MachineLearning
  packages:
  - Microsoft.Azure.Management.MachineLearning(0.9.5-preview)
  namespace: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  summary: "\nGets or sets level of tracing to be used: None - disables tracing;\nError - collects only error (stderr) traces; All - collects all\ntraces (stdout and stderr). Possible values include: 'None',\n'Error', 'All'\n"
  example: []
  syntax:
    content: public string Level { get; set; }
    content.vb: Public Property Level As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Expiry
  commentId: P:Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Expiry
  id: Expiry
  parent: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration
  langs:
  - csharp
  - vb
  name: Expiry
  fullName: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Expiry
  type: Property
  source:
    remote:
      path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
      branch: 6969d0e6090867b7f08eaa804ab4edc32e5e8a08
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Expiry
    path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
    startLine: 51
  assemblies:
  - Microsoft.Azure.Management.MachineLearning
  packages:
  - Microsoft.Azure.Management.MachineLearning(0.9.5-preview)
  namespace: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  summary: "\nGets or sets moment of time after which diagnostics are no longer\ncollected. If null, diagnostic collection is not time limited.\n"
  example: []
  syntax:
    content: public DateTime? Expiry { get; set; }
    content.vb: Public Property Expiry As Date?
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Validate
  commentId: M:Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Validate
  id: Validate
  parent: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration
  langs:
  - csharp
  - vb
  name: Validate()
  fullName: Microsoft.Azure.Management.MachineLearning.WebServices.Models.DiagnosticsConfiguration.Validate()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
      branch: 6969d0e6090867b7f08eaa804ab4edc32e5e8a08
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Validate
    path: src/ResourceManagement/MachineLearning/Microsoft.Azure.Management.MachineLearning/Generated/WebServices/Models/DiagnosticsConfiguration.cs
    startLine: 60
  assemblies:
  - Microsoft.Azure.Management.MachineLearning
  packages:
  - Microsoft.Azure.Management.MachineLearning(0.9.5-preview)
  namespace: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  summary: "\nValidate the object.\n"
  example: []
  syntax:
    content: public virtual void Validate()
    content.vb: Public Overridable Sub Validate
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  isExternal: false
  name: Microsoft.Azure.Management.MachineLearning.WebServices.Models
  fullName: Microsoft.Azure.Management.MachineLearning.WebServices.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.DateTime}
  parent: System
  definition: System.Nullable`1
  name: Nullable<DateTime>
  fullName: System.Nullable<System.DateTime>
  fullname.vb: System.Nullable(Of System.DateTime)
  name.vb: Nullable(Of DateTime)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.DateTime
    name: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.DateTime
    name: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  parent: System
  isExternal: true
  name: Nullable<T>
  fullName: System.Nullable<T>
  fullname.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
