items:
- uid: Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithMode
  commentId: T:Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithMode
  id: IWithMode
  parent: Microsoft.Azure.Management.V2.Resource.Deployment.Definition
  children:
  - Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithMode.WithMode(Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode)
  langs:
  - csharp
  - vb
  name: IWithMode
  fullName: Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithMode
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Domain/Deployment/Definition/IDefinition.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithMode
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Domain/Deployment/Definition/IDefinition.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Deployment.Definition
  summary: "\nA deployment definition allowing the deployment mode to be specified.\n"
  example: []
  syntax:
    content: public interface IWithMode
    content.vb: Public Interface IWithMode
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithMode.WithMode(Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode)
  commentId: M:Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithMode.WithMode(Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode)
  id: WithMode(Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode)
  parent: Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithMode
  langs:
  - csharp
  - vb
  name: WithMode(DeploymentMode)
  fullName: Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithMode.WithMode(Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Domain/Deployment/Definition/IDefinition.cs
      branch: 6e6b5dd6159baf4a7e695a7b62c3e8fdedcbcc8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithMode
    path: src/ResourceManagement/Resource/Microsoft.Azure.Management.V2.Resource/Domain/Deployment/Definition/IDefinition.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.V2.Resource
  packages:
  - Microsoft.Azure.Management.V2.Resource(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Resource.Deployment.Definition
  summary: "\nSpecifies the deployment mode.\n"
  example: []
  syntax:
    content: IWithCreate WithMode(DeploymentMode mode)
    content.vb: Function WithMode(mode As DeploymentMode) As IWithCreate
    parameters:
    - id: mode
      type: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
      description: mode the mode of the deployment
    return:
      type: Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithCreate
      description: the next stage of the deployment definition
references:
- uid: Microsoft.Azure.Management.V2.Resource.Deployment.Definition
  isExternal: false
  name: Microsoft.Azure.Management.V2.Resource.Deployment.Definition
  fullName: Microsoft.Azure.Management.V2.Resource.Deployment.Definition
- uid: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
  parent: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: DeploymentMode
  fullName: Microsoft.Azure.Management.ResourceManager.Models.DeploymentMode
- uid: Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithCreate
  parent: Microsoft.Azure.Management.V2.Resource.Deployment.Definition
  isExternal: false
  name: IWithCreate
  fullName: Microsoft.Azure.Management.V2.Resource.Deployment.Definition.IWithCreate
- uid: Microsoft.Azure.Management.ResourceManager.Models
  isExternal: false
  name: Microsoft.Azure.Management.ResourceManager.Models
  fullName: Microsoft.Azure.Management.ResourceManager.Models
