items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  id: ApplicationGatewayBackendHealthHttpSettings
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.#ctor(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer})
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.BackendHttpSettings
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.Servers
  langs:
  - csharp
  - vb
  name: ApplicationGatewayBackendHealthHttpSettings
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
      branch: 1e01bafcd8b025065a7c4afb930c63ba2e078288
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayBackendHealthHttpSettings
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
    startLine: 21
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nApplication gateway backendhealth http settings.\n"
  example: []
  syntax:
    content: public class ApplicationGatewayBackendHealthHttpSettings
    content.vb: Public Class ApplicationGatewayBackendHealthHttpSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  langs:
  - csharp
  - vb
  name: ApplicationGatewayBackendHealthHttpSettings()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.ApplicationGatewayBackendHealthHttpSettings()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
      branch: 1e01bafcd8b025065a7c4afb930c63ba2e078288
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
    startLine: 27
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayBackendHealthHttpSettings class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayBackendHealthHttpSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.#ctor(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer})
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.#ctor(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer})
  id: '#ctor(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings,System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer})'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  langs:
  - csharp
  - vb
  name: ApplicationGatewayBackendHealthHttpSettings(ApplicationGatewayBackendHttpSettings, IList<ApplicationGatewayBackendHealthServer>)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.ApplicationGatewayBackendHealthHttpSettings(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings, System.Collections.Generic.IList<Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer>)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
      branch: 1e01bafcd8b025065a7c4afb930c63ba2e078288
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayBackendHealthHttpSettings class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayBackendHealthHttpSettings(ApplicationGatewayBackendHttpSettings backendHttpSettings = null, IList<ApplicationGatewayBackendHealthServer> servers = null)
    content.vb: Public Sub New(backendHttpSettings As ApplicationGatewayBackendHttpSettings = Nothing, servers As IList(Of ApplicationGatewayBackendHealthServer) = Nothing)
    parameters:
    - id: backendHttpSettings
      type: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings
    - id: servers
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer}
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.ApplicationGatewayBackendHealthHttpSettings(Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings, System.Collections.Generic.IList(Of Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer))
  name.vb: ApplicationGatewayBackendHealthHttpSettings(ApplicationGatewayBackendHttpSettings, IList(Of ApplicationGatewayBackendHealthServer))
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.BackendHttpSettings
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.BackendHttpSettings
  id: BackendHttpSettings
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  langs:
  - csharp
  - vb
  name: BackendHttpSettings
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.BackendHttpSettings
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
      branch: 1e01bafcd8b025065a7c4afb930c63ba2e078288
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: BackendHttpSettings
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
    startLine: 42
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nReference of application gateway backend http settings resource.\n"
  example: []
  syntax:
    content: public ApplicationGatewayBackendHttpSettings BackendHttpSettings { get; set; }
    content.vb: Public Property BackendHttpSettings As ApplicationGatewayBackendHttpSettings
    parameters: []
    return:
      type: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.Servers
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.Servers
  id: Servers
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings
  langs:
  - csharp
  - vb
  name: Servers
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthHttpSettings.Servers
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
      branch: 1e01bafcd8b025065a7c4afb930c63ba2e078288
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Servers
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/ApplicationGatewayBackendHealthHttpSettings.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Network
  packages:
  - Microsoft.Azure.Management.Network(7.1.2-preview)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nList of application gateway backendhealth servers.\n"
  example: []
  syntax:
    content: public IList<ApplicationGatewayBackendHealthServer> Servers { get; set; }
    content.vb: Public Property Servers As IList(Of ApplicationGatewayBackendHealthServer)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    fullName: (
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    fullName: (
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings
  parent: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: ApplicationGatewayBackendHttpSettings
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHttpSettings
- uid: System.Collections.Generic.IList{Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<ApplicationGatewayBackendHealthServer>
  fullName: System.Collections.Generic.IList<Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer>
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer)
  name.vb: IList(Of ApplicationGatewayBackendHealthServer)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer
    name: ApplicationGatewayBackendHealthServer
    fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer
    name: ApplicationGatewayBackendHealthServer
    fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayBackendHealthServer
  - name: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  parent: System.Collections.Generic
  isExternal: true
  name: IList<T>
  fullName: System.Collections.Generic.IList<T>
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
