items:
- uid: Microsoft.Azure.Management.V2.Compute.ComputeManager.IConfigurable
  commentId: T:Microsoft.Azure.Management.V2.Compute.ComputeManager.IConfigurable
  id: ComputeManager.IConfigurable
  parent: Microsoft.Azure.Management.V2.Compute
  children:
  - Microsoft.Azure.Management.V2.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: ComputeManager.IConfigurable
  fullName: Microsoft.Azure.Management.V2.Compute.ComputeManager.IConfigurable
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/ComputeManager.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IConfigurable
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/ComputeManager.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute
  syntax:
    content: 'public interface IConfigurable : IAzureConfigurable<ComputeManager.IConfigurable>'
    content.vb: >-
      Public Interface IConfigurable
          Inherits IAzureConfigurable(Of ComputeManager.IConfigurable)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.V2.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.V2.Compute.ComputeManager.IConfigurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.V2.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/ComputeManager.cs
      branch: 44393803ad3862ae01821b5453d0aaa205cb3f0d
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/ComputeManager.cs
    startLine: 72
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute
  syntax:
    content: IComputeManager Authenticate(ServiceClientCredentials serviceClientCredentials, string subscriptionId)
    content.vb: Function Authenticate(serviceClientCredentials As ServiceClientCredentials, subscriptionId As String) As IComputeManager
    parameters:
    - id: serviceClientCredentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.V2.Compute.IComputeManager
references:
- uid: Microsoft.Azure.Management.V2.Compute
  isExternal: false
  name: Microsoft.Azure.Management.V2.Compute
  fullName: Microsoft.Azure.Management.V2.Compute
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Compute.IComputeManager
  parent: Microsoft.Azure.Management.V2.Compute
  isExternal: false
  name: IComputeManager
  fullName: Microsoft.Azure.Management.V2.Compute.IComputeManager
- uid: System
  isExternal: false
  name: System
  fullName: System
