### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse
  id: GatewayGetDeviceConfigurationScriptResponse
  parent: Microsoft.WindowsAzure.Management.Network.Models
  children:
  - Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse.#ctor
  - Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse.ConfigurationScript
  langs:
  - csharp
  - vb
  name: GatewayGetDeviceConfigurationScriptResponse
  nameWithType: GatewayGetDeviceConfigurationScriptResponse
  fullName: Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/GatewayGetDeviceConfigurationScriptResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: GatewayGetDeviceConfigurationScriptResponse
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/GatewayGetDeviceConfigurationScriptResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nThe configuration script returned from the get device configuration\nscript operation.\n"
  example: []
  syntax:
    content: 'public class GatewayGetDeviceConfigurationScriptResponse : AzureOperationResponse'
    content.vb: >-
      Public Class GatewayGetDeviceConfigurationScriptResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse.ConfigurationScript
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse.ConfigurationScript
  id: ConfigurationScript
  parent: Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse
  langs:
  - csharp
  - vb
  name: ConfigurationScript
  nameWithType: GatewayGetDeviceConfigurationScriptResponse.ConfigurationScript
  fullName: Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse.ConfigurationScript
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/GatewayGetDeviceConfigurationScriptResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ConfigurationScript
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/GatewayGetDeviceConfigurationScriptResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The requested configuration script for the local network\ndevice.\n"
  example: []
  syntax:
    content: public string ConfigurationScript { get; set; }
    content.vb: Public Property ConfigurationScript As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse
  langs:
  - csharp
  - vb
  name: GatewayGetDeviceConfigurationScriptResponse()
  nameWithType: GatewayGetDeviceConfigurationScriptResponse.GatewayGetDeviceConfigurationScriptResponse()
  fullName: Microsoft.WindowsAzure.Management.Network.Models.GatewayGetDeviceConfigurationScriptResponse.GatewayGetDeviceConfigurationScriptResponse()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/GatewayGetDeviceConfigurationScriptResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/GatewayGetDeviceConfigurationScriptResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nGatewayGetDeviceConfigurationScriptResponse class.\n"
  example: []
  syntax:
    content: public GatewayGetDeviceConfigurationScriptResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Network.Models
  commentId: N:Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Network.Models
  nameWithType: Microsoft.WindowsAzure.Management.Network.Models
  fullName: Microsoft.WindowsAzure.Management.Network.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
