items:
- uid: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithSecondaryIpConfiguration
  commentId: T:Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithSecondaryIpConfiguration
  id: IWithSecondaryIpConfiguration
  parent: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition
  children:
  - Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithSecondaryIpConfiguration.DefineSecondaryIpConfiguration(System.String)
  langs:
  - csharp
  - vb
  name: IWithSecondaryIpConfiguration
  fullName: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithSecondaryIpConfiguration
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NetworkInterface/Definition/IDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithSecondaryIpConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NetworkInterface/Definition/IDefinition.cs
    startLine: 119
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition
  summary: "\nThe stage of the network interface definition allowing to associate a secondary IP configurations.\n"
  example: []
  syntax:
    content: public interface IWithSecondaryIpConfiguration
    content.vb: Public Interface IWithSecondaryIpConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithSecondaryIpConfiguration.DefineSecondaryIpConfiguration(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithSecondaryIpConfiguration.DefineSecondaryIpConfiguration(System.String)
  id: DefineSecondaryIpConfiguration(System.String)
  parent: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithSecondaryIpConfiguration
  langs:
  - csharp
  - vb
  name: DefineSecondaryIpConfiguration(String)
  fullName: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithSecondaryIpConfiguration.DefineSecondaryIpConfiguration(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NetworkInterface/Definition/IDefinition.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefineSecondaryIpConfiguration
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.Fluent.Network/Domain/NetworkInterface/Definition/IDefinition.cs
    startLine: 126
  assemblies:
  - Microsoft.Azure.Management.Fluent.Network
  packages:
  - Microsoft.Azure.Management.Fluent.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition
  summary: "\nStarts definition of a secondary IP configuration.\n"
  example: []
  syntax:
    content: IBlank<IWithCreate> DefineSecondaryIpConfiguration(string name)
    content.vb: Function DefineSecondaryIpConfiguration(name As String) As IBlank(Of IWithCreate)
    parameters:
    - id: name
      type: System.String
      description: name name for the IP configuration
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank{Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithCreate}
      description: the first stage of a secondary IP configuration definition
references:
- uid: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition
  fullName: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank{Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithCreate}
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  definition: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
  name: IBlank<IWithCreate>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank<Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithCreate>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank(Of Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithCreate)
  name.vb: IBlank(Of IWithCreate)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithCreate
    name: IWithCreate
    fullName: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithCreate
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithCreate
    name: IWithCreate
    fullName: Microsoft.Azure.Management.Fluent.Network.NetworkInterface.Definition.IWithCreate
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IBlank<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank(Of ParentT)
  name.vb: IBlank(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank`1
    name: IBlank
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition.IBlank
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Definition
