items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  id: IWithOptionalProperties
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  children:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
  langs:
  - csharp
  - vb
  name: IWithOptionalProperties
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithOptionalProperties
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
    startLine: 12
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  summary: "\nThe stage of the application update allowing to enable or disable auto upgrade of the\napplication.\n"
  example: []
  syntax:
    content: public interface IWithOptionalProperties
    content.vb: Public Interface IWithOptionalProperties
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
  id: WithAllowUpdates(System.Boolean)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  langs:
  - csharp
  - vb
  name: WithAllowUpdates(Boolean)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithAllowUpdates(System.Boolean)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithAllowUpdates
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
    startLine: 19
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  summary: "\nAllow automatic application updates.\n"
  example: []
  syntax:
    content: IUpdate WithAllowUpdates(bool allowUpdates)
    content.vb: Function WithAllowUpdates(allowUpdates As Boolean) As IUpdate
    parameters:
    - id: allowUpdates
      type: System.Boolean
      description: allowUpdates true to allow the automatic updates of application, otherwise false
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
      description: the next stage of the update
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
  id: WithDisplayName(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties
  langs:
  - csharp
  - vb
  name: WithDisplayName(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithOptionalProperties.WithDisplayName(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithDisplayName
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
    startLine: 26
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  summary: "\nSpecifies the display name for the application.\n"
  example: []
  syntax:
    content: IUpdate WithDisplayName(string displayName)
    content.vb: Function WithDisplayName(displayName As String) As IUpdate
    parameters:
    - id: displayName
      type: System.String
      description: displayName the displayName value to set
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
      description: the next stage of the update
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
