items:
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.Configurable
  commentId: T:Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.Configurable
  id: GraphRbacManager.Configurable
  parent: Microsoft.Azure.Management.Fluent.Graph.RBAC
  children:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.Configurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  langs:
  - csharp
  - vb
  name: GraphRbacManager.Configurable
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.Configurable
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Graph.RBAC/Microsoft.Azure.Management.Fluent.Graph.RBAC/GraphRBACManager.cs
      branch: 7974ca03c7d6cb8e0c00d1addc5f9f63a9402530
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Configurable
    path: src/ResourceManagement/Graph.RBAC/Microsoft.Azure.Management.Fluent.Graph.RBAC/GraphRBACManager.cs
    startLine: 69
  assemblies:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC
  packages:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Graph.RBAC
  syntax:
    content: 'protected class Configurable : AzureConfigurable<GraphRbacManager.IConfigurable>, GraphRbacManager.IConfigurable, IAzureConfigurable<GraphRbacManager.IConfigurable>'
    content.vb: >-
      Protected Class Configurable
          Inherits AzureConfigurable(Of GraphRbacManager.IConfigurable)
          Implements GraphRbacManager.IConfigurable, IAzureConfigurable(Of GraphRbacManager.IConfigurable)
  inheritance:
  - System.Object
  implements:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  - IAzureConfigurable{Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable}
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.Configurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.Configurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  id: Authenticate(ServiceClientCredentials,System.String,System.String)
  parent: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.Configurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String, String)
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.Configurable.Authenticate(ServiceClientCredentials, System.String, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Graph.RBAC/Microsoft.Azure.Management.Fluent.Graph.RBAC/GraphRBACManager.cs
      branch: 7974ca03c7d6cb8e0c00d1addc5f9f63a9402530
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Graph.RBAC/Microsoft.Azure.Management.Fluent.Graph.RBAC/GraphRBACManager.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC
  packages:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Graph.RBAC
  syntax:
    content: public IGraphRbacManager Authenticate(ServiceClientCredentials credentials, string subscriptionId, string tenantId)
    content.vb: Public Function Authenticate(credentials As ServiceClientCredentials, subscriptionId As String, tenantId As String) As IGraphRbacManager
    parameters:
    - id: credentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    - id: tenantId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.Graph.RBAC.IGraphRbacManager
  implements:
  - Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Graph.RBAC
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  parent: Microsoft.Azure.Management.Fluent.Graph.RBAC
  isExternal: false
  name: GraphRbacManager.IConfigurable
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
- uid: IAzureConfigurable{Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable}
  definition: IAzureConfigurable`1
  name: IAzureConfigurable<GraphRbacManager.IConfigurable>
  fullName: IAzureConfigurable<Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable>
  fullname.vb: IAzureConfigurable(Of Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable)
  name.vb: IAzureConfigurable(Of GraphRbacManager.IConfigurable)
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
    name: GraphRbacManager.IConfigurable
    fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
    name: GraphRbacManager.IConfigurable
    fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: IAzureConfigurable`1
  isExternal: true
  name: IAzureConfigurable<>
  fullName: IAzureConfigurable<>
  fullname.vb: IAzureConfigurable(Of )
  name.vb: IAzureConfigurable(Of )
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
  parent: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable
  isExternal: true
  name: Authenticate(ServiceClientCredentials, String, String)
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String, System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.GraphRbacManager.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Graph.RBAC.IGraphRbacManager
  parent: Microsoft.Azure.Management.Fluent.Graph.RBAC
  isExternal: false
  name: IGraphRbacManager
  fullName: Microsoft.Azure.Management.Fluent.Graph.RBAC.IGraphRbacManager
