items:
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings
  commentId: T:Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings
  id: IWithOsDiskSettings
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition
  children:
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings.WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings.WithOsDiskName(System.String)
  langs:
  - csharp
  - vb
  name: IWithOsDiskSettings
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSet/Definition/IDefinition.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithOsDiskSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSet/Definition/IDefinition.cs
    startLine: 341
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition
  summary: "\nThe stage of the virtual machine scale set definition allowing to specify OS disk configurations.\n"
  example: []
  syntax:
    content: public interface IWithOsDiskSettings
    content.vb: Public Interface IWithOsDiskSettings
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings.WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings.WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  id: WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings
  langs:
  - csharp
  - vb
  name: WithOsDiskCaching(CachingTypes)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings.WithOsDiskCaching(Microsoft.Azure.Management.Compute.Models.CachingTypes)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSet/Definition/IDefinition.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithOsDiskCaching
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSet/Definition/IDefinition.cs
    startLine: 348
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition
  summary: "\nSpecifies the caching type for the Operating System disk.\n"
  example: []
  syntax:
    content: IWithCreate WithOsDiskCaching(CachingTypes cachingType)
    content.vb: Function WithOsDiskCaching(cachingType As CachingTypes) As IWithCreate
    parameters:
    - id: cachingType
      type: Microsoft.Azure.Management.Compute.Models.CachingTypes
      description: cachingType the caching type.
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithCreate
      description: the stage representing creatable VM scale set definition
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings.WithOsDiskName(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings.WithOsDiskName(System.String)
  id: WithOsDiskName(System.String)
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings
  langs:
  - csharp
  - vb
  name: WithOsDiskName(String)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithOsDiskSettings.WithOsDiskName(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSet/Definition/IDefinition.cs
      branch: cd270513306c57dd9b30d6848211d164d0a1fb5b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithOsDiskName
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSet/Definition/IDefinition.cs
    startLine: 355
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition
  summary: "\nSpecifies the name for the OS Disk.\n"
  example: []
  syntax:
    content: IWithCreate WithOsDiskName(string name)
    content.vb: Function WithOsDiskName(name As String) As IWithCreate
    parameters:
    - id: name
      type: System.String
      description: name the OS Disk name.
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithCreate
      description: the stage representing creatable VM scale set definition
references:
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition
  isExternal: false
  name: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition
- uid: Microsoft.Azure.Management.Compute.Models.CachingTypes
  parent: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: CachingTypes
  fullName: Microsoft.Azure.Management.Compute.Models.CachingTypes
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithCreate
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition
  isExternal: false
  name: IWithCreate
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSet.Definition.IWithCreate
- uid: Microsoft.Azure.Management.Compute.Models
  isExternal: false
  name: Microsoft.Azure.Management.Compute.Models
  fullName: Microsoft.Azure.Management.Compute.Models
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
