items:
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  commentId: T:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  id: HostingEnvironmentStatus
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Deleting
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Preparing
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Ready
  - Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Scaling
  langs:
  - csharp
  - vb
  name: HostingEnvironmentStatus
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
      branch: ddb12890afed95d791fcb3d7a4af9681569bbabd
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: HostingEnvironmentStatus
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nDefines values for HostingEnvironmentStatus.\n"
  example: []
  syntax:
    content: public enum HostingEnvironmentStatus
    content.vb: Public Enum HostingEnvironmentStatus
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Preparing
  commentId: F:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Preparing
  id: Preparing
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Preparing
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Preparing
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
      branch: ddb12890afed95d791fcb3d7a4af9681569bbabd
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Preparing
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: Preparing = 0
    return:
      type: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Ready
  commentId: F:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Ready
  id: Ready
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Ready
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Ready
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
      branch: ddb12890afed95d791fcb3d7a4af9681569bbabd
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Ready
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: Ready = 1
    return:
      type: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Scaling
  commentId: F:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Scaling
  id: Scaling
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Scaling
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Scaling
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
      branch: ddb12890afed95d791fcb3d7a4af9681569bbabd
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Scaling
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
    startLine: 24
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: Scaling = 2
    return:
      type: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Deleting
  commentId: F:Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Deleting
  id: Deleting
  parent: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Deleting
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus.Deleting
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
      branch: ddb12890afed95d791fcb3d7a4af9681569bbabd
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Deleting
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/HostingEnvironmentStatus.cs
    startLine: 26
  assemblies:
  - Microsoft.Azure.Management.Websites
  packages:
  - Microsoft.Azure.Management.Websites(1.3.2-preview)
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: Deleting = 3
    return:
      type: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: HostingEnvironmentStatus
  fullName: Microsoft.Azure.Management.WebSites.Models.HostingEnvironmentStatus
