items:
- uid: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.Configurable
  commentId: T:Microsoft.Azure.Management.Fluent.Compute.ComputeManager.Configurable
  id: ComputeManager.Configurable
  parent: Microsoft.Azure.Management.Fluent.Compute
  children:
  - Microsoft.Azure.Management.Fluent.Compute.ComputeManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  langs:
  - csharp
  - vb
  name: ComputeManager.Configurable
  fullName: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.Configurable
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/ComputeManager.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Configurable
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/ComputeManager.cs
    startLine: 76
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Compute
  syntax:
    content: 'protected class Configurable : AzureConfigurable<ComputeManager.IConfigurable>, ComputeManager.IConfigurable, IAzureConfigurable<ComputeManager.IConfigurable>'
    content.vb: >-
      Protected Class Configurable
          Inherits AzureConfigurable(Of ComputeManager.IConfigurable)
          Implements ComputeManager.IConfigurable, IAzureConfigurable(Of ComputeManager.IConfigurable)
  inheritance:
  - System.Object
  implements:
  - Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable
  - IAzureConfigurable{Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable}
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
- uid: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Compute.ComputeManager.Configurable.Authenticate(ServiceClientCredentials,System.String)
  id: Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.Configurable
  langs:
  - csharp
  - vb
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.Configurable.Authenticate(ServiceClientCredentials, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/ComputeManager.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Authenticate
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/ComputeManager.cs
    startLine: 80
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Compute
  syntax:
    content: public IComputeManager Authenticate(ServiceClientCredentials credentials, string subscriptionId)
    content.vb: Public Function Authenticate(credentials As ServiceClientCredentials, subscriptionId As String) As IComputeManager
    parameters:
    - id: credentials
      type: ServiceClientCredentials
    - id: subscriptionId
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.Compute.IComputeManager
  implements:
  - Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Fluent.Compute
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Compute
  fullName: Microsoft.Azure.Management.Fluent.Compute
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable
  parent: Microsoft.Azure.Management.Fluent.Compute
  isExternal: false
  name: ComputeManager.IConfigurable
  fullName: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable
- uid: IAzureConfigurable{Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable}
  definition: IAzureConfigurable`1
  name: IAzureConfigurable<ComputeManager.IConfigurable>
  fullName: IAzureConfigurable<Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable>
  fullname.vb: IAzureConfigurable(Of Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable)
  name.vb: IAzureConfigurable(Of ComputeManager.IConfigurable)
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable
    name: ComputeManager.IConfigurable
    fullName: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable
    name: ComputeManager.IConfigurable
    fullName: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: IAzureConfigurable`1
  isExternal: true
  name: IAzureConfigurable<>
  fullName: IAzureConfigurable<>
  fullname.vb: IAzureConfigurable(Of )
  name.vb: IAzureConfigurable(Of )
  spec.csharp:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IAzureConfigurable`1
    name: IAzureConfigurable
    fullName: IAzureConfigurable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
  parent: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable
  isExternal: true
  name: Authenticate(ServiceClientCredentials, String)
  fullName: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials, System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable.Authenticate(ServiceClientCredentials,System.String)
    name: Authenticate
    fullName: Microsoft.Azure.Management.Fluent.Compute.ComputeManager.IConfigurable.Authenticate
  - name: (
    fullName: (
  - uid: ServiceClientCredentials
    name: ServiceClientCredentials
    fullName: ServiceClientCredentials
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: ServiceClientCredentials
  isExternal: true
  name: ServiceClientCredentials
  fullName: ServiceClientCredentials
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Compute.IComputeManager
  parent: Microsoft.Azure.Management.Fluent.Compute
  isExternal: false
  name: IComputeManager
  fullName: Microsoft.Azure.Management.Fluent.Compute.IComputeManager
