### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings
  commentId: T:Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings
  id: JobCollectionIntrinsicSettings
  parent: Microsoft.WindowsAzure.Management.Scheduler.Models
  children:
  - Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.#ctor
  - Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.Plan
  - Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.Quota
  langs:
  - csharp
  - vb
  name: JobCollectionIntrinsicSettings
  nameWithType: JobCollectionIntrinsicSettings
  fullName: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Scheduler/SchedulerManagement/Generated/Models/JobCollectionIntrinsicSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: JobCollectionIntrinsicSettings
    path: src/ServiceManagement/Scheduler/SchedulerManagement/Generated/Models/JobCollectionIntrinsicSettings.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.Scheduler
  namespace: Microsoft.WindowsAzure.Management.Scheduler.Models
  summary: "\nParameters supplied to intrinsic settings for a job.\n"
  example: []
  syntax:
    content: public class JobCollectionIntrinsicSettings
    content.vb: Public Class JobCollectionIntrinsicSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.Plan
  commentId: P:Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.Plan
  id: Plan
  parent: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings
  langs:
  - csharp
  - vb
  name: Plan
  nameWithType: JobCollectionIntrinsicSettings.Plan
  fullName: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.Plan
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Scheduler/SchedulerManagement/Generated/Models/JobCollectionIntrinsicSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Plan
    path: src/ServiceManagement/Scheduler/SchedulerManagement/Generated/Models/JobCollectionIntrinsicSettings.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.Scheduler
  namespace: Microsoft.WindowsAzure.Management.Scheduler.Models
  summary: "\nOptional. The plan of the resource.\n"
  example: []
  syntax:
    content: public JobCollectionPlan Plan { get; set; }
    content.vb: Public Property Plan As JobCollectionPlan
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionPlan
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.Quota
  commentId: P:Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.Quota
  id: Quota
  parent: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings
  langs:
  - csharp
  - vb
  name: Quota
  nameWithType: JobCollectionIntrinsicSettings.Quota
  fullName: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.Quota
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Scheduler/SchedulerManagement/Generated/Models/JobCollectionIntrinsicSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Quota
    path: src/ServiceManagement/Scheduler/SchedulerManagement/Generated/Models/JobCollectionIntrinsicSettings.cs
    startLine: 48
  assemblies:
  - Microsoft.WindowsAzure.Management.Scheduler
  namespace: Microsoft.WindowsAzure.Management.Scheduler.Models
  summary: "\nOptional. Quota settings for the job collection.\n"
  example: []
  syntax:
    content: public JobCollectionQuota Quota { get; set; }
    content.vb: Public Property Quota As JobCollectionQuota
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionQuota
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings
  langs:
  - csharp
  - vb
  name: JobCollectionIntrinsicSettings()
  nameWithType: JobCollectionIntrinsicSettings.JobCollectionIntrinsicSettings()
  fullName: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionIntrinsicSettings.JobCollectionIntrinsicSettings()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Scheduler/SchedulerManagement/Generated/Models/JobCollectionIntrinsicSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Scheduler/SchedulerManagement/Generated/Models/JobCollectionIntrinsicSettings.cs
    startLine: 58
  assemblies:
  - Microsoft.WindowsAzure.Management.Scheduler
  namespace: Microsoft.WindowsAzure.Management.Scheduler.Models
  summary: "\nInitializes a new instance of the JobCollectionIntrinsicSettings\nclass.\n"
  example: []
  syntax:
    content: public JobCollectionIntrinsicSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Scheduler.Models
  commentId: N:Microsoft.WindowsAzure.Management.Scheduler.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Scheduler.Models
  nameWithType: Microsoft.WindowsAzure.Management.Scheduler.Models
  fullName: Microsoft.WindowsAzure.Management.Scheduler.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionPlan
  commentId: T:Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionPlan
  parent: Microsoft.WindowsAzure.Management.Scheduler.Models
  isExternal: false
  name: JobCollectionPlan
  nameWithType: JobCollectionPlan
  fullName: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionPlan
- uid: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionQuota
  commentId: T:Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionQuota
  parent: Microsoft.WindowsAzure.Management.Scheduler.Models
  isExternal: false
  name: JobCollectionQuota
  nameWithType: JobCollectionQuota
  fullName: Microsoft.WindowsAzure.Management.Scheduler.Models.JobCollectionQuota
