items:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  commentId: T:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  id: IWithLoadBalancer
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  children:
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithoutLoadBalancerBackends
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithoutLoadBalancerInboundNatRules
  langs:
  - csharp
  - vb
  name: IWithLoadBalancer
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithLoadBalancer
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 45
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  summary: "\nThe stage of the network interface's IP configuration allowing to specify the load balancer\nto associate this IP configuration with.\n"
  example: []
  syntax:
    content: public interface IWithLoadBalancer
    content.vb: Public Interface IWithLoadBalancer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  id: WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  langs:
  - csharp
  - vb
  name: WithExistingLoadBalancerBackend(ILoadBalancer, String)
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancerBackend(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithExistingLoadBalancerBackend
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 53
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  summary: "\nSpecifies the load balancer to associate this IP configuration with.\n"
  example: []
  syntax:
    content: IUpdate WithExistingLoadBalancerBackend(ILoadBalancer loadBalancer, string backendName)
    content.vb: Function WithExistingLoadBalancerBackend(loadBalancer As ILoadBalancer, backendName As String) As IUpdate
    parameters:
    - id: loadBalancer
      type: Microsoft.Azure.Management.Fluent.Network.ILoadBalancer
      description: loadBalancer an existing load balancer
    - id: backendName
      type: System.String
      description: backendName the name of an existing backend on that load balancer
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the update
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  id: WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer,System.String)
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  langs:
  - csharp
  - vb
  name: WithExistingLoadBalancerInboundNatRule(ILoadBalancer, String)
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithExistingLoadBalancerInboundNatRule(Microsoft.Azure.Management.Fluent.Network.ILoadBalancer, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithExistingLoadBalancerInboundNatRule
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  summary: "\nSpecifies the load balancer inbound NAT rule to associate this IP configuration with.\n"
  example: []
  syntax:
    content: IUpdate WithExistingLoadBalancerInboundNatRule(ILoadBalancer loadBalancer, string inboundNatRuleName)
    content.vb: Function WithExistingLoadBalancerInboundNatRule(loadBalancer As ILoadBalancer, inboundNatRuleName As String) As IUpdate
    parameters:
    - id: loadBalancer
      type: Microsoft.Azure.Management.Fluent.Network.ILoadBalancer
      description: loadBalancer an existing load balancer
    - id: inboundNatRuleName
      type: System.String
      description: inboundNatRuleName the name of an existing inbound NAT rule on the selected load balancer
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the update
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithoutLoadBalancerBackends
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithoutLoadBalancerBackends
  id: WithoutLoadBalancerBackends
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  langs:
  - csharp
  - vb
  name: WithoutLoadBalancerBackends()
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithoutLoadBalancerBackends()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithoutLoadBalancerBackends
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 67
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  summary: "\nRemoves all the existing associations with load balancer backends.\n"
  example: []
  syntax:
    content: IUpdate WithoutLoadBalancerBackends()
    content.vb: Function WithoutLoadBalancerBackends As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the update
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithoutLoadBalancerInboundNatRules
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithoutLoadBalancerInboundNatRules
  id: WithoutLoadBalancerInboundNatRules
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer
  langs:
  - csharp
  - vb
  name: WithoutLoadBalancerInboundNatRules()
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IWithLoadBalancer.WithoutLoadBalancerInboundNatRules()
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithoutLoadBalancerInboundNatRules
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 73
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  summary: "\nRemoves all the existing associations with load balancer inbound NAT rules.\n"
  example: []
  syntax:
    content: IUpdate WithoutLoadBalancerInboundNatRules()
    content.vb: Function WithoutLoadBalancerInboundNatRules As IUpdate
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the update
references:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
- uid: Microsoft.Azure.Management.Fluent.Network.ILoadBalancer
  parent: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: ILoadBalancer
  fullName: Microsoft.Azure.Management.Fluent.Network.ILoadBalancer
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.Update.IUpdate
- uid: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network
  fullName: Microsoft.Azure.Management.Fluent.Network
- uid: System
  isExternal: false
  name: System
  fullName: System
