items:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1
  commentId: T:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1
  id: IWithNetwork`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  children:
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.Fluent.Network.INetwork)
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.Fluent.Network.INetwork})
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(System.String)
  - Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
  langs:
  - csharp
  - vb
  name: IWithNetwork<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithNetwork
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 51
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  syntax:
    content: public interface IWithNetwork<ParentT>
    content.vb: Public Interface IWithNetwork(Of ParentT)
    typeParameters:
    - id: ParentT
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork(Of ParentT)
  name.vb: IWithNetwork(Of ParentT)
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.Fluent.Network.INetwork})
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.Fluent.Network.INetwork})
  id: WithNewNetwork(ICreatable{Microsoft.Azure.Management.Fluent.Network.INetwork})
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1
  langs:
  - csharp
  - vb
  name: WithNewNetwork(ICreatable<INetwork>)
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork<ParentT>.WithNewNetwork(ICreatable<Microsoft.Azure.Management.Fluent.Network.INetwork>)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewNetwork
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  summary: "\nCreate a new virtual network to associate with the  network interface IP configuration,\nbased on the provided definition.\n"
  example: []
  syntax:
    content: IWithPrivateIp<ParentT> WithNewNetwork(ICreatable<INetwork> creatable)
    content.vb: Function WithNewNetwork(creatable As ICreatable(Of INetwork)) As IWithPrivateIp(Of ParentT)
    parameters:
    - id: creatable
      type: ICreatable{Microsoft.Azure.Management.Fluent.Network.INetwork}
      description: creatable a creatable definition for a new virtual network
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp{{ParentT}}
      description: the next stage of the network interface IP configuration definition
  fullName.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork(Of ParentT).WithNewNetwork(ICreatable(Of Microsoft.Azure.Management.Fluent.Network.INetwork))
  name.vb: WithNewNetwork(ICreatable(Of INetwork))
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
  id: WithNewNetwork(System.String,System.String)
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1
  langs:
  - csharp
  - vb
  name: WithNewNetwork(String, String)
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork<ParentT>.WithNewNetwork(System.String, System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewNetwork
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 71
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  syntax:
    content: IWithPrivateIp<ParentT> WithNewNetwork(string name, string addressSpace)
    content.vb: Function WithNewNetwork(name As String, addressSpace As String) As IWithPrivateIp(Of ParentT)
    parameters:
    - id: name
      type: System.String
    - id: addressSpace
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp{{ParentT}}
  fullName.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork(Of ParentT).WithNewNetwork(System.String, System.String)
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithNewNetwork(System.String)
  id: WithNewNetwork(System.String)
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1
  langs:
  - csharp
  - vb
  name: WithNewNetwork(String)
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork<ParentT>.WithNewNetwork(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithNewNetwork
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 82
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  syntax:
    content: IWithPrivateIp<ParentT> WithNewNetwork(string addressSpace)
    content.vb: Function WithNewNetwork(addressSpace As String) As IWithPrivateIp(Of ParentT)
    parameters:
    - id: addressSpace
      type: System.String
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp{{ParentT}}
  fullName.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork(Of ParentT).WithNewNetwork(System.String)
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.Fluent.Network.INetwork)
  commentId: M:Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.Fluent.Network.INetwork)
  id: WithExistingNetwork(Microsoft.Azure.Management.Fluent.Network.INetwork)
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork`1
  langs:
  - csharp
  - vb
  name: WithExistingNetwork(INetwork)
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork<ParentT>.WithExistingNetwork(Microsoft.Azure.Management.Fluent.Network.INetwork)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
      branch: cb21ee0d08ee5a39fa8567afda7ff75bd7973cda
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithExistingNetwork
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/UpdateDefinition/IUpdateDefinition.cs
    startLine: 89
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  summary: "\nAssociate an existing virtual network with the network interface IP configuration.\n"
  example: []
  syntax:
    content: IWithSubnet<ParentT> WithExistingNetwork(INetwork network)
    content.vb: Function WithExistingNetwork(network As INetwork) As IWithSubnet(Of ParentT)
    parameters:
    - id: network
      type: Microsoft.Azure.Management.Fluent.Network.INetwork
      description: network an existing virtual network
    return:
      type: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet{{ParentT}}
      description: the next stage of the network interface IP configuration definition
  fullName.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithNetwork(Of ParentT).WithExistingNetwork(Microsoft.Azure.Management.Fluent.Network.INetwork)
references:
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
- uid: ICreatable{Microsoft.Azure.Management.Fluent.Network.INetwork}
  definition: ICreatable`1
  name: ICreatable<Network.INetwork>
  fullName: ICreatable<Microsoft.Azure.Management.Fluent.Network.INetwork>
  fullname.vb: ICreatable(Of Microsoft.Azure.Management.Fluent.Network.INetwork)
  name.vb: ICreatable(Of Network.INetwork)
  spec.csharp:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Fluent.Network.INetwork
    name: Network.INetwork
    fullName: Microsoft.Azure.Management.Fluent.Network.INetwork
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Fluent.Network.INetwork
    name: Network.INetwork
    fullName: Microsoft.Azure.Management.Fluent.Network.INetwork
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp{{ParentT}}
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  definition: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
  name: IWithPrivateIp<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp(Of ParentT)
  name.vb: IWithPrivateIp(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: ICreatable`1
  isExternal: true
  name: ICreatable<>
  fullName: ICreatable<>
  fullname.vb: ICreatable(Of )
  name.vb: ICreatable(Of )
  spec.csharp:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: IWithPrivateIp<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp(Of ParentT)
  name.vb: IWithPrivateIp(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp`1
    name: IWithPrivateIp
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithPrivateIp
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Fluent.Network.INetwork
  parent: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: INetwork
  fullName: Microsoft.Azure.Management.Fluent.Network.INetwork
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet{{ParentT}}
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  definition: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
  name: IWithSubnet<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet(Of ParentT)
  name.vb: IWithSubnet(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
    name: IWithSubnet
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
    name: IWithSubnet
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Fluent.Network
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Network
  fullName: Microsoft.Azure.Management.Fluent.Network
- uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
  parent: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition
  isExternal: false
  name: IWithSubnet<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet(Of ParentT)
  name.vb: IWithSubnet(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
    name: IWithSubnet
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet`1
    name: IWithSubnet
    fullName: Microsoft.Azure.Management.Fluent.Network.NicIpConfiguration.UpdateDefinition.IWithSubnet
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
