items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  id: IWithApplicationPackage`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  children:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  langs:
  - csharp
  - vb
  name: IWithApplicationPackage<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithApplicationPackage
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  syntax:
    content: public interface IWithApplicationPackage<ParentT>
    content.vb: Public Interface IWithApplicationPackage(Of ParentT)
    typeParameters:
    - id: ParentT
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT)
  name.vb: IWithApplicationPackage(Of ParentT)
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1.DefineNewApplicationPackage(System.String)
  id: DefineNewApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage`1
  langs:
  - csharp
  - vb
  name: DefineNewApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage<ParentT>.DefineNewApplicationPackage(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
      branch: 91c366fb88e1246de62d778537a6b9d27538844a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefineNewApplicationPackage
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Definition/IDefinition.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  summary: "\nFirst stage to create new application package in Batch account application.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> DefineNewApplicationPackage(string applicationPackageName)
    content.vb: Function DefineNewApplicationPackage(applicationPackageName As String) As IWithAttach(Of ParentT)
    parameters:
    - id: applicationPackageName
      type: System.String
      description: applicationPackageName the version of the application
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}
      description: next stage to create the application.
  fullName.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithApplicationPackage(Of ParentT).DefineNewApplicationPackage(System.String)
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach{{ParentT}}
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  definition: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Definition
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Definition.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
