items:
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1
  commentId: T:Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1
  id: IWithSettings`1
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  children:
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithProtectedSetting(System.String,System.Object)
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithProtectedSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithPublicSetting(System.String,System.Object)
  - Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithPublicSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  langs:
  - csharp
  - vb
  name: IWithSettings<ParentT>
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
    startLine: 137
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  syntax:
    content: public interface IWithSettings<ParentT>
    content.vb: Public Interface IWithSettings(Of ParentT)
    typeParameters:
    - id: ParentT
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings(Of ParentT)
  name.vb: IWithSettings(Of ParentT)
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithPublicSetting(System.String,System.Object)
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithPublicSetting(System.String,System.Object)
  id: WithPublicSetting(System.String,System.Object)
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1
  langs:
  - csharp
  - vb
  name: WithPublicSetting(String, Object)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings<ParentT>.WithPublicSetting(System.String, System.Object)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithPublicSetting
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
    startLine: 145
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  summary: "\nSpecifies a public settings entry.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithPublicSetting(string key, object value)
    content.vb: Function WithPublicSetting(key As String, value As Object) As IWithAttach(Of ParentT)
    parameters:
    - id: key
      type: System.String
      description: key the key of a public settings entry
    - id: value
      type: System.Object
      description: value the value of the public settings entry
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach{{ParentT}}
      description: the next stage of the definition
  fullName.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings(Of ParentT).WithPublicSetting(System.String, System.Object)
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithProtectedSetting(System.String,System.Object)
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithProtectedSetting(System.String,System.Object)
  id: WithProtectedSetting(System.String,System.Object)
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1
  langs:
  - csharp
  - vb
  name: WithProtectedSetting(String, Object)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings<ParentT>.WithProtectedSetting(System.String, System.Object)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithProtectedSetting
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
    startLine: 153
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  summary: "\nSpecifies a private settings entry.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithProtectedSetting(string key, object value)
    content.vb: Function WithProtectedSetting(key As String, value As Object) As IWithAttach(Of ParentT)
    parameters:
    - id: key
      type: System.String
      description: key the key of a private settings entry
    - id: value
      type: System.Object
      description: value the value of the private settings entry
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach{{ParentT}}
      description: the next stage of the definition
  fullName.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings(Of ParentT).WithProtectedSetting(System.String, System.Object)
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithPublicSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithPublicSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  id: WithPublicSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1
  langs:
  - csharp
  - vb
  name: WithPublicSettings(IDictionary<String, Object>)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings<ParentT>.WithPublicSettings(System.Collections.Generic.IDictionary<System.String, System.Object>)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithPublicSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
    startLine: 160
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  summary: "\nSpecifies public settings.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithPublicSettings(IDictionary<string, object> settings)
    content.vb: Function WithPublicSettings(settings As IDictionary(Of String, Object)) As IWithAttach(Of ParentT)
    parameters:
    - id: settings
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: settings the public settings
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach{{ParentT}}
      description: the next stage of the definition
  fullName.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings(Of ParentT).WithPublicSettings(System.Collections.Generic.IDictionary(Of System.String, System.Object))
  name.vb: WithPublicSettings(IDictionary(Of String, Object))
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithProtectedSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  commentId: M:Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1.WithProtectedSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  id: WithProtectedSettings(System.Collections.Generic.IDictionary{System.String,System.Object})
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings`1
  langs:
  - csharp
  - vb
  name: WithProtectedSettings(IDictionary<String, Object>)
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings<ParentT>.WithProtectedSettings(System.Collections.Generic.IDictionary<System.String, System.Object>)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
      branch: 5314ea29e61dbf96da9eec18d63cf62f07475e8a
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithProtectedSettings
    path: src/ResourceManagement/Compute/Microsoft.Azure.Management.V2.Compute/Domain/VirtualMachineScaleSetExtension/Update/IUpdateDefinition.cs
    startLine: 167
  assemblies:
  - Microsoft.Azure.Management.V2.Compute
  packages:
  - Microsoft.Azure.Management.V2.Compute(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  summary: "\nSpecifies private settings.\n"
  example: []
  syntax:
    content: IWithAttach<ParentT> WithProtectedSettings(IDictionary<string, object> settings)
    content.vb: Function WithProtectedSettings(settings As IDictionary(Of String, Object)) As IWithAttach(Of ParentT)
    parameters:
    - id: settings
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: settings the private settings
    return:
      type: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach{{ParentT}}
      description: the next stage of the definition
  fullName.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithSettings(Of ParentT).WithProtectedSettings(System.Collections.Generic.IDictionary(Of System.String, System.Object))
  name.vb: WithProtectedSettings(IDictionary(Of String, Object))
references:
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach{{ParentT}}
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  definition: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach`1
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach`1
  parent: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update
  isExternal: false
  name: IWithAttach<ParentT>
  fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach(Of ParentT)
  name.vb: IWithAttach(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach`1
    name: IWithAttach
    fullName: Microsoft.Azure.Management.V2.Compute.VirtualMachineScaleSetExtension.Update.IWithAttach
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IDictionary`2
  name: IDictionary<String, Object>
  fullName: System.Collections.Generic.IDictionary<System.String, System.Object>
  fullname.vb: System.Collections.Generic.IDictionary(Of System.String, System.Object)
  name.vb: IDictionary(Of String, Object)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    fullName: System.Object
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IDictionary`2
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IDictionary<TKey, TValue>
  fullname.vb: System.Collections.Generic.IDictionary(Of TKey, TValue)
  name.vb: IDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    fullName: <
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: TKey
    fullName: TKey
  - name: ', '
    fullName: ', '
  - name: TValue
    fullName: TValue
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
