items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool
  id: IWithBackendAddressPool
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  children:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool.WithBackendAddressPool(System.String)
  langs:
  - csharp
  - vb
  name: IWithBackendAddressPool
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithBackendAddressPool
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 14
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nThe stage of the network interface IP configuration update allowing to specify the load balancer\nback end address pool to add it to.\n"
  example: []
  syntax:
    content: public interface IWithBackendAddressPool
    content.vb: Public Interface IWithBackendAddressPool
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool.WithBackendAddressPool(System.String)
  commentId: M:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool.WithBackendAddressPool(System.String)
  id: WithBackendAddressPool(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool
  langs:
  - csharp
  - vb
  name: WithBackendAddressPool(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IWithBackendAddressPool.WithBackendAddressPool(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
      branch: 953e663ab177b9ff6936c94c9fc5835e0bdce93b
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithBackendAddressPool
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Update/IUpdate.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  summary: "\nAdds this network interface's IP configuration to the provided back end address pool of\nthe specified load balancer.\n"
  example: []
  syntax:
    content: IUpdate WithBackendAddressPool(string name)
    content.vb: Function WithBackendAddressPool(name As String) As IUpdate
    parameters:
    - id: name
      type: System.String
      description: name the name of an existing load balancer back end address pool
    return:
      type: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
      description: the next stage of the update
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Update.IUpdate
- uid: System
  isExternal: false
  name: System
  fullName: System
