items:
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  commentId: T:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  id: ApplicationGatewayIPConfigurationInner
  parent: Microsoft.Azure.Management.Network.Models
  children:
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.#ctor
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.#ctor(System.String,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Etag
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Name
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.ProvisioningState
  - Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Subnet
  langs:
  - csharp
  - vb
  name: ApplicationGatewayIPConfigurationInner
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayIPConfigurationInner
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
    startLine: 15
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nIP configuration of application gateway\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayIPConfigurationInner : Rest.Azure.SubResource'
    content.vb: >-
      Public Class ApplicationGatewayIPConfigurationInner
          Inherits Rest.Azure.SubResource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.#ctor
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayIPConfigurationInner()
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.ApplicationGatewayIPConfigurationInner()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayIPConfigurationInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayIPConfigurationInner()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.#ctor(System.String,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  commentId: M:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.#ctor(System.String,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)
  id: '#ctor(System.String,Microsoft.Rest.Azure.SubResource,System.String,System.String,System.String)'
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: ApplicationGatewayIPConfigurationInner(String, Rest.Azure.SubResource, String, String, String)
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.ApplicationGatewayIPConfigurationInner(System.String, Microsoft.Rest.Azure.SubResource, System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayIPConfigurationInner class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayIPConfigurationInner(string id = null, Rest.Azure.SubResource subnet = null, string provisioningState = null, string name = null, string etag = null)
    content.vb: Public Sub New(id As String = Nothing, subnet As Rest.Azure.SubResource = Nothing, provisioningState As String = Nothing, name As String = Nothing, etag As String = Nothing)
    parameters:
    - id: id
      type: System.String
    - id: subnet
      type: Microsoft.Rest.Azure.SubResource
      description: "Reference of the subnet resource. A subnet\nfrom where appliation gateway gets its private address "
    - id: provisioningState
      type: System.String
      description: >-
        Provisioning state of the

        application gateway subnet resource

        Updating/Deleting/Failed
    - id: name
      type: System.String
      description: >-
        Name of the resource that is unique within a

        resource group. This name can be used to access the

        resource
    - id: etag
      type: System.String
      description: >-
        A unique read-only string that changes whenever

        the resource is updated
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Subnet
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Subnet
  id: Subnet
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Subnet
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Subnet
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Subnet
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
    startLine: 51
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets reference of the subnet resource. A subnet from where\nappliation gateway gets its private address\n"
  example: []
  syntax:
    content: public Rest.Azure.SubResource Subnet { get; set; }
    content.vb: Public Property Subnet As Rest.Azure.SubResource
    parameters: []
    return:
      type: Microsoft.Rest.Azure.SubResource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
    startLine: 58
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets provisioning state of the application gateway subnet\nresource Updating/Deleting/Failed\n"
  example: []
  syntax:
    content: public string ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Name
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Name
  id: Name
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
    startLine: 65
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets name of the resource that is unique within a resource\ngroup. This name can be used to access the resource\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Etag
  commentId: P:Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Etag
  id: Etag
  parent: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner
  langs:
  - csharp
  - vb
  name: Etag
  fullName: Microsoft.Azure.Management.Network.Models.ApplicationGatewayIPConfigurationInner.Etag
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
      branch: 622625bad63c765bc9dae6a4780b25341c1997f0
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Etag
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Generated/Models/ApplicationGatewayIPConfigurationInner.cs
    startLine: 72
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Network.Models
  summary: "\nGets or sets a unique read-only string that changes whenever the\nresource is updated\n"
  example: []
  syntax:
    content: public string Etag { get; set; }
    content.vb: Public Property Etag As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Network.Models
  isExternal: false
  name: Microsoft.Azure.Management.Network.Models
  fullName: Microsoft.Azure.Management.Network.Models
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Rest.Azure.SubResource
  isExternal: false
  name: Rest.Azure.SubResource
  fullName: Microsoft.Rest.Azure.SubResource
