items:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  commentId: T:Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  id: IWithApplicationPackage
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  children:
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
  - Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
  langs:
  - csharp
  - vb
  name: IWithApplicationPackage
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IWithApplicationPackage
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  summary: "\nA application definition to allow creation of application package.\n"
  example: []
  syntax:
    content: public interface IWithApplicationPackage
    content.vb: Public Interface IWithApplicationPackage
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
  id: DefineNewApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  langs:
  - csharp
  - vb
  name: DefineNewApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.DefineNewApplicationPackage(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DefineNewApplicationPackage
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  summary: "\nFirst stage to create new application package in Batch account application.\n"
  example: []
  syntax:
    content: IUpdate DefineNewApplicationPackage(string version)
    content.vb: Function DefineNewApplicationPackage(version As String) As IUpdate
    parameters:
    - id: version
      type: System.String
      description: version the version of the application
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
      description: next stage to create the application.
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
  commentId: M:Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
  id: WithoutApplicationPackage(System.String)
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage
  langs:
  - csharp
  - vb
  name: WithoutApplicationPackage(String)
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IWithApplicationPackage.WithoutApplicationPackage(System.String)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
      branch: 915751bb98dc36580083db8233fb617f4c6dfd74
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: WithoutApplicationPackage
    path: src/ResourceManagement/Batch/Microsoft.Azure.Management.Fluent.Batch/Domain/Application/Update/IUpdate.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Fluent.Batch
  packages:
  - Microsoft.Azure.Management.Fluent.Batch(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  summary: "\nDeletes specified application package from the application.\n"
  example: []
  syntax:
    content: IUpdate WithoutApplicationPackage(string version)
    content.vb: Function WithoutApplicationPackage(version As String) As IUpdate
    parameters:
    - id: version
      type: System.String
      description: version the reference version of the application to be removed
    return:
      type: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
      description: the stage representing updatable batch account definition.
references:
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update
- uid: System.String
  parent: System
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
  parent: Microsoft.Azure.Management.Fluent.Batch.Application.Update
  isExternal: false
  name: IUpdate
  fullName: Microsoft.Azure.Management.Fluent.Batch.Application.Update.IUpdate
- uid: System
  isExternal: false
  name: System
  fullName: System
