items:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IBlank`1
  commentId: T:Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IBlank`1
  id: IBlank`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  children: []
  langs:
  - csharp
  - vb
  name: IBlank<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IBlank<ParentT>
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
      branch: 33fd3ea99c60bab0a8ccbb1cd87328cb5e82e49f
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: IBlank
    path: src/ResourceManagement/Network/Microsoft.Azure.Management.V2.Network/Domain/NicIpConfiguration/Definition/IDefinition.cs
    startLine: 156
  assemblies:
  - Microsoft.Azure.Management.V2.Network
  packages:
  - Microsoft.Azure.Management.V2.Network(0.0.1-prerelease)
  namespace: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  syntax:
    content: 'public interface IBlank<ParentT> : IWithNetwork<ParentT>'
    content.vb: >-
      Public Interface IBlank(Of ParentT)
          Inherits IWithNetwork(Of ParentT)
    typeParameters:
    - id: ParentT
  inheritedMembers:
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}.WithNewNetwork(ICreatable{Microsoft.Azure.Management.V2.Network.INetwork})
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}.WithNewNetwork(System.String,System.String)
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}.WithNewNetwork(System.String)
  - Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IBlank(Of ParentT)
  name.vb: IBlank(Of ParentT)
references:
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  isExternal: false
  name: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}.WithNewNetwork(ICreatable{Microsoft.Azure.Management.V2.Network.INetwork})
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.V2.Network.INetwork})
  name: WithNewNetwork(ICreatable<INetwork>)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork(ICreatable<Microsoft.Azure.Management.V2.Network.INetwork>)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork(ICreatable(Of Microsoft.Azure.Management.V2.Network.INetwork))
  name.vb: WithNewNetwork(ICreatable(Of INetwork))
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.V2.Network.INetwork})
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Network.INetwork
    name: INetwork
    fullName: Microsoft.Azure.Management.V2.Network.INetwork
  - name: '>'
    fullName: '>'
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.V2.Network.INetwork})
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Network.INetwork
    name: INetwork
    fullName: Microsoft.Azure.Management.V2.Network.INetwork
  - name: )
    fullName: )
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}.WithNewNetwork(System.String,System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
  name: WithNewNetwork(String, String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork(System.String, System.String)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork(System.String, System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}.WithNewNetwork(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String)
  name: WithNewNetwork(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork(System.String)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String)
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String)
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
  name: WithExistingNetwork(INetwork)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
    name: WithExistingNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithExistingNetwork
  - name: (
    fullName: (
  - uid: Microsoft.Azure.Management.V2.Network.INetwork
    name: INetwork
    fullName: Microsoft.Azure.Management.V2.Network.INetwork
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
    name: WithExistingNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithExistingNetwork
  - name: (
    fullName: (
  - uid: Microsoft.Azure.Management.V2.Network.INetwork
    name: INetwork
    fullName: Microsoft.Azure.Management.V2.Network.INetwork
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.V2.Network.INetwork})
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
  isExternal: true
  name: WithNewNetwork(ICreatable<INetwork>)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork(ICreatable<Microsoft.Azure.Management.V2.Network.INetwork>)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork(ICreatable(Of Microsoft.Azure.Management.V2.Network.INetwork))
  name.vb: WithNewNetwork(ICreatable(Of INetwork))
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.V2.Network.INetwork})
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.V2.Network.INetwork
    name: INetwork
    fullName: Microsoft.Azure.Management.V2.Network.INetwork
  - name: '>'
    fullName: '>'
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(ICreatable{Microsoft.Azure.Management.V2.Network.INetwork})
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork
  - name: (
    fullName: (
  - uid: ICreatable`1
    name: ICreatable
    fullName: ICreatable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.V2.Network.INetwork
    name: INetwork
    fullName: Microsoft.Azure.Management.V2.Network.INetwork
  - name: )
    fullName: )
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork{{ParentT}}
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  definition: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
  name: IWithNetwork<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT)
  name.vb: IWithNetwork(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
    name: IWithNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
    name: IWithNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
  isExternal: true
  name: WithNewNetwork(String, String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork(System.String, System.String)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork(System.String, System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String,System.String)
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
  isExternal: true
  name: WithNewNetwork(String)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork(System.String)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork(System.String)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String)
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithNewNetwork
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithNewNetwork(System.String)
    name: WithNewNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithNewNetwork
  - name: (
    fullName: (
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
  isExternal: false
  name: WithExistingNetwork(INetwork)
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
    name: WithExistingNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>.WithExistingNetwork
  - name: (
    fullName: (
  - uid: Microsoft.Azure.Management.V2.Network.INetwork
    name: INetwork
    fullName: Microsoft.Azure.Management.V2.Network.INetwork
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1.WithExistingNetwork(Microsoft.Azure.Management.V2.Network.INetwork)
    name: WithExistingNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT).WithExistingNetwork
  - name: (
    fullName: (
  - uid: Microsoft.Azure.Management.V2.Network.INetwork
    name: INetwork
    fullName: Microsoft.Azure.Management.V2.Network.INetwork
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
  parent: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition
  isExternal: false
  name: IWithNetwork<ParentT>
  fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork<ParentT>
  fullname.vb: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork(Of ParentT)
  name.vb: IWithNetwork(Of ParentT)
  spec.csharp:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
    name: IWithNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork
  - name: <
    fullName: <
  - name: ParentT
    fullName: ParentT
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork`1
    name: IWithNetwork
    fullName: Microsoft.Azure.Management.V2.Network.NicIpConfiguration.Definition.IWithNetwork
  - name: '(Of '
    fullName: '(Of '
  - name: ParentT
    fullName: ParentT
  - name: )
    fullName: )
