### YamlMime:ManagedReference
items:
- uid: ProcDetailsTestApplication
  commentId: N:ProcDetailsTestApplication
  id: ProcDetailsTestApplication
  children:
  - ProcDetailsTestApplication.Entries
  - ProcDetailsTestApplication.ProcDetails
  - ProcDetailsTestApplication.Sections
  - ProcDetailsTestApplication.SectionsSerializer
  - ProcDetailsTestApplication.SiteXmlSerializer
  langs:
  - csharp
  - vb
  name: ProcDetailsTestApplication
  nameWithType: ProcDetailsTestApplication
  fullName: ProcDetailsTestApplication
  type: Namespace
  assemblies:
  - Procdetails
references:
- uid: ProcDetailsTestApplication.Entries
  commentId: T:ProcDetailsTestApplication.Entries
  parent: ProcDetailsTestApplication
  isExternal: false
  name: Entries
  nameWithType: Entries
  fullName: ProcDetailsTestApplication.Entries
- uid: ProcDetailsTestApplication.ProcDetails
  commentId: T:ProcDetailsTestApplication.ProcDetails
  isExternal: false
  name: ProcDetails
  nameWithType: ProcDetails
  fullName: ProcDetailsTestApplication.ProcDetails
- uid: ProcDetailsTestApplication.Sections
  commentId: T:ProcDetailsTestApplication.Sections
  parent: ProcDetailsTestApplication
  isExternal: false
  name: Sections
  nameWithType: Sections
  fullName: ProcDetailsTestApplication.Sections
- uid: ProcDetailsTestApplication.SectionsSerializer
  commentId: T:ProcDetailsTestApplication.SectionsSerializer
  isExternal: false
  name: SectionsSerializer
  nameWithType: SectionsSerializer
  fullName: ProcDetailsTestApplication.SectionsSerializer
- uid: ProcDetailsTestApplication.SiteXmlSerializer
  commentId: T:ProcDetailsTestApplication.SiteXmlSerializer
  isExternal: false
  name: SiteXmlSerializer
  nameWithType: SiteXmlSerializer
  fullName: ProcDetailsTestApplication.SiteXmlSerializer
- uid: ProcDetailsTestApplication
  commentId: N:ProcDetailsTestApplication
  isExternal: false
  name: ProcDetailsTestApplication
  nameWithType: ProcDetailsTestApplication
  fullName: ProcDetailsTestApplication
