### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  commentId: T:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  id: ManagedHostingEnvironmentStatus
  parent: Microsoft.Azure.Management.WebSites.Models
  children:
  - Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Deleting
  - Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Preparing
  - Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Ready
  langs:
  - csharp
  - vb
  name: ManagedHostingEnvironmentStatus
  nameWithType: ManagedHostingEnvironmentStatus
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ManagedHostingEnvironmentStatus
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
    startLine: 17
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  summary: "\nDefines values for ManagedHostingEnvironmentStatus.\n"
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof (StringEnumConverter))]

      public enum ManagedHostingEnvironmentStatus
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum ManagedHostingEnvironmentStatus
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Preparing
  commentId: F:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Preparing
  id: Preparing
  parent: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Preparing
  nameWithType: ManagedHostingEnvironmentStatus.Preparing
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Preparing
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Preparing
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
    startLine: 20
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: >-
      [EnumMember(Value = "Preparing")]

      Preparing = 0
    content.vb: >-
      <EnumMember(Value:="Preparing")>

      Preparing = 0
    return:
      type: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Preparing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Ready
  commentId: F:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Ready
  id: Ready
  parent: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Ready
  nameWithType: ManagedHostingEnvironmentStatus.Ready
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Ready
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Ready
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
    startLine: 22
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: >-
      [EnumMember(Value = "Ready")]

      Ready = 1
    content.vb: >-
      <EnumMember(Value:="Ready")>

      Ready = 1
    return:
      type: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Ready
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Deleting
  commentId: F:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Deleting
  id: Deleting
  parent: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  langs:
  - csharp
  - vb
  name: Deleting
  nameWithType: ManagedHostingEnvironmentStatus.Deleting
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus.Deleting
  type: Field
  source:
    remote:
      path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Deleting
    path: src/ResourceManagement/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/ManagedHostingEnvironmentStatus.cs
    startLine: 24
  assemblies:
  - Microsoft.Azure.Management.Websites
  namespace: Microsoft.Azure.Management.WebSites.Models
  syntax:
    content: >-
      [EnumMember(Value = "Deleting")]

      Deleting = 2
    content.vb: >-
      <EnumMember(Value:="Deleting")>

      Deleting = 2
    return:
      type: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Deleting
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.WebSites.Models
  commentId: N:Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.Azure.Management.WebSites.Models
  nameWithType: Microsoft.Azure.Management.WebSites.Models
  fullName: Microsoft.Azure.Management.WebSites.Models
- uid: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  commentId: T:Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
  parent: Microsoft.Azure.Management.WebSites.Models
  isExternal: false
  name: ManagedHostingEnvironmentStatus
  nameWithType: ManagedHostingEnvironmentStatus
  fullName: Microsoft.Azure.Management.WebSites.Models.ManagedHostingEnvironmentStatus
