items:
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  id: SequencePropertyInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: SequencePropertyInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/SequencePropertyInitializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: SequencePropertyInitializer
    path: src/Core/Managed/Shared/Extensibility/SequencePropertyInitializer.cs
    startLine: 11
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nAn <xref href=\"Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer\" data-throw-if-not-resolved=\"false\"></xref> that that populates <xref href=\"Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence\" data-throw-if-not-resolved=\"false\"></xref> property for \nthe Microsoft internal telemetry sent to the Vortex endpoint.\n"
  example: []
  syntax:
    content: 'public sealed class SequencePropertyInitializer : object, ITelemetryInitializer'
    content.vb: >-
      Public NotInheritable Class SequencePropertyInitializer
          Inherits Object
          Implements ITelemetryInitializer
  inheritance:
  - System.Object
  implements:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  langs:
  - csharp
  - vb
  name: Initialize(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/SequencePropertyInitializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Initialize
    path: src/Core/Managed/Shared/Extensibility/SequencePropertyInitializer.cs
    startLine: 20
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nPopulates <xref href=\"Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence\" data-throw-if-not-resolved=\"false\"></xref> with unique ID and sequential number.\n"
  example: []
  syntax:
    content: public void Initialize(ITelemetry telemetry)
    content.vb: Public Sub Initialize(telemetry As ITelemetry)
    parameters:
    - id: telemetry
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
  implements:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: ITelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  isExternal: false
  name: Sequence
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
- uid: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  isExternal: false
  name: Initialize(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
    name: Initialize
    fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize
  - name: (
    fullName: (
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry
    name: ITelemetry
    fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
    name: Initialize
    fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize
  - name: (
    fullName: (
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry
    name: ITelemetry
    fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
  - name: )
    fullName: )
