items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  id: JsonSerializer
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.CompressionType
  - Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.ConvertToByteArray(System.String,System.Boolean)
  - Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Deserialize(System.Byte[],System.Boolean)
  - Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Serialize(IEnumerable{Microsoft.ApplicationInsights.Channel.ITelemetry},System.Boolean)
  langs:
  - csharp
  - vb
  name: JsonSerializer
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: JsonSerializer
    path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
    startLine: 20
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nSerializes and compress the telemetry items into a JSON string. Compression will be done using GZIP, for Windows Phone 8 compression will be disabled because there\nis API support for it. \n"
  example: []
  syntax:
    content: 'public class JsonSerializer : object'
    content.vb: >-
      Public Class JsonSerializer
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.CompressionType
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.CompressionType
  id: CompressionType
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  langs:
  - csharp
  - vb
  name: CompressionType
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.CompressionType
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: CompressionType
    path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
    startLine: 28
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets the compression type used by the serializer. \n"
  example: []
  syntax:
    content: public static string CompressionType { get; }
    content.vb: Public Shared ReadOnly Property CompressionType As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Serialize(IEnumerable{Microsoft.ApplicationInsights.Channel.ITelemetry},System.Boolean)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Serialize(IEnumerable{Microsoft.ApplicationInsights.Channel.ITelemetry},System.Boolean)
  id: Serialize(IEnumerable{Microsoft.ApplicationInsights.Channel.ITelemetry},System.Boolean)
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  langs:
  - csharp
  - vb
  name: Serialize(IEnumerable<ITelemetry>, Boolean)
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Serialize(IEnumerable<Microsoft.ApplicationInsights.Channel.ITelemetry>, System.Boolean)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Serialize
    path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
    startLine: 42
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nSerializes and compress the telemetry items into a JSON string. Each JSON object is separated by a new line. \n"
  example: []
  syntax:
    content: public static byte[] Serialize(IEnumerable<ITelemetry> telemetryItems, bool compress = true)
    content.vb: Public Shared Function Serialize(telemetryItems As IEnumerable(Of ITelemetry), compress As Boolean = True) As Byte()
    parameters:
    - id: telemetryItems
      type: IEnumerable{Microsoft.ApplicationInsights.Channel.ITelemetry}
      description: The list of telemetry items to serialize.
    - id: compress
      type: System.Boolean
      description: Should serialization also perform compression.
    return:
      type: System.Byte[]
      description: The compressed and serialized telemetry items.
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Serialize(IEnumerable(Of Microsoft.ApplicationInsights.Channel.ITelemetry), System.Boolean)
  name.vb: Serialize(IEnumerable(Of ITelemetry), Boolean)
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.ConvertToByteArray(System.String,System.Boolean)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.ConvertToByteArray(System.String,System.Boolean)
  id: ConvertToByteArray(System.String,System.Boolean)
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  langs:
  - csharp
  - vb
  name: ConvertToByteArray(String, Boolean)
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.ConvertToByteArray(System.String, System.Boolean)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ConvertToByteArray
    path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
    startLine: 63
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nConverts serialized telemetry items to a byte array.\n"
  example: []
  syntax:
    content: public static byte[] ConvertToByteArray(string telemetryItems, bool compress = true)
    content.vb: Public Shared Function ConvertToByteArray(telemetryItems As String, compress As Boolean = True) As Byte()
    parameters:
    - id: telemetryItems
      type: System.String
      description: Serialized telemetry items.
    - id: compress
      type: System.Boolean
      description: Should serialization also perform compression.
    return:
      type: System.Byte[]
      description: The compressed and serialized telemetry items.
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Deserialize(System.Byte[],System.Boolean)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Deserialize(System.Byte[],System.Boolean)
  id: Deserialize(System.Byte[],System.Boolean)
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  langs:
  - csharp
  - vb
  name: Deserialize(Byte[], Boolean)
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Deserialize(System.Byte[], System.Boolean)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Deserialize
    path: src/Core/Managed/Shared/Extensibility/Implementation/JsonSerializer.cs
    startLine: 87
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nDeserializes and decompress the telemetry items into a JSON string.\n"
  example: []
  syntax:
    content: public static string Deserialize(byte[] telemetryItemsData, bool compress = true)
    content.vb: Public Shared Function Deserialize(telemetryItemsData As Byte(), compress As Boolean = True) As String
    parameters:
    - id: telemetryItemsData
      type: System.Byte[]
      description: Serialized telemetry items.
    - id: compress
      type: System.Boolean
      description: Should deserialization also perform decompression.
    return:
      type: System.String
      description: Telemetry items serialized as a string.
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer.Deserialize(System.Byte(), System.Boolean)
  name.vb: Deserialize(Byte(), Boolean)
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: IEnumerable{Microsoft.ApplicationInsights.Channel.ITelemetry}
  definition: IEnumerable`1
  name: IEnumerable<ITelemetry>
  fullName: IEnumerable<Microsoft.ApplicationInsights.Channel.ITelemetry>
  fullname.vb: IEnumerable(Of Microsoft.ApplicationInsights.Channel.ITelemetry)
  name.vb: IEnumerable(Of ITelemetry)
  spec.csharp:
  - uid: IEnumerable`1
    name: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry
    name: ITelemetry
    fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerable`1
    name: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry
    name: ITelemetry
    fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
  - name: )
    fullName: )
- uid: System.Boolean
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: System.Byte[]
  isExternal: true
  name: Byte[]
  fullName: System.Byte[]
  fullname.vb: System.Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: Byte
    fullName: System.Byte
    isExternal: true
  - name: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Byte
    name: Byte
    fullName: System.Byte
    isExternal: true
  - name: ()
    fullName: ()
- uid: IEnumerable`1
  isExternal: true
  name: IEnumerable<>
  fullName: IEnumerable<>
  fullname.vb: IEnumerable(Of )
  name.vb: IEnumerable(Of )
  spec.csharp:
  - uid: IEnumerable`1
    name: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IEnumerable`1
    name: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
