### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  id: OperationContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.CorrelationVector
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  langs:
  - csharp
  - vb
  name: OperationContext
  nameWithType: OperationContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: OperationContext
    path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
    startLine: 9
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nEncapsulates information about an operation. Operation normally reflects an end to end scenario that starts from a user action (e.g. button click).  \n"
  example: []
  syntax:
    content: 'public sealed class OperationContext : object'
    content.vb: >-
      Public NotInheritable Class OperationContext
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  id: Id
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: OperationContext.Id
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Id
    path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
    startLine: 21
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the application-defined operation ID for the topmost operation.\n"
  example: []
  syntax:
    content: public string Id { get; set; }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  id: ParentId
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: ParentId
  nameWithType: OperationContext.ParentId
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ParentId
    path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
    startLine: 30
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the parent operation ID.\n"
  example: []
  syntax:
    content: public string ParentId { get; set; }
    content.vb: Public Property ParentId As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.CorrelationVector
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.CorrelationVector
  id: CorrelationVector
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: CorrelationVector
  nameWithType: OperationContext.CorrelationVector
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.CorrelationVector
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: CorrelationVector
    path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
    startLine: 39
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the correlation vector for the current telemetry item.\n"
  example: []
  syntax:
    content: public string CorrelationVector { get; set; }
    content.vb: Public Property CorrelationVector As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.CorrelationVector*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  id: Name
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: OperationContext.Name
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Name
    path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
    startLine: 49
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the application-defined topmost operation's name.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  id: SyntheticSource
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  langs:
  - csharp
  - vb
  name: SyntheticSource
  nameWithType: OperationContext.SyntheticSource
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: SyntheticSource
    path: src/Core/Managed/Shared/Extensibility/Implementation/OperationContext.cs
    startLine: 58
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the application-defined operation SyntheticSource.\n"
  example: []
  syntax:
    content: public string SyntheticSource { get; set; }
    content.vb: Public Property SyntheticSource As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
  isExternal: false
  name: Id
  nameWithType: OperationContext.Id
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Id
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
  isExternal: false
  name: ParentId
  nameWithType: OperationContext.ParentId
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.ParentId
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.CorrelationVector*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.CorrelationVector
  isExternal: false
  name: CorrelationVector
  nameWithType: OperationContext.CorrelationVector
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.CorrelationVector
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
  isExternal: false
  name: Name
  nameWithType: OperationContext.Name
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.Name
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
  isExternal: false
  name: SyntheticSource
  nameWithType: OperationContext.SyntheticSource
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext.SyntheticSource
