### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions
  id: TelemetryContextExtensions
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext(Microsoft.ApplicationInsights.DataContracts.TelemetryContext)
  langs:
  - csharp
  - vb
  name: TelemetryContextExtensions
  nameWithType: TelemetryContextExtensions
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryContextExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: TelemetryContextExtensions
    path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryContextExtensions.cs
    startLine: 8
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nExtension methods for TelemetryContext.\n"
  example: []
  syntax:
    content: 'public static class TelemetryContextExtensions : object'
    content.vb: >-
      Public Module TelemetryContextExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext(Microsoft.ApplicationInsights.DataContracts.TelemetryContext)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext(Microsoft.ApplicationInsights.DataContracts.TelemetryContext)
  id: GetInternalContext(Microsoft.ApplicationInsights.DataContracts.TelemetryContext)
  isExtensionMethod: true
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions
  langs:
  - csharp
  - vb
  name: GetInternalContext(TelemetryContext)
  nameWithType: TelemetryContextExtensions.GetInternalContext(TelemetryContext)
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext(Microsoft.ApplicationInsights.DataContracts.TelemetryContext)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryContextExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: GetInternalContext
    path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryContextExtensions.cs
    startLine: 16
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nReturns TelemetryContext's Internal context.\n"
  example: []
  syntax:
    content: public static InternalContext GetInternalContext(this TelemetryContext context)
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function GetInternalContext(context As TelemetryContext) As InternalContext
    parameters:
    - id: context
      type: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
      description: Telemetry context to get Internal context for.
    return:
      type: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
      description: Internal context for TelemetryContext.
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext
  isExternal: false
  name: GetInternalContext
  nameWithType: TelemetryContextExtensions.GetInternalContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions.GetInternalContext
- uid: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  commentId: T:Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: TelemetryContext
  nameWithType: TelemetryContext
  fullName: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: InternalContext
  nameWithType: InternalContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  nameWithType: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
