### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.TelemetryClientExtensions
  commentId: T:Microsoft.ApplicationInsights.TelemetryClientExtensions
  id: TelemetryClientExtensions
  parent: Microsoft.ApplicationInsights
  children:
  - Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation``1(Microsoft.ApplicationInsights.TelemetryClient,System.String)
  - Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation``1(Microsoft.ApplicationInsights.TelemetryClient,Microsoft.ApplicationInsights.Extensibility.IOperationHolder{``0})
  langs:
  - csharp
  - vb
  name: TelemetryClientExtensions
  nameWithType: TelemetryClientExtensions
  fullName: Microsoft.ApplicationInsights.TelemetryClientExtensions
  type: Class
  source:
    remote:
      path: src/Core/Managed/Operation.CC.Shared/TelemetryClientExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: TelemetryClientExtensions
    path: src/Core/Managed/Operation.CC.Shared/TelemetryClientExtensions.cs
    startLine: 11
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  summary: "\nExtension class to telemetry client that creates operation object with the respective fields initialized.\n"
  example: []
  syntax:
    content: 'public static class TelemetryClientExtensions : object'
    content.vb: >-
      Public Module TelemetryClientExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation``1(Microsoft.ApplicationInsights.TelemetryClient,System.String)
  commentId: M:Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation``1(Microsoft.ApplicationInsights.TelemetryClient,System.String)
  id: StartOperation``1(Microsoft.ApplicationInsights.TelemetryClient,System.String)
  isExtensionMethod: true
  parent: Microsoft.ApplicationInsights.TelemetryClientExtensions
  langs:
  - csharp
  - vb
  name: StartOperation<T>(TelemetryClient, String)
  nameWithType: TelemetryClientExtensions.StartOperation<T>(TelemetryClient, String)
  fullName: Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation<T>(Microsoft.ApplicationInsights.TelemetryClient, System.String)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Operation.CC.Shared/TelemetryClientExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: StartOperation
    path: src/Core/Managed/Operation.CC.Shared/TelemetryClientExtensions.cs
    startLine: 21
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  summary: "\nStart operation creates an operation object with a respective telemetry item. \n"
  example: []
  syntax:
    content: 'public static IOperationHolder<T> StartOperation<T>(this TelemetryClient telemetryClient, string operationName)where T : OperationTelemetry, new ()'
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function StartOperation(Of T As {OperationTelemetry, New})(telemetryClient As TelemetryClient, operationName As String) As IOperationHolder(Of T)
    parameters:
    - id: telemetryClient
      type: Microsoft.ApplicationInsights.TelemetryClient
      description: Telemetry client object.
    - id: operationName
      type: System.String
      description: Name of the operation that customer is planning to propagate.
    typeParameters:
    - id: T
      description: Type of the telemetry item.
    return:
      type: Microsoft.ApplicationInsights.Extensibility.IOperationHolder{{T}}
      description: Operation item object with a new telemetry item having current start time and timestamp.
  overload: Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation*
  nameWithType.vb: TelemetryClientExtensions.StartOperation(Of T)(TelemetryClient, String)
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation(Of T)(Microsoft.ApplicationInsights.TelemetryClient, System.String)
  name.vb: StartOperation(Of T)(TelemetryClient, String)
- uid: Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation``1(Microsoft.ApplicationInsights.TelemetryClient,Microsoft.ApplicationInsights.Extensibility.IOperationHolder{``0})
  commentId: M:Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation``1(Microsoft.ApplicationInsights.TelemetryClient,Microsoft.ApplicationInsights.Extensibility.IOperationHolder{``0})
  id: StopOperation``1(Microsoft.ApplicationInsights.TelemetryClient,Microsoft.ApplicationInsights.Extensibility.IOperationHolder{``0})
  isExtensionMethod: true
  parent: Microsoft.ApplicationInsights.TelemetryClientExtensions
  langs:
  - csharp
  - vb
  name: StopOperation<T>(TelemetryClient, IOperationHolder<T>)
  nameWithType: TelemetryClientExtensions.StopOperation<T>(TelemetryClient, IOperationHolder<T>)
  fullName: Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation<T>(Microsoft.ApplicationInsights.TelemetryClient, Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Operation.CC.Shared/TelemetryClientExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: StopOperation
    path: src/Core/Managed/Operation.CC.Shared/TelemetryClientExtensions.cs
    startLine: 74
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  summary: "\nStop operation computes the duration of the operation and tracks it using the respective telemetry client.\n"
  example: []
  syntax:
    content: public static void StopOperation<T>(this TelemetryClient telemetryClient, IOperationHolder<T> operation)
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub StopOperation(Of T)(telemetryClient As TelemetryClient, operation As IOperationHolder(Of T))
    parameters:
    - id: telemetryClient
      type: Microsoft.ApplicationInsights.TelemetryClient
      description: Telemetry client object.
    - id: operation
      type: Microsoft.ApplicationInsights.Extensibility.IOperationHolder{{T}}
      description: Operation object to compute duration and track.
    typeParameters:
    - id: T
  overload: Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation*
  nameWithType.vb: TelemetryClientExtensions.StopOperation(Of T)(TelemetryClient, IOperationHolder(Of T))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation(Of T)(Microsoft.ApplicationInsights.TelemetryClient, Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T))
  name.vb: StopOperation(Of T)(TelemetryClient, IOperationHolder(Of T))
references:
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  isExternal: false
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation*
  commentId: Overload:Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation
  isExternal: false
  name: StartOperation<T>
  nameWithType: TelemetryClientExtensions.StartOperation<T>
  fullName: Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation<T>
  nameWithType.vb: TelemetryClientExtensions.StartOperation(Of T)
  fullname.vb: Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation(Of T)
  name.vb: StartOperation(Of T)
- uid: Microsoft.ApplicationInsights.TelemetryClient
  commentId: T:Microsoft.ApplicationInsights.TelemetryClient
  parent: Microsoft.ApplicationInsights
  isExternal: false
  name: TelemetryClient
  nameWithType: TelemetryClient
  fullName: Microsoft.ApplicationInsights.TelemetryClient
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder{{T}}
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IOperationHolder{``0}
  parent: Microsoft.ApplicationInsights.Extensibility
  definition: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  name: IOperationHolder<T>
  nameWithType: IOperationHolder<T>
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>
  nameWithType.vb: IOperationHolder(Of T)
  fullname.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T)
  name.vb: IOperationHolder(Of T)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
    name: IOperationHolder
    nameWithType: IOperationHolder
    fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
    name: IOperationHolder
    nameWithType: IOperationHolder
    fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  commentId: T:Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  isExternal: false
  name: IOperationHolder<T>
  nameWithType: IOperationHolder<T>
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>
  nameWithType.vb: IOperationHolder(Of T)
  fullname.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T)
  name.vb: IOperationHolder(Of T)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
    name: IOperationHolder
    nameWithType: IOperationHolder
    fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
    name: IOperationHolder
    nameWithType: IOperationHolder
    fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility
  nameWithType: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
- uid: Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation*
  commentId: Overload:Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation
  isExternal: false
  name: StopOperation<T>
  nameWithType: TelemetryClientExtensions.StopOperation<T>
  fullName: Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation<T>
  nameWithType.vb: TelemetryClientExtensions.StopOperation(Of T)
  fullname.vb: Microsoft.ApplicationInsights.TelemetryClientExtensions.StopOperation(Of T)
  name.vb: StopOperation(Of T)
