items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter
  id: TelemetryDebugWriter
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.IsTracingDisabled
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.WriteTelemetry(Microsoft.ApplicationInsights.Channel.ITelemetry,System.String)
  langs:
  - csharp
  - vb
  name: TelemetryDebugWriter
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryDebugWriter.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: TelemetryDebugWriter
    path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryDebugWriter.cs
    startLine: 17
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nWrites telemetry items to debug output.\n"
  example: []
  syntax:
    content: 'public class TelemetryDebugWriter : object, IDebugOutput'
    content.vb: >-
      Public Class TelemetryDebugWriter
          Inherits Object
          Implements IDebugOutput
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.IsTracingDisabled
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.IsTracingDisabled
  id: IsTracingDisabled
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter
  langs:
  - csharp
  - vb
  name: IsTracingDisabled
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.IsTracingDisabled
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryDebugWriter.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: IsTracingDisabled
    path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryDebugWriter.cs
    startLine: 22
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets a value indicating whether writing telemetry items to debug output is enabled.\n"
  example: []
  syntax:
    content: public static bool IsTracingDisabled { get; set; }
    content.vb: Public Shared Property IsTracingDisabled As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.WriteTelemetry(Microsoft.ApplicationInsights.Channel.ITelemetry,System.String)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.WriteTelemetry(Microsoft.ApplicationInsights.Channel.ITelemetry,System.String)
  id: WriteTelemetry(Microsoft.ApplicationInsights.Channel.ITelemetry,System.String)
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter
  langs:
  - csharp
  - vb
  name: WriteTelemetry(ITelemetry, String)
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.WriteTelemetry(Microsoft.ApplicationInsights.Channel.ITelemetry, System.String)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryDebugWriter.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: WriteTelemetry
    path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryDebugWriter.cs
    startLine: 29
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nWrite the specified <xref href=\"Microsoft.ApplicationInsights.Channel.ITelemetry\" data-throw-if-not-resolved=\"false\"></xref> item to debug output.\n"
  example: []
  syntax:
    content: public static void WriteTelemetry(ITelemetry telemetry, string filteredBy = null)
    content.vb: Public Shared Sub WriteTelemetry(telemetry As ITelemetry, filteredBy As String = Nothing)
    parameters:
    - id: telemetry
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
      description: Item to write.
    - id: filteredBy
      type: System.String
      description: If specified, indicates the telemetry item was filtered out and not sent to the API.
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.Boolean
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
