### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  id: TelemetryProcessorChain
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: TelemetryProcessorChain
  nameWithType: TelemetryProcessorChain
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryProcessorChain.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: TelemetryProcessorChain
    path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryProcessorChain.cs
    startLine: 11
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nRepresents the TelemetryProcessor chain. Clients should use TelemetryProcessorChainBuilder to construct this object.\n"
  example: []
  syntax:
    content: 'public sealed class TelemetryProcessorChain : IDisposable'
    content.vb: >-
      Public NotInheritable Class TelemetryProcessorChain
          Inherits IDisposable
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  langs:
  - csharp
  - vb
  name: Process(ITelemetry)
  nameWithType: TelemetryProcessorChain.Process(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryProcessorChain.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Process
    path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryProcessorChain.cs
    startLine: 54
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nInvokes the process method in the first telemetry processor.\n"
  example: []
  syntax:
    content: public void Process(ITelemetry item)
    content.vb: Public Sub Process(item As ITelemetry)
    parameters:
    - id: item
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose
  id: Dispose
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  langs:
  - csharp
  - vb
  name: Dispose()
  nameWithType: TelemetryProcessorChain.Dispose()
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose()
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryProcessorChain.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Dispose
    path: src/Core/Managed/Shared/Extensibility/Implementation/TelemetryProcessorChain.cs
    startLine: 62
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nReleases resources used by the current instance of the <xref href=\"Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public void Dispose()
    content.vb: Public Sub Dispose
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process
  isExternal: false
  name: Process
  nameWithType: TelemetryProcessorChain.Process
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  nameWithType: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  nameWithType: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  isExternal: false
  name: TelemetryProcessorChain
  nameWithType: TelemetryProcessorChain
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose
  isExternal: false
  name: Dispose
  nameWithType: TelemetryProcessorChain.Dispose
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Dispose
