items:
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  commentId: T:Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  id: SessionStateTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.#ctor
  - Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.#ctor(Microsoft.ApplicationInsights.DataContracts.SessionState)
  - Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Context
  - Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Microsoft#ApplicationInsights#Channel#ITelemetry#Sanitize
  - Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Sequence
  - Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.State
  - Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Timestamp
  langs:
  - csharp
  - vb
  name: SessionStateTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: SessionStateTelemetry
    path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
    startLine: 9
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nTelemetry type used to track user sessions.\n"
  example: []
  syntax:
    content: 'public sealed class SessionStateTelemetry : object, ITelemetry'
    content.vb: >-
      Public NotInheritable Class SessionStateTelemetry
          Inherits Object
          Implements ITelemetry
  inheritance:
  - System.Object
  implements:
  - Microsoft.ApplicationInsights.Channel.ITelemetry
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.#ctor
  commentId: M:Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.#ctor
  id: '#ctor'
  parent: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  langs:
  - csharp
  - vb
  name: SessionStateTelemetry()
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.SessionStateTelemetry()
  type: Constructor
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: .ctor
    path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
    startLine: 19
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nInitializes a new instance of the <xref href=\"Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public SessionStateTelemetry()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.#ctor(Microsoft.ApplicationInsights.DataContracts.SessionState)
  commentId: M:Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.#ctor(Microsoft.ApplicationInsights.DataContracts.SessionState)
  id: '#ctor(Microsoft.ApplicationInsights.DataContracts.SessionState)'
  parent: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  langs:
  - csharp
  - vb
  name: SessionStateTelemetry(SessionState)
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.SessionStateTelemetry(Microsoft.ApplicationInsights.DataContracts.SessionState)
  type: Constructor
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: .ctor
    path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
    startLine: 31
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nInitializes a new instance of the <xref href=\"Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry\" data-throw-if-not-resolved=\"false\"></xref> class with the specified <em>state</em>.\n"
  example: []
  syntax:
    content: public SessionStateTelemetry(SessionState state)
    content.vb: Public Sub New(state As SessionState)
    parameters:
    - id: state
      type: Microsoft.ApplicationInsights.DataContracts.SessionState
      description: "\nA <xref href=\"Microsoft.ApplicationInsights.DataContracts.SessionState\" data-throw-if-not-resolved=\"false\"></xref> value indicating state of the user session.\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Timestamp
  commentId: P:Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Timestamp
  id: Timestamp
  parent: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  langs:
  - csharp
  - vb
  name: Timestamp
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Timestamp
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Timestamp
    path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
    startLine: 39
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nGets or sets the date and time the session state was recorded.\n"
  example: []
  syntax:
    content: public DateTimeOffset Timestamp { get; set; }
    content.vb: Public Property Timestamp As DateTimeOffset
    parameters: []
    return:
      type: DateTimeOffset
  implements:
  - Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Context
  commentId: P:Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Context
  id: Context
  parent: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  langs:
  - csharp
  - vb
  name: Context
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Context
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Context
    path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
    startLine: 44
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nGets the <xref href=\"Microsoft.ApplicationInsights.DataContracts.TelemetryContext\" data-throw-if-not-resolved=\"false\"></xref> of the application when the session state was recorded.\n"
  example: []
  syntax:
    content: public TelemetryContext Context { get; }
    content.vb: Public ReadOnly Property Context As TelemetryContext
    parameters: []
    return:
      type: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  implements:
  - Microsoft.ApplicationInsights.Channel.ITelemetry.Context
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Sequence
  commentId: P:Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Sequence
  id: Sequence
  parent: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  langs:
  - csharp
  - vb
  name: Sequence
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Sequence
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Sequence
    path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
    startLine: 52
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nGets or sets the value that defines absolute order of the telemetry item.\n"
  example: []
  syntax:
    content: public string Sequence { get; set; }
    content.vb: Public Property Sequence As String
    parameters: []
    return:
      type: System.String
  implements:
  - Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.State
  commentId: P:Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.State
  id: State
  parent: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  langs:
  - csharp
  - vb
  name: State
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.State
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: State
    path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
    startLine: 57
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nGets or sets the value describing state of the user session.\n"
  example: []
  syntax:
    content: public SessionState State { get; set; }
    content.vb: Public Property State As SessionState
    parameters: []
    return:
      type: Microsoft.ApplicationInsights.DataContracts.SessionState
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Microsoft#ApplicationInsights#Channel#ITelemetry#Sanitize
  commentId: M:Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Microsoft#ApplicationInsights#Channel#ITelemetry#Sanitize
  id: Microsoft#ApplicationInsights#Channel#ITelemetry#Sanitize
  isEii: true
  parent: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  langs:
  - csharp
  - vb
  name: ITelemetry.Sanitize()
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry.Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize()
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
    path: src/Core/Managed/Shared/DataContracts/SessionStateTelemetry.cs
    startLine: 62
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.DataContracts
  summary: "\nSanitizes this telemetry instance to ensure it can be accepted by the Application Insights.\n"
  example: []
  syntax:
    content: void ITelemetry.Sanitize()
    content.vb: Sub Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize Implements ITelemetry.Sanitize
  implements:
  - Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
  name.vb: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize()
references:
- uid: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  isExternal: false
  name: SessionStateTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.SessionState
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: SessionState
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionState
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  isExternal: false
  name: Timestamp
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Timestamp
- uid: DateTimeOffset
  isExternal: true
  name: DateTimeOffset
  fullName: DateTimeOffset
- uid: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: TelemetryContext
  fullName: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Context
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  isExternal: false
  name: Context
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Context
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  isExternal: false
  name: Sequence
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sequence
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
  parent: Microsoft.ApplicationInsights.Channel.ITelemetry
  isExternal: false
  name: Sanitize()
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize()
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
    name: Sanitize
    fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
  - name: (
    fullName: (
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
    name: Sanitize
    fullName: Microsoft.ApplicationInsights.Channel.ITelemetry.Sanitize
  - name: (
    fullName: (
  - name: )
    fullName: )
