items:
- uid: Microsoft.ApplicationInsights.Channel
  commentId: N:Microsoft.ApplicationInsights.Channel
  id: Microsoft.ApplicationInsights.Channel
  children:
  - Microsoft.ApplicationInsights.Channel.InMemoryChannel
  - Microsoft.ApplicationInsights.Channel.ITelemetry
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  - Microsoft.ApplicationInsights.Channel.Transmission
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Channel.InMemoryChannel
  isExternal: false
  name: InMemoryChannel
  fullName: Microsoft.ApplicationInsights.Channel.InMemoryChannel
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetryChannel
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
- uid: Microsoft.ApplicationInsights.Channel.Transmission
  isExternal: false
  name: Transmission
  fullName: Microsoft.ApplicationInsights.Channel.Transmission
- uid: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
