### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext
  id: CloudContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleInstance
  - Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleName
  langs:
  - csharp
  - vb
  name: CloudContext
  nameWithType: CloudContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/CloudContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: CloudContext
    path: src/Core/Managed/Shared/Extensibility/Implementation/CloudContext.cs
    startLine: 9
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nEncapsulates information about a cloud where an application is running.\n"
  example: []
  syntax:
    content: 'public sealed class CloudContext : object'
    content.vb: >-
      Public NotInheritable Class CloudContext
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleName
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleName
  id: RoleName
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext
  langs:
  - csharp
  - vb
  name: RoleName
  nameWithType: CloudContext.RoleName
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleName
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/CloudContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: RoleName
    path: src/Core/Managed/Shared/Extensibility/Implementation/CloudContext.cs
    startLine: 21
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the role name.\n"
  example: []
  syntax:
    content: public string RoleName { get; set; }
    content.vb: Public Property RoleName As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleInstance
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleInstance
  id: RoleInstance
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext
  langs:
  - csharp
  - vb
  name: RoleInstance
  nameWithType: CloudContext.RoleInstance
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleInstance
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/CloudContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: RoleInstance
    path: src/Core/Managed/Shared/Extensibility/Implementation/CloudContext.cs
    startLine: 30
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the role instance.\n"
  example: []
  syntax:
    content: public string RoleInstance { get; set; }
    content.vb: Public Property RoleInstance As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleInstance*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleName*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleName
  isExternal: false
  name: RoleName
  nameWithType: CloudContext.RoleName
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleName
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleInstance*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleInstance
  isExternal: false
  name: RoleInstance
  nameWithType: CloudContext.RoleInstance
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext.RoleInstance
