items:
- uid: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  commentId: T:Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  id: OperationCorrelationTelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: OperationCorrelationTelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  type: Class
  source:
    remote:
      path: src/Core/Managed/Operation.CC.Shared/Extensibility/OperationCorrelationTelemetryInitializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: OperationCorrelationTelemetryInitializer
    path: src/Core/Managed/Operation.CC.Shared/Extensibility/OperationCorrelationTelemetryInitializer.cs
    startLine: 8
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nTelemetry initializer that populates OperationContext for the telemetry item based on context stored in CallContext.\n"
  example: []
  syntax:
    content: 'public class OperationCorrelationTelemetryInitializer : object, ITelemetryInitializer'
    content.vb: >-
      Public Class OperationCorrelationTelemetryInitializer
          Inherits Object
          Implements ITelemetryInitializer
  inheritance:
  - System.Object
  implements:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  langs:
  - csharp
  - vb
  name: Initialize(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Operation.CC.Shared/Extensibility/OperationCorrelationTelemetryInitializer.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Initialize
    path: src/Core/Managed/Operation.CC.Shared/Extensibility/OperationCorrelationTelemetryInitializer.cs
    startLine: 14
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility
  summary: "\nInitializes/Adds operation id to the existing telemetry item.\n"
  example: []
  syntax:
    content: public void Initialize(ITelemetry telemetryItem)
    content.vb: Public Sub Initialize(telemetryItem As ITelemetry)
    parameters:
    - id: telemetryItem
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
      description: Target telemetry item to add operation id.
  implements:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: ITelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  isExternal: false
  name: Initialize(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
    name: Initialize
    fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize
  - name: (
    fullName: (
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry
    name: ITelemetry
    fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)
    name: Initialize
    fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.Initialize
  - name: (
    fullName: (
  - uid: Microsoft.ApplicationInsights.Channel.ITelemetry
    name: ITelemetry
    fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
  - name: )
    fullName: )
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
