items:
- uid: Microsoft.ApplicationInsights.DataContracts
  commentId: N:Microsoft.ApplicationInsights.DataContracts
  id: Microsoft.ApplicationInsights.DataContracts
  children:
  - Microsoft.ApplicationInsights.DataContracts.AvailabilityTelemetry
  - Microsoft.ApplicationInsights.DataContracts.DependencyTelemetry
  - Microsoft.ApplicationInsights.DataContracts.EventTelemetry
  - Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  - Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry
  - Microsoft.ApplicationInsights.DataContracts.IJsonWriter
  - Microsoft.ApplicationInsights.DataContracts.ISupportProperties
  - Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  - Microsoft.ApplicationInsights.DataContracts.MetricTelemetry
  - Microsoft.ApplicationInsights.DataContracts.PageViewTelemetry
  - Microsoft.ApplicationInsights.DataContracts.PerformanceCounterTelemetry
  - Microsoft.ApplicationInsights.DataContracts.RequestTelemetry
  - Microsoft.ApplicationInsights.DataContracts.SessionState
  - Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  - Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  - Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  - Microsoft.ApplicationInsights.DataContracts.TraceTelemetry
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.DataContracts.AvailabilityTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: AvailabilityTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.AvailabilityTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.EventTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: EventTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.EventTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: ExceptionHandledAt
  fullName: Microsoft.ApplicationInsights.DataContracts.ExceptionHandledAt
- uid: Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: ExceptionTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.IJsonWriter
  isExternal: false
  name: IJsonWriter
  fullName: Microsoft.ApplicationInsights.DataContracts.IJsonWriter
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportProperties
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: ISupportProperties
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportProperties
- uid: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: ISupportSampling
  fullName: Microsoft.ApplicationInsights.DataContracts.ISupportSampling
- uid: Microsoft.ApplicationInsights.DataContracts.MetricTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: MetricTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.MetricTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.PageViewTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: PageViewTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.PageViewTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.PerformanceCounterTelemetry
  isExternal: false
  name: PerformanceCounterTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.PerformanceCounterTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.DependencyTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: DependencyTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.DependencyTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.RequestTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: RequestTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.RequestTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.SessionState
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: SessionState
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionState
- uid: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
  isExternal: false
  name: SessionStateTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.SessionStateTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: SeverityLevel
  fullName: Microsoft.ApplicationInsights.DataContracts.SeverityLevel
- uid: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: TelemetryContext
  fullName: Microsoft.ApplicationInsights.DataContracts.TelemetryContext
- uid: Microsoft.ApplicationInsights.DataContracts.TraceTelemetry
  parent: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: TraceTelemetry
  fullName: Microsoft.ApplicationInsights.DataContracts.TraceTelemetry
- uid: Microsoft.ApplicationInsights.DataContracts
  isExternal: false
  name: Microsoft.ApplicationInsights.DataContracts
  fullName: Microsoft.ApplicationInsights.DataContracts
