items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
  id: HttpWebResponseWrapper
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.Content
  - Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.RetryAfterHeader
  - Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.StatusCode
  langs:
  - csharp
  - vb
  name: HttpWebResponseWrapper
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/HttpWebResponseWrapper.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: HttpWebResponseWrapper
    path: src/Core/Managed/Shared/Extensibility/Implementation/HttpWebResponseWrapper.cs
    startLine: 5
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nHttpWebResponse wrapper object.\n"
  example: []
  syntax:
    content: 'public class HttpWebResponseWrapper : object'
    content.vb: >-
      Public Class HttpWebResponseWrapper
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.Content
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.Content
  id: Content
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
  langs:
  - csharp
  - vb
  name: Content
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.Content
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/HttpWebResponseWrapper.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Content
    path: src/Core/Managed/Shared/Extensibility/Implementation/HttpWebResponseWrapper.cs
    startLine: 10
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets HttpWebResponse content.\n"
  example: []
  syntax:
    content: public string Content { get; set; }
    content.vb: Public Property Content As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.StatusCode
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.StatusCode
  id: StatusCode
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
  langs:
  - csharp
  - vb
  name: StatusCode
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.StatusCode
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/HttpWebResponseWrapper.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: StatusCode
    path: src/Core/Managed/Shared/Extensibility/Implementation/HttpWebResponseWrapper.cs
    startLine: 15
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets HttpWebResponse StatusCode. \n"
  example: []
  syntax:
    content: public int StatusCode { get; set; }
    content.vb: Public Property StatusCode As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.RetryAfterHeader
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.RetryAfterHeader
  id: RetryAfterHeader
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
  langs:
  - csharp
  - vb
  name: RetryAfterHeader
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper.RetryAfterHeader
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/HttpWebResponseWrapper.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: RetryAfterHeader
    path: src/Core/Managed/Shared/Extensibility/Implementation/HttpWebResponseWrapper.cs
    startLine: 20
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets HttpWebResponse Retry-After header value.\n"
  example: []
  syntax:
    content: public string RetryAfterHeader { get; set; }
    content.vb: Public Property RetryAfterHeader As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Int32
  isExternal: true
  name: Int32
  fullName: System.Int32
