items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  id: UserContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.AccountId
  - Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.AuthenticatedUserId
  - Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.Id
  - Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.UserAgent
  langs:
  - csharp
  - vb
  name: UserContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: UserContext
    path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
    startLine: 10
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nEncapsulates information about a user using an application.\n"
  example: []
  syntax:
    content: 'public sealed class UserContext : object'
    content.vb: >-
      Public NotInheritable Class UserContext
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.Id
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.Id
  id: Id
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  langs:
  - csharp
  - vb
  name: Id
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.Id
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Id
    path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
    startLine: 25
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the ID of user accessing the application.\n"
  remarks: "\nUnique user ID is automatically generated in default Application Insights configuration. \n"
  example: []
  syntax:
    content: public string Id { get; set; }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.AccountId
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.AccountId
  id: AccountId
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  langs:
  - csharp
  - vb
  name: AccountId
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.AccountId
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: AccountId
    path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
    startLine: 34
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the ID of an application-defined account associated with the user.\n"
  example: []
  syntax:
    content: public string AccountId { get; set; }
    content.vb: Public Property AccountId As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.UserAgent
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.UserAgent
  id: UserAgent
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  langs:
  - csharp
  - vb
  name: UserAgent
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.UserAgent
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: UserAgent
    path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
    startLine: 43
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the UserAgent of an application-defined account associated with the user.\n"
  example: []
  syntax:
    content: public string UserAgent { get; set; }
    content.vb: Public Property UserAgent As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.AuthenticatedUserId
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.AuthenticatedUserId
  id: AuthenticatedUserId
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  langs:
  - csharp
  - vb
  name: AuthenticatedUserId
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext.AuthenticatedUserId
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: AuthenticatedUserId
    path: src/Core/Managed/Shared/Extensibility/Implementation/UserContext.cs
    startLine: 53
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the authenticated user id.\nAuthenticated user id should be a persistent string that uniquely represents each authenticated user in the application or service.\n"
  example: []
  syntax:
    content: public string AuthenticatedUserId { get; set; }
    content.vb: Public Property AuthenticatedUserId As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
