items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext
  id: ComponentContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext.Version
  langs:
  - csharp
  - vb
  name: ComponentContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/ComponentContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ComponentContext
    path: src/Core/Managed/Shared/Extensibility/Implementation/ComponentContext.cs
    startLine: 14
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nEncapsulates information describing an Application Insights component.\n"
  remarks: "\nThis class matches the \"Application\" schema concept. We are intentionally calling it \"Component\" for consistency \nwith terminology used by our portal and services and to encourage standardization of terminology within our \norganization. Once a consensus is reached, we will change type and property names to match.\n"
  example: []
  syntax:
    content: 'public sealed class ComponentContext : object'
    content.vb: >-
      Public NotInheritable Class ComponentContext
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext.Version
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext.Version
  id: Version
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext
  langs:
  - csharp
  - vb
  name: Version
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext.Version
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/ComponentContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Version
    path: src/Core/Managed/Shared/Extensibility/Implementation/ComponentContext.cs
    startLine: 26
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the application version.\n"
  example: []
  syntax:
    content: public string Version { get; set; }
    content.vb: Public Property Version As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
