items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  id: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  isExternal: false
  name: DiagnosticsTelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions
  isExternal: false
  name: Extensions
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions
