items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation
  id: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext
  - Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext
  - Microsoft.ApplicationInsights.Extensibility.Implementation.DeviceContext
  - Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
  - Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  - Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  - Microsoft.ApplicationInsights.Extensibility.Implementation.LocationContext
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  - Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
  - Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TaskTimer
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  - Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder
  - Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: ComponentContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.ComponentContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
  isExternal: false
  name: HttpWebResponseWrapper
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.HttpWebResponseWrapper
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter
  isExternal: false
  name: TelemetryDebugWriter
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: CloudContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.CloudContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.DeviceContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: DeviceContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.DeviceContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: InternalContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
  isExternal: false
  name: JsonSerializer
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.JsonSerializer
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.LocationContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: LocationContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.LocationContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: OperationContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: OperationTelemetry
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: SessionContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TaskTimer
  isExternal: false
  name: TaskTimer
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TaskTimer
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions
  isExternal: false
  name: TelemetryContextExtensions
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryContextExtensions
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
  isExternal: false
  name: TelemetryProcessorChain
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: TelemetryProcessorChainBuilder
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: UserContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.UserContext
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: TelemetryModules
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
