items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext
  id: SessionContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext.Id
  - Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext.IsFirst
  langs:
  - csharp
  - vb
  name: SessionContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/SessionContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: SessionContext
    path: src/Core/Managed/Shared/Extensibility/Implementation/SessionContext.cs
    startLine: 9
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nEncapsulates information about a user session.\n"
  example: []
  syntax:
    content: 'public sealed class SessionContext : object'
    content.vb: >-
      Public NotInheritable Class SessionContext
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext.Id
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext.Id
  id: Id
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext
  langs:
  - csharp
  - vb
  name: Id
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext.Id
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/SessionContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Id
    path: src/Core/Managed/Shared/Extensibility/Implementation/SessionContext.cs
    startLine: 21
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the application-defined session ID.\n"
  example: []
  syntax:
    content: public string Id { get; set; }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext.IsFirst
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext.IsFirst
  id: IsFirst
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext
  langs:
  - csharp
  - vb
  name: IsFirst
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.SessionContext.IsFirst
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/SessionContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: IsFirst
    path: src/Core/Managed/Shared/Extensibility/Implementation/SessionContext.cs
    startLine: 30
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets the IsFirst Session for the user.\n"
  example: []
  syntax:
    content: public bool ? IsFirst { get; set; }
    content.vb: Public Property IsFirst As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Nullable{System.Boolean}
  definition: System.Nullable`1
  name: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  isExternal: true
  name: Nullable<>
  fullName: System.Nullable<>
  fullname.vb: System.Nullable(Of )
  name.vb: Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
