items:
- uid: Microsoft.ApplicationInsights.Extensibility
  commentId: N:Microsoft.ApplicationInsights.Extensibility
  id: Microsoft.ApplicationInsights.Extensibility
  children:
  - Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  - Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  - Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  - Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: IOperationHolder<T>
  fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder<T>
  fullname.vb: Microsoft.ApplicationInsights.Extensibility.IOperationHolder(Of T)
  name.vb: IOperationHolder(Of T)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
    name: IOperationHolder
    fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1
    name: IOperationHolder
    fullName: Microsoft.ApplicationInsights.Extensibility.IOperationHolder
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: ITelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: ITelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
  isExternal: false
  name: ITelemetryProcessor
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryProcessor
- uid: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: TelemetryConfiguration
  fullName: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
- uid: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
  isExternal: false
  name: SequencePropertyInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.SequencePropertyInitializer
- uid: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
  isExternal: false
  name: OperationCorrelationTelemetryInitializer
  fullName: Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer
- uid: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
