items:
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  commentId: T:Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  id: ITelemetryChannel
  parent: Microsoft.ApplicationInsights.Channel
  children:
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush
  - Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  langs:
  - csharp
  - vb
  name: ITelemetryChannel
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  type: Interface
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ITelemetryChannel
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 12
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nRepresents a communication channel for sending telemetry to application insights.\n"
  example: []
  syntax:
    content: 'public interface ITelemetryChannel : IDisposable'
    content.vb: >-
      Public Interface ITelemetryChannel
          Inherits IDisposable
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  commentId: P:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  id: DeveloperMode
  parent: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  langs:
  - csharp
  - vb
  name: DeveloperMode
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.DeveloperMode
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: DeveloperMode
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 17
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nGets or sets a value indicating whether this channel is in developer mode.\n"
  example: []
  syntax:
    content: bool ? DeveloperMode { get; set; }
    content.vb: Property DeveloperMode As Boolean?
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
  modifiers.csharp:
  - get
  - set
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  commentId: P:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  id: EndpointAddress
  parent: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  langs:
  - csharp
  - vb
  name: EndpointAddress
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.EndpointAddress
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: EndpointAddress
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 22
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nGets or sets the endpoint address of the channel.\n"
  example: []
  syntax:
    content: string EndpointAddress { get; set; }
    content.vb: Property EndpointAddress As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - get
  - set
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  commentId: M:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  id: Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  parent: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  langs:
  - csharp
  - vb
  name: Send(ITelemetry)
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Send(Microsoft.ApplicationInsights.Channel.ITelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Send
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 27
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nSends an instance of ITelemetry through the channel.\n"
  example: []
  syntax:
    content: void Send(ITelemetry item)
    content.vb: Sub Send(item As ITelemetry)
    parameters:
    - id: item
      type: Microsoft.ApplicationInsights.Channel.ITelemetry
- uid: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush
  commentId: M:Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush
  id: Flush
  parent: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  langs:
  - csharp
  - vb
  name: Flush()
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetryChannel.Flush()
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Flush
    path: src/Core/Managed/Shared/Channel/ITelemetryChannel.cs
    startLine: 32
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Channel
  summary: "\nFlushes the in-memory buffer.\n"
  example: []
  syntax:
    content: void Flush()
    content.vb: Sub Flush
references:
- uid: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: Microsoft.ApplicationInsights.Channel
  fullName: Microsoft.ApplicationInsights.Channel
- uid: System.Nullable{System.Boolean}
  definition: System.Nullable`1
  name: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  fullname.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    fullName: )
- uid: System.Nullable`1
  isExternal: true
  name: Nullable<>
  fullName: System.Nullable<>
  fullname.vb: System.Nullable(Of )
  name.vb: Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Channel.ITelemetry
  parent: Microsoft.ApplicationInsights.Channel
  isExternal: false
  name: ITelemetry
  fullName: Microsoft.ApplicationInsights.Channel.ITelemetry
