items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  id: DiagnosticsTelemetryModule
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.#ctor
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.DiagnosticsInstrumentationKey
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Dispose
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Finalize
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Severity
  langs:
  - csharp
  - vb
  name: DiagnosticsTelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: DiagnosticsTelemetryModule
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
    startLine: 17
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nUse diagnostics telemetry module to report SDK internal problems to the portal and VS debug output window.\n"
  example: []
  syntax:
    content: 'public sealed class DiagnosticsTelemetryModule : object, ITelemetryModule, IDisposable'
    content.vb: >-
      Public NotInheritable Class DiagnosticsTelemetryModule
          Inherits Object
          Implements ITelemetryModule, IDisposable
  inheritance:
  - System.Object
  implements:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  - IDisposable
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.#ctor
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.#ctor
  id: '#ctor'
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  langs:
  - csharp
  - vb
  name: DiagnosticsTelemetryModule()
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.DiagnosticsTelemetryModule()
  type: Constructor
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: .ctor
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
    startLine: 34
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nInitializes a new instance of the <xref href=\"Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule\" data-throw-if-not-resolved=\"false\"></xref> class. \n"
  example: []
  syntax:
    content: public DiagnosticsTelemetryModule()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Finalize
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Finalize
  id: Finalize
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  langs:
  - csharp
  - vb
  name: Finalize()
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Finalize()
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Finalize
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
    startLine: 46
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nFinalizes an instance of the <xref href=\"Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: protected void Finalize()
    content.vb: Protected Sub Finalize
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Severity
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Severity
  id: Severity
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  langs:
  - csharp
  - vb
  name: Severity
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Severity
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Severity
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
    startLine: 55
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nGets or sets diagnostics Telemetry Module LogLevel configuration setting. \nPossible values LogAlways, Critical, Error, Warning, Informational and Verbose.\n"
  example: []
  syntax:
    content: public string Severity { get; set; }
    content.vb: Public Property Severity As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.DiagnosticsInstrumentationKey
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.DiagnosticsInstrumentationKey
  id: DiagnosticsInstrumentationKey
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  langs:
  - csharp
  - vb
  name: DiagnosticsInstrumentationKey
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.DiagnosticsInstrumentationKey
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: DiagnosticsInstrumentationKey
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
    startLine: 81
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nGets or sets instrumentation key for diagnostics. Use to redirect SDK \ninternal problems reporting to the separate instrumentation key.\n"
  example: []
  syntax:
    content: public string DiagnosticsInstrumentationKey { get; set; }
    content.vb: Public Property DiagnosticsInstrumentationKey As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  id: Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  langs:
  - csharp
  - vb
  name: Initialize(TelemetryConfiguration)
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Initialize
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
    startLine: 107
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nInitializes this telemetry module.\n"
  example: []
  syntax:
    content: public void Initialize(TelemetryConfiguration configuration)
    content.vb: Public Sub Initialize(configuration As TelemetryConfiguration)
    parameters:
    - id: configuration
      type: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
      description: Telemetry configuration to use for this telemetry module.
  implements:
  - Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Dispose
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Dispose
  id: Dispose
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  langs:
  - csharp
  - vb
  name: Dispose()
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule.Dispose()
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Dispose
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs
    startLine: 150
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nDisposes this object.\n"
  example: []
  syntax:
    content: public void Dispose()
    content.vb: Public Sub Dispose
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
- uid: System.Object
  isExternal: true
  name: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: ITelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
- uid: IDisposable
  isExternal: true
  name: IDisposable
  fullName: IDisposable
- uid: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility
  fullName: Microsoft.ApplicationInsights.Extensibility
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
  isExternal: false
  name: DiagnosticsTelemetryModule
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  parent: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  isExternal: false
  name: Initialize(TelemetryConfiguration)
  fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
  spec.csharp:
  - uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
    name: Initialize
    fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize
  - name: (
    fullName: (
  - uid: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
    name: TelemetryConfiguration
    fullName: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  - name: )
    fullName: )
  spec.vb:
  - uid: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration)
    name: Initialize
    fullName: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule.Initialize
  - name: (
    fullName: (
  - uid: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
    name: TelemetryConfiguration
    fullName: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  - name: )
    fullName: )
- uid: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  parent: Microsoft.ApplicationInsights.Extensibility
  isExternal: false
  name: TelemetryConfiguration
  fullName: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
