### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  id: InternalContext
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.AgentVersion
  - Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.SdkVersion
  langs:
  - csharp
  - vb
  name: InternalContext
  nameWithType: InternalContext
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/InternalContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: InternalContext
    path: src/Core/Managed/Shared/Extensibility/Implementation/InternalContext.cs
    startLine: 12
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nEncapsulates Internal information.\n"
  example: []
  syntax:
    content: 'public sealed class InternalContext : object'
    content.vb: >-
      Public NotInheritable Class InternalContext
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.SdkVersion
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.SdkVersion
  id: SdkVersion
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  langs:
  - csharp
  - vb
  name: SdkVersion
  nameWithType: InternalContext.SdkVersion
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.SdkVersion
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/InternalContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: SdkVersion
    path: src/Core/Managed/Shared/Extensibility/Implementation/InternalContext.cs
    startLine: 24
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets application insights SDK version.\n"
  example: []
  syntax:
    content: public string SdkVersion { get; set; }
    content.vb: Public Property SdkVersion As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.SdkVersion*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.AgentVersion
  commentId: P:Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.AgentVersion
  id: AgentVersion
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext
  langs:
  - csharp
  - vb
  name: AgentVersion
  nameWithType: InternalContext.AgentVersion
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.AgentVersion
  type: Property
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/InternalContext.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: AgentVersion
    path: src/Core/Managed/Shared/Extensibility/Implementation/InternalContext.cs
    startLine: 33
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation
  summary: "\nGets or sets application insights agent version.\n"
  example: []
  syntax:
    content: public string AgentVersion { get; set; }
    content.vb: Public Property AgentVersion As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.AgentVersion*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.SdkVersion*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.SdkVersion
  isExternal: false
  name: SdkVersion
  nameWithType: InternalContext.SdkVersion
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.SdkVersion
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.AgentVersion*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.AgentVersion
  isExternal: false
  name: AgentVersion
  nameWithType: InternalContext.AgentVersion
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.InternalContext.AgentVersion
