### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions
  id: Extensions
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  children:
  - Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString(Exception)
  langs:
  - csharp
  - vb
  name: Extensions
  nameWithType: Extensions
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/Extensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Extensions
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/Extensions.cs
    startLine: 10
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nProvides a set of extension methods for tracing.\n"
  example: []
  syntax:
    content: 'public static class Extensions : object'
    content.vb: >-
      Public Module Extensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString(Exception)
  commentId: M:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString(Exception)
  id: ToInvariantString(Exception)
  isExtensionMethod: true
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions
  langs:
  - csharp
  - vb
  name: ToInvariantString(Exception)
  nameWithType: Extensions.ToInvariantString(Exception)
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString(Exception)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/Extensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: ToInvariantString
    path: src/Core/Managed/Shared/Extensibility/Implementation/Tracing/Extensions.cs
    startLine: 17
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  summary: "\nReturns a culture-independent string representation of the given <em>exception</em> object, \nappropriate for diagnostics tracing.\n"
  example: []
  syntax:
    content: public static string ToInvariantString(this Exception exception)
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function ToInvariantString(exception As Exception) As String
    parameters:
    - id: exception
      type: Exception
    return:
      type: System.String
  overload: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString*
  commentId: Overload:Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString
  isExternal: false
  name: ToInvariantString
  nameWithType: Extensions.ToInvariantString
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.Extensions.ToInvariantString
- uid: Exception
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: Exception
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
