### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights.OperationTelemetryExtensions
  commentId: T:Microsoft.ApplicationInsights.OperationTelemetryExtensions
  id: OperationTelemetryExtensions
  parent: Microsoft.ApplicationInsights
  children:
  - Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  - Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  - Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  langs:
  - csharp
  - vb
  name: OperationTelemetryExtensions
  nameWithType: OperationTelemetryExtensions
  fullName: Microsoft.ApplicationInsights.OperationTelemetryExtensions
  type: Class
  source:
    remote:
      path: src/Core/Managed/Shared/OperationTelemetryExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: OperationTelemetryExtensions
    path: src/Core/Managed/Shared/OperationTelemetryExtensions.cs
    startLine: 10
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  summary: "\nExtension functions to operation telemetry that start and stop the timer.\n"
  example: []
  syntax:
    content: 'public static class OperationTelemetryExtensions : object'
    content.vb: >-
      Public Module OperationTelemetryExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  commentId: M:Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  id: Start(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  isExtensionMethod: true
  parent: Microsoft.ApplicationInsights.OperationTelemetryExtensions
  langs:
  - csharp
  - vb
  name: Start(OperationTelemetry)
  nameWithType: OperationTelemetryExtensions.Start(OperationTelemetry)
  fullName: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/OperationTelemetryExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Start
    path: src/Core/Managed/Shared/OperationTelemetryExtensions.cs
    startLine: 17
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  summary: "\nAn extension to telemetry item that starts the timer for the the respective telemetry.\n"
  example: []
  syntax:
    content: public static void Start(this OperationTelemetry telemetry)
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub Start(telemetry As OperationTelemetry)
    parameters:
    - id: telemetry
      type: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
      description: Telemetry item object that calls this extension method.
  overload: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  commentId: M:Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  id: Stop(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  isExtensionMethod: true
  parent: Microsoft.ApplicationInsights.OperationTelemetryExtensions
  langs:
  - csharp
  - vb
  name: Stop(OperationTelemetry)
  nameWithType: OperationTelemetryExtensions.Stop(OperationTelemetry)
  fullName: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/OperationTelemetryExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: Stop
    path: src/Core/Managed/Shared/OperationTelemetryExtensions.cs
    startLine: 28
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  summary: "\nAn extension method to telemetry item that stops the timer and computes the duration of the request or dependency.\n"
  example: []
  syntax:
    content: public static void Stop(this OperationTelemetry telemetry)
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub Stop(telemetry As OperationTelemetry)
    parameters:
    - id: telemetry
      type: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
      description: Telemetry item object that calls this extension method.
  overload: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  commentId: M:Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  id: GenerateOperationId(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  isExtensionMethod: true
  parent: Microsoft.ApplicationInsights.OperationTelemetryExtensions
  langs:
  - csharp
  - vb
  name: GenerateOperationId(OperationTelemetry)
  nameWithType: OperationTelemetryExtensions.GenerateOperationId(OperationTelemetry)
  fullName: Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId(Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry)
  type: Method
  source:
    remote:
      path: src/Core/Managed/Shared/OperationTelemetryExtensions.cs
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-dotnet
    id: GenerateOperationId
    path: src/Core/Managed/Shared/OperationTelemetryExtensions.cs
    startLine: 46
  assemblies:
  - Microsoft.ApplicationInsights
  namespace: Microsoft.ApplicationInsights
  summary: "\nGenerate random operation Id and set it to OperationContext.\n"
  example: []
  syntax:
    content: public static void GenerateOperationId(this OperationTelemetry telemetry)
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub GenerateOperationId(telemetry As OperationTelemetry)
    parameters:
    - id: telemetry
      type: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
      description: Telemetry to initialize Operation id for.
  overload: Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  isExternal: false
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start*
  commentId: Overload:Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start
  isExternal: false
  name: Start
  nameWithType: OperationTelemetryExtensions.Start
  fullName: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Start
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
  commentId: T:Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
  parent: Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: OperationTelemetry
  nameWithType: OperationTelemetry
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation.OperationTelemetry
- uid: Microsoft.ApplicationInsights.Extensibility.Implementation
  commentId: N:Microsoft.ApplicationInsights.Extensibility.Implementation
  isExternal: false
  name: Microsoft.ApplicationInsights.Extensibility.Implementation
  nameWithType: Microsoft.ApplicationInsights.Extensibility.Implementation
  fullName: Microsoft.ApplicationInsights.Extensibility.Implementation
- uid: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop*
  commentId: Overload:Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop
  isExternal: false
  name: Stop
  nameWithType: OperationTelemetryExtensions.Stop
  fullName: Microsoft.ApplicationInsights.OperationTelemetryExtensions.Stop
- uid: Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId*
  commentId: Overload:Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId
  isExternal: false
  name: GenerateOperationId
  nameWithType: OperationTelemetryExtensions.GenerateOperationId
  fullName: Microsoft.ApplicationInsights.OperationTelemetryExtensions.GenerateOperationId
