### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  id: Microsoft.ApplicationInsights
  children:
  - Microsoft.ApplicationInsights.OperationTelemetryExtensions
  - Microsoft.ApplicationInsights.TelemetryClient
  - Microsoft.ApplicationInsights.TelemetryClientExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.OperationTelemetryExtensions
  commentId: T:Microsoft.ApplicationInsights.OperationTelemetryExtensions
  parent: Microsoft.ApplicationInsights
  isExternal: false
  name: OperationTelemetryExtensions
  nameWithType: OperationTelemetryExtensions
  fullName: Microsoft.ApplicationInsights.OperationTelemetryExtensions
- uid: Microsoft.ApplicationInsights.TelemetryClient
  commentId: T:Microsoft.ApplicationInsights.TelemetryClient
  parent: Microsoft.ApplicationInsights
  isExternal: false
  name: TelemetryClient
  nameWithType: TelemetryClient
  fullName: Microsoft.ApplicationInsights.TelemetryClient
- uid: Microsoft.ApplicationInsights.TelemetryClientExtensions
  commentId: T:Microsoft.ApplicationInsights.TelemetryClientExtensions
  parent: Microsoft.ApplicationInsights
  isExternal: false
  name: TelemetryClientExtensions
  nameWithType: TelemetryClientExtensions
  fullName: Microsoft.ApplicationInsights.TelemetryClientExtensions
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  isExternal: false
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
