### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty
  id: DscNodeConfigurationAssociationProperty
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.Name
  langs:
  - csharp
  - vb
  name: DscNodeConfigurationAssociationProperty
  nameWithType: DscNodeConfigurationAssociationProperty
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationAssociationProperty.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DscNodeConfigurationAssociationProperty
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationAssociationProperty.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe dsc nodeconfiguration property associated with the entity.\n"
  example: []
  syntax:
    content: 'public class DscNodeConfigurationAssociationProperty : object'
    content.vb: >-
      Public Class DscNodeConfigurationAssociationProperty
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.Name
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.Name
  id: Name
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: DscNodeConfigurationAssociationProperty.Name
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationAssociationProperty.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationAssociationProperty.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the name of the dsc nodeconfiguration.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  overload: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty
  langs:
  - csharp
  - vb
  name: DscNodeConfigurationAssociationProperty()
  nameWithType: DscNodeConfigurationAssociationProperty.DscNodeConfigurationAssociationProperty()
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.DscNodeConfigurationAssociationProperty()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationAssociationProperty.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationAssociationProperty.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscNodeConfigurationAssociationProperty class.\n"
  example: []
  syntax:
    content: public DscNodeConfigurationAssociationProperty()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.Name*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.Name
  isExternal: false
  name: Name
  nameWithType: DscNodeConfigurationAssociationProperty.Name
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.Name
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.#ctor
  isExternal: false
  name: DscNodeConfigurationAssociationProperty
  nameWithType: DscNodeConfigurationAssociationProperty.DscNodeConfigurationAssociationProperty
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationAssociationProperty.DscNodeConfigurationAssociationProperty
