### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
  id: DscConfigurationListResponse
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.Configurations
  langs:
  - csharp
  - vb
  name: DscConfigurationListResponse
  nameWithType: DscConfigurationListResponse
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationListResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationListResponse
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationListResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe response model for the list configuration operation.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationListResponse : OperationResponseWithSkipToken'
    content.vb: >-
      Public Class DscConfigurationListResponse
          Inherits OperationResponseWithSkipToken
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.NextLink
  - Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.SkipToken
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.Configurations
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.Configurations
  id: Configurations
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
  langs:
  - csharp
  - vb
  name: Configurations
  nameWithType: DscConfigurationListResponse.Configurations
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.Configurations
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationListResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Configurations
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationListResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets a list of configurations.\n"
  example: []
  syntax:
    content: public IList<DscConfiguration> Configurations { get; set; }
    content.vb: Public Property Configurations As IList(Of DscConfiguration)
    parameters: []
    return:
      type: IList{Microsoft.Azure.Management.Automation.Models.DscConfiguration}
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.Configurations*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
  langs:
  - csharp
  - vb
  name: DscConfigurationListResponse()
  nameWithType: DscConfigurationListResponse.DscConfigurationListResponse()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.DscConfigurationListResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationListResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationListResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscConfigurationListResponse\nclass.\n"
  example: []
  syntax:
    content: public DscConfigurationListResponse()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  commentId: T:Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: OperationResponseWithSkipToken
  nameWithType: OperationResponseWithSkipToken
  fullName: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
- uid: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.NextLink
  commentId: P:Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.NextLink
  parent: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  isExternal: false
  name: NextLink
  nameWithType: OperationResponseWithSkipToken.NextLink
  fullName: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.NextLink
- uid: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.SkipToken
  commentId: P:Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.SkipToken
  parent: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  isExternal: false
  name: SkipToken
  nameWithType: OperationResponseWithSkipToken.SkipToken
  fullName: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.SkipToken
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.Configurations*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.Configurations
  isExternal: false
  name: Configurations
  nameWithType: DscConfigurationListResponse.Configurations
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.Configurations
- uid: IList{Microsoft.Azure.Management.Automation.Models.DscConfiguration}
  commentId: '!:IList{Microsoft.Azure.Management.Automation.Models.DscConfiguration}'
  definition: IList`1
  name: IList<DscConfiguration>
  nameWithType: IList<DscConfiguration>
  fullName: IList<Microsoft.Azure.Management.Automation.Models.DscConfiguration>
  nameWithType.vb: IList(Of DscConfiguration)
  fullname.vb: IList(Of Microsoft.Azure.Management.Automation.Models.DscConfiguration)
  name.vb: IList(Of DscConfiguration)
  spec.csharp:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration
    name: DscConfiguration
    nameWithType: DscConfiguration
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration
    name: DscConfiguration
    nameWithType: DscConfiguration
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: IList`1
  isExternal: true
  name: IList<>
  nameWithType: IList<>
  fullName: IList<>
  nameWithType.vb: IList(Of )
  fullname.vb: IList(Of )
  name.vb: IList(Of )
  spec.csharp:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.#ctor
  isExternal: false
  name: DscConfigurationListResponse
  nameWithType: DscConfigurationListResponse.DscConfigurationListResponse
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse.DscConfigurationListResponse
