### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration
  commentId: T:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration
  id: ScalarFunctionConfiguration
  parent: Microsoft.Azure.Management.StreamAnalytics.Models
  children:
  - Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.#ctor
  - Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Binding
  - Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Inputs
  - Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Output
  langs:
  - csharp
  - vb
  name: ScalarFunctionConfiguration
  nameWithType: ScalarFunctionConfiguration
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: ScalarFunctionConfiguration
    path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.StreamAnalytics
  namespace: Microsoft.Azure.Management.StreamAnalytics.Models
  summary: "\nThe configuration of the scalar function.\n"
  example: []
  syntax:
    content: 'public class ScalarFunctionConfiguration : object'
    content.vb: >-
      Public Class ScalarFunctionConfiguration
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Binding
  commentId: P:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Binding
  id: Binding
  parent: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration
  langs:
  - csharp
  - vb
  name: Binding
  nameWithType: ScalarFunctionConfiguration.Binding
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Binding
  type: Property
  source:
    remote:
      path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Binding
    path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
    startLine: 40
  assemblies:
  - Microsoft.Azure.Management.StreamAnalytics
  namespace: Microsoft.Azure.Management.StreamAnalytics.Models
  summary: "\nOptional. Gets or sets the physical binding of the function. In the\nAzure Machine Learning web service’s case, this describes the\nendpoint.\n"
  example: []
  syntax:
    content: public FunctionBinding Binding { get; set; }
    content.vb: Public Property Binding As FunctionBinding
    parameters: []
    return:
      type: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionBinding
  overload: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Binding*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Inputs
  commentId: P:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Inputs
  id: Inputs
  parent: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration
  langs:
  - csharp
  - vb
  name: Inputs
  nameWithType: ScalarFunctionConfiguration.Inputs
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Inputs
  type: Property
  source:
    remote:
      path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Inputs
    path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
    startLine: 52
  assemblies:
  - Microsoft.Azure.Management.StreamAnalytics
  namespace: Microsoft.Azure.Management.StreamAnalytics.Models
  summary: "\nOptional. Gets or sets a list of inputs describing the parameters\nof the function.\n"
  example: []
  syntax:
    content: public IList<FunctionInput> Inputs { get; set; }
    content.vb: Public Property Inputs As IList(Of FunctionInput)
    parameters: []
    return:
      type: IList{Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput}
  overload: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Inputs*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Output
  commentId: P:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Output
  id: Output
  parent: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration
  langs:
  - csharp
  - vb
  name: Output
  nameWithType: ScalarFunctionConfiguration.Output
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Output
  type: Property
  source:
    remote:
      path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: Output
    path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
    startLine: 63
  assemblies:
  - Microsoft.Azure.Management.StreamAnalytics
  namespace: Microsoft.Azure.Management.StreamAnalytics.Models
  summary: "\nOptional. Gets or sets the output of the function.\n"
  example: []
  syntax:
    content: public FunctionOutput Output { get; set; }
    content.vb: Public Property Output As FunctionOutput
    parameters: []
    return:
      type: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionOutput
  overload: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Output*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration
  langs:
  - csharp
  - vb
  name: ScalarFunctionConfiguration()
  nameWithType: ScalarFunctionConfiguration.ScalarFunctionConfiguration()
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.ScalarFunctionConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-net
    id: .ctor
    path: src/ResourceManagement/StreamAnalytics/StreamAnalyticsManagement/Generated/Models/ScalarFunctionConfiguration.cs
    startLine: 72
  assemblies:
  - Microsoft.Azure.Management.StreamAnalytics
  namespace: Microsoft.Azure.Management.StreamAnalytics.Models
  summary: "\nInitializes a new instance of the ScalarFunctionConfiguration class.\n"
  example: []
  syntax:
    content: public ScalarFunctionConfiguration()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.StreamAnalytics.Models
  commentId: N:Microsoft.Azure.Management.StreamAnalytics.Models
  isExternal: false
  name: Microsoft.Azure.Management.StreamAnalytics.Models
  nameWithType: Microsoft.Azure.Management.StreamAnalytics.Models
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Binding*
  commentId: Overload:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Binding
  isExternal: false
  name: Binding
  nameWithType: ScalarFunctionConfiguration.Binding
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Binding
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionBinding
  commentId: T:Microsoft.Azure.Management.StreamAnalytics.Models.FunctionBinding
  parent: Microsoft.Azure.Management.StreamAnalytics.Models
  isExternal: false
  name: FunctionBinding
  nameWithType: FunctionBinding
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionBinding
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Inputs*
  commentId: Overload:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Inputs
  isExternal: false
  name: Inputs
  nameWithType: ScalarFunctionConfiguration.Inputs
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Inputs
- uid: IList{Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput}
  commentId: '!:IList{Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput}'
  definition: IList`1
  name: IList<FunctionInput>
  nameWithType: IList<FunctionInput>
  fullName: IList<Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput>
  nameWithType.vb: IList(Of FunctionInput)
  fullname.vb: IList(Of Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput)
  name.vb: IList(Of FunctionInput)
  spec.csharp:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput
    name: FunctionInput
    nameWithType: FunctionInput
    fullName: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput
    name: FunctionInput
    nameWithType: FunctionInput
    fullName: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionInput
  - name: )
    nameWithType: )
    fullName: )
- uid: IList`1
  isExternal: true
  name: IList<>
  nameWithType: IList<>
  fullName: IList<>
  nameWithType.vb: IList(Of )
  fullname.vb: IList(Of )
  name.vb: IList(Of )
  spec.csharp:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: IList`1
    name: IList
    nameWithType: IList
    fullName: IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Output*
  commentId: Overload:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Output
  isExternal: false
  name: Output
  nameWithType: ScalarFunctionConfiguration.Output
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.Output
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionOutput
  commentId: T:Microsoft.Azure.Management.StreamAnalytics.Models.FunctionOutput
  parent: Microsoft.Azure.Management.StreamAnalytics.Models
  isExternal: false
  name: FunctionOutput
  nameWithType: FunctionOutput
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.FunctionOutput
- uid: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.#ctor*
  commentId: Overload:Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.#ctor
  isExternal: false
  name: ScalarFunctionConfiguration
  nameWithType: ScalarFunctionConfiguration.ScalarFunctionConfiguration
  fullName: Microsoft.Azure.Management.StreamAnalytics.Models.ScalarFunctionConfiguration.ScalarFunctionConfiguration
