### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationState
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationState
  id: DscConfigurationState
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationState.Edit
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationState.New
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationState.Published
  langs:
  - csharp
  - vb
  name: DscConfigurationState
  nameWithType: DscConfigurationState
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationState
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationState.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationState
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationState.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe configuration state.\n"
  example: []
  syntax:
    content: 'public static class DscConfigurationState : object'
    content.vb: >-
      Public Module DscConfigurationState
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationState.New
  commentId: F:Microsoft.Azure.Management.Automation.Models.DscConfigurationState.New
  id: New
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationState
  langs:
  - csharp
  - vb
  name: New
  nameWithType: DscConfigurationState.New
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationState.New
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationState.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: New
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationState.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  syntax:
    content: public const string New = null
    content.vb: Public Const New As String = Nothing
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationState.Edit
  commentId: F:Microsoft.Azure.Management.Automation.Models.DscConfigurationState.Edit
  id: Edit
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationState
  langs:
  - csharp
  - vb
  name: Edit
  nameWithType: DscConfigurationState.Edit
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationState.Edit
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationState.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Edit
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationState.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  syntax:
    content: public const string Edit = null
    content.vb: Public Const Edit As String = Nothing
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationState.Published
  commentId: F:Microsoft.Azure.Management.Automation.Models.DscConfigurationState.Published
  id: Published
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationState
  langs:
  - csharp
  - vb
  name: Published
  nameWithType: DscConfigurationState.Published
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationState.Published
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationState.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Published
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationState.cs
    startLine: 35
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  syntax:
    content: public const string Published = null
    content.vb: Public Const Published As String = Nothing
    return:
      type: System.String
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
