items:
- uid: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  commentId: T:Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  id: IDscConfigurationOperations
  parent: Microsoft.Azure.Management.Automation
  children:
  - Microsoft.Azure.Management.Automation.IDscConfigurationOperations.CreateOrUpdateAsync(System.String,System.String,Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters,CancellationToken)
  - Microsoft.Azure.Management.Automation.IDscConfigurationOperations.GetAsync(System.String,System.String,System.String,CancellationToken)
  - Microsoft.Azure.Management.Automation.IDscConfigurationOperations.GetContentAsync(System.String,System.String,System.String,CancellationToken)
  - Microsoft.Azure.Management.Automation.IDscConfigurationOperations.ListAsync(System.String,System.String,CancellationToken)
  - Microsoft.Azure.Management.Automation.IDscConfigurationOperations.ListNextAsync(System.String,CancellationToken)
  langs:
  - csharp
  - vb
  name: IDscConfigurationOperations
  fullName: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: IDscConfigurationOperations
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nService operation for configurations.  (see\nhttp://aka.ms/azureautomationsdk/configurationoperations for more\ninformation)\n"
  example: []
  syntax:
    content: public interface IDscConfigurationOperations
    content.vb: Public Interface IDscConfigurationOperations
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.CreateOrUpdateAsync(System.String,System.String,Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters,CancellationToken)
  commentId: M:Microsoft.Azure.Management.Automation.IDscConfigurationOperations.CreateOrUpdateAsync(System.String,System.String,Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters,CancellationToken)
  id: CreateOrUpdateAsync(System.String,System.String,Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters,CancellationToken)
  parent: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  langs:
  - csharp
  - vb
  name: CreateOrUpdateAsync(String, String, DscConfigurationCreateOrUpdateParameters, CancellationToken)
  fullName: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.CreateOrUpdateAsync(System.String, System.String, Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters, CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: CreateOrUpdateAsync
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nCreate the configuration identified by configuration name.  (see\nhttp://aka.ms/azureautomationsdk/configurationoperations for more\ninformation)\n"
  example: []
  syntax:
    content: Task<DscConfigurationCreateOrUpdateResponse> CreateOrUpdateAsync(string resourceGroupName, string automationAccount, DscConfigurationCreateOrUpdateParameters parameters, CancellationToken cancellationToken)
    content.vb: Function CreateOrUpdateAsync(resourceGroupName As String, automationAccount As String, parameters As DscConfigurationCreateOrUpdateParameters, cancellationToken As CancellationToken) As Task(Of DscConfigurationCreateOrUpdateResponse)
    parameters:
    - id: resourceGroupName
      type: System.String
      description: "\nThe name of the resource group\n"
    - id: automationAccount
      type: System.String
      description: "\nThe automation account name.\n"
    - id: parameters
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
      description: "\nThe create or update parameters for configuration.\n"
    - id: cancellationToken
      type: CancellationToken
      description: "\nCancellation token.\n"
    return:
      type: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse}
      description: "\nThe response model for the configuration create response.\n"
- uid: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.GetAsync(System.String,System.String,System.String,CancellationToken)
  commentId: M:Microsoft.Azure.Management.Automation.IDscConfigurationOperations.GetAsync(System.String,System.String,System.String,CancellationToken)
  id: GetAsync(System.String,System.String,System.String,CancellationToken)
  parent: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  langs:
  - csharp
  - vb
  name: GetAsync(String, String, String, CancellationToken)
  fullName: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.GetAsync(System.String, System.String, System.String, CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: GetAsync
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
    startLine: 78
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nRetrieve the configuration identified by configuration name.  (see\nhttp://aka.ms/azureautomationsdk/configurationoperations for more\ninformation)\n"
  example: []
  syntax:
    content: Task<DscConfigurationGetResponse> GetAsync(string resourceGroupName, string automationAccount, string configurationName, CancellationToken cancellationToken)
    content.vb: Function GetAsync(resourceGroupName As String, automationAccount As String, configurationName As String, cancellationToken As CancellationToken) As Task(Of DscConfigurationGetResponse)
    parameters:
    - id: resourceGroupName
      type: System.String
      description: "\nThe name of the resource group\n"
    - id: automationAccount
      type: System.String
      description: "\nThe automation account name.\n"
    - id: configurationName
      type: System.String
      description: "\nThe configuration name.\n"
    - id: cancellationToken
      type: CancellationToken
      description: "\nCancellation token.\n"
    return:
      type: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse}
      description: "\nThe response model for the get configuration operation.\n"
- uid: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.GetContentAsync(System.String,System.String,System.String,CancellationToken)
  commentId: M:Microsoft.Azure.Management.Automation.IDscConfigurationOperations.GetContentAsync(System.String,System.String,System.String,CancellationToken)
  id: GetContentAsync(System.String,System.String,System.String,CancellationToken)
  parent: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  langs:
  - csharp
  - vb
  name: GetContentAsync(String, String, String, CancellationToken)
  fullName: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.GetContentAsync(System.String, System.String, System.String, CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: GetContentAsync
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
    startLine: 100
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nRetrieve the configuration script identified by configuration name.\n(see http://aka.ms/azureautomationsdk/configurationoperations for\nmore information)\n"
  example: []
  syntax:
    content: Task<DscConfigurationGetContentResponse> GetContentAsync(string resourceGroupName, string automationAccount, string configurationName, CancellationToken cancellationToken)
    content.vb: Function GetContentAsync(resourceGroupName As String, automationAccount As String, configurationName As String, cancellationToken As CancellationToken) As Task(Of DscConfigurationGetContentResponse)
    parameters:
    - id: resourceGroupName
      type: System.String
      description: "\nThe name of the resource group\n"
    - id: automationAccount
      type: System.String
      description: "\nThe automation account name.\n"
    - id: configurationName
      type: System.String
      description: "\nThe configuration name.\n"
    - id: cancellationToken
      type: CancellationToken
      description: "\nCancellation token.\n"
    return:
      type: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse}
      description: "\nThe response model for the get configuration operation.\n"
- uid: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.ListAsync(System.String,System.String,CancellationToken)
  commentId: M:Microsoft.Azure.Management.Automation.IDscConfigurationOperations.ListAsync(System.String,System.String,CancellationToken)
  id: ListAsync(System.String,System.String,CancellationToken)
  parent: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  langs:
  - csharp
  - vb
  name: ListAsync(String, String, CancellationToken)
  fullName: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.ListAsync(System.String, System.String, CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ListAsync
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
    startLine: 119
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nRetrieve a list of configurations.  (see\nhttp://aka.ms/azureautomationsdk/configurationoperations for more\ninformation)\n"
  example: []
  syntax:
    content: Task<DscConfigurationListResponse> ListAsync(string resourceGroupName, string automationAccount, CancellationToken cancellationToken)
    content.vb: Function ListAsync(resourceGroupName As String, automationAccount As String, cancellationToken As CancellationToken) As Task(Of DscConfigurationListResponse)
    parameters:
    - id: resourceGroupName
      type: System.String
      description: "\nThe name of the resource group\n"
    - id: automationAccount
      type: System.String
      description: "\nThe automation account name.\n"
    - id: cancellationToken
      type: CancellationToken
      description: "\nCancellation token.\n"
    return:
      type: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse}
      description: "\nThe response model for the list configuration operation.\n"
- uid: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.ListNextAsync(System.String,CancellationToken)
  commentId: M:Microsoft.Azure.Management.Automation.IDscConfigurationOperations.ListNextAsync(System.String,CancellationToken)
  id: ListNextAsync(System.String,CancellationToken)
  parent: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  langs:
  - csharp
  - vb
  name: ListNextAsync(String, CancellationToken)
  fullName: Microsoft.Azure.Management.Automation.IDscConfigurationOperations.ListNextAsync(System.String, CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ListNextAsync
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscConfigurationOperations.cs
    startLine: 135
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nRetrieve next list of configurations.  (see\nhttp://aka.ms/azureautomationsdk/configurationoperations for more\ninformation)\n"
  example: []
  syntax:
    content: Task<DscConfigurationListResponse> ListNextAsync(string nextLink, CancellationToken cancellationToken)
    content.vb: Function ListNextAsync(nextLink As String, cancellationToken As CancellationToken) As Task(Of DscConfigurationListResponse)
    parameters:
    - id: nextLink
      type: System.String
      description: "\nThe link to retrieve next set of items.\n"
    - id: cancellationToken
      type: CancellationToken
      description: "\nCancellation token.\n"
    return:
      type: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse}
      description: "\nThe response model for the list configuration operation.\n"
references:
- uid: Microsoft.Azure.Management.Automation
  isExternal: false
  name: Microsoft.Azure.Management.Automation
  fullName: Microsoft.Azure.Management.Automation
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationCreateOrUpdateParameters
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
- uid: CancellationToken
  isExternal: true
  name: CancellationToken
  fullName: CancellationToken
- uid: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse}
  definition: Task`1
  name: Task<DscConfigurationCreateOrUpdateResponse>
  fullName: Task<Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse>
  fullname.vb: Task(Of Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse)
  name.vb: Task(Of DscConfigurationCreateOrUpdateResponse)
  spec.csharp:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
    name: DscConfigurationCreateOrUpdateResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
    name: DscConfigurationCreateOrUpdateResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Task`1
  isExternal: true
  name: Task<>
  fullName: Task<>
  fullname.vb: Task(Of )
  name.vb: Task(Of )
  spec.csharp:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse}
  definition: Task`1
  name: Task<DscConfigurationGetResponse>
  fullName: Task<Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse>
  fullname.vb: Task(Of Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse)
  name.vb: Task(Of DscConfigurationGetResponse)
  spec.csharp:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
    name: DscConfigurationGetResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
    name: DscConfigurationGetResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
  - name: )
    fullName: )
- uid: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse}
  definition: Task`1
  name: Task<DscConfigurationGetContentResponse>
  fullName: Task<Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse>
  fullname.vb: Task(Of Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse)
  name.vb: Task(Of DscConfigurationGetContentResponse)
  spec.csharp:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
    name: DscConfigurationGetContentResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
    name: DscConfigurationGetContentResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
  - name: )
    fullName: )
- uid: Task{Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse}
  definition: Task`1
  name: Task<DscConfigurationListResponse>
  fullName: Task<Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse>
  fullname.vb: Task(Of Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse)
  name.vb: Task(Of DscConfigurationListResponse)
  spec.csharp:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
    name: DscConfigurationListResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
    name: DscConfigurationListResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationListResponse
  - name: )
    fullName: )
