items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
  id: DscConfigurationCreateOrUpdateResponse
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse.Configuration
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateResponse
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationCreateOrUpdateResponse
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe response model for the configuration create response.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationCreateOrUpdateResponse : AzureOperationResponse'
    content.vb: >-
      Public Class DscConfigurationCreateOrUpdateResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse.Configuration
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse.Configuration
  id: Configuration
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: Configuration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse.Configuration
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Configuration
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets a configuration.\n"
  example: []
  syntax:
    content: public DscConfiguration Configuration { get; set; }
    content.vb: Public Property Configuration As DscConfiguration
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateResponse()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateResponse.DscConfigurationCreateOrUpdateResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateResponse.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationCreateOrUpdateResponse class.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfiguration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration
