items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  id: DscConfigurationParameter
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  langs:
  - csharp
  - vb
  name: DscConfigurationParameter
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationParameter
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nDefinition of the configuration parameter type.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationParameter : object'
    content.vb: >-
      Public Class DscConfigurationParameter
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  id: DefaultValue
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: DefaultValue
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DefaultValue
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DefaultValue
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the default value of parameter.\n"
  example: []
  syntax:
    content: public string DefaultValue { get; set; }
    content.vb: Public Property DefaultValue As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  id: IsMandatory
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: IsMandatory
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.IsMandatory
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: IsMandatory
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets a Boolean value to indicate whether the\nparameter is madatory or not.\n"
  example: []
  syntax:
    content: public bool IsMandatory { get; set; }
    content.vb: Public Property IsMandatory As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  id: Position
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: Position
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Position
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Position
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Get or sets the position of the parameter.\n"
  example: []
  syntax:
    content: public int Position { get; set; }
    content.vb: Public Property Position As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  id: Type
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: Type
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.Type
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Type
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the type of the parameter.\n"
  example: []
  syntax:
    content: public string Type { get; set; }
    content.vb: Public Property Type As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  langs:
  - csharp
  - vb
  name: DscConfigurationParameter()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter.DscConfigurationParameter()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationParameter.cs
    startLine: 79
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscConfigurationParameter class.\n"
  example: []
  syntax:
    content: public DscConfigurationParameter()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Boolean
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: System.Int32
  isExternal: true
  name: Int32
  fullName: System.Int32
