items:
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
  id: DscNodeConfigurationListResponse
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse.DscNodeConfigurations
  langs:
  - csharp
  - vb
  name: DscNodeConfigurationListResponse
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscNodeConfigurationListResponse
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe response model for the list job operation.\n"
  example: []
  syntax:
    content: 'public class DscNodeConfigurationListResponse : OperationResponseWithSkipToken'
    content.vb: >-
      Public Class DscNodeConfigurationListResponse
          Inherits OperationResponseWithSkipToken
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.NextLink
  - Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.SkipToken
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse.DscNodeConfigurations
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse.DscNodeConfigurations
  id: DscNodeConfigurations
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
  langs:
  - csharp
  - vb
  name: DscNodeConfigurations
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse.DscNodeConfigurations
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscNodeConfigurations
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets a list of Dsc node configurations.\n"
  example: []
  syntax:
    content: public IList<DscNodeConfiguration> DscNodeConfigurations { get; set; }
    content.vb: Public Property DscNodeConfigurations As IList(Of DscNodeConfiguration)
    parameters: []
    return:
      type: IList{Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
  langs:
  - csharp
  - vb
  name: DscNodeConfigurationListResponse()
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse.DscNodeConfigurationListResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscNodeConfigurationListResponse\nclass.\n"
  example: []
  syntax:
    content: public DscNodeConfigurationListResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: OperationResponseWithSkipToken
  fullName: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
- uid: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.NextLink
  parent: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  isExternal: false
  name: NextLink
  fullName: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.NextLink
- uid: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.SkipToken
  parent: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken
  isExternal: false
  name: SkipToken
  fullName: Microsoft.Azure.Management.Automation.Models.OperationResponseWithSkipToken.SkipToken
- uid: IList{Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration}
  definition: IList`1
  name: IList<DscNodeConfiguration>
  fullName: IList<Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration>
  fullname.vb: IList(Of Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration)
  name.vb: IList(Of DscNodeConfiguration)
  spec.csharp:
  - uid: IList`1
    name: IList
    fullName: IList
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
    name: DscNodeConfiguration
    fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IList`1
    name: IList
    fullName: IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
    name: DscNodeConfiguration
    fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  - name: )
    fullName: )
- uid: IList`1
  isExternal: true
  name: IList<>
  fullName: IList<>
  fullname.vb: IList(Of )
  name.vb: IList(Of )
  spec.csharp:
  - uid: IList`1
    name: IList
    fullName: IList
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IList`1
    name: IList
    fullName: IList
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
