items:
- uid: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
  commentId: T:Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
  id: IDscNodeConfigurationOperations
  parent: Microsoft.Azure.Management.Automation
  children:
  - Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.GetAsync(System.String,System.String,System.String,CancellationToken)
  - Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.ListAsync(System.String,System.String,Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters,CancellationToken)
  - Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.ListNextAsync(System.String,CancellationToken)
  langs:
  - csharp
  - vb
  name: IDscNodeConfigurationOperations
  fullName: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
  type: Interface
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscNodeConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: IDscNodeConfigurationOperations
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscNodeConfigurationOperations.cs
    startLine: 34
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nService operation for automation dsc node configurations.  (see\nhttp://aka.ms/azureautomationsdk/dscnodeconfigurations for more\ninformation)\n"
  example: []
  syntax:
    content: public interface IDscNodeConfigurationOperations
    content.vb: Public Interface IDscNodeConfigurationOperations
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.GetAsync(System.String,System.String,System.String,CancellationToken)
  commentId: M:Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.GetAsync(System.String,System.String,System.String,CancellationToken)
  id: GetAsync(System.String,System.String,System.String,CancellationToken)
  parent: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
  langs:
  - csharp
  - vb
  name: GetAsync(String, String, String, CancellationToken)
  fullName: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.GetAsync(System.String, System.String, System.String, CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscNodeConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: GetAsync
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscNodeConfigurationOperations.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nRetrieve the Dsc node configurations by node configuration.  (see\nhttp://aka.ms/azureautomationsdk/dscnodeconfigurations for more\ninformation)\n"
  example: []
  syntax:
    content: Task<DscNodeConfigurationGetResponse> GetAsync(string resourceGroupName, string automationAccount, string nodeConfigurationName, CancellationToken cancellationToken)
    content.vb: Function GetAsync(resourceGroupName As String, automationAccount As String, nodeConfigurationName As String, cancellationToken As CancellationToken) As Task(Of DscNodeConfigurationGetResponse)
    parameters:
    - id: resourceGroupName
      type: System.String
      description: "\nThe name of the resource group\n"
    - id: automationAccount
      type: System.String
      description: "\nThe automation account name.\n"
    - id: nodeConfigurationName
      type: System.String
      description: "\nThe Dsc node configuration name.\n"
    - id: cancellationToken
      type: CancellationToken
      description: "\nCancellation token.\n"
    return:
      type: Task{Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse}
      description: "\nThe response model for the get Dsc node configuration operation.\n"
- uid: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.ListAsync(System.String,System.String,Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters,CancellationToken)
  commentId: M:Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.ListAsync(System.String,System.String,Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters,CancellationToken)
  id: ListAsync(System.String,System.String,Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters,CancellationToken)
  parent: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
  langs:
  - csharp
  - vb
  name: ListAsync(String, String, DscNodeConfigurationListParameters, CancellationToken)
  fullName: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.ListAsync(System.String, System.String, Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters, CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscNodeConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ListAsync
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscNodeConfigurationOperations.cs
    startLine: 78
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nRetrieve a list of dsc node configurations.  (see\nhttp://aka.ms/azureautomationsdk/dscnodeconfigurations for more\ninformation)\n"
  example: []
  syntax:
    content: Task<DscNodeConfigurationListResponse> ListAsync(string resourceGroupName, string automationAccount, DscNodeConfigurationListParameters parameters, CancellationToken cancellationToken)
    content.vb: Function ListAsync(resourceGroupName As String, automationAccount As String, parameters As DscNodeConfigurationListParameters, cancellationToken As CancellationToken) As Task(Of DscNodeConfigurationListResponse)
    parameters:
    - id: resourceGroupName
      type: System.String
      description: "\nThe name of the resource group\n"
    - id: automationAccount
      type: System.String
      description: "\nThe automation account name.\n"
    - id: parameters
      type: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters
      description: "\nThe parameters supplied to the list operation.\n"
    - id: cancellationToken
      type: CancellationToken
      description: "\nCancellation token.\n"
    return:
      type: Task{Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse}
      description: "\nThe response model for the list job operation.\n"
- uid: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.ListNextAsync(System.String,CancellationToken)
  commentId: M:Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.ListNextAsync(System.String,CancellationToken)
  id: ListNextAsync(System.String,CancellationToken)
  parent: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
  langs:
  - csharp
  - vb
  name: ListNextAsync(String, CancellationToken)
  fullName: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations.ListNextAsync(System.String, CancellationToken)
  type: Method
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscNodeConfigurationOperations.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ListNextAsync
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/IDscNodeConfigurationOperations.cs
    startLine: 94
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation
  summary: "\nRetrieve next list of dsc node configrations.  (see\nhttp://aka.ms/azureautomationsdk/dscnodeconfigurations for more\ninformation)\n"
  example: []
  syntax:
    content: Task<DscNodeConfigurationListResponse> ListNextAsync(string nextLink, CancellationToken cancellationToken)
    content.vb: Function ListNextAsync(nextLink As String, cancellationToken As CancellationToken) As Task(Of DscNodeConfigurationListResponse)
    parameters:
    - id: nextLink
      type: System.String
      description: "\nThe link to retrieve next set of items.\n"
    - id: cancellationToken
      type: CancellationToken
      description: "\nCancellation token.\n"
    return:
      type: Task{Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse}
      description: "\nThe response model for the list job operation.\n"
references:
- uid: Microsoft.Azure.Management.Automation
  isExternal: false
  name: Microsoft.Azure.Management.Automation
  fullName: Microsoft.Azure.Management.Automation
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: CancellationToken
  isExternal: true
  name: CancellationToken
  fullName: CancellationToken
- uid: Task{Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse}
  definition: Task`1
  name: Task<DscNodeConfigurationGetResponse>
  fullName: Task<Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse>
  fullname.vb: Task(Of Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse)
  name.vb: Task(Of DscNodeConfigurationGetResponse)
  spec.csharp:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
    name: DscNodeConfigurationGetResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
    name: DscNodeConfigurationGetResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
  - name: )
    fullName: )
- uid: Task`1
  isExternal: true
  name: Task<>
  fullName: Task<>
  fullname.vb: Task(Of )
  name.vb: Task(Of )
  spec.csharp:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscNodeConfigurationListParameters
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters
- uid: Task{Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse}
  definition: Task`1
  name: Task<DscNodeConfigurationListResponse>
  fullName: Task<Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse>
  fullname.vb: Task(Of Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse)
  name.vb: Task(Of DscNodeConfigurationListResponse)
  spec.csharp:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: <
    fullName: <
  - uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
    name: DscNodeConfigurationListResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Task`1
    name: Task
    fullName: Task
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
    name: DscNodeConfigurationListResponse
    fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListResponse
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
