items:
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters
  id: DscNodeConfigurationListParameters
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters.ConfigurationName
  langs:
  - csharp
  - vb
  name: DscNodeConfigurationListParameters
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListParameters.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscNodeConfigurationListParameters
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListParameters.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe parameters supplied to the list node configuration operation.\n"
  example: []
  syntax:
    content: 'public class DscNodeConfigurationListParameters : object'
    content.vb: >-
      Public Class DscNodeConfigurationListParameters
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters.ConfigurationName
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters.ConfigurationName
  id: ConfigurationName
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters
  langs:
  - csharp
  - vb
  name: ConfigurationName
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters.ConfigurationName
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListParameters.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ConfigurationName
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListParameters.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the configuration name.\n"
  example: []
  syntax:
    content: public string ConfigurationName { get; set; }
    content.vb: Public Property ConfigurationName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters
  langs:
  - csharp
  - vb
  name: DscNodeConfigurationListParameters()
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationListParameters.DscNodeConfigurationListParameters()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListParameters.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationListParameters.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscNodeConfigurationListParameters class.\n"
  example: []
  syntax:
    content: public DscNodeConfigurationListParameters()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
