items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfiguration
  id: DscConfiguration
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  langs:
  - csharp
  - vb
  name: DscConfiguration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfiguration
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nDefinition of the configuration type.\n"
  example: []
  syntax:
    content: 'public class DscConfiguration : ResourceBase'
    content.vb: >-
      Public Class DscConfiguration
          Inherits ResourceBase
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.ResourceBase
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Name
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  id: Properties
  parent: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  langs:
  - csharp
  - vb
  name: Properties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Properties
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the configuration properties.\n"
  example: []
  syntax:
    content: public DscConfigurationProperties Properties { get; set; }
    content.vb: Public Property Properties As DscConfigurationProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  langs:
  - csharp
  - vb
  name: DscConfiguration()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration.DscConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfiguration.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscConfiguration class.\n"
  example: []
  syntax:
    content: public DscConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: ResourceBase
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Etag
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Location
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Name
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Name
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Name
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Tags
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Type
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationProperties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
