items:
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  id: DscNodeConfiguration
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.Configuration
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.CreationTime
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.LastModifiedTime
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.Name
  langs:
  - csharp
  - vb
  name: DscNodeConfiguration
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscNodeConfiguration
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nDefinition of the dsc node configuration.\n"
  example: []
  syntax:
    content: 'public class DscNodeConfiguration : ResourceBase'
    content.vb: >-
      Public Class DscNodeConfiguration
          Inherits ResourceBase
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.ResourceBase
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
  - Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.Configuration
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.Configuration
  id: Configuration
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  langs:
  - csharp
  - vb
  name: Configuration
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.Configuration
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Configuration
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the configuration of the node.\n"
  example: []
  syntax:
    content: public DscConfigurationAssociationProperty Configuration { get; set; }
    content.vb: Public Property Configuration As DscConfigurationAssociationProperty
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.CreationTime
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.CreationTime
  id: CreationTime
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  langs:
  - csharp
  - vb
  name: CreationTime
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.CreationTime
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: CreationTime
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets creation time.\n"
  example: []
  syntax:
    content: public DateTimeOffset CreationTime { get; set; }
    content.vb: Public Property CreationTime As DateTimeOffset
    parameters: []
    return:
      type: DateTimeOffset
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.LastModifiedTime
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.LastModifiedTime
  id: LastModifiedTime
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  langs:
  - csharp
  - vb
  name: LastModifiedTime
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.LastModifiedTime
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: LastModifiedTime
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the last modified time.\n"
  example: []
  syntax:
    content: public DateTimeOffset LastModifiedTime { get; set; }
    content.vb: Public Property LastModifiedTime As DateTimeOffset
    parameters: []
    return:
      type: DateTimeOffset
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.Name
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.Name
  id: Name
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
    startLine: 70
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the node configuration name.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  langs:
  - csharp
  - vb
  name: DscNodeConfiguration()
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration.DscNodeConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfiguration.cs
    startLine: 79
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscNodeConfiguration class.\n"
  example: []
  syntax:
    content: public DscNodeConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: ResourceBase
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Etag
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Etag
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Id
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Id
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Location
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Location
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Tags
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Tags
- uid: Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
  parent: Microsoft.Azure.Management.Automation.Models.ResourceBase
  isExternal: false
  name: Type
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceBase.Type
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationAssociationProperty
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
- uid: DateTimeOffset
  isExternal: true
  name: DateTimeOffset
  fullName: DateTimeOffset
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
