items:
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
  id: DscNodeConfigurationGetResponse
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse.NodeConfiguration
  langs:
  - csharp
  - vb
  name: DscNodeConfigurationGetResponse
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscNodeConfigurationGetResponse
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationGetResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe response model for the get Dsc node configuration operation.\n"
  example: []
  syntax:
    content: 'public class DscNodeConfigurationGetResponse : AzureOperationResponse'
    content.vb: >-
      Public Class DscNodeConfigurationGetResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse.NodeConfiguration
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse.NodeConfiguration
  id: NodeConfiguration
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
  langs:
  - csharp
  - vb
  name: NodeConfiguration
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse.NodeConfiguration
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: NodeConfiguration
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationGetResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets a Dsc Node Configuration.\n"
  example: []
  syntax:
    content: public DscNodeConfiguration NodeConfiguration { get; set; }
    content.vb: Public Property NodeConfiguration As DscNodeConfiguration
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse
  langs:
  - csharp
  - vb
  name: DscNodeConfigurationGetResponse()
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfigurationGetResponse.DscNodeConfigurationGetResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscNodeConfigurationGetResponse.cs
    startLine: 48
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscNodeConfigurationGetResponse\nclass.\n"
  example: []
  syntax:
    content: public DscNodeConfigurationGetResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscNodeConfiguration
  fullName: Microsoft.Azure.Management.Automation.Models.DscNodeConfiguration
