items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties
  id: DscConfigurationJobProperties
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.Configuration
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.ConfigurationName
  langs:
  - csharp
  - vb
  name: DscConfigurationJobProperties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationJobProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationJobProperties
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationJobProperties.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nDefinition of Dsc configuration job properties.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationJobProperties : JobPropertiesBase'
    content.vb: >-
      Public Class DscConfigurationJobProperties
          Inherits JobPropertiesBase
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.CreationTime
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.EndTime
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Exception
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.JobId
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.LastModifiedTime
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.LastStatusModifiedTime
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Parameters
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.StartTime
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Status
  - Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.StatusDetails
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.Configuration
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.Configuration
  id: Configuration
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties
  langs:
  - csharp
  - vb
  name: Configuration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.Configuration
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationJobProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Configuration
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationJobProperties.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the configuration.\n"
  example: []
  syntax:
    content: public DscConfigurationAssociationProperty Configuration { get; set; }
    content.vb: Public Property Configuration As DscConfigurationAssociationProperty
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.ConfigurationName
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.ConfigurationName
  id: ConfigurationName
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties
  langs:
  - csharp
  - vb
  name: ConfigurationName
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.ConfigurationName
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationJobProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ConfigurationName
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationJobProperties.cs
    startLine: 49
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the configuration name of the Dsc\nconfiguration job.\n"
  example: []
  syntax:
    content: public string ConfigurationName { get; set; }
    content.vb: Public Property ConfigurationName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties
  langs:
  - csharp
  - vb
  name: DscConfigurationJobProperties()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationJobProperties.DscConfigurationJobProperties()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationJobProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationJobProperties.cs
    startLine: 59
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscConfigurationJobProperties\nclass.\n"
  example: []
  syntax:
    content: public DscConfigurationJobProperties()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: JobPropertiesBase
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.CreationTime
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: CreationTime
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.CreationTime
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.EndTime
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: EndTime
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.EndTime
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Exception
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: Exception
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Exception
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.JobId
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: JobId
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.JobId
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.LastModifiedTime
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: LastModifiedTime
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.LastModifiedTime
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.LastStatusModifiedTime
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: LastStatusModifiedTime
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.LastStatusModifiedTime
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Parameters
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: Parameters
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Parameters
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.StartTime
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: StartTime
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.StartTime
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Status
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: Status
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.Status
- uid: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.StatusDetails
  parent: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase
  isExternal: false
  name: StatusDetails
  fullName: Microsoft.Azure.Management.Automation.Models.JobPropertiesBase.StatusDetails
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationAssociationProperty
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
