items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  id: DscConfigurationCreateOrUpdateParameters
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateParameters
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationCreateOrUpdateParameters
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe parameters supplied to the create or update configuration operation.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationCreateOrUpdateParameters : ResourceCreateOrUpdateParameterBase'
    content.vb: >-
      Public Class DscConfigurationCreateOrUpdateParameters
          Inherits ResourceCreateOrUpdateParameterBase
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Location
  - Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Name
  - Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Tags
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  id: Properties
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: Properties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.Properties
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Properties
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nRequired. Gets or sets configuration create or update properties.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateProperties Properties { get; set; }
    content.vb: Public Property Properties As DscConfigurationCreateOrUpdateProperties
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateParameters()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.DscConfigurationCreateOrUpdateParameters()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationCreateOrUpdateParameters class.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateParameters()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.#ctor(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)
  id: '#ctor(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateParameters(DscConfigurationCreateOrUpdateProperties)
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateParameters.DscConfigurationCreateOrUpdateParameters(Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateParameters.cs
    startLine: 56
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationCreateOrUpdateParameters class with required\narguments.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateParameters(DscConfigurationCreateOrUpdateProperties properties)
    content.vb: Public Sub New(properties As DscConfigurationCreateOrUpdateProperties)
    parameters:
    - id: properties
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: ResourceCreateOrUpdateParameterBase
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Location
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  isExternal: false
  name: Location
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Location
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Name
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  isExternal: false
  name: Name
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Name
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Tags
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase
  isExternal: false
  name: Tags
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCreateOrUpdateParameterBase.Tags
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationCreateOrUpdateProperties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
