items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  id: DscConfigurationCreateOrUpdateProperties
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.#ctor(Microsoft.Azure.Management.Automation.Models.ContentSource)
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Description
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.LogProgress
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.LogVerbose
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Parameters
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Source
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateProperties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationCreateOrUpdateProperties
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe properties to create or update configuration.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationCreateOrUpdateProperties : object'
    content.vb: >-
      Public Class DscConfigurationCreateOrUpdateProperties
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Description
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Description
  id: Description
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: Description
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Description
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Description
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the description of the configuration.\n"
  example: []
  syntax:
    content: public string Description { get; set; }
    content.vb: Public Property Description As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.LogProgress
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.LogProgress
  id: LogProgress
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: LogProgress
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.LogProgress
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: LogProgress
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets progress log option.\n"
  example: []
  syntax:
    content: public bool LogProgress { get; set; }
    content.vb: Public Property LogProgress As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.LogVerbose
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.LogVerbose
  id: LogVerbose
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: LogVerbose
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.LogVerbose
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: LogVerbose
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets verbose log option.\n"
  example: []
  syntax:
    content: public bool LogVerbose { get; set; }
    content.vb: Public Property LogVerbose As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Parameters
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Parameters
  id: Parameters
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: Parameters
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Parameters
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Parameters
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
    startLine: 72
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the configuration parameters.\n"
  example: []
  syntax:
    content: public IDictionary<string, DscConfigurationParameter> Parameters { get; set; }
    content.vb: Public Property Parameters As IDictionary(Of String, DscConfigurationParameter)
    parameters: []
    return:
      type: IDictionary{System.String,Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Source
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Source
  id: Source
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: Source
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.Source
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Source
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
    startLine: 83
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nRequired. Gets or sets the source.\n"
  example: []
  syntax:
    content: public ContentSource Source { get; set; }
    content.vb: Public Property Source As ContentSource
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.ContentSource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateProperties()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.DscConfigurationCreateOrUpdateProperties()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
    startLine: 93
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationCreateOrUpdateProperties class.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateProperties()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.#ctor(Microsoft.Azure.Management.Automation.Models.ContentSource)
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.#ctor(Microsoft.Azure.Management.Automation.Models.ContentSource)
  id: '#ctor(Microsoft.Azure.Management.Automation.Models.ContentSource)'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties
  langs:
  - csharp
  - vb
  name: DscConfigurationCreateOrUpdateProperties(ContentSource)
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationCreateOrUpdateProperties.DscConfigurationCreateOrUpdateProperties(Microsoft.Azure.Management.Automation.Models.ContentSource)
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationCreateOrUpdateProperties.cs
    startLine: 103
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationCreateOrUpdateProperties class with required\narguments.\n"
  example: []
  syntax:
    content: public DscConfigurationCreateOrUpdateProperties(ContentSource source)
    content.vb: Public Sub New(source As ContentSource)
    parameters:
    - id: source
      type: Microsoft.Azure.Management.Automation.Models.ContentSource
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
- uid: System.Boolean
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: IDictionary{System.String,Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter}
  definition: IDictionary`2
  name: IDictionary<String, DscConfigurationParameter>
  fullName: IDictionary<System.String, Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter>
  fullname.vb: IDictionary(Of System.String, Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter)
  name.vb: IDictionary(Of String, DscConfigurationParameter)
  spec.csharp:
  - uid: IDictionary`2
    name: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
    name: DscConfigurationParameter
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IDictionary`2
    name: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
    name: DscConfigurationParameter
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  - name: )
    fullName: )
- uid: IDictionary`2
  isExternal: true
  name: IDictionary<, >
  fullName: IDictionary<, >
  fullname.vb: IDictionary(Of , )
  name.vb: IDictionary(Of , )
  spec.csharp:
  - uid: IDictionary`2
    name: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: ', '
    fullName: ', '
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IDictionary`2
    name: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: ', '
    fullName: ', '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Automation.Models.ContentSource
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: ContentSource
  fullName: Microsoft.Azure.Management.Automation.Models.ContentSource
