### YamlMime:ManagedReference
items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
  id: DscConfigurationGetResponse
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.Configuration
  langs:
  - csharp
  - vb
  name: DscConfigurationGetResponse
  nameWithType: DscConfigurationGetResponse
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationGetResponse
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe response model for the get configuration operation.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationGetResponse : AzureOperationResponse'
    content.vb: >-
      Public Class DscConfigurationGetResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.Configuration
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.Configuration
  id: Configuration
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: DscConfigurationGetResponse.Configuration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.Configuration
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Configuration
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets a configuration.\n"
  example: []
  syntax:
    content: public DscConfiguration Configuration { get; set; }
    content.vb: Public Property Configuration As DscConfiguration
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.Configuration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse
  langs:
  - csharp
  - vb
  name: DscConfigurationGetResponse()
  nameWithType: DscConfigurationGetResponse.DscConfigurationGetResponse()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.DscConfigurationGetResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetResponse.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscConfigurationGetResponse class.\n"
  example: []
  syntax:
    content: public DscConfigurationGetResponse()
    content.vb: Public Sub New
  overload: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.Configuration*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.Configuration
  isExternal: false
  name: Configuration
  nameWithType: DscConfigurationGetResponse.Configuration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.Configuration
- uid: Microsoft.Azure.Management.Automation.Models.DscConfiguration
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfiguration
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfiguration
  nameWithType: DscConfiguration
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfiguration
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.#ctor*
  commentId: Overload:Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.#ctor
  isExternal: false
  name: DscConfigurationGetResponse
  nameWithType: DscConfigurationGetResponse.DscConfigurationGetResponse
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetResponse.DscConfigurationGetResponse
