items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  id: DscConfigurationProperties
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.JobCount
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.LogVerbose
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.Parameters
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.ProvisioningState
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.Source
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.State
  langs:
  - csharp
  - vb
  name: DscConfigurationProperties
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationProperties
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
    startLine: 32
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nDefinition of the configuration property type.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationProperties : ResourceCommonPropertiesBase'
    content.vb: >-
      Public Class DscConfigurationProperties
          Inherits ResourceCommonPropertiesBase
  inheritance:
  - System.Object
  - Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase
  inheritedMembers:
  - Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.CreationTime
  - Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.Description
  - Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.LastModifiedTime
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.JobCount
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.JobCount
  id: JobCount
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  langs:
  - csharp
  - vb
  name: JobCount
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.JobCount
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: JobCount
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
    startLine: 39
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the job count of the configuration.\n"
  example: []
  syntax:
    content: public int JobCount { get; set; }
    content.vb: Public Property JobCount As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.LogVerbose
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.LogVerbose
  id: LogVerbose
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  langs:
  - csharp
  - vb
  name: LogVerbose
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.LogVerbose
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: LogVerbose
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
    startLine: 50
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets verbose log option.\n"
  example: []
  syntax:
    content: public bool LogVerbose { get; set; }
    content.vb: Public Property LogVerbose As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.Parameters
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.Parameters
  id: Parameters
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  langs:
  - csharp
  - vb
  name: Parameters
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.Parameters
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Parameters
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
    startLine: 61
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the configuration parameters.\n"
  example: []
  syntax:
    content: public IDictionary<string, DscConfigurationParameter> Parameters { get; set; }
    content.vb: Public Property Parameters As IDictionary(Of String, DscConfigurationParameter)
    parameters: []
    return:
      type: IDictionary{System.String,Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.ProvisioningState
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.ProvisioningState
  id: ProvisioningState
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  langs:
  - csharp
  - vb
  name: ProvisioningState
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.ProvisioningState
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: ProvisioningState
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
    startLine: 72
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the provisioning state of the configuration.\n"
  example: []
  syntax:
    content: public DscConfigurationProvisioningState ProvisioningState { get; set; }
    content.vb: Public Property ProvisioningState As DscConfigurationProvisioningState
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.Source
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.Source
  id: Source
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  langs:
  - csharp
  - vb
  name: Source
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.Source
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Source
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
    startLine: 83
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the source.\n"
  example: []
  syntax:
    content: public ContentSource Source { get; set; }
    content.vb: Public Property Source As ContentSource
    parameters: []
    return:
      type: Microsoft.Azure.Management.Automation.Models.ContentSource
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.State
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.State
  id: State
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  langs:
  - csharp
  - vb
  name: State
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.State
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: State
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
    startLine: 94
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the state of the configuration.\n"
  example: []
  syntax:
    content: public string State { get; set; }
    content.vb: Public Property State As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties
  langs:
  - csharp
  - vb
  name: DscConfigurationProperties()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProperties.DscConfigurationProperties()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProperties.cs
    startLine: 103
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the DscConfigurationProperties class.\n"
  example: []
  syntax:
    content: public DscConfigurationProperties()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: ResourceCommonPropertiesBase
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.CreationTime
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase
  isExternal: false
  name: CreationTime
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.CreationTime
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.Description
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase
  isExternal: false
  name: Description
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.Description
- uid: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.LastModifiedTime
  parent: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase
  isExternal: false
  name: LastModifiedTime
  fullName: Microsoft.Azure.Management.Automation.Models.ResourceCommonPropertiesBase.LastModifiedTime
- uid: System.Int32
  isExternal: true
  name: Int32
  fullName: System.Int32
- uid: System.Boolean
  isExternal: true
  name: Boolean
  fullName: System.Boolean
- uid: IDictionary{System.String,Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter}
  definition: IDictionary`2
  name: IDictionary<String, DscConfigurationParameter>
  fullName: IDictionary<System.String, Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter>
  fullname.vb: IDictionary(Of System.String, Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter)
  name.vb: IDictionary(Of String, DscConfigurationParameter)
  spec.csharp:
  - uid: IDictionary`2
    name: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: <
    fullName: <
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
    name: DscConfigurationParameter
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IDictionary`2
    name: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    fullName: System.String
    isExternal: true
  - name: ', '
    fullName: ', '
  - uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
    name: DscConfigurationParameter
    fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationParameter
  - name: )
    fullName: )
- uid: IDictionary`2
  isExternal: true
  name: IDictionary<, >
  fullName: IDictionary<, >
  fullname.vb: IDictionary(Of , )
  name.vb: IDictionary(Of , )
  spec.csharp:
  - uid: IDictionary`2
    name: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: <
    fullName: <
  - name: 
    fullName: 
  - name: ', '
    fullName: ', '
  - name: 
    fullName: 
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: IDictionary`2
    name: IDictionary
    fullName: IDictionary
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - name: 
    fullName: 
  - name: ', '
    fullName: ', '
  - name: 
    fullName: 
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationProvisioningState
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
- uid: Microsoft.Azure.Management.Automation.Models.ContentSource
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: ContentSource
  fullName: Microsoft.Azure.Management.Automation.Models.ContentSource
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
