items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  id: DscConfigurationAssociationProperty
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty.Name
  langs:
  - csharp
  - vb
  name: DscConfigurationAssociationProperty
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationAssociationProperty.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationAssociationProperty
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationAssociationProperty.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe Dsc configuration property associated with the entity.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationAssociationProperty : object'
    content.vb: >-
      Public Class DscConfigurationAssociationProperty
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty.Name
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty.Name
  id: Name
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  langs:
  - csharp
  - vb
  name: Name
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty.Name
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationAssociationProperty.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Name
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationAssociationProperty.cs
    startLine: 36
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the name of the Dsc configuration.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty
  langs:
  - csharp
  - vb
  name: DscConfigurationAssociationProperty()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationAssociationProperty.DscConfigurationAssociationProperty()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationAssociationProperty.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationAssociationProperty.cs
    startLine: 46
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationAssociationProperty class.\n"
  example: []
  syntax:
    content: public DscConfigurationAssociationProperty()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
