items:
- uid: Microsoft.Azure.Management.Automation
  commentId: N:Microsoft.Azure.Management.Automation
  id: Microsoft.Azure.Management.Automation
  children:
  - Microsoft.Azure.Management.Automation.ActivityOperationsExtensions
  - Microsoft.Azure.Management.Automation.AgentRegistrationOperationExtensions
  - Microsoft.Azure.Management.Automation.AutomationAccountOperationsExtensions
  - Microsoft.Azure.Management.Automation.AutomationManagementClient
  - Microsoft.Azure.Management.Automation.AutomationManagementClientExtensions
  - Microsoft.Azure.Management.Automation.CertificateOperationsExtensions
  - Microsoft.Azure.Management.Automation.ConnectionOperationsExtensions
  - Microsoft.Azure.Management.Automation.ConnectionTypeOperationsExtensions
  - Microsoft.Azure.Management.Automation.CredentialOperationsExtensions
  - Microsoft.Azure.Management.Automation.DscCompilationJobOperationsExtensions
  - Microsoft.Azure.Management.Automation.DscConfigurationOperationsExtensions
  - Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions
  - Microsoft.Azure.Management.Automation.DscNodeOperationsExtensions
  - Microsoft.Azure.Management.Automation.DscNodeReportsOperationsExtensions
  - Microsoft.Azure.Management.Automation.HybridRunbookWorkerGroupOperationsExtensions
  - Microsoft.Azure.Management.Automation.IActivityOperations
  - Microsoft.Azure.Management.Automation.IAgentRegistrationOperation
  - Microsoft.Azure.Management.Automation.IAutomationAccountOperations
  - Microsoft.Azure.Management.Automation.IAutomationManagementClient
  - Microsoft.Azure.Management.Automation.ICertificateOperations
  - Microsoft.Azure.Management.Automation.IConnectionOperations
  - Microsoft.Azure.Management.Automation.IConnectionTypeOperations
  - Microsoft.Azure.Management.Automation.ICredentialOperations
  - Microsoft.Azure.Management.Automation.IDscCompilationJobOperations
  - Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  - Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
  - Microsoft.Azure.Management.Automation.IDscNodeOperations
  - Microsoft.Azure.Management.Automation.IDscNodeReportsOperations
  - Microsoft.Azure.Management.Automation.IHybridRunbookWorkerGroupOperations
  - Microsoft.Azure.Management.Automation.IJobOperations
  - Microsoft.Azure.Management.Automation.IJobScheduleOperations
  - Microsoft.Azure.Management.Automation.IJobStreamOperations
  - Microsoft.Azure.Management.Automation.IModuleOperations
  - Microsoft.Azure.Management.Automation.IRunbookDraftOperations
  - Microsoft.Azure.Management.Automation.IRunbookOperations
  - Microsoft.Azure.Management.Automation.IScheduleOperations
  - Microsoft.Azure.Management.Automation.ITestJobOperations
  - Microsoft.Azure.Management.Automation.IVariableOperations
  - Microsoft.Azure.Management.Automation.IWebhookOperations
  - Microsoft.Azure.Management.Automation.JobOperationsExtensions
  - Microsoft.Azure.Management.Automation.JobScheduleOperationsExtensions
  - Microsoft.Azure.Management.Automation.JobStreamOperationsExtensions
  - Microsoft.Azure.Management.Automation.ModuleOperationsExtensions
  - Microsoft.Azure.Management.Automation.ResponseWithSkipToken`1
  - Microsoft.Azure.Management.Automation.RunbookDraftOperationsExtensions
  - Microsoft.Azure.Management.Automation.RunbookOperationsExtensions
  - Microsoft.Azure.Management.Automation.ScheduleOperationsExtensions
  - Microsoft.Azure.Management.Automation.TestJobOperationsExtensions
  - Microsoft.Azure.Management.Automation.VariableOperationsExtensions
  - Microsoft.Azure.Management.Automation.WebhookOperationsExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.Azure.Management.Automation
  fullName: Microsoft.Azure.Management.Automation
  type: Namespace
  assemblies:
  - Microsoft.Azure.Management.Automation
references:
- uid: Microsoft.Azure.Management.Automation.ResponseWithSkipToken`1
  isExternal: false
  name: ResponseWithSkipToken<T>
  fullName: Microsoft.Azure.Management.Automation.ResponseWithSkipToken<T>
  fullname.vb: Microsoft.Azure.Management.Automation.ResponseWithSkipToken(Of T)
  name.vb: ResponseWithSkipToken(Of T)
  spec.csharp:
  - uid: Microsoft.Azure.Management.Automation.ResponseWithSkipToken`1
    name: ResponseWithSkipToken
    fullName: Microsoft.Azure.Management.Automation.ResponseWithSkipToken
  - name: <
    fullName: <
  - name: T
    fullName: T
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Azure.Management.Automation.ResponseWithSkipToken`1
    name: ResponseWithSkipToken
    fullName: Microsoft.Azure.Management.Automation.ResponseWithSkipToken
  - name: '(Of '
    fullName: '(Of '
  - name: T
    fullName: T
  - name: )
    fullName: )
- uid: Microsoft.Azure.Management.Automation.ActivityOperationsExtensions
  isExternal: false
  name: ActivityOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.ActivityOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.AgentRegistrationOperationExtensions
  isExternal: false
  name: AgentRegistrationOperationExtensions
  fullName: Microsoft.Azure.Management.Automation.AgentRegistrationOperationExtensions
- uid: Microsoft.Azure.Management.Automation.AutomationAccountOperationsExtensions
  isExternal: false
  name: AutomationAccountOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.AutomationAccountOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.AutomationManagementClient
  isExternal: false
  name: AutomationManagementClient
  fullName: Microsoft.Azure.Management.Automation.AutomationManagementClient
- uid: Microsoft.Azure.Management.Automation.AutomationManagementClientExtensions
  isExternal: false
  name: AutomationManagementClientExtensions
  fullName: Microsoft.Azure.Management.Automation.AutomationManagementClientExtensions
- uid: Microsoft.Azure.Management.Automation.CertificateOperationsExtensions
  isExternal: false
  name: CertificateOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.CertificateOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.ConnectionOperationsExtensions
  isExternal: false
  name: ConnectionOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.ConnectionOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.ConnectionTypeOperationsExtensions
  isExternal: false
  name: ConnectionTypeOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.ConnectionTypeOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.CredentialOperationsExtensions
  isExternal: false
  name: CredentialOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.CredentialOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.DscCompilationJobOperationsExtensions
  isExternal: false
  name: DscCompilationJobOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.DscCompilationJobOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.DscConfigurationOperationsExtensions
  isExternal: false
  name: DscConfigurationOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.DscConfigurationOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions
  isExternal: false
  name: DscNodeConfigurationOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.DscNodeOperationsExtensions
  isExternal: false
  name: DscNodeOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.DscNodeOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.DscNodeReportsOperationsExtensions
  isExternal: false
  name: DscNodeReportsOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.DscNodeReportsOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.HybridRunbookWorkerGroupOperationsExtensions
  isExternal: false
  name: HybridRunbookWorkerGroupOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.HybridRunbookWorkerGroupOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.IActivityOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IActivityOperations
  fullName: Microsoft.Azure.Management.Automation.IActivityOperations
- uid: Microsoft.Azure.Management.Automation.IAgentRegistrationOperation
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IAgentRegistrationOperation
  fullName: Microsoft.Azure.Management.Automation.IAgentRegistrationOperation
- uid: Microsoft.Azure.Management.Automation.IAutomationAccountOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IAutomationAccountOperations
  fullName: Microsoft.Azure.Management.Automation.IAutomationAccountOperations
- uid: Microsoft.Azure.Management.Automation.IAutomationManagementClient
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IAutomationManagementClient
  fullName: Microsoft.Azure.Management.Automation.IAutomationManagementClient
- uid: Microsoft.Azure.Management.Automation.ICertificateOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: ICertificateOperations
  fullName: Microsoft.Azure.Management.Automation.ICertificateOperations
- uid: Microsoft.Azure.Management.Automation.IConnectionOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IConnectionOperations
  fullName: Microsoft.Azure.Management.Automation.IConnectionOperations
- uid: Microsoft.Azure.Management.Automation.IConnectionTypeOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IConnectionTypeOperations
  fullName: Microsoft.Azure.Management.Automation.IConnectionTypeOperations
- uid: Microsoft.Azure.Management.Automation.ICredentialOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: ICredentialOperations
  fullName: Microsoft.Azure.Management.Automation.ICredentialOperations
- uid: Microsoft.Azure.Management.Automation.IDscCompilationJobOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IDscCompilationJobOperations
  fullName: Microsoft.Azure.Management.Automation.IDscCompilationJobOperations
- uid: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IDscConfigurationOperations
  fullName: Microsoft.Azure.Management.Automation.IDscConfigurationOperations
- uid: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IDscNodeConfigurationOperations
  fullName: Microsoft.Azure.Management.Automation.IDscNodeConfigurationOperations
- uid: Microsoft.Azure.Management.Automation.IDscNodeOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IDscNodeOperations
  fullName: Microsoft.Azure.Management.Automation.IDscNodeOperations
- uid: Microsoft.Azure.Management.Automation.IDscNodeReportsOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IDscNodeReportsOperations
  fullName: Microsoft.Azure.Management.Automation.IDscNodeReportsOperations
- uid: Microsoft.Azure.Management.Automation.IHybridRunbookWorkerGroupOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IHybridRunbookWorkerGroupOperations
  fullName: Microsoft.Azure.Management.Automation.IHybridRunbookWorkerGroupOperations
- uid: Microsoft.Azure.Management.Automation.IJobOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IJobOperations
  fullName: Microsoft.Azure.Management.Automation.IJobOperations
- uid: Microsoft.Azure.Management.Automation.IJobScheduleOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IJobScheduleOperations
  fullName: Microsoft.Azure.Management.Automation.IJobScheduleOperations
- uid: Microsoft.Azure.Management.Automation.IJobStreamOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IJobStreamOperations
  fullName: Microsoft.Azure.Management.Automation.IJobStreamOperations
- uid: Microsoft.Azure.Management.Automation.IModuleOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IModuleOperations
  fullName: Microsoft.Azure.Management.Automation.IModuleOperations
- uid: Microsoft.Azure.Management.Automation.IRunbookDraftOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IRunbookDraftOperations
  fullName: Microsoft.Azure.Management.Automation.IRunbookDraftOperations
- uid: Microsoft.Azure.Management.Automation.IRunbookOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IRunbookOperations
  fullName: Microsoft.Azure.Management.Automation.IRunbookOperations
- uid: Microsoft.Azure.Management.Automation.IScheduleOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IScheduleOperations
  fullName: Microsoft.Azure.Management.Automation.IScheduleOperations
- uid: Microsoft.Azure.Management.Automation.ITestJobOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: ITestJobOperations
  fullName: Microsoft.Azure.Management.Automation.ITestJobOperations
- uid: Microsoft.Azure.Management.Automation.IVariableOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IVariableOperations
  fullName: Microsoft.Azure.Management.Automation.IVariableOperations
- uid: Microsoft.Azure.Management.Automation.IWebhookOperations
  parent: Microsoft.Azure.Management.Automation
  isExternal: false
  name: IWebhookOperations
  fullName: Microsoft.Azure.Management.Automation.IWebhookOperations
- uid: Microsoft.Azure.Management.Automation.JobOperationsExtensions
  isExternal: false
  name: JobOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.JobOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.JobScheduleOperationsExtensions
  isExternal: false
  name: JobScheduleOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.JobScheduleOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.JobStreamOperationsExtensions
  isExternal: false
  name: JobStreamOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.JobStreamOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.ModuleOperationsExtensions
  isExternal: false
  name: ModuleOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.ModuleOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.RunbookDraftOperationsExtensions
  isExternal: false
  name: RunbookDraftOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.RunbookDraftOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.RunbookOperationsExtensions
  isExternal: false
  name: RunbookOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.RunbookOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.ScheduleOperationsExtensions
  isExternal: false
  name: ScheduleOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.ScheduleOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.TestJobOperationsExtensions
  isExternal: false
  name: TestJobOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.TestJobOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.VariableOperationsExtensions
  isExternal: false
  name: VariableOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.VariableOperationsExtensions
- uid: Microsoft.Azure.Management.Automation.WebhookOperationsExtensions
  isExternal: false
  name: WebhookOperationsExtensions
  fullName: Microsoft.Azure.Management.Automation.WebhookOperationsExtensions
- uid: Microsoft.Azure.Management.Automation
  isExternal: false
  name: Microsoft.Azure.Management.Automation
  fullName: Microsoft.Azure.Management.Automation
