items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
  id: DscConfigurationGetContentResponse
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse.#ctor
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse.Content
  langs:
  - csharp
  - vb
  name: DscConfigurationGetContentResponse
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
  type: Class
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetContentResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: DscConfigurationGetContentResponse
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetContentResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nThe response model for the get configuration operation.\n"
  example: []
  syntax:
    content: 'public class DscConfigurationGetContentResponse : AzureOperationResponse'
    content.vb: >-
      Public Class DscConfigurationGetContentResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse.Content
  commentId: P:Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse.Content
  id: Content
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
  langs:
  - csharp
  - vb
  name: Content
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse.Content
  type: Property
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetContentResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: Content
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetContentResponse.cs
    startLine: 37
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nOptional. Gets or sets a configuration content.\n"
  example: []
  syntax:
    content: public string Content { get; set; }
    content.vb: Public Property Content As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse.#ctor
  commentId: M:Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse.#ctor
  id: '#ctor'
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse
  langs:
  - csharp
  - vb
  name: DscConfigurationGetContentResponse()
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationGetContentResponse.DscConfigurationGetContentResponse()
  type: Constructor
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetContentResponse.cs
      branch: AutoRest
      repo: https://github.com/Visual-Studio-China/azure-sdk-for-net.git
    id: .ctor
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationGetContentResponse.cs
    startLine: 47
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nInitializes a new instance of the\nDscConfigurationGetContentResponse class.\n"
  example: []
  syntax:
    content: public DscConfigurationGetContentResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: System.String
  isExternal: true
  name: String
  fullName: System.String
