### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult
  id: VNetConfigScriptResult
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  children:
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult.#ctor
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult.ConfigScript
  langs:
  - csharp
  - vb
  name: VNetConfigScriptResult
  nameWithType: VNetConfigScriptResult
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult
  type: Class
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/VNetConfigScriptResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: VNetConfigScriptResult
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/VNetConfigScriptResult.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nScript that can be used to set up a VPN device.\n"
  example: []
  syntax:
    content: 'public class VNetConfigScriptResult : AzureOperationResponse'
    content.vb: >-
      Public Class VNetConfigScriptResult
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult.ConfigScript
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult.ConfigScript
  id: ConfigScript
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult
  langs:
  - csharp
  - vb
  name: ConfigScript
  nameWithType: VNetConfigScriptResult.ConfigScript
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult.ConfigScript
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/VNetConfigScriptResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ConfigScript
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/VNetConfigScriptResult.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nOptional. Gets the script.\n"
  example: []
  syntax:
    content: public string ConfigScript { get; set; }
    content.vb: Public Property ConfigScript As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult
  langs:
  - csharp
  - vb
  name: VNetConfigScriptResult()
  nameWithType: VNetConfigScriptResult.VNetConfigScriptResult()
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.VNetConfigScriptResult.VNetConfigScriptResult()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/VNetConfigScriptResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/VNetConfigScriptResult.cs
    startLine: 46
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the VNetConfigScriptResult class.\n"
  example: []
  syntax:
    content: public VNetConfigScriptResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models
  commentId: N:Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.RemoteApp.Models
  nameWithType: Microsoft.WindowsAzure.Management.RemoteApp.Models
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
