items:
- uid: Microsoft.WindowsAzure.Management.Automation
  commentId: N:Microsoft.WindowsAzure.Management.Automation
  id: Microsoft.WindowsAzure.Management.Automation
  children:
  - Microsoft.WindowsAzure.Management.Automation.ActivityOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.AutomationAccountOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.AutomationManagementClient
  - Microsoft.WindowsAzure.Management.Automation.AutomationManagementClientExtensions
  - Microsoft.WindowsAzure.Management.Automation.AutomationManagementExtensions
  - Microsoft.WindowsAzure.Management.Automation.CertificateOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.CloudServiceOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.ConnectionOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.ConnectionTypeOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.CredentialOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.IActivityOperations
  - Microsoft.WindowsAzure.Management.Automation.IAutomationAccountOperations
  - Microsoft.WindowsAzure.Management.Automation.IAutomationManagementClient
  - Microsoft.WindowsAzure.Management.Automation.ICertificateOperations
  - Microsoft.WindowsAzure.Management.Automation.ICloudServiceOperations
  - Microsoft.WindowsAzure.Management.Automation.IConnectionOperations
  - Microsoft.WindowsAzure.Management.Automation.IConnectionTypeOperations
  - Microsoft.WindowsAzure.Management.Automation.ICredentialOperations
  - Microsoft.WindowsAzure.Management.Automation.IJobOperations
  - Microsoft.WindowsAzure.Management.Automation.IJobScheduleOperations
  - Microsoft.WindowsAzure.Management.Automation.IJobStreamOperations
  - Microsoft.WindowsAzure.Management.Automation.IModuleOperations
  - Microsoft.WindowsAzure.Management.Automation.IRunbookDraftOperations
  - Microsoft.WindowsAzure.Management.Automation.IRunbookOperations
  - Microsoft.WindowsAzure.Management.Automation.IScheduleOperations
  - Microsoft.WindowsAzure.Management.Automation.ITestJobOperations
  - Microsoft.WindowsAzure.Management.Automation.IVariableOperations
  - Microsoft.WindowsAzure.Management.Automation.JobOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.JobScheduleOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.JobStreamOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.ModuleOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken`1
  - Microsoft.WindowsAzure.Management.Automation.RunbookDraftOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.RunbookOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.ScheduleOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.TestJobOperationsExtensions
  - Microsoft.WindowsAzure.Management.Automation.VariableOperationsExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.WindowsAzure.Management.Automation
  nameWithType: Microsoft.WindowsAzure.Management.Automation
  fullName: Microsoft.WindowsAzure.Management.Automation
  type: Namespace
  assemblies:
  - Microsoft.WindowsAzure.Management.Automation
references:
- uid: Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken`1
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken`1
  isExternal: false
  name: ResponseWithSkipToken<T>
  nameWithType: ResponseWithSkipToken<T>
  fullName: Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken<T>
  nameWithType.vb: ResponseWithSkipToken(Of T)
  fullname.vb: Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken(Of T)
  name.vb: ResponseWithSkipToken(Of T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken`1
    name: ResponseWithSkipToken
    nameWithType: ResponseWithSkipToken
    fullName: Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken`1
    name: ResponseWithSkipToken
    nameWithType: ResponseWithSkipToken
    fullName: Microsoft.WindowsAzure.Management.Automation.ResponseWithSkipToken
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.Automation.ActivityOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ActivityOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ActivityOperationsExtensions
  nameWithType: ActivityOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.ActivityOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.AutomationAccountOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.AutomationAccountOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: AutomationAccountOperationsExtensions
  nameWithType: AutomationAccountOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.AutomationAccountOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.AutomationManagementClient
  commentId: T:Microsoft.WindowsAzure.Management.Automation.AutomationManagementClient
  isExternal: false
  name: AutomationManagementClient
  nameWithType: AutomationManagementClient
  fullName: Microsoft.WindowsAzure.Management.Automation.AutomationManagementClient
- uid: Microsoft.WindowsAzure.Management.Automation.AutomationManagementClientExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.AutomationManagementClientExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: AutomationManagementClientExtensions
  nameWithType: AutomationManagementClientExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.AutomationManagementClientExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.CertificateOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.CertificateOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: CertificateOperationsExtensions
  nameWithType: CertificateOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.CertificateOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.CloudServiceOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.CloudServiceOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: CloudServiceOperationsExtensions
  nameWithType: CloudServiceOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.CloudServiceOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.ConnectionOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ConnectionOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ConnectionOperationsExtensions
  nameWithType: ConnectionOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.ConnectionOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.ConnectionTypeOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ConnectionTypeOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ConnectionTypeOperationsExtensions
  nameWithType: ConnectionTypeOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.ConnectionTypeOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.CredentialOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.CredentialOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: CredentialOperationsExtensions
  nameWithType: CredentialOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.CredentialOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.IActivityOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IActivityOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IActivityOperations
  nameWithType: IActivityOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IActivityOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IAutomationAccountOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IAutomationAccountOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IAutomationAccountOperations
  nameWithType: IAutomationAccountOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IAutomationAccountOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IAutomationManagementClient
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IAutomationManagementClient
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IAutomationManagementClient
  nameWithType: IAutomationManagementClient
  fullName: Microsoft.WindowsAzure.Management.Automation.IAutomationManagementClient
- uid: Microsoft.WindowsAzure.Management.Automation.ICertificateOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ICertificateOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ICertificateOperations
  nameWithType: ICertificateOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.ICertificateOperations
- uid: Microsoft.WindowsAzure.Management.Automation.ICloudServiceOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ICloudServiceOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ICloudServiceOperations
  nameWithType: ICloudServiceOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.ICloudServiceOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IConnectionOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IConnectionOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IConnectionOperations
  nameWithType: IConnectionOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IConnectionOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IConnectionTypeOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IConnectionTypeOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IConnectionTypeOperations
  nameWithType: IConnectionTypeOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IConnectionTypeOperations
- uid: Microsoft.WindowsAzure.Management.Automation.ICredentialOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ICredentialOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ICredentialOperations
  nameWithType: ICredentialOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.ICredentialOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IJobOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IJobOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IJobOperations
  nameWithType: IJobOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IJobOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IJobScheduleOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IJobScheduleOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IJobScheduleOperations
  nameWithType: IJobScheduleOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IJobScheduleOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IJobStreamOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IJobStreamOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IJobStreamOperations
  nameWithType: IJobStreamOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IJobStreamOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IModuleOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IModuleOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IModuleOperations
  nameWithType: IModuleOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IModuleOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IRunbookDraftOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IRunbookDraftOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IRunbookDraftOperations
  nameWithType: IRunbookDraftOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IRunbookDraftOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IRunbookOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IRunbookOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IRunbookOperations
  nameWithType: IRunbookOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IRunbookOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IScheduleOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IScheduleOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IScheduleOperations
  nameWithType: IScheduleOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IScheduleOperations
- uid: Microsoft.WindowsAzure.Management.Automation.ITestJobOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ITestJobOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ITestJobOperations
  nameWithType: ITestJobOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.ITestJobOperations
- uid: Microsoft.WindowsAzure.Management.Automation.IVariableOperations
  commentId: T:Microsoft.WindowsAzure.Management.Automation.IVariableOperations
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: IVariableOperations
  nameWithType: IVariableOperations
  fullName: Microsoft.WindowsAzure.Management.Automation.IVariableOperations
- uid: Microsoft.WindowsAzure.Management.Automation.JobOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.JobOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: JobOperationsExtensions
  nameWithType: JobOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.JobOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.JobScheduleOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.JobScheduleOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: JobScheduleOperationsExtensions
  nameWithType: JobScheduleOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.JobScheduleOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.JobStreamOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.JobStreamOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: JobStreamOperationsExtensions
  nameWithType: JobStreamOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.JobStreamOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.ModuleOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ModuleOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ModuleOperationsExtensions
  nameWithType: ModuleOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.ModuleOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.RunbookDraftOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.RunbookDraftOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: RunbookDraftOperationsExtensions
  nameWithType: RunbookDraftOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.RunbookDraftOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.RunbookOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.RunbookOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: RunbookOperationsExtensions
  nameWithType: RunbookOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.RunbookOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.ScheduleOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.ScheduleOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: ScheduleOperationsExtensions
  nameWithType: ScheduleOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.ScheduleOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.TestJobOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.TestJobOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: TestJobOperationsExtensions
  nameWithType: TestJobOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.TestJobOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.VariableOperationsExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.VariableOperationsExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: VariableOperationsExtensions
  nameWithType: VariableOperationsExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.VariableOperationsExtensions
- uid: Microsoft.WindowsAzure.Management.Automation.AutomationManagementExtensions
  commentId: T:Microsoft.WindowsAzure.Management.Automation.AutomationManagementExtensions
  parent: Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: AutomationManagementExtensions
  nameWithType: AutomationManagementExtensions
  fullName: Microsoft.WindowsAzure.Management.Automation.AutomationManagementExtensions
- uid: Microsoft.WindowsAzure.Management.Automation
  commentId: N:Microsoft.WindowsAzure.Management.Automation
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Automation
  nameWithType: Microsoft.WindowsAzure.Management.Automation
  fullName: Microsoft.WindowsAzure.Management.Automation
