items:
- uid: Microsoft.WindowsAzure.Management.Configuration.Data
  commentId: N:Microsoft.WindowsAzure.Management.Configuration.Data
  id: Microsoft.WindowsAzure.Management.Configuration.Data
  children:
  - Microsoft.WindowsAzure.Management.Configuration.Data.AzureHDInsightClusterConfiguration
  - Microsoft.WindowsAzure.Management.Configuration.Data.ComponentSettingAddress
  - Microsoft.WindowsAzure.Management.Configuration.Data.ConfigurationPropertyCollection
  - Microsoft.WindowsAzure.Management.Configuration.Data.CoreSiteConfigurationCollection
  - Microsoft.WindowsAzure.Management.Configuration.Data.HdfsSiteConfigurationCollection
  - Microsoft.WindowsAzure.Management.Configuration.Data.HiveSiteConfigurationCollection
  - Microsoft.WindowsAzure.Management.Configuration.Data.MapReduceSiteConfigurationCollection
  - Microsoft.WindowsAzure.Management.Configuration.Data.OozieSiteConfigurationCollection
  - Microsoft.WindowsAzure.Management.Configuration.Data.YarnSiteConfigurationCollection
  langs:
  - csharp
  - vb
  name: Microsoft.WindowsAzure.Management.Configuration.Data
  nameWithType: Microsoft.WindowsAzure.Management.Configuration.Data
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data
  type: Namespace
  assemblies:
  - Microsoft.WindowsAzure.Management.Configuration
references:
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.AzureHDInsightClusterConfiguration
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.AzureHDInsightClusterConfiguration
  isExternal: false
  name: AzureHDInsightClusterConfiguration
  nameWithType: AzureHDInsightClusterConfiguration
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.AzureHDInsightClusterConfiguration
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.ComponentSettingAddress
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.ComponentSettingAddress
  isExternal: false
  name: ComponentSettingAddress
  nameWithType: ComponentSettingAddress
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.ComponentSettingAddress
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.ConfigurationPropertyCollection
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.ConfigurationPropertyCollection
  parent: Microsoft.WindowsAzure.Management.Configuration.Data
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.ConfigurationPropertyCollection
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.MapReduceSiteConfigurationCollection
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.MapReduceSiteConfigurationCollection
  parent: Microsoft.WindowsAzure.Management.Configuration.Data
  isExternal: false
  name: MapReduceSiteConfigurationCollection
  nameWithType: MapReduceSiteConfigurationCollection
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.MapReduceSiteConfigurationCollection
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.OozieSiteConfigurationCollection
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.OozieSiteConfigurationCollection
  parent: Microsoft.WindowsAzure.Management.Configuration.Data
  isExternal: false
  name: OozieSiteConfigurationCollection
  nameWithType: OozieSiteConfigurationCollection
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.OozieSiteConfigurationCollection
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.HiveSiteConfigurationCollection
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.HiveSiteConfigurationCollection
  parent: Microsoft.WindowsAzure.Management.Configuration.Data
  isExternal: false
  name: HiveSiteConfigurationCollection
  nameWithType: HiveSiteConfigurationCollection
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.HiveSiteConfigurationCollection
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.HdfsSiteConfigurationCollection
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.HdfsSiteConfigurationCollection
  parent: Microsoft.WindowsAzure.Management.Configuration.Data
  isExternal: false
  name: HdfsSiteConfigurationCollection
  nameWithType: HdfsSiteConfigurationCollection
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.HdfsSiteConfigurationCollection
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.CoreSiteConfigurationCollection
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.CoreSiteConfigurationCollection
  parent: Microsoft.WindowsAzure.Management.Configuration.Data
  isExternal: false
  name: CoreSiteConfigurationCollection
  nameWithType: CoreSiteConfigurationCollection
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.CoreSiteConfigurationCollection
- uid: Microsoft.WindowsAzure.Management.Configuration.Data.YarnSiteConfigurationCollection
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.Data.YarnSiteConfigurationCollection
  parent: Microsoft.WindowsAzure.Management.Configuration.Data
  isExternal: false
  name: YarnSiteConfigurationCollection
  nameWithType: YarnSiteConfigurationCollection
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data.YarnSiteConfigurationCollection
- uid: Microsoft.WindowsAzure.Management.Configuration.Data
  commentId: N:Microsoft.WindowsAzure.Management.Configuration.Data
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Configuration.Data
  nameWithType: Microsoft.WindowsAzure.Management.Configuration.Data
  fullName: Microsoft.WindowsAzure.Management.Configuration.Data
