items:
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  id: DeploymentUpgradeMode
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  children:
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Auto
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Manual
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Simultaneous
  langs:
  - csharp
  - vb
  name: DeploymentUpgradeMode
  nameWithType: DeploymentUpgradeMode
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentUpgradeMode.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: DeploymentUpgradeMode
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentUpgradeMode.cs
    startLine: 26
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: 'public enum DeploymentUpgradeMode : int'
    content.vb: Public Enum DeploymentUpgradeMode As Integer
  extensionMethods:
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Auto
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Auto
  id: Auto
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  langs:
  - csharp
  - vb
  name: Auto
  nameWithType: DeploymentUpgradeMode.Auto
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Auto
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentUpgradeMode.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Auto
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentUpgradeMode.cs
    startLine: 28
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Auto = null
    content.vb: Auto = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Manual
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Manual
  id: Manual
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  langs:
  - csharp
  - vb
  name: Manual
  nameWithType: DeploymentUpgradeMode.Manual
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Manual
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentUpgradeMode.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Manual
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentUpgradeMode.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Manual = null
    content.vb: Manual = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Simultaneous
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Simultaneous
  id: Simultaneous
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  langs:
  - csharp
  - vb
  name: Simultaneous
  nameWithType: DeploymentUpgradeMode.Simultaneous
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Simultaneous
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentUpgradeMode.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Simultaneous
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentUpgradeMode.cs
    startLine: 32
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Simultaneous = null
    content.vb: Simultaneous = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.WindowsAzure.Management.Compute.Models
  commentId: N:Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Compute.Models
  nameWithType: Microsoft.WindowsAzure.Management.Compute.Models
  fullName: Microsoft.WindowsAzure.Management.Compute.Models
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<DeploymentUpgradeMode>()
  nameWithType: ObjectExtensions.MakeEnumeration<DeploymentUpgradeMode>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of DeploymentUpgradeMode)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode)()
  name.vb: MakeEnumeration(Of DeploymentUpgradeMode)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<DeploymentUpgradeMode>
    nameWithType: ObjectExtensions.MakeEnumeration<DeploymentUpgradeMode>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of DeploymentUpgradeMode)
    nameWithType: ObjectExtensions.MakeEnumeration(Of DeploymentUpgradeMode)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: DeploymentUpgradeMode
  nameWithType: DeploymentUpgradeMode
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentUpgradeMode
