items:
- uid: Microsoft.Azure.Management.Resources.Models.DeploymentMode
  commentId: T:Microsoft.Azure.Management.Resources.Models.DeploymentMode
  id: DeploymentMode
  parent: Microsoft.Azure.Management.Resources.Models
  children:
  - Microsoft.Azure.Management.Resources.Models.DeploymentMode.Complete
  - Microsoft.Azure.Management.Resources.Models.DeploymentMode.Incremental
  langs:
  - csharp
  - vb
  name: DeploymentMode
  nameWithType: DeploymentMode
  fullName: Microsoft.Azure.Management.Resources.Models.DeploymentMode
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/Resource/ResourceManagement/Generated/Models/DeploymentMode.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: DeploymentMode
    path: src/ResourceManagement/Resource/ResourceManagement/Generated/Models/DeploymentMode.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.ResourceManager
  namespace: Microsoft.Azure.Management.Resources.Models
  summary: "\nSpecifies the deployment type for the deployment operations.\n"
  example: []
  syntax:
    content: 'public enum DeploymentMode : int'
    content.vb: Public Enum DeploymentMode As Integer
  extensionMethods:
  - Microsoft.Azure.Management.Resources.Models.DeploymentMode.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.Resources.Models.DeploymentMode.Incremental
  commentId: F:Microsoft.Azure.Management.Resources.Models.DeploymentMode.Incremental
  id: Incremental
  parent: Microsoft.Azure.Management.Resources.Models.DeploymentMode
  langs:
  - csharp
  - vb
  name: Incremental
  nameWithType: DeploymentMode.Incremental
  fullName: Microsoft.Azure.Management.Resources.Models.DeploymentMode.Incremental
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Resource/ResourceManagement/Generated/Models/DeploymentMode.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Incremental
    path: src/ResourceManagement/Resource/ResourceManagement/Generated/Models/DeploymentMode.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.ResourceManager
  namespace: Microsoft.Azure.Management.Resources.Models
  syntax:
    content: Incremental = null
    content.vb: Incremental = Nothing
    return:
      type: Microsoft.Azure.Management.Resources.Models.DeploymentMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Azure.Management.Resources.Models.DeploymentMode.Complete
  commentId: F:Microsoft.Azure.Management.Resources.Models.DeploymentMode.Complete
  id: Complete
  parent: Microsoft.Azure.Management.Resources.Models.DeploymentMode
  langs:
  - csharp
  - vb
  name: Complete
  nameWithType: DeploymentMode.Complete
  fullName: Microsoft.Azure.Management.Resources.Models.DeploymentMode.Complete
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Resource/ResourceManagement/Generated/Models/DeploymentMode.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Complete
    path: src/ResourceManagement/Resource/ResourceManagement/Generated/Models/DeploymentMode.cs
    startLine: 33
  assemblies:
  - Microsoft.Azure.ResourceManager
  namespace: Microsoft.Azure.Management.Resources.Models
  syntax:
    content: Complete = null
    content.vb: Complete = Nothing
    return:
      type: Microsoft.Azure.Management.Resources.Models.DeploymentMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.Resources.Models
  commentId: N:Microsoft.Azure.Management.Resources.Models
  isExternal: false
  name: Microsoft.Azure.Management.Resources.Models
  nameWithType: Microsoft.Azure.Management.Resources.Models
  fullName: Microsoft.Azure.Management.Resources.Models
- uid: Microsoft.Azure.Management.Resources.Models.DeploymentMode.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<DeploymentMode>()
  nameWithType: ObjectExtensions.MakeEnumeration<DeploymentMode>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Azure.Management.Resources.Models.DeploymentMode>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of DeploymentMode)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Azure.Management.Resources.Models.DeploymentMode)()
  name.vb: MakeEnumeration(Of DeploymentMode)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<DeploymentMode>
    nameWithType: ObjectExtensions.MakeEnumeration<DeploymentMode>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Azure.Management.Resources.Models.DeploymentMode>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of DeploymentMode)
    nameWithType: ObjectExtensions.MakeEnumeration(Of DeploymentMode)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Azure.Management.Resources.Models.DeploymentMode)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.Azure.Management.Resources.Models.DeploymentMode
  commentId: T:Microsoft.Azure.Management.Resources.Models.DeploymentMode
  parent: Microsoft.Azure.Management.Resources.Models
  isExternal: false
  name: DeploymentMode
  nameWithType: DeploymentMode
  fullName: Microsoft.Azure.Management.Resources.Models.DeploymentMode
