items:
- uid: Microsoft.Hadoop.Client.ApplicationAttemptState
  commentId: T:Microsoft.Hadoop.Client.ApplicationAttemptState
  id: ApplicationAttemptState
  parent: Microsoft.Hadoop.Client
  children:
  - Microsoft.Hadoop.Client.ApplicationAttemptState.Failed
  - Microsoft.Hadoop.Client.ApplicationAttemptState.Finished
  - Microsoft.Hadoop.Client.ApplicationAttemptState.Killed
  - Microsoft.Hadoop.Client.ApplicationAttemptState.Unknown
  langs:
  - csharp
  - vb
  name: ApplicationAttemptState
  nameWithType: ApplicationAttemptState
  fullName: Microsoft.Hadoop.Client.ApplicationAttemptState
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: ApplicationAttemptState
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 77
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nEnum for the possible application attempt states.\n"
  example: []
  syntax:
    content: 'public enum ApplicationAttemptState : int'
    content.vb: Public Enum ApplicationAttemptState As Integer
  extensionMethods:
  - Microsoft.Hadoop.Client.ApplicationAttemptState.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Hadoop.Client.ApplicationAttemptState.Unknown
  commentId: F:Microsoft.Hadoop.Client.ApplicationAttemptState.Unknown
  id: Unknown
  parent: Microsoft.Hadoop.Client.ApplicationAttemptState
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: ApplicationAttemptState.Unknown
  fullName: Microsoft.Hadoop.Client.ApplicationAttemptState.Unknown
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Unknown
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 82
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that application attempt state is not known.\n"
  example: []
  syntax:
    content: Unknown = 0
    return:
      type: Microsoft.Hadoop.Client.ApplicationAttemptState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationAttemptState.Finished
  commentId: F:Microsoft.Hadoop.Client.ApplicationAttemptState.Finished
  id: Finished
  parent: Microsoft.Hadoop.Client.ApplicationAttemptState
  langs:
  - csharp
  - vb
  name: Finished
  nameWithType: ApplicationAttemptState.Finished
  fullName: Microsoft.Hadoop.Client.ApplicationAttemptState.Finished
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Finished
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 87
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application attempt has finished.\n"
  example: []
  syntax:
    content: Finished = 1
    return:
      type: Microsoft.Hadoop.Client.ApplicationAttemptState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationAttemptState.Failed
  commentId: F:Microsoft.Hadoop.Client.ApplicationAttemptState.Failed
  id: Failed
  parent: Microsoft.Hadoop.Client.ApplicationAttemptState
  langs:
  - csharp
  - vb
  name: Failed
  nameWithType: ApplicationAttemptState.Failed
  fullName: Microsoft.Hadoop.Client.ApplicationAttemptState.Failed
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Failed
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 92
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application has failed.\n"
  example: []
  syntax:
    content: Failed = 2
    return:
      type: Microsoft.Hadoop.Client.ApplicationAttemptState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationAttemptState.Killed
  commentId: F:Microsoft.Hadoop.Client.ApplicationAttemptState.Killed
  id: Killed
  parent: Microsoft.Hadoop.Client.ApplicationAttemptState
  langs:
  - csharp
  - vb
  name: Killed
  nameWithType: ApplicationAttemptState.Killed
  fullName: Microsoft.Hadoop.Client.ApplicationAttemptState.Killed
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Killed
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 97
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application was killed.\n"
  example: []
  syntax:
    content: Killed = 3
    return:
      type: Microsoft.Hadoop.Client.ApplicationAttemptState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Hadoop.Client
  commentId: N:Microsoft.Hadoop.Client
  isExternal: false
  name: Microsoft.Hadoop.Client
  nameWithType: Microsoft.Hadoop.Client
  fullName: Microsoft.Hadoop.Client
- uid: Microsoft.Hadoop.Client.ApplicationAttemptState.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<ApplicationAttemptState>()
  nameWithType: ObjectExtensions.MakeEnumeration<ApplicationAttemptState>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Hadoop.Client.ApplicationAttemptState>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of ApplicationAttemptState)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Hadoop.Client.ApplicationAttemptState)()
  name.vb: MakeEnumeration(Of ApplicationAttemptState)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<ApplicationAttemptState>
    nameWithType: ObjectExtensions.MakeEnumeration<ApplicationAttemptState>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Hadoop.Client.ApplicationAttemptState>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of ApplicationAttemptState)
    nameWithType: ObjectExtensions.MakeEnumeration(Of ApplicationAttemptState)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Hadoop.Client.ApplicationAttemptState)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.Hadoop.Client.ApplicationAttemptState
  commentId: T:Microsoft.Hadoop.Client.ApplicationAttemptState
  parent: Microsoft.Hadoop.Client
  isExternal: false
  name: ApplicationAttemptState
  nameWithType: ApplicationAttemptState
  fullName: Microsoft.Hadoop.Client.ApplicationAttemptState
