### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration
  id: FrontendIPConfiguration
  parent: Microsoft.WindowsAzure.Management.Network.Models
  children:
  - Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.#ctor
  - Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.Name
  - Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.StaticIPAddress
  - Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.Type
  langs:
  - csharp
  - vb
  name: FrontendIPConfiguration
  nameWithType: FrontendIPConfiguration
  fullName: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: FrontendIPConfiguration
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nFrontend IP\n"
  example: []
  syntax:
    content: public class FrontendIPConfiguration
    content.vb: Public Class FrontendIPConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.Name
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.Name
  id: Name
  parent: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: FrontendIPConfiguration.Name
  fullName: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.Name
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
    startLine: 36
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Name of the Frontend IP.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.StaticIPAddress
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.StaticIPAddress
  id: StaticIPAddress
  parent: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: StaticIPAddress
  nameWithType: FrontendIPConfiguration.StaticIPAddress
  fullName: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.StaticIPAddress
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: StaticIPAddress
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
    startLine: 47
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Frontend IP address.\n"
  example: []
  syntax:
    content: public string StaticIPAddress { get; set; }
    content.vb: Public Property StaticIPAddress As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.Type
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.Type
  id: Type
  parent: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: FrontendIPConfiguration.Type
  fullName: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.Type
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Type
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
    startLine: 58
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Type of the Frontend IP.\n"
  example: []
  syntax:
    content: public string Type { get; set; }
    content.vb: Public Property Type As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration
  langs:
  - csharp
  - vb
  name: FrontendIPConfiguration()
  nameWithType: FrontendIPConfiguration.FrontendIPConfiguration()
  fullName: Microsoft.WindowsAzure.Management.Network.Models.FrontendIPConfiguration.FrontendIPConfiguration()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/FrontendIPConfiguration.cs
    startLine: 67
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nInitializes a new instance of the FrontendIPConfiguration class.\n"
  example: []
  syntax:
    content: public FrontendIPConfiguration()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Network.Models
  commentId: N:Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Network.Models
  nameWithType: Microsoft.WindowsAzure.Management.Network.Models
  fullName: Microsoft.WindowsAzure.Management.Network.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
