### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate
  id: ApplicationGatewayGetCertificate
  parent: Microsoft.WindowsAzure.Management.Network.Models
  children:
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.#ctor
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.Data
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.Name
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.State
  langs:
  - csharp
  - vb
  name: ApplicationGatewayGetCertificate
  nameWithType: ApplicationGatewayGetCertificate
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayGetCertificate
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nResponse of GetApplicationGatewayCertificate request.\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayGetCertificate : AzureOperationResponse'
    content.vb: >-
      Public Class ApplicationGatewayGetCertificate
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.Data
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.Data
  id: Data
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: ApplicationGatewayGetCertificate.Data
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.Data
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Data
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Certificate file data.\n"
  example: []
  syntax:
    content: public string Data { get; set; }
    content.vb: Public Property Data As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.Name
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.Name
  id: Name
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ApplicationGatewayGetCertificate.Name
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.Name
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
    startLine: 48
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Certificate name.\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.State
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.State
  id: State
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate
  langs:
  - csharp
  - vb
  name: State
  nameWithType: ApplicationGatewayGetCertificate.State
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.State
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: State
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
    startLine: 59
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Certificate provisioning state.\n"
  example: []
  syntax:
    content: public string State { get; set; }
    content.vb: Public Property State As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate
  langs:
  - csharp
  - vb
  name: ApplicationGatewayGetCertificate()
  nameWithType: ApplicationGatewayGetCertificate.ApplicationGatewayGetCertificate()
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetCertificate.ApplicationGatewayGetCertificate()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetCertificate.cs
    startLine: 69
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nInitializes a new instance of the ApplicationGatewayGetCertificate\nclass.\n"
  example: []
  syntax:
    content: public ApplicationGatewayGetCertificate()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Network.Models
  commentId: N:Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Network.Models
  nameWithType: Microsoft.WindowsAzure.Management.Network.Models
  fullName: Microsoft.WindowsAzure.Management.Network.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
