items:
- uid: Microsoft.Hadoop.Client.ApplicationContainerState
  commentId: T:Microsoft.Hadoop.Client.ApplicationContainerState
  id: ApplicationContainerState
  parent: Microsoft.Hadoop.Client
  children:
  - Microsoft.Hadoop.Client.ApplicationContainerState.Complete
  - Microsoft.Hadoop.Client.ApplicationContainerState.Unknown
  langs:
  - csharp
  - vb
  name: ApplicationContainerState
  nameWithType: ApplicationContainerState
  fullName: Microsoft.Hadoop.Client.ApplicationContainerState
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: ApplicationContainerState
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 103
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nEnum for the possible container states.\n"
  example: []
  syntax:
    content: 'public enum ApplicationContainerState : int'
    content.vb: Public Enum ApplicationContainerState As Integer
  extensionMethods:
  - Microsoft.Hadoop.Client.ApplicationContainerState.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Hadoop.Client.ApplicationContainerState.Unknown
  commentId: F:Microsoft.Hadoop.Client.ApplicationContainerState.Unknown
  id: Unknown
  parent: Microsoft.Hadoop.Client.ApplicationContainerState
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: ApplicationContainerState.Unknown
  fullName: Microsoft.Hadoop.Client.ApplicationContainerState.Unknown
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Unknown
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 108
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that container state is not known.\n"
  example: []
  syntax:
    content: Unknown = 0
    return:
      type: Microsoft.Hadoop.Client.ApplicationContainerState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationContainerState.Complete
  commentId: F:Microsoft.Hadoop.Client.ApplicationContainerState.Complete
  id: Complete
  parent: Microsoft.Hadoop.Client.ApplicationContainerState
  langs:
  - csharp
  - vb
  name: Complete
  nameWithType: ApplicationContainerState.Complete
  fullName: Microsoft.Hadoop.Client.ApplicationContainerState.Complete
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Complete
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 113
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the container has completed.\n"
  example: []
  syntax:
    content: Complete = 1
    return:
      type: Microsoft.Hadoop.Client.ApplicationContainerState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Hadoop.Client
  commentId: N:Microsoft.Hadoop.Client
  isExternal: false
  name: Microsoft.Hadoop.Client
  nameWithType: Microsoft.Hadoop.Client
  fullName: Microsoft.Hadoop.Client
- uid: Microsoft.Hadoop.Client.ApplicationContainerState.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<ApplicationContainerState>()
  nameWithType: ObjectExtensions.MakeEnumeration<ApplicationContainerState>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Hadoop.Client.ApplicationContainerState>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of ApplicationContainerState)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Hadoop.Client.ApplicationContainerState)()
  name.vb: MakeEnumeration(Of ApplicationContainerState)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<ApplicationContainerState>
    nameWithType: ObjectExtensions.MakeEnumeration<ApplicationContainerState>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Hadoop.Client.ApplicationContainerState>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of ApplicationContainerState)
    nameWithType: ObjectExtensions.MakeEnumeration(Of ApplicationContainerState)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Hadoop.Client.ApplicationContainerState)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.Hadoop.Client.ApplicationContainerState
  commentId: T:Microsoft.Hadoop.Client.ApplicationContainerState
  parent: Microsoft.Hadoop.Client
  isExternal: false
  name: ApplicationContainerState
  nameWithType: ApplicationContainerState
  fullName: Microsoft.Hadoop.Client.ApplicationContainerState
