items:
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  id: DeploymentStatus
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  children:
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Deleting
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Deploying
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Running
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.RunningTransitioning
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Starting
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Suspended
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.SuspendedTransitioning
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Suspending
  langs:
  - csharp
  - vb
  name: DeploymentStatus
  nameWithType: DeploymentStatus
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: DeploymentStatus
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\nThe status of the deployment.\n"
  example: []
  syntax:
    content: 'public enum DeploymentStatus : int'
    content.vb: Public Enum DeploymentStatus As Integer
  extensionMethods:
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Running
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Running
  id: Running
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  langs:
  - csharp
  - vb
  name: Running
  nameWithType: DeploymentStatus.Running
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Running
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Running
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Running = null
    content.vb: Running = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Suspended
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Suspended
  id: Suspended
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  langs:
  - csharp
  - vb
  name: Suspended
  nameWithType: DeploymentStatus.Suspended
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Suspended
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Suspended
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 33
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Suspended = null
    content.vb: Suspended = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.RunningTransitioning
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.RunningTransitioning
  id: RunningTransitioning
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  langs:
  - csharp
  - vb
  name: RunningTransitioning
  nameWithType: DeploymentStatus.RunningTransitioning
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.RunningTransitioning
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: RunningTransitioning
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 35
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: RunningTransitioning = null
    content.vb: RunningTransitioning = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.SuspendedTransitioning
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.SuspendedTransitioning
  id: SuspendedTransitioning
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  langs:
  - csharp
  - vb
  name: SuspendedTransitioning
  nameWithType: DeploymentStatus.SuspendedTransitioning
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.SuspendedTransitioning
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: SuspendedTransitioning
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: SuspendedTransitioning = null
    content.vb: SuspendedTransitioning = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Starting
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Starting
  id: Starting
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  langs:
  - csharp
  - vb
  name: Starting
  nameWithType: DeploymentStatus.Starting
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Starting
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Starting
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 39
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Starting = null
    content.vb: Starting = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Suspending
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Suspending
  id: Suspending
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  langs:
  - csharp
  - vb
  name: Suspending
  nameWithType: DeploymentStatus.Suspending
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Suspending
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Suspending
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 41
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Suspending = null
    content.vb: Suspending = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Deploying
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Deploying
  id: Deploying
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  langs:
  - csharp
  - vb
  name: Deploying
  nameWithType: DeploymentStatus.Deploying
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Deploying
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Deploying
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 43
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Deploying = null
    content.vb: Deploying = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Deleting
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Deleting
  id: Deleting
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  langs:
  - csharp
  - vb
  name: Deleting
  nameWithType: DeploymentStatus.Deleting
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Deleting
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Deleting
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentStatus.cs
    startLine: 45
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Deleting = null
    content.vb: Deleting = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.WindowsAzure.Management.Compute.Models
  commentId: N:Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Compute.Models
  nameWithType: Microsoft.WindowsAzure.Management.Compute.Models
  fullName: Microsoft.WindowsAzure.Management.Compute.Models
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<DeploymentStatus>()
  nameWithType: ObjectExtensions.MakeEnumeration<DeploymentStatus>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of DeploymentStatus)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus)()
  name.vb: MakeEnumeration(Of DeploymentStatus)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<DeploymentStatus>
    nameWithType: ObjectExtensions.MakeEnumeration<DeploymentStatus>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of DeploymentStatus)
    nameWithType: ObjectExtensions.MakeEnumeration(Of DeploymentStatus)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: DeploymentStatus
  nameWithType: DeploymentStatus
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentStatus
