items:
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  id: DeploymentSlot
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  children:
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Production
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Staging
  langs:
  - csharp
  - vb
  name: DeploymentSlot
  nameWithType: DeploymentSlot
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentSlot.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: DeploymentSlot
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentSlot.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  summary: "\nThe deployment environment in which this deployment is running.\n"
  example: []
  syntax:
    content: 'public enum DeploymentSlot : int'
    content.vb: Public Enum DeploymentSlot As Integer
  extensionMethods:
  - Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Staging
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Staging
  id: Staging
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  langs:
  - csharp
  - vb
  name: Staging
  nameWithType: DeploymentSlot.Staging
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Staging
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentSlot.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Staging
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentSlot.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Staging = null
    content.vb: Staging = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Production
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Production
  id: Production
  parent: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  langs:
  - csharp
  - vb
  name: Production
  nameWithType: DeploymentSlot.Production
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Production
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentSlot.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Production
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/DeploymentSlot.cs
    startLine: 33
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Production = null
    content.vb: Production = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.WindowsAzure.Management.Compute.Models
  commentId: N:Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Compute.Models
  nameWithType: Microsoft.WindowsAzure.Management.Compute.Models
  fullName: Microsoft.WindowsAzure.Management.Compute.Models
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<DeploymentSlot>()
  nameWithType: ObjectExtensions.MakeEnumeration<DeploymentSlot>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of DeploymentSlot)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot)()
  name.vb: MakeEnumeration(Of DeploymentSlot)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<DeploymentSlot>
    nameWithType: ObjectExtensions.MakeEnumeration<DeploymentSlot>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of DeploymentSlot)
    nameWithType: ObjectExtensions.MakeEnumeration(Of DeploymentSlot)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: DeploymentSlot
  nameWithType: DeploymentSlot
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.DeploymentSlot
