items:
- uid: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  id: UpdatedDeploymentStatus
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  children:
  - Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Running
  - Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Suspended
  langs:
  - csharp
  - vb
  name: UpdatedDeploymentStatus
  nameWithType: UpdatedDeploymentStatus
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/UpdatedDeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: UpdatedDeploymentStatus
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/UpdatedDeploymentStatus.cs
    startLine: 26
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: 'public enum UpdatedDeploymentStatus : int'
    content.vb: Public Enum UpdatedDeploymentStatus As Integer
  extensionMethods:
  - Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Running
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Running
  id: Running
  parent: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  langs:
  - csharp
  - vb
  name: Running
  nameWithType: UpdatedDeploymentStatus.Running
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Running
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/UpdatedDeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Running
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/UpdatedDeploymentStatus.cs
    startLine: 28
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Running = null
    content.vb: Running = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Suspended
  commentId: F:Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Suspended
  id: Suspended
  parent: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  langs:
  - csharp
  - vb
  name: Suspended
  nameWithType: UpdatedDeploymentStatus.Suspended
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Suspended
  type: Field
  source:
    remote:
      path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/UpdatedDeploymentStatus.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Suspended
    path: src/ServiceManagement/Compute/ComputeManagement/Generated/Models/UpdatedDeploymentStatus.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.Compute
  namespace: Microsoft.WindowsAzure.Management.Compute.Models
  syntax:
    content: Suspended = null
    content.vb: Suspended = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.WindowsAzure.Management.Compute.Models
  commentId: N:Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Compute.Models
  nameWithType: Microsoft.WindowsAzure.Management.Compute.Models
  fullName: Microsoft.WindowsAzure.Management.Compute.Models
- uid: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<UpdatedDeploymentStatus>()
  nameWithType: ObjectExtensions.MakeEnumeration<UpdatedDeploymentStatus>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of UpdatedDeploymentStatus)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus)()
  name.vb: MakeEnumeration(Of UpdatedDeploymentStatus)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<UpdatedDeploymentStatus>
    nameWithType: ObjectExtensions.MakeEnumeration<UpdatedDeploymentStatus>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of UpdatedDeploymentStatus)
    nameWithType: ObjectExtensions.MakeEnumeration(Of UpdatedDeploymentStatus)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  commentId: T:Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
  parent: Microsoft.WindowsAzure.Management.Compute.Models
  isExternal: false
  name: UpdatedDeploymentStatus
  nameWithType: UpdatedDeploymentStatus
  fullName: Microsoft.WindowsAzure.Management.Compute.Models.UpdatedDeploymentStatus
