### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings
  commentId: T:Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings
  id: SubscriptionIntrinsicSettings
  parent: Microsoft.WindowsAzure.Management.Automation.Models
  children:
  - Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings.#ctor
  - Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings.SubscriptionPlan
  langs:
  - csharp
  - vb
  name: SubscriptionIntrinsicSettings
  nameWithType: SubscriptionIntrinsicSettings
  fullName: Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/SubscriptionIntrinsicSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: SubscriptionIntrinsicSettings
    path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/SubscriptionIntrinsicSettings.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.Automation
  namespace: Microsoft.WindowsAzure.Management.Automation.Models
  summary: "\nAn automation resource intrinsic settings.\n"
  example: []
  syntax:
    content: public class SubscriptionIntrinsicSettings
    content.vb: Public Class SubscriptionIntrinsicSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings.SubscriptionPlan
  commentId: P:Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings.SubscriptionPlan
  id: SubscriptionPlan
  parent: Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings
  langs:
  - csharp
  - vb
  name: SubscriptionPlan
  nameWithType: SubscriptionIntrinsicSettings.SubscriptionPlan
  fullName: Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings.SubscriptionPlan
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/SubscriptionIntrinsicSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: SubscriptionPlan
    path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/SubscriptionIntrinsicSettings.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.Automation
  namespace: Microsoft.WindowsAzure.Management.Automation.Models
  summary: "\nOptional. Gets or sets the plan for this item as selected by the\nuser.\n"
  example: []
  syntax:
    content: public string SubscriptionPlan { get; set; }
    content.vb: Public Property SubscriptionPlan As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings
  langs:
  - csharp
  - vb
  name: SubscriptionIntrinsicSettings()
  nameWithType: SubscriptionIntrinsicSettings.SubscriptionIntrinsicSettings()
  fullName: Microsoft.WindowsAzure.Management.Automation.Models.SubscriptionIntrinsicSettings.SubscriptionIntrinsicSettings()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/SubscriptionIntrinsicSettings.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Automation/AutomationManagement/Generated/Models/SubscriptionIntrinsicSettings.cs
    startLine: 47
  assemblies:
  - Microsoft.WindowsAzure.Management.Automation
  namespace: Microsoft.WindowsAzure.Management.Automation.Models
  summary: "\nInitializes a new instance of the SubscriptionIntrinsicSettings\nclass.\n"
  example: []
  syntax:
    content: public SubscriptionIntrinsicSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Automation.Models
  commentId: N:Microsoft.WindowsAzure.Management.Automation.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Automation.Models
  nameWithType: Microsoft.WindowsAzure.Management.Automation.Models
  fullName: Microsoft.WindowsAzure.Management.Automation.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
