items:
- uid: Microsoft.Hadoop.Client.ApplicationState
  commentId: T:Microsoft.Hadoop.Client.ApplicationState
  id: ApplicationState
  parent: Microsoft.Hadoop.Client
  children:
  - Microsoft.Hadoop.Client.ApplicationState.Failed
  - Microsoft.Hadoop.Client.ApplicationState.Finished
  - Microsoft.Hadoop.Client.ApplicationState.Killed
  - Microsoft.Hadoop.Client.ApplicationState.Unknown
  langs:
  - csharp
  - vb
  name: ApplicationState
  nameWithType: ApplicationState
  fullName: Microsoft.Hadoop.Client.ApplicationState
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: ApplicationState
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 20
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nEnum for the possible application states. This is tied to the state returned by Resource Manager.\nDO NOT UPDATE/CHANGE unless the values returned from Resource Manager change. \n"
  example: []
  syntax:
    content: 'public enum ApplicationState : int'
    content.vb: Public Enum ApplicationState As Integer
  extensionMethods:
  - Microsoft.Hadoop.Client.ApplicationState.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Hadoop.Client.ApplicationState.Unknown
  commentId: F:Microsoft.Hadoop.Client.ApplicationState.Unknown
  id: Unknown
  parent: Microsoft.Hadoop.Client.ApplicationState
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: ApplicationState.Unknown
  fullName: Microsoft.Hadoop.Client.ApplicationState.Unknown
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Unknown
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 25
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that application state is not known.\n"
  example: []
  syntax:
    content: Unknown = 0
    return:
      type: Microsoft.Hadoop.Client.ApplicationState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationState.Finished
  commentId: F:Microsoft.Hadoop.Client.ApplicationState.Finished
  id: Finished
  parent: Microsoft.Hadoop.Client.ApplicationState
  langs:
  - csharp
  - vb
  name: Finished
  nameWithType: ApplicationState.Finished
  fullName: Microsoft.Hadoop.Client.ApplicationState.Finished
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Finished
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 30
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application has finished.\n"
  example: []
  syntax:
    content: Finished = 1
    return:
      type: Microsoft.Hadoop.Client.ApplicationState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationState.Failed
  commentId: F:Microsoft.Hadoop.Client.ApplicationState.Failed
  id: Failed
  parent: Microsoft.Hadoop.Client.ApplicationState
  langs:
  - csharp
  - vb
  name: Failed
  nameWithType: ApplicationState.Failed
  fullName: Microsoft.Hadoop.Client.ApplicationState.Failed
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Failed
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 35
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application has failed.\n"
  example: []
  syntax:
    content: Failed = 2
    return:
      type: Microsoft.Hadoop.Client.ApplicationState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationState.Killed
  commentId: F:Microsoft.Hadoop.Client.ApplicationState.Killed
  id: Killed
  parent: Microsoft.Hadoop.Client.ApplicationState
  langs:
  - csharp
  - vb
  name: Killed
  nameWithType: ApplicationState.Killed
  fullName: Microsoft.Hadoop.Client.ApplicationState.Killed
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Killed
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 40
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application was killed.\n"
  example: []
  syntax:
    content: Killed = 3
    return:
      type: Microsoft.Hadoop.Client.ApplicationState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Hadoop.Client
  commentId: N:Microsoft.Hadoop.Client
  isExternal: false
  name: Microsoft.Hadoop.Client
  nameWithType: Microsoft.Hadoop.Client
  fullName: Microsoft.Hadoop.Client
- uid: Microsoft.Hadoop.Client.ApplicationState.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<ApplicationState>()
  nameWithType: ObjectExtensions.MakeEnumeration<ApplicationState>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Hadoop.Client.ApplicationState>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of ApplicationState)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Hadoop.Client.ApplicationState)()
  name.vb: MakeEnumeration(Of ApplicationState)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<ApplicationState>
    nameWithType: ObjectExtensions.MakeEnumeration<ApplicationState>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Hadoop.Client.ApplicationState>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of ApplicationState)
    nameWithType: ObjectExtensions.MakeEnumeration(Of ApplicationState)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Hadoop.Client.ApplicationState)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.Hadoop.Client.ApplicationState
  commentId: T:Microsoft.Hadoop.Client.ApplicationState
  parent: Microsoft.Hadoop.Client
  isExternal: false
  name: ApplicationState
  nameWithType: ApplicationState
  fullName: Microsoft.Hadoop.Client.ApplicationState
