items:
- uid: Microsoft.WindowsAzure.Management.Configuration
  commentId: N:Microsoft.WindowsAzure.Management.Configuration
  id: Microsoft.WindowsAzure.Management.Configuration
  children:
  - Microsoft.WindowsAzure.Management.Configuration.IAzureHDInsightClusterConfigurationAccessor
  - Microsoft.WindowsAzure.Management.Configuration.IAzureHDInsightClusterConfigurationAccessorFactory
  langs:
  - csharp
  - vb
  name: Microsoft.WindowsAzure.Management.Configuration
  nameWithType: Microsoft.WindowsAzure.Management.Configuration
  fullName: Microsoft.WindowsAzure.Management.Configuration
  type: Namespace
  assemblies:
  - Microsoft.WindowsAzure.Management.Configuration
references:
- uid: Microsoft.WindowsAzure.Management.Configuration.IAzureHDInsightClusterConfigurationAccessorFactory
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.IAzureHDInsightClusterConfigurationAccessorFactory
  isExternal: false
  name: IAzureHDInsightClusterConfigurationAccessorFactory
  nameWithType: IAzureHDInsightClusterConfigurationAccessorFactory
  fullName: Microsoft.WindowsAzure.Management.Configuration.IAzureHDInsightClusterConfigurationAccessorFactory
- uid: Microsoft.WindowsAzure.Management.Configuration.IAzureHDInsightClusterConfigurationAccessor
  commentId: T:Microsoft.WindowsAzure.Management.Configuration.IAzureHDInsightClusterConfigurationAccessor
  parent: Microsoft.WindowsAzure.Management.Configuration
  isExternal: false
  name: IAzureHDInsightClusterConfigurationAccessor
  nameWithType: IAzureHDInsightClusterConfigurationAccessor
  fullName: Microsoft.WindowsAzure.Management.Configuration.IAzureHDInsightClusterConfigurationAccessor
- uid: Microsoft.WindowsAzure.Management.Configuration
  commentId: N:Microsoft.WindowsAzure.Management.Configuration
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Configuration
  nameWithType: Microsoft.WindowsAzure.Management.Configuration
  fullName: Microsoft.WindowsAzure.Management.Configuration
