### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  id: ApplicationGatewayGetResponse
  parent: Microsoft.WindowsAzure.Management.Network.Models
  children:
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.#ctor
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Description
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.DnsName
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.GatewaySize
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.InstanceCount
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Name
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.State
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Subnets
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.VirtualIPs
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.VnetName
  langs:
  - csharp
  - vb
  name: ApplicationGatewayGetResponse
  nameWithType: ApplicationGatewayGetResponse
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayGetResponse
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 32
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nThe response body contains details of the application gateway.\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayGetResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ApplicationGatewayGetResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Description
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Description
  id: Description
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: ApplicationGatewayGetResponse.Description
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Description
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Description
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. User supplied description of the gateway\n"
  example: []
  syntax:
    content: public string Description { get; set; }
    content.vb: Public Property Description As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.DnsName
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.DnsName
  id: DnsName
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: DnsName
  nameWithType: ApplicationGatewayGetResponse.DnsName
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.DnsName
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DnsName
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 50
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. DNS name for the gateay.\n"
  example: []
  syntax:
    content: public string DnsName { get; set; }
    content.vb: Public Property DnsName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.GatewaySize
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.GatewaySize
  id: GatewaySize
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: GatewaySize
  nameWithType: ApplicationGatewayGetResponse.GatewaySize
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.GatewaySize
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: GatewaySize
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 61
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The size of each gateway instance.\n"
  example: []
  syntax:
    content: public string GatewaySize { get; set; }
    content.vb: Public Property GatewaySize As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.InstanceCount
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.InstanceCount
  id: InstanceCount
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: InstanceCount
  nameWithType: ApplicationGatewayGetResponse.InstanceCount
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.InstanceCount
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: InstanceCount
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 72
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The number of instances of this gateway.\n"
  example: []
  syntax:
    content: public uint InstanceCount { get; set; }
    content.vb: Public Property InstanceCount As UInteger
    parameters: []
    return:
      type: System.UInt32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Name
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Name
  id: Name
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ApplicationGatewayGetResponse.Name
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Name
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Name
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 83
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The friendly name of the gateway\n"
  example: []
  syntax:
    content: public string Name { get; set; }
    content.vb: Public Property Name As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.State
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.State
  id: State
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: State
  nameWithType: ApplicationGatewayGetResponse.State
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.State
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: State
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 94
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The provisioning state of the gateway.\n"
  example: []
  syntax:
    content: public string State { get; set; }
    content.vb: Public Property State As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Subnets
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Subnets
  id: Subnets
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: Subnets
  nameWithType: ApplicationGatewayGetResponse.Subnets
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.Subnets
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Subnets
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 105
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Subnets in the vnet to which the gateway belongs.\n"
  example: []
  syntax:
    content: public IList<string> Subnets { get; set; }
    content.vb: Public Property Subnets As IList(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.VirtualIPs
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.VirtualIPs
  id: VirtualIPs
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: VirtualIPs
  nameWithType: ApplicationGatewayGetResponse.VirtualIPs
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.VirtualIPs
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: VirtualIPs
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 116
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Virtual IP list of the gateway.\n"
  example: []
  syntax:
    content: public IList<string> VirtualIPs { get; set; }
    content.vb: Public Property VirtualIPs As IList(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.VnetName
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.VnetName
  id: VnetName
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: VnetName
  nameWithType: ApplicationGatewayGetResponse.VnetName
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.VnetName
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: VnetName
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 127
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The VNET to which the gateway belongs.\n"
  example: []
  syntax:
    content: public string VnetName { get; set; }
    content.vb: Public Property VnetName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse
  langs:
  - csharp
  - vb
  name: ApplicationGatewayGetResponse()
  nameWithType: ApplicationGatewayGetResponse.ApplicationGatewayGetResponse()
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayGetResponse.ApplicationGatewayGetResponse()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayGetResponse.cs
    startLine: 137
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nInitializes a new instance of the ApplicationGatewayGetResponse\nclass.\n"
  example: []
  syntax:
    content: public ApplicationGatewayGetResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Network.Models
  commentId: N:Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Network.Models
  nameWithType: Microsoft.WindowsAzure.Management.Network.Models
  fullName: Microsoft.WindowsAzure.Management.Network.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  name: UInt32
  nameWithType: UInt32
  fullName: System.UInt32
- uid: System.Collections.Generic.IList{System.String}
  commentId: T:System.Collections.Generic.IList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<String>
  nameWithType: IList<String>
  fullName: System.Collections.Generic.IList<System.String>
  nameWithType.vb: IList(Of String)
  fullname.vb: System.Collections.Generic.IList(Of System.String)
  name.vb: IList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  commentId: T:System.Collections.Generic.IList`1
  isExternal: true
  name: IList<T>
  nameWithType: IList<T>
  fullName: System.Collections.Generic.IList<T>
  nameWithType.vb: IList(Of T)
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
