### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  id: ActiveDirectoryConfig
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  children:
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.#ctor
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.#ctor(System.String,System.String,System.String)
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.DomainName
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.OrganizationalUnit
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.Password
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.UserName
  langs:
  - csharp
  - vb
  name: ActiveDirectoryConfig
  nameWithType: ActiveDirectoryConfig
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  type: Class
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ActiveDirectoryConfig
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nDetails of a RemoteApp active directory configuration.\n"
  example: []
  syntax:
    content: public class ActiveDirectoryConfig
    content.vb: Public Class ActiveDirectoryConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.DomainName
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.DomainName
  id: DomainName
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  langs:
  - csharp
  - vb
  name: DomainName
  nameWithType: ActiveDirectoryConfig.DomainName
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.DomainName
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: DomainName
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nRequired. The name of the on-premise domain to join the RD Session\nHost servers to.\n"
  example: []
  syntax:
    content: public string DomainName { get; set; }
    content.vb: Public Property DomainName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.OrganizationalUnit
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.OrganizationalUnit
  id: OrganizationalUnit
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  langs:
  - csharp
  - vb
  name: OrganizationalUnit
  nameWithType: ActiveDirectoryConfig.OrganizationalUnit
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.OrganizationalUnit
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: OrganizationalUnit
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
    startLine: 51
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nOptional. The name of your organizational unit to join the RD\nSession Host servers, e.g.\nOU=MyOu,DC=MyDomain,DC=ParentDomain,DC=com. Attributes such as OU,\nDC, etc. must be in uppercase.\n"
  example: []
  syntax:
    content: public string OrganizationalUnit { get; set; }
    content.vb: Public Property OrganizationalUnit As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.Password
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.Password
  id: Password
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: ActiveDirectoryConfig.Password
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.Password
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Password
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
    startLine: 62
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nRequired. The service account's password.\n"
  example: []
  syntax:
    content: public string Password { get; set; }
    content.vb: Public Property Password As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.UserName
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.UserName
  id: UserName
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  langs:
  - csharp
  - vb
  name: UserName
  nameWithType: ActiveDirectoryConfig.UserName
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.UserName
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: UserName
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
    startLine: 76
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nRequired. The user name of a service account that has permission to\nadd computers to the domain.The username must be specified in the\nUPN or down-level logon name format (user@some.domain or\nsome.domain\\\\user).\n"
  example: []
  syntax:
    content: public string UserName { get; set; }
    content.vb: Public Property UserName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  langs:
  - csharp
  - vb
  name: ActiveDirectoryConfig()
  nameWithType: ActiveDirectoryConfig.ActiveDirectoryConfig()
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.ActiveDirectoryConfig()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
    startLine: 85
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the ActiveDirectoryConfig class.\n"
  example: []
  syntax:
    content: public ActiveDirectoryConfig()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.#ctor(System.String,System.String,System.String)
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig
  langs:
  - csharp
  - vb
  name: ActiveDirectoryConfig(String, String, String)
  nameWithType: ActiveDirectoryConfig.ActiveDirectoryConfig(String, String, String)
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.ActiveDirectoryConfig.ActiveDirectoryConfig(System.String, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/ActiveDirectoryConfig.cs
    startLine: 93
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the ActiveDirectoryConfig class with\nrequired arguments.\n"
  example: []
  syntax:
    content: public ActiveDirectoryConfig(string domainName, string userName, string password)
    content.vb: Public Sub New(domainName As String, userName As String, password As String)
    parameters:
    - id: domainName
      type: System.String
    - id: userName
      type: System.String
    - id: password
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models
  commentId: N:Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.RemoteApp.Models
  nameWithType: Microsoft.WindowsAzure.Management.RemoteApp.Models
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
