### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult
  commentId: T:Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult
  id: UnpublishApplicationsResult
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models
  children:
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult.#ctor
  - Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult.ResultList
  langs:
  - csharp
  - vb
  name: UnpublishApplicationsResult
  nameWithType: UnpublishApplicationsResult
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult
  type: Class
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/UnpublishApplicationsResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: UnpublishApplicationsResult
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/UnpublishApplicationsResult.cs
    startLine: 33
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nDefinition for result of UnpublishApplications operation.\n"
  example: []
  syntax:
    content: 'public class UnpublishApplicationsResult : AzureOperationResponse'
    content.vb: >-
      Public Class UnpublishApplicationsResult
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult.ResultList
  commentId: P:Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult.ResultList
  id: ResultList
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult
  langs:
  - csharp
  - vb
  name: ResultList
  nameWithType: UnpublishApplicationsResult.ResultList
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult.ResultList
  type: Property
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/UnpublishApplicationsResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ResultList
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/UnpublishApplicationsResult.cs
    startLine: 40
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nOptional. List of unpublish operation results.\n"
  example: []
  syntax:
    content: public IList<PublishingOperationResult> ResultList { get; set; }
    content.vb: Public Property ResultList As IList(Of PublishingOperationResult)
    parameters: []
    return:
      type: System.Collections.Generic.IList{Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult
  langs:
  - csharp
  - vb
  name: UnpublishApplicationsResult()
  nameWithType: UnpublishApplicationsResult.UnpublishApplicationsResult()
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.UnpublishApplicationsResult.UnpublishApplicationsResult()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/UnpublishApplicationsResult.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/RemoteApp/RemoteApp/Generated/Models/UnpublishApplicationsResult.cs
    startLine: 49
  assemblies:
  - Microsoft.WindowsAzure.Management.RemoteApp
  namespace: Microsoft.WindowsAzure.Management.RemoteApp.Models
  summary: "\nInitializes a new instance of the UnpublishApplicationsResult class.\n"
  example: []
  syntax:
    content: public UnpublishApplicationsResult()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.RemoteApp.Models
  commentId: N:Microsoft.WindowsAzure.Management.RemoteApp.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.RemoteApp.Models
  nameWithType: Microsoft.WindowsAzure.Management.RemoteApp.Models
  fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.IList{Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult}
  commentId: T:System.Collections.Generic.IList{Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<PublishingOperationResult>
  nameWithType: IList<PublishingOperationResult>
  fullName: System.Collections.Generic.IList<Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult>
  nameWithType.vb: IList(Of PublishingOperationResult)
  fullname.vb: System.Collections.Generic.IList(Of Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult)
  name.vb: IList(Of PublishingOperationResult)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult
    name: PublishingOperationResult
    nameWithType: PublishingOperationResult
    fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult
    name: PublishingOperationResult
    nameWithType: PublishingOperationResult
    fullName: Microsoft.WindowsAzure.Management.RemoteApp.Models.PublishingOperationResult
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  commentId: T:System.Collections.Generic.IList`1
  isExternal: true
  name: IList<T>
  nameWithType: IList<T>
  fullName: System.Collections.Generic.IList<T>
  nameWithType.vb: IList(Of T)
  fullname.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
