items:
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  id: DscConfigurationProvisioningState
  parent: Microsoft.Azure.Management.Automation.Models
  children:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Succeeded
  langs:
  - csharp
  - vb
  name: DscConfigurationProvisioningState
  nameWithType: DscConfigurationProvisioningState
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  type: Enum
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProvisioningState.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: DscConfigurationProvisioningState
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProvisioningState.cs
    startLine: 29
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  summary: "\nProvisioning state of the configuration operation.\n"
  example: []
  syntax:
    content: 'public enum DscConfigurationProvisioningState : int'
    content.vb: Public Enum DscConfigurationProvisioningState As Integer
  extensionMethods:
  - Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Succeeded
  commentId: F:Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Succeeded
  id: Succeeded
  parent: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  langs:
  - csharp
  - vb
  name: Succeeded
  nameWithType: DscConfigurationProvisioningState.Succeeded
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Succeeded
  type: Field
  source:
    remote:
      path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProvisioningState.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Succeeded
    path: src/ResourceManagement/Automation/AutomationManagement/Generated/Models/DscConfigurationProvisioningState.cs
    startLine: 31
  assemblies:
  - Microsoft.Azure.Management.Automation
  namespace: Microsoft.Azure.Management.Automation.Models
  syntax:
    content: Succeeded = null
    content.vb: Succeeded = Nothing
    return:
      type: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Azure.Management.Automation.Models
  commentId: N:Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: Microsoft.Azure.Management.Automation.Models
  nameWithType: Microsoft.Azure.Management.Automation.Models
  fullName: Microsoft.Azure.Management.Automation.Models
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<DscConfigurationProvisioningState>()
  nameWithType: ObjectExtensions.MakeEnumeration<DscConfigurationProvisioningState>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of DscConfigurationProvisioningState)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState)()
  name.vb: MakeEnumeration(Of DscConfigurationProvisioningState)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<DscConfigurationProvisioningState>
    nameWithType: ObjectExtensions.MakeEnumeration<DscConfigurationProvisioningState>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of DscConfigurationProvisioningState)
    nameWithType: ObjectExtensions.MakeEnumeration(Of DscConfigurationProvisioningState)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  commentId: T:Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
  parent: Microsoft.Azure.Management.Automation.Models
  isExternal: false
  name: DscConfigurationProvisioningState
  nameWithType: DscConfigurationProvisioningState
  fullName: Microsoft.Azure.Management.Automation.Models.DscConfigurationProvisioningState
