### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters
  commentId: T:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters
  id: MetricSettingsPutParameters
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  children:
  - Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.#ctor
  - Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.#ctor(Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting)
  - Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.MetricSetting
  langs:
  - csharp
  - vb
  name: MetricSettingsPutParameters
  nameWithType: MetricSettingsPutParameters
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/MetricSettingsPutParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: MetricSettingsPutParameters
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/MetricSettingsPutParameters.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nParameters supplied to the Put Metric Settings operation.\n"
  example: []
  syntax:
    content: public class MetricSettingsPutParameters
    content.vb: Public Class MetricSettingsPutParameters
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.MetricSetting
  commentId: P:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.MetricSetting
  id: MetricSetting
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters
  langs:
  - csharp
  - vb
  name: MetricSetting
  nameWithType: MetricSettingsPutParameters.MetricSetting
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.MetricSetting
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/MetricSettingsPutParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: MetricSetting
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/MetricSettingsPutParameters.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nRequired. The metric setting.\n"
  example: []
  syntax:
    content: public MetricSetting MetricSetting { get; set; }
    content.vb: Public Property MetricSetting As MetricSetting
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters
  langs:
  - csharp
  - vb
  name: MetricSettingsPutParameters()
  nameWithType: MetricSettingsPutParameters.MetricSettingsPutParameters()
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.MetricSettingsPutParameters()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/MetricSettingsPutParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/MetricSettingsPutParameters.cs
    startLine: 46
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nInitializes a new instance of the MetricSettingsPutParameters class.\n"
  example: []
  syntax:
    content: public MetricSettingsPutParameters()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.#ctor(Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting)
  commentId: M:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.#ctor(Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting)
  id: '#ctor(Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting)'
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters
  langs:
  - csharp
  - vb
  name: MetricSettingsPutParameters(MetricSetting)
  nameWithType: MetricSettingsPutParameters.MetricSettingsPutParameters(MetricSetting)
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSettingsPutParameters.MetricSettingsPutParameters(Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting)
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/MetricSettingsPutParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Monitoring/Monitoring/Generated/Metrics/Models/MetricSettingsPutParameters.cs
    startLine: 54
  assemblies:
  - Microsoft.WindowsAzure.Management.Monitoring
  namespace: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  summary: "\nInitializes a new instance of the MetricSettingsPutParameters class\nwith required arguments.\n"
  example: []
  syntax:
    content: public MetricSettingsPutParameters(MetricSetting metricSetting)
    content.vb: Public Sub New(metricSetting As MetricSetting)
    parameters:
    - id: metricSetting
      type: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  commentId: N:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  nameWithType: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting
  commentId: T:Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting
  parent: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models
  isExternal: false
  name: MetricSetting
  nameWithType: MetricSetting
  fullName: Microsoft.WindowsAzure.Management.Monitoring.Metrics.Models.MetricSetting
