items:
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  id: RemoteManagementModeConfiguration
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  children:
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Disabled
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsEnabled
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Unknown
  langs:
  - csharp
  - vb
  name: RemoteManagementModeConfiguration
  nameWithType: RemoteManagementModeConfiguration
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: RemoteManagementModeConfiguration
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 29
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nRemoteManagementModeConfiguration\n"
  example: []
  syntax:
    content: 'public enum RemoteManagementModeConfiguration : int'
    content.vb: Public Enum RemoteManagementModeConfiguration As Integer
  extensionMethods:
  - Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Unknown
  commentId: F:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Unknown
  id: Unknown
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: RemoteManagementModeConfiguration.Unknown
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Unknown
  type: Field
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Unknown
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  syntax:
    content: Unknown = null
    content.vb: Unknown = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Disabled
  commentId: F:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Disabled
  id: Disabled
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: RemoteManagementModeConfiguration.Disabled
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Disabled
  type: Field
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Disabled
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 33
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  syntax:
    content: Disabled = null
    content.vb: Disabled = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsEnabled
  commentId: F:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsEnabled
  id: HttpsEnabled
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  langs:
  - csharp
  - vb
  name: HttpsEnabled
  nameWithType: RemoteManagementModeConfiguration.HttpsEnabled
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsEnabled
  type: Field
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: HttpsEnabled
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 35
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  syntax:
    content: HttpsEnabled = null
    content.vb: HttpsEnabled = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  commentId: F:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  id: HttpsAndHttpEnabled
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  langs:
  - csharp
  - vb
  name: HttpsAndHttpEnabled
  nameWithType: RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.HttpsAndHttpEnabled
  type: Field
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: HttpsAndHttpEnabled
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/RemoteManagementModeConfiguration.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  syntax:
    content: HttpsAndHttpEnabled = null
    content.vb: HttpsAndHttpEnabled = Nothing
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models
  commentId: N:Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.StorSimple.Models
  nameWithType: Microsoft.WindowsAzure.Management.StorSimple.Models
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<RemoteManagementModeConfiguration>()
  nameWithType: ObjectExtensions.MakeEnumeration<RemoteManagementModeConfiguration>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of RemoteManagementModeConfiguration)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration)()
  name.vb: MakeEnumeration(Of RemoteManagementModeConfiguration)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<RemoteManagementModeConfiguration>
    nameWithType: ObjectExtensions.MakeEnumeration<RemoteManagementModeConfiguration>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of RemoteManagementModeConfiguration)
    nameWithType: ObjectExtensions.MakeEnumeration(Of RemoteManagementModeConfiguration)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: RemoteManagementModeConfiguration
  nameWithType: RemoteManagementModeConfiguration
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.RemoteManagementModeConfiguration
