### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse
  id: ServiceConfigurationResponse
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  children:
  - Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.#ctor
  - Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.AcrChangeList
  - Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.CredentialChangeList
  - Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.OperationInProgress
  langs:
  - csharp
  - vb
  name: ServiceConfigurationResponse
  nameWithType: ServiceConfigurationResponse
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse
  type: Class
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ServiceConfigurationResponse
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
    startLine: 31
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nInfo about the service configuration regarding the resource\n"
  example: []
  syntax:
    content: 'public class ServiceConfigurationResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ServiceConfigurationResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.AcrChangeList
  commentId: P:Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.AcrChangeList
  id: AcrChangeList
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse
  langs:
  - csharp
  - vb
  name: AcrChangeList
  nameWithType: ServiceConfigurationResponse.AcrChangeList
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.AcrChangeList
  type: Property
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: AcrChangeList
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
    startLine: 38
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nOptional. List of access control record\n"
  example: []
  syntax:
    content: public AcrChangeList AcrChangeList { get; set; }
    content.vb: Public Property AcrChangeList As AcrChangeList
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.AcrChangeList
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.CredentialChangeList
  commentId: P:Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.CredentialChangeList
  id: CredentialChangeList
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse
  langs:
  - csharp
  - vb
  name: CredentialChangeList
  nameWithType: ServiceConfigurationResponse.CredentialChangeList
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.CredentialChangeList
  type: Property
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: CredentialChangeList
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
    startLine: 49
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nOptional. List of credential change list\n"
  example: []
  syntax:
    content: public SacChangeListResponse CredentialChangeList { get; set; }
    content.vb: Public Property CredentialChangeList As SacChangeListResponse
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.StorSimple.Models.SacChangeListResponse
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.OperationInProgress
  commentId: P:Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.OperationInProgress
  id: OperationInProgress
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse
  langs:
  - csharp
  - vb
  name: OperationInProgress
  nameWithType: ServiceConfigurationResponse.OperationInProgress
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.OperationInProgress
  type: Property
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: OperationInProgress
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
    startLine: 60
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nOptional. Is operation in progress\n"
  example: []
  syntax:
    content: public bool OperationInProgress { get; set; }
    content.vb: Public Property OperationInProgress As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse
  langs:
  - csharp
  - vb
  name: ServiceConfigurationResponse()
  nameWithType: ServiceConfigurationResponse.ServiceConfigurationResponse()
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.ServiceConfigurationResponse.ServiceConfigurationResponse()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/StorSimple/StorSimple/Generated/Models/ServiceConfigurationResponse.cs
    startLine: 70
  assemblies:
  - Microsoft.WindowsAzure.Management.StorSimple
  namespace: Microsoft.WindowsAzure.Management.StorSimple.Models
  summary: "\nInitializes a new instance of the ServiceConfigurationResponse\nclass.\n"
  example: []
  syntax:
    content: public ServiceConfigurationResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models
  commentId: N:Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.StorSimple.Models
  nameWithType: Microsoft.WindowsAzure.Management.StorSimple.Models
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.AcrChangeList
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.AcrChangeList
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: AcrChangeList
  nameWithType: AcrChangeList
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.AcrChangeList
- uid: Microsoft.WindowsAzure.Management.StorSimple.Models.SacChangeListResponse
  commentId: T:Microsoft.WindowsAzure.Management.StorSimple.Models.SacChangeListResponse
  parent: Microsoft.WindowsAzure.Management.StorSimple.Models
  isExternal: false
  name: SacChangeListResponse
  nameWithType: SacChangeListResponse
  fullName: Microsoft.WindowsAzure.Management.StorSimple.Models.SacChangeListResponse
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
