items:
- uid: Microsoft.Hadoop.Client.ApplicationFinalStatus
  commentId: T:Microsoft.Hadoop.Client.ApplicationFinalStatus
  id: ApplicationFinalStatus
  parent: Microsoft.Hadoop.Client
  children:
  - Microsoft.Hadoop.Client.ApplicationFinalStatus.Failed
  - Microsoft.Hadoop.Client.ApplicationFinalStatus.Killed
  - Microsoft.Hadoop.Client.ApplicationFinalStatus.Succeeded
  - Microsoft.Hadoop.Client.ApplicationFinalStatus.Undefined
  - Microsoft.Hadoop.Client.ApplicationFinalStatus.Unknown
  langs:
  - csharp
  - vb
  name: ApplicationFinalStatus
  nameWithType: ApplicationFinalStatus
  fullName: Microsoft.Hadoop.Client.ApplicationFinalStatus
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: ApplicationFinalStatus
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 46
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nEnum for the the final status of application if finished, as returned by the application itself. \n"
  example: []
  syntax:
    content: 'public enum ApplicationFinalStatus : int'
    content.vb: Public Enum ApplicationFinalStatus As Integer
  extensionMethods:
  - Microsoft.Hadoop.Client.ApplicationFinalStatus.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Hadoop.Client.ApplicationFinalStatus.Unknown
  commentId: F:Microsoft.Hadoop.Client.ApplicationFinalStatus.Unknown
  id: Unknown
  parent: Microsoft.Hadoop.Client.ApplicationFinalStatus
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: ApplicationFinalStatus.Unknown
  fullName: Microsoft.Hadoop.Client.ApplicationFinalStatus.Unknown
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Unknown
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 51
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that application' final status is not known.\n"
  example: []
  syntax:
    content: Unknown = 0
    return:
      type: Microsoft.Hadoop.Client.ApplicationFinalStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationFinalStatus.Undefined
  commentId: F:Microsoft.Hadoop.Client.ApplicationFinalStatus.Undefined
  id: Undefined
  parent: Microsoft.Hadoop.Client.ApplicationFinalStatus
  langs:
  - csharp
  - vb
  name: Undefined
  nameWithType: ApplicationFinalStatus.Undefined
  fullName: Microsoft.Hadoop.Client.ApplicationFinalStatus.Undefined
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Undefined
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 56
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application has not yet reported its final status. The application may still be running.\n"
  example: []
  syntax:
    content: Undefined = 1
    return:
      type: Microsoft.Hadoop.Client.ApplicationFinalStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationFinalStatus.Succeeded
  commentId: F:Microsoft.Hadoop.Client.ApplicationFinalStatus.Succeeded
  id: Succeeded
  parent: Microsoft.Hadoop.Client.ApplicationFinalStatus
  langs:
  - csharp
  - vb
  name: Succeeded
  nameWithType: ApplicationFinalStatus.Succeeded
  fullName: Microsoft.Hadoop.Client.ApplicationFinalStatus.Succeeded
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Succeeded
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 61
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application has succeeded.\n"
  example: []
  syntax:
    content: Succeeded = 2
    return:
      type: Microsoft.Hadoop.Client.ApplicationFinalStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationFinalStatus.Failed
  commentId: F:Microsoft.Hadoop.Client.ApplicationFinalStatus.Failed
  id: Failed
  parent: Microsoft.Hadoop.Client.ApplicationFinalStatus
  langs:
  - csharp
  - vb
  name: Failed
  nameWithType: ApplicationFinalStatus.Failed
  fullName: Microsoft.Hadoop.Client.ApplicationFinalStatus.Failed
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Failed
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 66
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application has failed.\n"
  example: []
  syntax:
    content: Failed = 3
    return:
      type: Microsoft.Hadoop.Client.ApplicationFinalStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Hadoop.Client.ApplicationFinalStatus.Killed
  commentId: F:Microsoft.Hadoop.Client.ApplicationFinalStatus.Killed
  id: Killed
  parent: Microsoft.Hadoop.Client.ApplicationFinalStatus
  langs:
  - csharp
  - vb
  name: Killed
  nameWithType: ApplicationFinalStatus.Killed
  fullName: Microsoft.Hadoop.Client.ApplicationFinalStatus.Killed
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Killed
    path: src/ServiceManagement/HDInsight/Microsoft.Hadoop.Client/YarnApplicationEntities/Enums.cs
    startLine: 71
  assemblies:
  - Microsoft.Hadoop.Client
  namespace: Microsoft.Hadoop.Client
  summary: "\nIndicates that the application was killed.\n"
  example: []
  syntax:
    content: Killed = 4
    return:
      type: Microsoft.Hadoop.Client.ApplicationFinalStatus
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Hadoop.Client
  commentId: N:Microsoft.Hadoop.Client
  isExternal: false
  name: Microsoft.Hadoop.Client
  nameWithType: Microsoft.Hadoop.Client
  fullName: Microsoft.Hadoop.Client
- uid: Microsoft.Hadoop.Client.ApplicationFinalStatus.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<ApplicationFinalStatus>()
  nameWithType: ObjectExtensions.MakeEnumeration<ApplicationFinalStatus>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Hadoop.Client.ApplicationFinalStatus>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of ApplicationFinalStatus)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Hadoop.Client.ApplicationFinalStatus)()
  name.vb: MakeEnumeration(Of ApplicationFinalStatus)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<ApplicationFinalStatus>
    nameWithType: ObjectExtensions.MakeEnumeration<ApplicationFinalStatus>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.Hadoop.Client.ApplicationFinalStatus>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of ApplicationFinalStatus)
    nameWithType: ObjectExtensions.MakeEnumeration(Of ApplicationFinalStatus)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.Hadoop.Client.ApplicationFinalStatus)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.Hadoop.Client.ApplicationFinalStatus
  commentId: T:Microsoft.Hadoop.Client.ApplicationFinalStatus
  parent: Microsoft.Hadoop.Client
  isExternal: false
  name: ApplicationFinalStatus
  nameWithType: ApplicationFinalStatus
  fullName: Microsoft.Hadoop.Client.ApplicationFinalStatus
