### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  id: ApplicationGatewayOperationResponse
  parent: Microsoft.WindowsAzure.Management.Network.Models
  children:
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.#ctor
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Data
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Error
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.HttpStatusCode
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Id
  - Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Status
  langs:
  - csharp
  - vb
  name: ApplicationGatewayOperationResponse
  nameWithType: ApplicationGatewayOperationResponse
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ApplicationGatewayOperationResponse
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
    startLine: 39
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nThe response body contains the status of the specified asynchronous\noperation, indicating whether it has succeeded, is inprogress, or has\nfailed. Note that this status is distinct from the HTTP status code\nreturned for the Get Operation Status operation itself.  If the\nasynchronous operation succeeded, the response body includes the HTTP\nstatus code for the successful request.  If the asynchronous operation\nfailed, the response body includes the HTTP status code for the failed\nrequest, and also includes error information regarding the failure.\n"
  example: []
  syntax:
    content: 'public class ApplicationGatewayOperationResponse : AzureOperationResponse'
    content.vb: >-
      Public Class ApplicationGatewayOperationResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Data
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Data
  id: Data
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: ApplicationGatewayOperationResponse.Data
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Data
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Data
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
    startLine: 46
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. Data returned for the asynchronous request.\n"
  example: []
  syntax:
    content: public string Data { get; set; }
    content.vb: Public Property Data As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Error
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Error
  id: Error
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  langs:
  - csharp
  - vb
  name: Error
  nameWithType: ApplicationGatewayOperationResponse.Error
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Error
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Error
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
    startLine: 59
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. If the asynchronous operation failed, the response body\nincludes the HTTP status code for the failed request, and also\nincludes error information regarding the failure.\n"
  example: []
  syntax:
    content: public ApplicationGatewayOperationResponse.ErrorDetails Error { get; set; }
    content.vb: Public Property Error As ApplicationGatewayOperationResponse.ErrorDetails
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.ErrorDetails
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.HttpStatusCode
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.HttpStatusCode
  id: HttpStatusCode
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  langs:
  - csharp
  - vb
  name: HttpStatusCode
  nameWithType: ApplicationGatewayOperationResponse.HttpStatusCode
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.HttpStatusCode
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: HttpStatusCode
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
    startLine: 70
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The HTTP status code for the asynchronous request.\n"
  example: []
  syntax:
    content: public HttpStatusCode HttpStatusCode { get; set; }
    content.vb: Public Property HttpStatusCode As HttpStatusCode
    parameters: []
    return:
      type: System.Net.HttpStatusCode
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Id
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Id
  id: Id
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: ApplicationGatewayOperationResponse.Id
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Id
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Id
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
    startLine: 83
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The request ID of the asynchronous request. This value is\nreturned in the x-ms-request-id response header of the\nasynchronous request.\n"
  example: []
  syntax:
    content: public string Id { get; set; }
    content.vb: Public Property Id As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Status
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Status
  id: Status
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  langs:
  - csharp
  - vb
  name: Status
  nameWithType: ApplicationGatewayOperationResponse.Status
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.Status
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Status
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
    startLine: 94
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nOptional. The status of the asynchronous request.\n"
  example: []
  syntax:
    content: public AsyncOperationStatus Status { get; set; }
    content.vb: Public Property Status As AsyncOperationStatus
    parameters: []
    return:
      type: Microsoft.WindowsAzure.Management.Network.Models.AsyncOperationStatus
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse
  langs:
  - csharp
  - vb
  name: ApplicationGatewayOperationResponse()
  nameWithType: ApplicationGatewayOperationResponse.ApplicationGatewayOperationResponse()
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.ApplicationGatewayOperationResponse()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/ApplicationGatewayOperationResponse.cs
    startLine: 104
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nInitializes a new instance of the\nApplicationGatewayOperationResponse class.\n"
  example: []
  syntax:
    content: public ApplicationGatewayOperationResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Network.Models
  commentId: N:Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Network.Models
  nameWithType: Microsoft.WindowsAzure.Management.Network.Models
  fullName: Microsoft.WindowsAzure.Management.Network.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.ErrorDetails
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.ErrorDetails
  parent: Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: ApplicationGatewayOperationResponse.ErrorDetails
  nameWithType: ApplicationGatewayOperationResponse.ErrorDetails
  fullName: Microsoft.WindowsAzure.Management.Network.Models.ApplicationGatewayOperationResponse.ErrorDetails
- uid: System.Net.HttpStatusCode
  commentId: T:System.Net.HttpStatusCode
  parent: System.Net
  isExternal: true
  name: HttpStatusCode
  nameWithType: HttpStatusCode
  fullName: System.Net.HttpStatusCode
- uid: System.Net
  commentId: N:System.Net
  isExternal: false
  name: System.Net
  nameWithType: System.Net
  fullName: System.Net
- uid: Microsoft.WindowsAzure.Management.Network.Models.AsyncOperationStatus
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.AsyncOperationStatus
  parent: Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: AsyncOperationStatus
  nameWithType: AsyncOperationStatus
  fullName: Microsoft.WindowsAzure.Management.Network.Models.AsyncOperationStatus
