### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping
  commentId: T:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping
  id: WebSiteUpdateConfigurationParameters.HandlerMapping
  parent: Microsoft.WindowsAzure.Management.WebSites.Models
  children:
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.#ctor
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.Arguments
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.Extension
  - Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.ScriptProcessor
  langs:
  - csharp
  - vb
  name: WebSiteUpdateConfigurationParameters.HandlerMapping
  nameWithType: WebSiteUpdateConfigurationParameters.HandlerMapping
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping
  type: Class
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: HandlerMapping
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 440
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\nSpecifies a custom executable program for handling requests for\nspecific file name extensions.\n"
  example: []
  syntax:
    content: public class HandlerMapping
    content.vb: Public Class HandlerMapping
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.Arguments
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.Arguments
  id: Arguments
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping
  langs:
  - csharp
  - vb
  name: Arguments
  nameWithType: WebSiteUpdateConfigurationParameters.HandlerMapping.Arguments
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.Arguments
  type: Property
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Arguments
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 450
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\nOptional. A string that contains optional arguments for the\nscript processor specified by the\nSiteConfig.HandlerMappings.HandlerMapping.ScriptProcessor\nelement.\n"
  example: []
  syntax:
    content: public string Arguments { get; set; }
    content.vb: Public Property Arguments As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.Extension
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.Extension
  id: Extension
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping
  langs:
  - csharp
  - vb
  name: Extension
  nameWithType: WebSiteUpdateConfigurationParameters.HandlerMapping.Extension
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.Extension
  type: Property
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Extension
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 463
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\nOptional. A string that specifies the extension of the file\ntype that the script processor will handle (for example,\n*.php).\n"
  example: []
  syntax:
    content: public string Extension { get; set; }
    content.vb: Public Property Extension As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.ScriptProcessor
  commentId: P:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.ScriptProcessor
  id: ScriptProcessor
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping
  langs:
  - csharp
  - vb
  name: ScriptProcessor
  nameWithType: WebSiteUpdateConfigurationParameters.HandlerMapping.ScriptProcessor
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.ScriptProcessor
  type: Property
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: ScriptProcessor
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 476
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\nOptional. The absolute path to the location of the executable\nfile that will handle the files specified in the\nSiteConfig.HandlerMappings.HandlerMapping.Extension element.\n"
  example: []
  syntax:
    content: public string ScriptProcessor { get; set; }
    content.vb: Public Property ScriptProcessor As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping
  langs:
  - csharp
  - vb
  name: HandlerMapping()
  nameWithType: WebSiteUpdateConfigurationParameters.HandlerMapping.HandlerMapping()
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models.WebSiteUpdateConfigurationParameters.HandlerMapping.HandlerMapping()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/WebSite/WebSiteManagement/Generated/Models/WebSiteUpdateConfigurationParameters.cs
    startLine: 485
  assemblies:
  - Microsoft.WindowsAzure.Management.WebSites
  namespace: Microsoft.WindowsAzure.Management.WebSites.Models
  summary: "\nInitializes a new instance of the HandlerMapping class.\n"
  example: []
  syntax:
    content: public HandlerMapping()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.WebSites.Models
  commentId: N:Microsoft.WindowsAzure.Management.WebSites.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.WebSites.Models
  nameWithType: Microsoft.WindowsAzure.Management.WebSites.Models
  fullName: Microsoft.WindowsAzure.Management.WebSites.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
