### YamlMime:ManagedReference
items:
- uid: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse
  commentId: T:Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse
  id: NetworkGetConfigurationResponse
  parent: Microsoft.WindowsAzure.Management.Network.Models
  children:
  - Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.#ctor
  - Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.#ctor(System.String)
  - Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.Configuration
  langs:
  - csharp
  - vb
  name: NetworkGetConfigurationResponse
  nameWithType: NetworkGetConfigurationResponse
  fullName: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse
  type: Class
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/NetworkGetConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: NetworkGetConfigurationResponse
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/NetworkGetConfigurationResponse.cs
    startLine: 30
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nThe Get Network Configuration operation response.\n"
  example: []
  syntax:
    content: 'public class NetworkGetConfigurationResponse : AzureOperationResponse'
    content.vb: >-
      Public Class NetworkGetConfigurationResponse
          Inherits AzureOperationResponse
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.Configuration
  commentId: P:Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.Configuration
  id: Configuration
  parent: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: NetworkGetConfigurationResponse.Configuration
  fullName: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.Configuration
  type: Property
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/NetworkGetConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: Configuration
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/NetworkGetConfigurationResponse.cs
    startLine: 37
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nRequired. The network configuration for this subscription.\n"
  example: []
  syntax:
    content: public string Configuration { get; set; }
    content.vb: Public Property Configuration As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.#ctor
  commentId: M:Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.#ctor
  id: '#ctor'
  parent: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse
  langs:
  - csharp
  - vb
  name: NetworkGetConfigurationResponse()
  nameWithType: NetworkGetConfigurationResponse.NetworkGetConfigurationResponse()
  fullName: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.NetworkGetConfigurationResponse()
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/NetworkGetConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/NetworkGetConfigurationResponse.cs
    startLine: 47
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nInitializes a new instance of the NetworkGetConfigurationResponse\nclass.\n"
  example: []
  syntax:
    content: public NetworkGetConfigurationResponse()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.#ctor(System.String)
  commentId: M:Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse
  langs:
  - csharp
  - vb
  name: NetworkGetConfigurationResponse(String)
  nameWithType: NetworkGetConfigurationResponse.NetworkGetConfigurationResponse(String)
  fullName: Microsoft.WindowsAzure.Management.Network.Models.NetworkGetConfigurationResponse.NetworkGetConfigurationResponse(System.String)
  type: Constructor
  source:
    remote:
      path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/NetworkGetConfigurationResponse.cs
      branch: AutoRest
      repo: https://github.com/Azure/azure-sdk-for-net.git
    id: .ctor
    path: src/ServiceManagement/Network/NetworkManagement/Generated/Models/NetworkGetConfigurationResponse.cs
    startLine: 55
  assemblies:
  - Microsoft.WindowsAzure.Management.Network
  namespace: Microsoft.WindowsAzure.Management.Network.Models
  summary: "\nInitializes a new instance of the NetworkGetConfigurationResponse\nclass with required arguments.\n"
  example: []
  syntax:
    content: public NetworkGetConfigurationResponse(string configuration)
    content.vb: Public Sub New(configuration As String)
    parameters:
    - id: configuration
      type: System.String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.WindowsAzure.Management.Network.Models
  commentId: N:Microsoft.WindowsAzure.Management.Network.Models
  isExternal: false
  name: Microsoft.WindowsAzure.Management.Network.Models
  nameWithType: Microsoft.WindowsAzure.Management.Network.Models
  fullName: Microsoft.WindowsAzure.Management.Network.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
