items:
- uid: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  id: EnvironmentType
  parent: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  children:
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Current
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.DogFood
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Next
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Production
  langs:
  - csharp
  - vb
  name: EnvironmentType
  nameWithType: EnvironmentType
  fullName: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  type: Enum
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: EnvironmentType
    path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
    startLine: 55
  assemblies:
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  namespace: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  syntax:
    content: 'public enum EnvironmentType : int'
    content.vb: Public Enum EnvironmentType As Integer
  extensionMethods:
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Production
  commentId: F:Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Production
  id: Production
  parent: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  langs:
  - csharp
  - vb
  name: Production
  nameWithType: EnvironmentType.Production
  fullName: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Production
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Production
    path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
    startLine: 57
  assemblies:
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  namespace: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  syntax:
    content: Production = 0
    return:
      type: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Current
  commentId: F:Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Current
  id: Current
  parent: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  langs:
  - csharp
  - vb
  name: Current
  nameWithType: EnvironmentType.Current
  fullName: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Current
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Current
    path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
    startLine: 58
  assemblies:
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  namespace: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  syntax:
    content: Current = 1
    return:
      type: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Next
  commentId: F:Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Next
  id: Next
  parent: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  langs:
  - csharp
  - vb
  name: Next
  nameWithType: EnvironmentType.Next
  fullName: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Next
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: Next
    path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
    startLine: 59
  assemblies:
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  namespace: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  syntax:
    content: Next = 2
    return:
      type: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.DogFood
  commentId: F:Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.DogFood
  id: DogFood
  parent: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  langs:
  - csharp
  - vb
  name: DogFood
  nameWithType: EnvironmentType.DogFood
  fullName: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.DogFood
  type: Field
  source:
    remote:
      path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
      branch: master
      repo: git@github.com:qinezh/azure-sdk-for-net.git
    id: DogFood
    path: src/ServiceManagement/HDInsight/Microsoft.WindowsAzure.Management.HDInsight.TestUtilities/AzureTestCredentials.cs
    startLine: 60
  assemblies:
  - Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  namespace: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  syntax:
    content: DogFood = 3
    return:
      type: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  fullName: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
- uid: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType.Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  definition: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  name: MakeEnumeration<EnvironmentType>()
  nameWithType: ObjectExtensions.MakeEnumeration<EnvironmentType>()
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType>()
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of EnvironmentType)()
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType)()
  name.vb: MakeEnumeration(Of EnvironmentType)()
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration<EnvironmentType>
    nameWithType: ObjectExtensions.MakeEnumeration<EnvironmentType>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1
    name: MakeEnumeration(Of EnvironmentType)
    nameWithType: ObjectExtensions.MakeEnumeration(Of EnvironmentType)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  commentId: M:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
  isExternal: false
  name: MakeEnumeration<T>(T)
  nameWithType: ObjectExtensions.MakeEnumeration<T>(T)
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>(T)
  nameWithType.vb: ObjectExtensions.MakeEnumeration(Of T)(T)
  fullname.vb: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)(T)
  name.vb: MakeEnumeration(Of T)(T)
  spec.csharp:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration<T>
    nameWithType: ObjectExtensions.MakeEnumeration<T>
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration``1(``0)
    name: MakeEnumeration(Of T)
    nameWithType: ObjectExtensions.MakeEnumeration(Of T)
    fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions.MakeEnumeration(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
  parent: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library.ObjectExtensions
- uid: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  commentId: N:Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  isExternal: false
  name: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  nameWithType: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
  fullName: Microsoft.WindowsAzure.Management.HDInsight.Framework.Core.Library
- uid: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  commentId: T:Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
  parent: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities
  isExternal: false
  name: EnvironmentType
  nameWithType: EnvironmentType
  fullName: Microsoft.WindowsAzure.Management.HDInsight.TestUtilities.EnvironmentType
