items:
- uid: SampleKeyVaultConfigurationManager
  commentId: N:SampleKeyVaultConfigurationManager
  id: SampleKeyVaultConfigurationManager
  children:
  - SampleKeyVaultConfigurationManager.ConfigurationManager
  langs:
  - csharp
  - vb
  name: SampleKeyVaultConfigurationManager
  nameWithType: SampleKeyVaultConfigurationManager
  fullName: SampleKeyVaultConfigurationManager
  type: Namespace
  assemblies:
  - SampleKeyVaultConfigurationManager
references:
- uid: SampleKeyVaultConfigurationManager.ConfigurationManager
  commentId: T:SampleKeyVaultConfigurationManager.ConfigurationManager
  isExternal: false
  name: ConfigurationManager
  nameWithType: ConfigurationManager
  fullName: SampleKeyVaultConfigurationManager.ConfigurationManager
